sublimehq/Packages

README.md
Essentially what @jskinner put in the forum announcement.
=> Added readme for instructions

Ruby/Ruby.sublime-syntax
=> [Ruby] Highlight end of regexp character

Ruby/Ruby.sublime-syntax
Added Vagrantfile to the file_extensions in order to auto-detect it as a ruby-syntax file.
=> Added Vagrantfile syntax detection.

Batch File/Comments.tmPreferences
So you can do `Ctrl + /` to quickly comment/uncomment lines.
=> Comment character for Batch Files

JavaScript/Object-Method.sublime-snippet, JavaScript/Object-Value-JS.sublime-snippet
Fix `Object-Method`, `Object-Value-JS`. Make their styles the same with `function` and `Object-key-key-value` snippets.
=> [JavaScript] Add missing blank

TCL/Tcl.sublime-syntax, TCL/syntax_test_tcl.tcl
Fix issue  SublimeTextIssues/DefaultPackages#134
Also add test file
=> [TCL] Fix highlighting of escape character \\

Java/Java.sublime-syntax, Java/syntax_test_java.java
This represents what I think should be the final solution to the original problem.
For context, I'm including a diff showing the changes in the previous two PRs #117 and #119 as well so we can see the summarised difference of all the changes I've made as one. I wouldn't be surprised if there's a way to do this in github itself but for now I'll just paste the diff, for illustration purposes:
```diff
diff --git a/Java/Java.sublime-syntax b/Java/Java.sublime-syntax
index bf086fa..bff61b2 100644
--- a/Java/Java.sublime-syntax
+++ b/Java/Java.sublime-syntax
@@ -223,6 +223,11 @@ contexts:
scope: keyword.operator.comparison.java
- match: (=)
scope: keyword.operator.assignment.java
+      push:
+        - meta_scope: meta.assignment.rhs.java
+        - match: (?=(;|\)))
+          pop: true
+ …
```
=> use lookahead to properly identify RHS

README.md
=> remove uneeded shell command in example

Python/Python.sublime-syntax
Add support for main SnakeMake file name. SnakeMake (https://bitbucket.org/snakemake/snakemake/wiki/Home) is Python-based Make-like workflow management system.
=> [Python] Support for SnakeMake

PHP/PHP.sublime-syntax
As the title.
Related issue: https://github.com/sublimehq/Packages/issues/134
=> [PHP] Also set syntax to PHP if the first line starts with <?php

HTML/syntax_test_html.html
Updating tests to reflect changes in https://github.com/sublimehq/Packages/commit/9d2ff48c8df42b42874360661e2c719e6278f3ec
Edited on phone so double check me :p
=> [HTML] Updates tests to use new class-name scope

HTML/HTML.sublime-syntax, HTML/syntax_test_html.html
Added custom scopes for table tags (table,tr,td...), form tags (form,input,button...) and a tag to be able to custom color them in themes.
=> [HTML] added table, form and link syntax highlighting

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
This PR fixes #244 
Test also added.
=> [PHP] Fixed function last argument highlight bug

R/R.sublime-build
The R build system runs an R script
=> [R] Adding build system

JavaScript/JavaScript.sublime-syntax
Added JavaScript methods:
- `console.timestamp()` - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Console/timeStamp)
- `Array.prototype.copyWithin()` - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin)
- `Array.prototype.fill()` - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill)
Added Node.js [Process](https://nodejs.org/dist/latest/docs/api/process.html) methods:
*all methods are supported in Node.js LTS 4.4.0 and Node.js 5.9.0 Stable*
- `process.disconnect()` - [4.x](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_disconnect)
- `process.getegid()` - [4.x](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_getegid)
- …
=> [JavaScript] Added missing console, process, and mutator methods

PHP/PHP Source.sublime-syntax, PHP/PHP.sublime-completions
PHP 7 added a new function to divide numbers and not involve floats.
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.intdiv
=> [PHP] Add support for the intdiv() function

PHP/PHP Source.sublime-syntax, PHP/PHP.sublime-completions
PHP 7 added a new function for handling regex search and replace
http://php.net/manual/en/function.preg-replace-callback-array.php
=> [PHP] Add support for the preg_replace_callback_array() function

PHP/PHP Source.sublime-syntax, PHP/PHP.sublime-completions
PHP 7 added some new random functions
http://php.net/manual/en/ref.csprng.php
=> [PHP] Add support for the CSPRNG functions

Batch File/syntax_test_batch_file.bat, Graphviz/syntax_test_dot.dot, JavaScript/syntax_test_json.json
=> [Batch / Graphviz / JSON] Added tests

XML/XML.sublime-syntax, XML/syntax_test_xml.xml
fixes https://github.com/SublimeTextIssues/DefaultPackages/issues/93
=> [XML] attributes: allow whitespace before equals sign

CSS/CSS.sublime-syntax
Updated & reorganized the property names & values.
Added the following:
**Property Names**:
```
flex-negative
flex-positive
flex-preferred-size
force-broken-image-icon
nbsp-mode
tap-highlight-color
touch-action
touch-callout
```
**Property Values**:
```
autohiding-scrollbar
button
element
(nwse|nesw|ns|ew|sw|se|nw|ne|w|s|e|n)-resize
scrollbar
sticky
subpixel-antialiased
zoom-in
zoom-out
```
=> [CSS] Update property names & values

ASP/ASP.sublime-syntax, ASP/syntax_test_asp.asp
[ASP] add missing / operator
[ASP] fix hexadecimal constants
[ASP] support comments after method definition
[ASP] support method definition with no parenthesis
=> [ASP] support line continuation

CSS/CSS.sublime-syntax
Consolidated the blend-mode and isolation-mode property values with the other property values
=> [CSS] Consolidate property values

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
The combinators `>>>`, `>>`, `>`, `~`, `+` are now scoped
=> [CSS] Scoped combinators

ASP/ASP.sublime-syntax, ASP/syntax_test_asp.asp
=> [ASP] add missing constants

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
Implements strings & comments with scopes consistent with other languages.
=> [Batch] More consistent strings & comments

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
Added conditional operators `& && ||`, the `@` operator,  and the `==` string comparison operator
=> [Batch] Added operators

Batch File/Batch File.sublime-syntax, Batch File/Symbol List.tmPreferences, Batch File/syntax_test_batch_file.bat
Hopefully the scopes are okay. I picked them explicitly to get picked up by the "Goto Symbol..." feature.
=> [Batch File] Scope for Goto labels

PHP/Symbol List.tmPreferences
=> [PHP] show class name in Goto Symbol

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
better test coverage for "use" statements in the PHP syntax
=> [PHP] make "use" consistent with "new" and fix magic methods

Haskell/Comments.tmPreferences, Haskell/Haskell.sublime-syntax, Haskell/syntax_test_haskell.hs
=> [Haskell] comment fixes

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Allow comments within property values

HTML/HTML.sublime-syntax, HTML/syntax_test_html.html
=> [HTML] give script and style close tags the same scope as the open tags

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
Adds support for operators when using the `SET` command with the `/A` flag
=> [Batch] Add SET /A command expressions

Batch File/Comments.tmPreferences, C#/Symbol List Inner Function.tmPreferences, C++/Completion Rules.tmPreferences, C++/Symbol Index Hide Ctors.tmPreferences, C++/Symbol Index Include Constants.tmPreferences, C++/Symbol Index.tmPreferences, C++/Symbol List Hide Forward Decls.tmPreferences, Go/Symbol Index.tmPreferences
These changes are an addendum to 61bfd68ea07a3aede68cd6a65c80be702b3d6db8
Indentation is tabs
=> Cleanup .tmPreferences

JavaScript/JavaScript.sublime-syntax, JavaScript/syntax_test_js.js
Improved test coverage & fixed the order of conditional variables
=> [JavaScript] Improve test coverage

Java/Indexed Symbol List.tmPreferences, Java/Java Server Pages (JSP).sublime-syntax, Java/Java.sublime-syntax, Java/syntax_test_java.java, Java/syntax_test_jsp.jsp
=> [Java] add tests, improve generic type detection

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp
Highlighting operator overloads for user-defined literals.
=> [C++] Adding support for user-defined literal operator overloading

Python/Snippets/self.sublime-snippet
=> [Python] Fix self.sublime-snippet causes problems in basic usages of autocomplete

Lisp/Lisp.sublime-syntax, Lisp/syntax_test_lisp.lisp
- Implemented operators & block comments
- Scoped parentheses
- Converted `captures: 0` to `scope`
- Added tests
=> [Lisp] Implemented operators & block comments

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
Adds the [`symbols()`](https://drafts.csswg.org/css-counter-styles-3/#symbols-function) counter function
=> [CSS] Add symbols function

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] With statements with multiple resources

Regular Expressions/RegExp.sublime-syntax, Regular Expressions/syntax_test_regexp.re
=> [Regular Expressions] support escaped "-" char in control set

Python/Python.sublime-syntax, Python/syntax_test_python.py
[PEP 3127](https://www.python.org/dev/peps/pep-3127/) proposed binary and octal prefixes for integers.
[Waf](https://waf.io/) is a build system which is written in Python and uses Python scripts to control the building process.
=> [Python] Enhancements

Python/Python.sublime-syntax
This is a frequent start keyword for SQL-queries in PostgreSQL.
=> [Python] Add sql indicator "WITH"

Java/Java.sublime-syntax, Java/syntax_test_java.java
* Add a scope with .static for static imports. This allows scripts to extract static imports easily.
* Use scopes to simplify the regex.
=> Update Java import and package keywords

Regular Expressions/RegExp.sublime-syntax, Regular Expressions/syntax_test_regexp.re
=> [Regular Expressions] support conditionals

JavaScript/JSON.sublime-syntax
=> [JSON] Add sublime-macro extension

HTML/html_completions.py
=> [HTML] fix failing unit tests for completions

D/Snippets/class.sublime-snippet, D/Snippets/struct.sublime-snippet, D/Snippets/warning.sublime-snippet, D/Snippets/while.sublime-snippet
* D relies heavily on commented code
* Functions the same way as `method` does
* There was a stray }
* To match rest of snippets, a space was removed
=> [D] Small fixes

YAML/Indentation Rules.tmPreferences, YAML/Symbol List.tmPreferences, YAML/YAML.sublime-syntax, YAML/tests/syntax_test_block.yaml, YAML/tests/syntax_test_flow.yaml, YAML/tests/syntax_test_general.yaml, YAML/tests/syntax_test_properties.yaml
I continued @infininight's work in  #600 and added a couple changes myself beyond fixing what he provided.
=> [YAML] Continuation of #600

YAML/Indentation Rules.tmPreferences, YAML/YAML.sublime-syntax, YAML/tests/syntax_test_flow-plain.yaml
Fixes #628 and improves indentation preferences.
=> [Yaml] Plain-in tweaks

LaTeX/LaTeX.sublime-syntax, LaTeX/TeX.sublime-syntax, LaTeX/syntax_test_latex.tex
=> [LaTeX] multiple newcommand options and greek word break

JavaScript/JavaScript.sublime-syntax, Makefile/Makefile.sublime-syntax, Python/Python.sublime-syntax, Ruby/Ruby.sublime-syntax
Spaces are allowed between the `#!` and `/` bits - this'll make syntax detection friendlier for those of us who think the space helps readability.
=> Allow spaces in shebang lines.

Java/Java.sublime-syntax, Java/syntax_test_java.java
Still several things to be addressed, especially related to the over-use of `storage.type`, but it's getting better.  Notably fixed here:
- Scoping on `class`/`enum`/`interface` to be in line with the guidelines
+ Also improved user-experience while typing with better lookahead
- Added `volatile` to the set of keywords
- Scoping for function calls
- Tweaked `extends`/`implements` scoping to be uniform with Scala's `extends`/`with`
Further high priority things to address in later PRs:
- `storage.type` is applied to any identifier-ish thing in random code
- Generic brackets (`<`/`>`) are not properly scoped in types
- Lambdas are entirely unscoped
- Annotations are barely scoped
=> [Java] Misc Fixes

Python/Python.sublime-syntax, Python/syntax_test_python.py
https://www.python.org/dev/peps/pep-0515
Ref #694
=> [Python] Underscores in number literals

Python/Python.sublime-syntax, Python/syntax_test_python.py
https://www.python.org/dev/peps/pep-0530/
Ref #694
=> [Python] Asynchronous generators

Python/Python.sublime-syntax, Python/syntax_test_python.py
https://www.python.org/dev/peps/pep-0526
Chose the simple route.
Ref #694
=> [Python] Variable annotations

ASP/ASP.sublime-syntax, ASP/Comments.tmPreferences, ASP/syntax_test_asp.asp
add missing `Comments.tmPreferences` file to allow "toggle comment" functionality to work inside ASP files
=> [ASP] add missing Comments.tmPreferences file

C#/C#.sublime-syntax, C#/tests/syntax_test_Using.cs
=> [C#] fix IDisposable using  statements

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] fix lambdas breaking try/catch

Java/Java Server Pages (JSP).sublime-syntax, Java/Java.sublime-syntax, Java/syntax_test_jsp.jsp
a few fixes for comments in Java Server Pages (JSP) (from #775)
=> [Java] a few JSP comment fixes

Ruby/Ruby.sublime-syntax, Ruby/syntax_test_ruby.rb
=> [Ruby] fix a highlight bug

C++/C.sublime-syntax, C++/syntax_test_c.c
Fix https://github.com/sublimehq/Packages/issues/821.
Ref: https://docs.oracle.com/cd/E19422-01/819-3688/sun.specific.html
=> [C] Fix integral constants

HTML/HTML.sublime-syntax, HTML/syntax_test_html.html
=> [HTML] scope self closing HR tag punctuation

JavaScript/JavaScript.sublime-syntax, JavaScript/Regular Expressions (JavaScript).sublime-syntax, JavaScript/Snippets/Object-Method.sublime-snippet, JavaScript/syntax_test_js.js
Fixes #826 and fixes #791 and fixes #780 and fixes #778 and fixes #640 and fixes #604 and fixes #665 and fixes #86
=> [JavaScript] many issue fixes

Lisp/Lisp.sublime-syntax, Lisp/syntax_test_lisp.lisp
=> [Lisp] allow multi-line strings

D/syntax_test_d.d
=> [D] add test for regex closing quote

TCL/Tcl.sublime-syntax, TCL/syntax_test_tcl.tcl
fixes #779, fixes #783, fixes #784
=> [TCL] regexp improvements

XML/XML.sublime-syntax, XML/syntax_test_xml.xml
fixes https://github.com/sublimehq/Packages/issues/882
=> [XML] correctly scope xml-stylesheet instructions

Markdown/Markdown.sublime-syntax, Markdown/Symbol List - Heading.tmPreferences, Markdown/syntax_test_markdown.md
=> [Markdown] fix multiline list items with blank line separators

Python/Python.sublime-syntax, Python/syntax_test_python.py
Fixes #931 and a couple other minor improvements.
=> [Python] Do better at matching numbers

XML/XML.sublime-syntax, XML/syntax_test_xml.xml
See Issue #977 for details, please.
=> [XML] fix comments in doctype international subset

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/object-and-collection-initializers
=> [C#] support object/collection initializers on a separate line

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs, C#/tests/syntax_test_Generics.cs
=> [C#] add support for composite string placeholder formatting

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] fix catch with generic type and no variable name

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] support nested parens in calc function call

TCL/Tcl.sublime-syntax, TCL/syntax_test_tcl.tcl
fixes https://github.com/sublimehq/Packages/issues/963
=> [TCL] fix bug where switch and foreach body contents were unscoped

Python/Python.sublime-syntax, Python/syntax_test_python.py, Python/syntax_test_python_strings.py
Some changes that didn't fit anywhere else and were too small to warrant a separate PR.
=> [Python] Language constants and string placeholder update and

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
This is an attempt to fix https://github.com/sublimehq/Packages/issues/899.
Currently, https://github.com/sublimehq/Packages/issues/899#issuecomment-294446880 still fails, but https://github.com/sublimehq/Packages/issues/899#issuecomment-293856070 is fixed.
=> [C++] Fix static assert decl

Lua/Comments.tmPreferences
Been using this for years, just never bothered with submitting it until now.
=> [Lua] Add support for multiline comments

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
Fixes https://github.com/sublimehq/Packages/issues/1032
See: https://stackoverflow.com/questions/10721130/calling-constexpr-in-default-template-argument
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53464
See: https://bugs.llvm.org/show_bug.cgi?id=11851
=> [C++] [Objective-C] Fix template highlighting

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
redo https://github.com/sublimehq/Packages/pull/1043 - the original PR accidentally missed a match (along with it's corresponding scope and pop).
=> [C#] more stray brace detection

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] fix accessor brackets incorrectly being seen as a type

R/R.sublime-syntax, R/syntax_test_r.R
=> [R] handle closing square bracket

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
fixes https://github.com/sublimehq/Packages/issues/964
=> [CSS] improve (variable) identifier matching

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
=> [C++] [Objective-C] Fix issue 1069

R/R.sublime-syntax, R/syntax_test_r.R
=> [R] Two fixes

YAML/YAML.sublime-syntax, YAML/tests/syntax_test_block.yaml
=> [YAML] Fix comments starting a sequence

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Recognize escape sequences in docstrings

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] support code fences inside list items

Batch File/syntax_test_batch_file.bat
Issue: 
https://github.com/sublimehq/Packages/issues/1097
=> Removed trailing white space on Batch syntax test.

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] fix goto case bug

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] cope with stray underscores/asterisks in bold markup

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] HTML blocks fix - follow CommonMark spec

R/R.sublime-syntax, R/syntax_test_r.R
issue from R-Box https://github.com/randy3k/R-Box/issues/113
=> [R] include comments in lambda function

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] support case ... when syntax

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
- Fix ligature not working on comparison operators (#1194)
- [spaceship operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op)
- [nullable types](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types)
- [multi catch exception handling](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.mulit-catch-exception-handling)
=> [PHP] Add some PHP 7.x features

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] inline code spans can start with whitespace

HTML/Miscellaneous.tmPreferences, PHP/Indentation Rules.tmPreferences, PHP/PHP Source.sublime-syntax, PHP/PHP.sublime-syntax
=> [PHP] smarter indentation rules to ignore colons in strings

Java/Java.sublime-syntax, Java/syntax_test_java.java
This also adds support for annotations in lambda definitions.
=> [Java] Unify lambda and method params

Ruby/Ruby.sublime-syntax, Ruby/syntax_test_ruby.rb
close https://github.com/sublimehq/Packages/issues/1150
=> [Ruby] highlight "/"

Markdown/Markdown.sublime-syntax, Markdown/Symbol List - Reference Link.tmPreferences, Markdown/syntax_test_markdown.md
...and show them in the local symbol index - fixes #1133
=> [Markdown] scope link definitions with an entity.name scope

C++/C++.sublime-syntax, C++/C.sublime-syntax, C++/syntax_test_c.c, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/Objective-C.sublime-syntax, Objective-C/syntax_test_objc++.mm, Objective-C/syntax_test_objc.m
This PR does NOT fix https://github.com/sublimehq/Packages/issues/1078, but it is a step towards the fix.
=> [C++] [Objective-C] Allow line-continuations inside function parameter lists

C++/C++.sublime-syntax, C++/C.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
Fixes https://github.com/sublimehq/Packages/issues/1044.
=> [C++] [Objective-C] Fix Member template specialization after . or -> or ::

C++/C.sublime-syntax, C++/syntax_test_c.c, PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
- [C/C++] https://forum.sublimetext.com/t/dev-build-3145/32340/27
- [PHP] Add scopes for augmented operators
- [PHP] Fix the scope for the "." in ".5"
=> [C/C++,PHP] Fix ligatures for some operators

Java/Java.sublime-syntax, Java/syntax_test_java.java
=> [Java] Fix a few syntax bugs

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
Fix https://github.com/sublimehq/Packages/issues/1095
Ref: http://php.net/manual/en/function.include.php#example-125
=> [PHP] Fix include/require could be used as an expression

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] handle code fences in loose lists

Graphviz/Comments.tmPreferences
=> [Graphviz] add metadata to support toggle comment functionality

Python/Python.sublime-syntax, Python/syntax_test_python_strings.py
=> [Python] fix nested string placeholder detection being too eager

Groovy/Groovy.sublime-syntax, Groovy/syntax_test_groovy.groovy
=> [Groovy] Add word bounds to type in function definition

Makefile/Makefile.sublime-syntax, Makefile/syntax_test_makefile.mak
=> [Makefile] Fix interplay between "@" or "-" from Make and comments from shell

LaTeX/LaTeX.sublime-syntax, LaTeX/syntax_test_latex.tex
=> [LaTeX] fix regression

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
```php
echo $this->pro1::bar();
//                ^^^ variable.function
```
=> [PHP] Fix PHP static method call scope

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
=> [PHP] support embedded syntaxes in nowdoc sections

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
for consistency with other syntax definitions i.e. Python https://github.com/sublimehq/Packages/pull/1049
=> [Batch File] more specific number scoping

ASP/ASP.sublime-syntax, ASP/syntax_test_asp.asp
just like for other syntaxes e.g. batch files https://github.com/sublimehq/Packages/pull/1050
=> [ASP] more specific number scopes

Go/Go.sublime-syntax, Go/syntax_test_go.go
just like for PHP https://github.com/sublimehq/Packages/pull/1052
=> [Go] more specific number scoping

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Disable brace and pattern expansion in heredocs

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Add word boundary anchor to some keywords

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
=> [Batch File] fix set quoted string bug

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
fixes https://github.com/SublimeTextIssues/Core/issues/2075
=> [C#] support casted lambdas

Matlab/Matlab.sublime-syntax, Matlab/syntax_test_matlab.m
=> [Matlab] Fix highlight of functions with no return or argument

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
as used by Firefox chrome customizations - https://support.mozilla.org/en-US/questions/1178962#answer-1015047
=> [CSS] allow url function to be used in at-namespace

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] support strikethrough

C#/C#.sublime-syntax
this is just a better way to do it, so as not to pollute the `code_block` context - no new tests needed I think :)
=> [C#] tweak to code block handling outside of a class

Rails/Snippets/render-(partial)-(rp).sublime-snippet, Rails/Snippets/render-(partial-collection)-(rpc).sublime-snippet, Rails/Snippets/render-(partial-locals)-(rpl).sublime-snippet, Rails/Snippets/render-(partial-object)-(rpo).sublime-snippet, Rails/Snippets/render-(partial-status)-(rps).sublime-snippet
I would like to default to the new hash syntax
=> [Rails] Rails partial snippet

Rust/Rust.sublime-syntax, Rust/syntax_test_rust.rs
=> [Rust] fix nested array template arguments

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
supersedes https://github.com/sublimehq/Packages/pull/1373
=> [Markdown] support footnotes from PHP Markdown Extra

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
https://github.com/sublimehq/Packages/issues/1411
=> [Batch File] Fix highlight for parentheses in double quotes

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
=> [PHP] fix docblock comments that transition to normal comments

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix stray brackets in with statements

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Handles tagged templates where the tag is an arbitrary expression or where the tag is separated from the template string by whitespace or comments.
=> [JavaScript] Improved handling of tagged template strings.

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2
=> [C#] improvements to support C# 7.2

Java/Java.sublime-syntax, Java/Symbol List - Modules.tmPreferences, Java/syntax_test_java.java
Main feature of Java 9, now in full color.
=> [Java] Support for modules

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Ignore some invalid code instead of marking it.

PHP/Snippets/class-{-}.sublime-snippet
References:
- https://en.wikipedia.org/wiki/PHPDoc
=> [PHP] Fix PHPDoc for the "class" snippet

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp
Fixes https://github.com/sublimehq/Packages/issues/1456
=> [C++] Fix highlight for direct operator method calling

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
http://php.net/manual/en/language.generators.syntax.php#control-structures.yield.from
=> [PHP] Add highlight for "yield from" keyword

Batch File/Batch File.sublime-syntax, Batch File/syntax_test_batch_file.bat
Fixes https://github.com/sublimehq/Packages/issues/1475
=> [Batch File] fix some `set` string related bugs

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
fixes https://github.com/sublimehq/Packages/issues/1433
=> [C++/ObjC] Fix: operator definitions combined with template classes

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs
=> [C#] support expression bodied constructor methods

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Added/enhanced a number of tests to match. It turns out there weren't any tests for bracket property accesses.
=> [JavaScript] Added `begin` and `end` to many scopes.

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
Anonymous classes can pass arguments through to their constructors.
Ref: http://php.net/manual/en/language.oop5.anonymous.php
=> [PHP] Fix anonymous class with arguments

HTML/HTML.sublime-syntax
=> [HTML] Parse attribute names character-by-character

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
Fix https://github.com/sublimehq/Packages/issues/1545.
=> [PHP] Fix one-liner "include" does not pop

HTML/HTML.sublime-syntax, HTML/syntax_test_html.html
See [core issue #2354](https://github.com/SublimeTextIssues/Core/issues/2354).
Modified the test to make sure that the ignore-case flag is working.
=> [HTML] Remove isolated options in variables.

HTML/HTML.sublime-syntax
Re-fixes #1160, which was un-fixed in #1379.
=> [HTML] Fix indentation in style tags.

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
Fix #1067 and add tests for it
=> [CSS] Fix issue with CSS supports and rule list in block

R/R.sublime-syntax, R/syntax_test_r.R
improve some punctuation highlights
=> [R] improve some punctuation highlights

C++/C Single File.sublime-build, C++/C++ Single File.sublime-build
it's recommended to compile source.c by gcc
=> [C++] add C Single File.sublime-build

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Fixed a minor bug and added a test.
=> [JavaScript] Fixed highlighting for generator method star.

ShellScript/Shell-Unix-Generic.sublime-syntax, ShellScript/test/syntax_test_shell_unix_generic.sh
fixes https://github.com/sublimehq/Packages/issues/1603
=> [ShellScript] Fix: forgot prototype context in old Shell-Unix-Generic syntax

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Fix: subshell functions now highlight correctly

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
=> [JavaScript] Fix ending of blocks.

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
fixes https://github.com/sublimehq/Packages/issues/1626
=> [Markdown] support HTML tags inside GFM tables

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Fix: add lookahead for regex character group

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs
fixes https://github.com/sublimehq/Packages/issues/1630
=> [C#] better support for C#7 ValueTuples and deconstructions

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
=> [JavaScript] Fixed ASI bug with binary word operators.

Groovy/Groovy.sublime-syntax
Since Jenkinsfile is basically groovy adding it to groovy extension list
=> [Groovy] Add Jenkinsfile extension

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] improvements for clip-path polygon

Diff/diff.py
This commit does not introduce any functional changes.
It just provides the following changes to Diff/diff.py:
- sorts imports alphabetically by use (global, local)
- fix some smaller issues marked by pylint
=> [Diff] Fix linting issues

Makefile/Comments.tmPreferences
fixes https://github.com/SublimeTextIssues/Core/issues/2372
=> [Makefile] line comments should always be placed at the first column

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
fixes https://forum.sublimetext.com/t/c-wrong-syntax-highlighting-for-event-accessors/38853
=> [C#] support custom event accessors

C#/C#.sublime-syntax, C#/tests/syntax_test_Strings.cs
fixes https://github.com/sublimehq/Packages/issues/1730
=> [C#] don't treat GUIDs in strings as placeholder substitutions

Ruby/Ruby.sublime-syntax
=> Adds Podfile to Ruby sublime syntax

JavaScript/JSON.sublime-syntax
=> Added Pipfile.lock to list of json filetypes

C#/C#.sublime-syntax, C#/tests/syntax_test_Strings.cs
To match scopes for normal interpolated strings
Needed for completeness on facelessuser/BracketHighlighter#468
=> [C#] meta.string scope for interpolated verbatim strings

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Comments in `calc`

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
=> [JavaScript] Removed pointless variable.other.object scope.

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Feature at Stage 3: https://github.com/tc39/proposal-global
=> [JavaScript] Implement globalThis.

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js_support_builtin.js
Support `BigInt64Array` and `BigUint64Array`.
Stage 3: https://github.com/tc39/proposal-bigint
=> [JavaScript] Improved BigInt support.

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
https://drafts.csswg.org/css-grid/#grid-shorthand
e.g.:
```
grid: repeat(auto-fill, 5em) / auto-flow 1fr;
```
https://drafts.csswg.org/css-grid/#overview-grid
=> [CSS] auto-flow is a valid value for grid

PHP/Indentation Rules - heredoc end.tmPreferences, PHP/Indentation Rules.tmPreferences, PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
Ref: https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes
PHP 7.3 alpha 1 just released today :+1:
=> [PHP] Support PHP 7.3 Flexible Heredoc and Nowdoc Syntaxes

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
=> [JavaScript] yield template string.

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs, C#/tests/syntax_test_GeneralStructure.cs
This commit introduces no functional changes.
It just removes whitespace from blank lines and the end of lines.
=> [C#] Trim all whitespace

Scala/Scala.sublime-syntax
These are either [scala worksheet](https://github.com/scala-ide/scala-worksheet/wiki/Getting-Started) files or [ammonite script files](https://ammonite.io/#import$file)
=> [Scala] Add .sc files to scala

Lua/Indent.tmPreferences
Indenting fix for nested tables, and other additions and fixes.
Current:
Fixed:
=> [Lua] indent fixes

Python/Python.sublime-syntax
Used for [Vapoursynth](http://www.vapoursynth.com/) scripts.
=> [Python] Add vpy extension

Perl/Perl.sublime-syntax, Perl/syntax_test_perl.pl
This commit does not introduce any functional changes, but does fix some formatting issues with the section comments.
=> [Perl] Fix context section comments

SQL/SQL.sublime-syntax, SQL/syntax_test_sql.sql
=> [SQL] Add USING keyword

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Fix single value template instantiations in first-value

D/D.sublime-syntax, D/tests/syntax_test_d.d
Fixes #1894 with more edgecases supported.
Also fixes extraneous brackets not being marked invalid in some circumstances.
=> Small D fixes/improvements

Lua/Lua.sublime-syntax, Lua/tests/syntax_test_lua.lua
=> [Lua] Terminate string context on unexpected newline

Graphviz/Completions/Objects.sublime-completions, Graphviz/Graphviz.sublime-build
Add the png-version of the Graphviz [CLI commands](https://graphviz.gitlab.io/_pages/pdf/dot.1.pdf) (plus one for `dot` to make SVGs).
Also fix some completions that throw errors as they currently exist.
=> [Graphviz] Build system

Lua/Lua.sublime-syntax, Lua/tests/syntax_test_lua.lua
Fixes #1903.
```lua
if true
42
```
=> [Lua] Improve highlighting when typing an if statement.

Lua/Indent.tmPreferences
Including global functions for indentation.
=> [Lua] Indentation fix

Makefile/Makefile.sublime-syntax, Makefile/syntax_test_makefile.mak
=> [Makefile] Fix line continuation in comments

Perl/Perl.sublime-build
This commit adds a Perl.sublime-build file with commands to
1. run the file
2. perform a syntax check on the file
This commit is inspired by Python.sublime-build
=> [Perl] Add sublime-build

Lua/Lua.sublime-syntax, Lua/tests/syntax_test_lua.lua
=> [Lua] Recognize long strings in table constructors

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Also extend a few related tests. In addition to being correct, should fix Thom1729/Sublime-JS-Custom#60.
=> [JavaScript] Add meta.string scopes.

YAML/YAML.sublime-syntax, YAML/tests/syntax_test_flow.yaml
Kinda hard to imagine how this could have gone unnoticed for 4 years, but apparently it has.
=> [YAML] Fix escape sequences to recognize hex digits

JavaScript/JavaScript.sublime-syntax
=> [JavaScript] Allow node-specific variables as valid identifiers

PHP/syntax_test_php.php, SQL/SQL.sublime-syntax, SQL/syntax_test_sql.sql
=> [SQL] Logical operator and `*` scopes

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
Similar to https://github.com/sublimehq/Packages/pull/2012
=> [PHP] Fix heredocs

Makefile/Makefile.sublime-syntax, Makefile/syntax_test_makefile.mak
=> [Makefile] Ignore nested define directives

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
First part of #1793
__Previously__
__Now__
=> [C++/ObjC++] Improve function call syntax

Java/Java.sublime-syntax, Java/syntax_test_java.java
=> [Java] Fix multiple class inheritance

D/D.sublime-syntax, D/tests/syntax_test_d.d
Fix some small bugs/missing syntax handling
=> [D] various fixes

Groovy/Groovy.sublime-syntax, Groovy/syntax_test_groovy.groovy
=> [Groovy] Fix line continuation

Java/Java.sublime-syntax, Java/syntax_test_java.java, Java/syntax_test_jsp.jsp
=> [Java] Update keyword scopes

Java/Java.sublime-syntax
This PR is about removing captureing groups in various situations as we found them to regress performance a little bit.
For some more details, please refer to the commit messages.
=> [Java] Some code cleanups

SQL/SQL.sublime-syntax, SQL/syntax_test_sql.sql
=> [SQL] `exists` is a logical operator

PHP/PHP Source.sublime-syntax, PHP/syntax_test_php.php
https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html
=> [PHP] Add scope for phpdoc's {@inheritdoc} 

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js_support_builtin.js
[Promise.any](https://github.com/tc39/proposal-promise-any) (Stage 3)
[Promise.allSettled](https://github.com/tc39/proposal-promise-allSettled) (Stage 4)
=> [JavaScript] Add Promise.any|allSettled

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
[Dynamic import](https://github.com/tc39/proposal-dynamic-import) (Stage 4)
=> [JavaScript] Add dynamic import expression.

Rails/Snippets/Create-controller-class.sublime-snippet
before_filter -> before_action, see: https://guides.rubyonrails.org/action_controller_overview.html#filters
=> update hook in actually rails 5.x

.github/ISSUE_TEMPLATE/01-bug-syntax-highlighting.md, .github/ISSUE_TEMPLATE/02-bug-file-indexing.md, .github/ISSUE_TEMPLATE/03-supporting-files.md, .github/PULL_REQUEST_TEMPLATE/01-syntax-update-small.md, .github/PULL_REQUEST_TEMPLATE/02-syntax-update-significant.md, .github/PULL_REQUEST_TEMPLATE/03-supporting-files.md
I cannot seem to test the PR template, but I'm reasonably happy with these minimal issue templates. I am hoping to avoid some of the screenshot-only and duplicate bug reports.
If anyone has suggestions or knows how to put content directly into the issue title itself, please let me know.
=> Add Issue and PR templates

Java/Java.sublime-syntax, Java/syntax_test_java.java
Fixes #1404
This PR
1. adds support for hexadecimal floating point numbers
2. improves parsing performance by about 16%
3. introduces some variables to improve readability of the number match patterns.
4. scopes all trailing/leading underscores illegal in order to give a hit about them not to be allowed while keeping the rest of the number highlighted correctly in order to avoid color changes during typing.
5. adds dozens of test cases to ensure all the various states of incomplete or illegal numbers.
6. rearranges the test cases to make the order match the order of the rules in the sublime-syntax
*Note:*
The benchmark was made with all `a = ...;` test cases of this commit put into a single file and duplicated to get a file with about 10k lines of code. Parsing time before (233ms) after …
=> [Java] Improve numbers

Clojure/Clojure.sublime-syntax, Clojure/tests/syntax_test_clojure.clj
This PR ...
1. applies numeric scopes according to the scope naming guidelines
2. simplifies the numeric literal suffixes
3. fixes floating point pattern not to match integers by accident
4. renames the numeric variables
=> [Clojure] Improve numbers

Lua/Lua.sublime-syntax, Lua/tests/syntax_test_lua.lua
1. applies numeric scopes according to the scope naming guidelines
2. distinguishes between floats and integers
=> [Lua] Improve numbers

Python/Python.sublime-syntax, Python/syntax_test_python.py
Via https://github.com/sublimehq/Packages/pull/2166.
=> [Python] punctuation.definition.numeric.base

Python/Python.sublime-syntax, Python/syntax_test_python.py
Same as https://github.com/sublimehq/Packages/pull/2161 but for Python.
=> [Python] keyword.declaration.*

Diff/Diff.sublime-syntax, Diff/syntax_test_diff.diff
=> [Diff] Make scopes consistent (backwards compatible)

JavaScript/Comments.tmPreferences
Also fixes https://github.com/20Tauri/DoxyDoxygen/issues/145
=> [TS/JSX] Fix comment (ctrl+/) doesn't not work

Java/Java.sublime-syntax, Java/syntax_test_java.java
For situations like this:
```java
List<@NotBlank(message="Address must not be blank") String> addresses;
```
=> [Java] Allow annotations in generics

Git Formats/Git Common.sublime-syntax, Git Formats/syntax_test_git_config
See
- git/git@c22f63c
- git/git@d37cfe3
=> [Git] Add new v2.25.0 pretty-formats

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
- Reuse existing contexts where possible.
- Detect arrow functions with a single bare parameter.
- Add tests.
=> [JavaScript] Improve implementation of arrow function branching.

Git Formats/Git Ignore.sublime-syntax
see: https://www.git-scm.com/docs/git-sparse-checkout
=> [Git Formats] Assign git ignore syntax to sparse-checkout

Clojure/Symbol Index - Hide Special Functions.tmPreferences
1. renames the symbol index file
2. tweaks its content
=> [Clojure] Fix tmPreferences

C#/Symbol List - Inner Function.tmPreferences
Add class properties to <kbd>cmd</kbd>+<kbd>R</kbd>, and add `(…)` to functions like Python does.
=> [C#] Index properties

ShellScript/Bash.sublime-syntax, ShellScript/commands-builtin-shell-bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh, ShellScript/tools/update-commands.py
Fixes #2306
Fixes #2311
For details, please refer to the commit messages
=> [ShellScript] Fix merged compact flags highlighting

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
=> [C#] scope event delegates correctly

Python/Python.sublime-syntax
See <https://docs.python.org/3/library/exceptions.html#ResourceWarning>.
Bye :wave:
=> [Python] Adds `ResourceWarning` to builtins exceptions list

PHP/PHP.sublime-completions
Not all but almost. 
The diff is too large to be shown on GitHub. The whole file is on https://github.com/jfcherng/Sublime-Official-Packages/blob/feat-php-completion-details/PHP/PHP.sublime-completions
---
Data source: https://www.php.net/distributions/manual/php_manual_en.tar.gz
Dealt with scripts: [php-completion-add-details.zip](https://github.com/sublimehq/Packages/files/4741569/php-completion-add-details.zip)
=> [PHP] Add lots of "details" fields for AC

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] correctly scope escaped html tags

Markdown/Markdown.sublime-syntax
Add yaml syntax highlight to code blocks
=> [Markdown] Add YAML syntax highlight to code blocks

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Fixes https://github.com/sublimehq/Packages/issues/2349#issuecomment-618329776
---
@Thom1729 feel free to take over this since you definitely have better understanding than me in JS syntax definition rules to do this PR
=> [JavaScript] Fix optional chaining typos

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix lambda termination in list/dict/set

HTML/HTML.sublime-syntax, HTML/html_completions.py
You have to add `&` in your HTML/XML `auto_complete_triggers` to see it working. Thanks to @FichteFoll for the `html.entities` tip.
Apparently, I cannot reopen the other PR after force-pushing. 🤷
=> [HTML] Entity completion

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
=> [JavaScript] Fix bug with block comment after line continuation.

Markdown/Markdown.sublime-syntax
Take advantage of the lazy embedd.
=> [Markdown] Add fenced perl code blocks

HTML/HTML.sublime-syntax, HTML/syntax_test_html.html
specs: https://url.spec.whatwg.org/#userinfo-percent-encode-set
Addresses a "lively" discussion at https://forum.sublimetext.com/t/advanced-other-color-or-hide-html-20-in-st-user-interface/51447
=> [HTML] Add scopes for utf8 percent encoded characters

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/syntax_test_objc++.mm
* Update syntax definitions for C++ and Objective-C++
* Add new tests
=> [C/C++] Recognize C++20 spaceship operator

XML/DTD.sublime-syntax, XML/XML.sublime-syntax
This commit...
1. updates XML/DTD syntax to sublime-syntax version 2.
2. sorts the main keys according to proposal #2430
3. sorts hidden file extensions
4. removes some quotation marks from values.
=> [XML] Update to sublime-syntax version 2

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
Yet another one why we didn't notice this... so weird
=> [PHP] Add scope for ternary operator

CSS/Default.sublime-keymap
Fixes https://github.com/sublimehq/sublime_text/issues/3569
=> [CSS] Fix commit completion using enter

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Fixes the bug @rwols reported in #1950.
=> [JavaScript] Implement private methods.

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix unpack operators of first function-call arguments

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Fix mixin not being considered a type

C++/C++.sublime-syntax, C++/C.sublime-syntax, C++/syntax_test_c.c, C++/syntax_test_cpp.cpp, Objective-C/syntax_test_objc++.mm, Objective-C/syntax_test_objc.m
Adds missing patterns to match suffixes of hex floats.
=> [C/C++] Fix hexadecimal floating point numbers

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs, C#/tests/syntax_test_GeneralStructure.cs, C#/tests/syntax_test_Generics.cs, C#/tests/syntax_test_Operators.cs, C#/tests/syntax_test_c#.cs
This implements the approach for meta scopes suggested in [#2460 (comment)](https://github.com/sublimehq/Packages/pull/2460#issuecomment-680957362).
=> [C#] Add meta.number

Regular Expressions/RegExp.sublime-syntax
=> [Regular Expressions] Match literal characters greedily

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js.js
Reported by @JackGoff98 in https://github.com/sublimehq/Packages/pull/2476#issuecomment-690529563.
=> [JavaScript] Fix scoping of called private method names.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Interface inheritance

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Support function parameter decorators

JavaScript/JSX Comments.tmPreferences, JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
For #2461. See discussion there.
=> [JSX] Commenting

D/D.sublime-syntax, D/tests/syntax_test_d.d, D/tests/syntax_test_old.d
=> [D] Add meta.number

C++/C++.sublime-syntax, C++/C.sublime-syntax, C++/syntax_test_c.c, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax, Objective-C/Objective-C.sublime-syntax, Objective-C/syntax_test_objc++.mm, Objective-C/syntax_test_objc.m
=> [C/C++/Objc/Objc++] Add meta.number

Go/Go.sublime-syntax, Go/syntax_test_go.go
=> [GO] Add meta.number

Haskell/Haskell.sublime-syntax, Haskell/syntax_test_haskell.hs
=> [Haskell] Add meta.number

Clojure/Clojure.sublime-syntax, Clojure/tests/syntax_test_clojure.clj, Clojure/tests/syntax_test_clojure_old.clj, Markdown/syntax_test_markdown.md
=> [Clojure] Add meta.number

OCaml/OCaml.sublime-syntax, OCaml/syntax_test_ml.ml
=> [OCaml] Add meta.number

Scala/Scala.sublime-syntax, Scala/syntax_test_scala.scala
=> [Scala] Add meta.number

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css, HTML/syntax_test_html.html
This commit applies updated meta.number scope naming guidelines and sorts numeric contexts alphabetically.
=> [CSS] Update meta.number constant.numeric

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
=> [PHP] Update meta.number constant.numeric

Java/Java.sublime-syntax, Java/syntax_test_java.java
=> [Java] Update meta.number constant.numeric

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Implement parenthesized types.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_tsx.tsx
=> [TypeScript] Fix some type modifiers in dotted types.

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
Fixes #1797
Fixes #2369
For details please refer to commit messages.
=> [CSS] Improve var() functions

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
Minor tweak for 7608ae7d6c33850d680a0e2a07d49f409b6c817f.
=> [TypeScript] Fix minor bug with left shift operator.

Matlab/Matlab.sublime-syntax, Matlab/syntax_test_matlab.m
=> [Matlab] Fix ellipsis comments

SQL/SQL.sublime-syntax, SQL/syntax_test_sql.sql
This PR adds support for 'ADD COLUMN/CONSTRAINT/INDEX/...' expression but also makes some existing expressions more robust against white space characters.
=> [SQL] add support for 'add column/constraint/index/...' expression

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] correctly scope ATX headings immediately after list items

C#/C#.sublime-syntax, C#/tests/syntax_test_GeneralStructure.cs
https://discord.com/channels/280102180189634562/280102180189634562/773291314984910849
=> [C#] Add string scopes to characters

C#/C#.sublime-syntax, C#/tests/syntax_test_C#7.cs, C#/tests/syntax_test_C#8.cs, C#/tests/syntax_test_C#9.cs
improvements to the syntax highlighting to cater for C#9 - including pattern matching :)
https://dotnetcoretutorials.com/2020/08/10/relational-pattern-matching-in-c-9/
https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/#improved-pattern-matching
=> [C#] improvements to the syntax highlighting to cater for C#9

ASP/ASP.sublime-syntax
ASP is visual basic. Thus we can also use that syntax for vbs files.
=> [ASP] Add vbs file extension

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
Fixes an issue discussed at https://discord.com/channels/280102180189634562/280157121897562114/777870917673156628
=> [ShellScript] Remove line continuation from comments

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
Fixes #2632.
Also adds more tests for number literal types.
=> [TypeScript] Implement negative number literal types.

Go/Go.sublime-syntax, Go/syntax_test_go.go
=> [Go] Fix decimal point scope in floats

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Fix negative value highlighting

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Fix leading combinators in selectors

Markdown/Markdown.sublime-syntax
=> [Markdown] Add JSP support in fenced code blocks

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Add scope for anchor path separator

ShellScript/test/syntax_test_bash.sh
This commit makes various tests more precise.
It does not change syntax itself.
=> [ShellScript] Improve various test cases

JSON/Default.sublime-keymap
This PR proposes to add some key bindings which fix some core functions for JSON syntax.
Some more details may be found in commit messages.
=> [JSON] Fix auto-pair and auto-indent while typing

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Fix extent of function name in assignment.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Allow interface to extend multiple interfaces.

Markdown/Default.sublime-keymap
Please refer to commit messages for details about the changes.
=> [Markdown] Improve auto-pairing key bindings

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Implement template string types.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#abstract-construct-signatures.
=> [TypeScript] Implement constructor types.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
Fixes a couple of bugs where TypeScript would fail the JavaScript syntax test.
=> [TypeScript] Fix regressions relative to JavaScript.

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
Fixes #2756
A table may not start with an hyphon.
=> [Markdown] Fix 2nd list item being scoped as table header

Ruby/Ruby.sublime-syntax
[Pry](https://github.com/pry/pry) configuration, similar to .irbrc
=> [Ruby] Add .pryrc support

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Fix type arguments in decorators.

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js_support_dom.js
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval
=> [JavaScript] add setInterval and clearInterval

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
For TypeScript 4.3. See https://github.com/microsoft/TypeScript/pull/39669.
=> [TypeScript] Implement override keyword.

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Support definite annotation for class fields.

Markdown/Markdown.sublime-syntax, Markdown/syntax_test_markdown.md
=> [Markdown] Allow indented reference links after lists

Lua/Lua.sublime-syntax
Fixes https://github.com/sublimehq/Packages/issues/2875
=> [Lua] Fix shebang

C#/C#.sublime-syntax, C#/tests/syntax_test_C#9.cs
=> [C#] Correctly highlight records which use positional syntax

HTML/Snippets/html.sublime-snippet, PHP/PHP.sublime-completions, PHP/Snippets/new-array(-).sublime-snippet, ShellScript/Snippets/#!-usr-bin-env-(!env).sublime-snippet
Fixes https://forum.sublimetext.com/t/st4-php-autocompletion-workflow/58405
We don't need AC for built-in functions when in `string` or `comment`.
=> [PHP] Fix AC scope

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
This PR adds support for new media queries features:
*   [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
*   [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
=> [CSS] Add support for `prefers-color-scheme` and `prefers-reduced-motion`

README.md
https://www.sublimetext.com/dev
- `version: 2` is introduced in 4075
- as per 4095's changelog: Resolve some bugs with syntax definitions that use branching
=> [Docs] Update readme for ST 4

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix comments in import statements

D/D.sublime-syntax
https://dlang.org/spec/type.html#aliased-types
=> [D] Updated the list of basic_types to include aliased types

ASP/HTML (ASP).sublime-syntax, ASP/syntax_test_asp.asp
Fixes https://forum.sublimetext.com/t/classic-asp-syntax-selection/60164/7
The primary commit of this PR is https://github.com/sublimehq/Packages/commit/5c57c0c4706f571eb5d1501b4d139c2feb7d80cb
This PR is based on the branch from PR #2831 as it would need to be implemented twice otherwise.
Hope that can merged without conflicts then.
=> [ASP] Add vbscript syntax highlighting in script tags

Ruby/Ruby.sublime-syntax, Ruby/syntax_test_ruby.rb
=> [Ruby] fix singleton class declarations

Go/Go.sublime-syntax, Go/syntax_test_go.go
=> [Go] Fix floating point placeholder in format strings

HTML/HTML (Plain).sublime-syntax, HTML/syntax_test_html.html
Fixes https://github.com/sublimehq/Packages/issues/3010
=> [HTML] Fix false positive comment ending punctuation

Makefile/Makefile.sublime-syntax, Makefile/syntax_test_makefile.mak
=> [Makefile] Fix multiline comments

C++/C++.sublime-syntax, C++/C.sublime-syntax, C++/syntax_test_c.c, C++/syntax_test_cpp.cpp, Objective-C/Objective-C++.sublime-syntax
1. bring out numeric constants in variables section
2. preprocessor numeric constants detection improvement
=> [C/C++] syntax improvement: numeric constants detection improvement

Python/Python.sublime-syntax
Resolves stale https://github.com/sublimehq/Packages/pull/2916
=> [Python] Add `smk` to `file_extensions`

D/D.sublime-syntax, D/tests/syntax_test_d.d
Fixes #3052
Fixes #3058
Two issues same line of code to fix.
=> [D] Fix pointer variable declarations

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Fix syntax highlight of templated UDAs

R/R.sublime-syntax, R/syntax_test_r.R
=> [R] Add native pipe operator support

ShellScript/Bash.sublime-syntax, ShellScript/commands-builtin-shell-bash.sublime-syntax, ShellScript/commands-builtin-shell-bash.yml, ShellScript/test/syntax_test_bash.sh
This commit ensures correct command highlighting after exec keywords.
=> [ShellScript] Fix exec command highlighting

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
Fixes https://github.com/sublimehq/Packages/issues/3134
=> [PHP] Fix `)` after closure is not scoped

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
=> [PHP] Fix closing parentheses in for loops

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Fix highlighting of nested ternary expressions

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
- Fixes https://github.com/sublimehq/Packages/issues/3139
- Add colon scope for https://github.com/sublimehq/Packages/issues/3140
=> [PHP] Fix comma scope in arrays

C#/C#.sublime-syntax, C#/tests/syntax_test_Generics.cs
=> [C#] fix generic function calls

JavaScript/tests/syntax_test_js_regexp.js
This commit illustrates issue #3150 not to be an issue of ST's JavaScript syntax.
=> [JavaScript] Add some slash related regexp test cases

PHP/PHP Source.sublime-syntax
- https://www.php.net/manual/en/class.unitenum.php
- https://www.php.net/manual/en/class.backedenum.php
=> [PHP] Add built-in interfaces: UnitEnum, BackedEnum

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Support new import type syntax

JavaScript/JavaScript.sublime-syntax, JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_js_import_export.js
See https://github.com/tc39/proposal-import-assertions.
It's in Stage 3, which is our benchmark for inclusion. It is also part of TypeScript 4.5.
=> [JavaScript] Support import assertions

JavaScript/TSX.sublime-syntax, JavaScript/tests/syntax_test_tsx.tsx
=> [TSX] Support generic components

README.md
- fix links with `https`
- add reference section with links to docs
=> [meta] update README

Git Formats/Git Rebase.sublime-syntax, Git Formats/tests/syntax_test_git_rebase
=> [Git Formats] Add highlighting for missing command descriptions

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Support type in export braces

C++/C++.sublime-syntax, C++/syntax_test_cpp.cpp
Implement support for C++20 modules. (Fixes #2867)
=> [C++] Implement support for C++20 modules.

Python/Console Input Widget.sublime-settings
Resolves https://github.com/sublimehq/Packages/issues/3229
=> [Python] Add "Console Input Widget.sublime-settings"

Haskell/Haskell.sublime-syntax, Haskell/tests/syntax_test_shebang.hs
The keywords `cabal` and `stack` are borrowed from
- https://github.com/haskell/haskell-language-server/blob/4b8f9d53bed3e775ccd120d9a2471ae374a88db3/install.hs#L1
- https://github.com/haskell/haskell-language-server/blob/4b8f9d53bed3e775ccd120d9a2471ae374a88db3/GenChangelogs.hs#L1
=> [Haskell] Add shebang highlighting

.github/workflows/ci.yml
=> [meta] Update workflow

PHP/PHP Source.sublime-syntax, PHP/PHP.sublime-syntax, PHP/tests/syntax_test_php.php
Fixes https://github.com/sublimehq/Packages/issues/3246
=> [PHP] Fix scope for invalid PHP opening tag

YAML/YAML.sublime-syntax, YAML/tests/syntax_test_flow.yaml, YAML/tests/syntax_test_types.yaml
=> [YAML] Rename mapping separator scopes

Git Formats/Git Attributes.sublime-syntax, Git Formats/Git Commit.sublime-syntax, Git Formats/Git Common.sublime-syntax, Git Formats/Git Link.sublime-syntax, Git Formats/Git Log.sublime-syntax, Git Formats/Git Rebase.sublime-syntax, Git Formats/tests/syntax_test_git_attributes, Git Formats/tests/syntax_test_git_commit, Git Formats/tests/syntax_test_git_link, Git Formats/tests/syntax_test_git_log, Git Formats/tests/syntax_test_git_rebase
=> [Git Formats] Rename mapping separator scopes

Java/JavaProperties.sublime-syntax, Java/tests/syntax_test_java_properties.properties
=> [Java] Rename mapping separator scopes

Haskell/Haskell.sublime-syntax, Haskell/tests/syntax_test_haskell.hs
Found at https://gitlab.haskell.org/ghc/ghc/-/blob/master/ghc/Main.hs#L5
=> [Haskell] Add OPTIONS directive

C++/Indentation Rules.tmPreferences, C++/tests/syntax_test_indent_common.c++
This commit replaces that setting by explicit increase/decrease indent patterns.
related with #3277
=> [C/C++/ObjC/ObjC++] Fix bracket indentation

Java/Java - Indentation Rules.tmPreferences, Java/tests/syntax_test_java_indentation.java
This commit replaces that setting by explicit increase/decrease indent patterns.
related with #3277
=> [Java] Fix bracket indentation

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
This PR refactors class declarations in order to
1. fix duplicated `meta.block` scopes
2. add `meta.class` scope
3. convert multiple anonymous into named contexts
=> [PHP] Refactor class declarations

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
This PR refactors enum declarations after the scheme of class declarations. It required some rework of type hints as well.
=> [PHP] Refactor enum declarations

CSS/CSS.sublime-settings
=> [CSS] Add hyphen to list of sub-word-separators

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
This PR provides some minor code style improvements without changing syntax's behavior.
The changes are explained in each commit.
=> [PHP] formal changes

Regular Expressions/RegExp.sublime-syntax, Regular Expressions/syntax_test_regexp.re
=> [Regular Expressions] fix capture group name over-eagerness

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Rename mapping separator scopes

Erlang/Erlang.sublime-syntax, Erlang/syntax_test_erlang.erl
=> [Erlang] Rename mapping separator scopes

C#/C#.sublime-syntax, C#/tests/syntax_test_C#8.cs
=> [C#] fix using declaration when inside a control block

CSS/CSS.sublime-syntax
This commit just contains some cosmetics.
=> [CSS] Tweak indentation of multi-line variables

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
see: https://developer.mozilla.org/en-US/docs/Web/CSS/length
=> [CSS] Add missing length units

Markdown/Code Block Syntaxes.sublime-completions, Markdown/Markdown.sublime-syntax
see: https://github.com/SublimeText-Markdown/MarkdownEditing/pull/688
=> [Markdown] Add `yml` language tag in frontmatter and code blocks

PHP/PHP Source.sublime-syntax
=> [PHP] Make use of global_modifier variable

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Add viewport units

Matlab/Matlab.sublime-syntax, Matlab/syntax_test_matlab.matlab
Align with other syntaxes and scope naming guidelines.
=> [Matlab] Adjust scope for path in qualified base class

HTML/html_completions.py
=> [HTML] Fix slot name attribute completion

JavaScript/JavaScript.sublime-syntax
This PR adds named contexts for literal strings and templates to better support inheritance.
It doesn't change behavior.
=> [JavaScript] Refactor literal strings

Java/Java.sublime-syntax, Java/tests/syntax_test_java.java
=> [Java] Fix default method modifier

Markdown/Markdown.sublime-syntax, Markdown/tests/syntax_test_markdown.md
=> [Markdown] Add support for LaTeX math blocks

Python/Python.sublime-syntax, Python/syntax_test_python_strings.py
=> [Python] Fix f-string format spec

Erlang/Erlang.sublime-syntax, Erlang/syntax_test_erlang.erl
The `maybe` keyword is introduced by OTP-25.
=> [Erlang] Add support for `maybe` statements

HTML/html_completions.py
Fixes #3467 regression introduced in https://github.com/sublimehq/Packages/commit/9e35426d39030880ddf952caab000ec7a5eadf24.
=> [HTML] Fix html completion not working prior to tag

PHP/Embeddings/CSS (for PHP double-quoted).sublime-syntax, PHP/Embeddings/CSS (for PHP single-quoted).sublime-syntax, PHP/Embeddings/JavaScript (for PHP double-quoted).sublime-syntax, PHP/Embeddings/JavaScript (for PHP single-quoted).sublime-syntax, PHP/PHP.sublime-syntax, PHP/tests/syntax_test_php.php
Fixes https://discord.com/channels/280102180189634562/280157121897562114/1006265433244041298
=> [PHP] Fix quoted PHP strings in tag attributes

JavaScript/Fold.tmPreferences
=> [JavaScript] Re-enable indentation based folding

JavaScript/JavaScript.sublime-syntax, JavaScript/tests/syntax_test_js_import_export.js
Reported by mitranim on Discord.
=> [JavaScript] Allow string import/export aliases

CSS/CSS.sublime-syntax, CSS/syntax_test_css.css
=> [CSS] Add support for host() pseudo-class function

Rust/Rust.sublime-syntax, Rust/tests/syntax_test_enum.rs, Rust/tests/syntax_test_functions.rs, Rust/tests/syntax_test_generics.rs, Rust/tests/syntax_test_traits.rs, Rust/tests/syntax_test_types.rs
See commits for more details.
|Before|After|
|:-|:-|
|![2022-10-23_14-53-32](https://user-images.githubusercontent.com/931051/197393263-fedc76b5-a3e2-45f8-bff4-4c1a8f542e11.png)|![2022-10-23_14-53-13](https://user-images.githubusercontent.com/931051/197393238-cec87501-8595-4c88-975e-941ae71e3e47.png)|
=> [Rust] Various tweaks and fixes to type matching

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix parenthesized with statements

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
=> [PHP] Fix php end tags in block comments

CSS/completions/properties.py
This PR is an excerpt from #3526.
The goal is to have a PR per topic. Typing and typos are unrelated.
=> [CSS] Fix missing commas in property completions

PHP/Embeddings/SQL (for PHP Interpolated).sublime-syntax, PHP/tests/syntax_test_php.php
=> [PHP] Fix SQL string interpolation

YAML/YAML.sublime-syntax, YAML/tests/syntax_test_block.yaml
=> [YAML] Fix block scalar headers

Perl/Perl.sublime-syntax, Perl/syntax_test_perl.pl, Ruby/Ruby.sublime-syntax
see: #3607
Co-authored-by @ngc92
=> [Perl/Ruby] Fix scope typo

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
This commit scopes all strftime fomrat placeholders. 
see: https://www.php.net/manual/en/function.strftime
inspired by: https://forum.sublimetext.com/t/color-schemes-doesnt-work-properly/66479
=> [PHP] Add strftime() placeholders

.github/workflows/ci.yml
- do not run tests on or for `st3`-branch
- run tests on or for `develop/`-branches
=> [meta] run tests on certain branches

.github/workflows/ci.yml
- also run when switching a PR from "draft" to "ready for review"
=> [meta] update ci workflow

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Fix !in operator highlighting

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Fix comments in compound/test expressions

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] fix pattern expansions in test expressions

Go/Go.sublime-syntax, Go/syntax_test_go.go
=> [Go] improve control flow scopes

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php
=> [PHP] Fix single expression termination in ternaries

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix multi assignment highlighting

JavaScript/TypeScript.sublime-syntax, JavaScript/tests/syntax_test_typescript.ts
=> [TypeScript] Allow arbitrary binding patterns in function types

Python/Python.sublime-syntax, Python/syntax_test_python.py
=> [Python] Fix comments in function parameters

C#/C#.sublime-syntax, C#/tests/syntax_test_C#8.cs
=> [C#] Fix global `using var` declarations

CSS/completions/properties.py
=> [CSS] Fix implicit concatenation error

Go/Fold.tmPreferences
This PR proposes to 
1. make multi-line strings foldable
2. include trailing newline of comments into fold region
=> [Go] Comment and String folding rules

Batch File/Batch File.sublime-syntax, Batch File/tests/syntax_test_batch_file.bat
=> [Batch File] Fix at operator highlighting

Git Formats/Completions/Git Attributes - Diff.sublime-completions
Source: https://git-scm.com/docs/gitattributes#_generating_diff_text
=> [Git Formats] Add missing diff drivers

Python/Python.sublime-syntax, Python/tests/syntax_test_python.py
Fixes #3794
Properly handle unpack operators vs. arithmetic operators within dicts and sets.
=> [Python] Fix set and dict comprehension with asterisk

C#/C#.sublime-syntax, C#/tests/syntax_test_C#11.cs
=> [C#] Fix premature bailout of block strings

PHP/PHP Source.sublime-syntax, PHP/tests/syntax_test_php.php, Python/Python.sublime-syntax, Python/tests/syntax_test_python_strings.py
`MERGE INTO` is ANSI SQL: https://en.wikipedia.org/wiki/Merge_(SQL)#Usage `BEGIN` works for MySQL and TSQL
=> [Python] add more sql indicators

Batch File/Batch File.sublime-syntax
=> [Batch File] Fix typo in `ctl-goto-label`

Java/Java.sublime-syntax, Java/tests/syntax_test_java.java
New in JDK 21
see: https://openjdk.org/jeps/443
=> [Java] Add JEP443: Unnamed Patterns and Variables

Java/Java.sublime-syntax, Java/tests/syntax_test_java.java
=> [Java] Fix primitive class literals

Batch File/Batch File.sublime-syntax, Batch File/tests/syntax_test_batch_file.bat
This addresses the concern expressed in #3865.
=> [Batch File] Expand comment scope to subsequent colons

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Add declare -I

ShellScript/Bash.sublime-syntax, ShellScript/test/syntax_test_bash.sh
=> [ShellScript] Fix grouped test r-value termination

Go/Go.sublime-syntax, Go/tests/syntax_test_go.go
=> [Go] fix pipe after square brackets

Markdown/Code Block Syntaxes.sublime-completions, Markdown/Markdown.sublime-syntax, Markdown/tests/syntax_test_markdown.md
=> [Markdown] Add support for LaTeX in fenced code blocks

C#/C#.sublime-syntax, C#/tests/syntax_test_C#10.cs, C#/tests/syntax_test_C#11.cs, C#/tests/syntax_test_C#9.cs
=> [C#] support primary constructors not just for records

Batch File/Batch File.sublime-syntax, Batch File/tests/syntax_test_batch_file.bat
=> [Batch File] Fix redirection after certain commands

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Add support for named arguments

D/D.sublime-syntax, D/tests/syntax_test_d.d
Fixes #3391.
Changes:
- Add support for attributes in enum members…
=> [D] Add support for enum member attributes

Rust/Rust.sublime-syntax, Rust/tests/syntax_test_identifiers.rs
=> [Rust] Fix identifiers in let-based pattern matching

Rust/Cargo.sublime-build
See individual commit messages.
=> [Rust] Fix regexps for Cargo build system & add clippy variant

Batch File/Default.sublime-keymap
For use in delayed expansion mode.
=> [Batch File] Auto-pair exclamation mark

Java/Java.sublime-syntax, Java/tests/syntax_test_java.java
=> [Java] Fix annoted enum constans

Git Formats/Git Code Owners.sublime-syntax, Git Formats/Git Common.sublime-syntax, Git Formats/tests/syntax_test_git_codeowners
Live example can be found [here][1].
[1]: https://github.com/gradle/gradle/blob/master/.github/CODEOWNERS#L18
=> [Git Formats] Support inline comments in CODEOWNERS

Go/Go.sublime-syntax, Go/tests/syntax_test_template.html, Go/tests/syntax_test_template.yaml
=> [Go] Fix go interpolation termination

.github/workflows/ci.yml
Fix deprecation warning, when running syntax tests.
=> [CI] Update actions/checkout

Java/Java.sublime-syntax, Java/tests/syntax_test_java.java
Implements JEP 476, shipped with Java 23+
see: https://openjdk.org/jeps/476
=> [Java] Add support for module imports

Groovy/Groovy.sublime-syntax, Groovy/syntax_test_groovy.groovy, Groovy/tests/syntax_test_Strings.groovy, Groovy/tests/syntax_test_jenkins.Jenkinsfile
[Groovy] various improvements which should hopefully please people working with Jenkins:
- many scope fixes
- support for highlighting embedded Bash scripts
- move some anonymous contexts to named contexts
=> [Groovy] various improvements

ShellScript/Bash.sublime-syntax, ShellScript/Bash/tests/syntax_test_scope.bash
=> [ShellScript] Fix read options

D/D.sublime-syntax, D/tests/syntax_test_d.d
=> [D] Add support for interpolated strings

.github/ISSUE_TEMPLATE/01-bug-syntax-highlighting.yml, .github/ISSUE_TEMPLATE/02-bug-file-indexing.yml, .github/ISSUE_TEMPLATE/03-supporting-files.yml
=> [meta] Fix issue template bug tags

SQL/MySQL.sublime-syntax, SQL/tests/syntax/syntax_test_mysql.sql
- improve `SELECT INTO` highlighting
- improve `SHOW` highlighting
=> [SQL] More MySql improvements

R/R Console.sublime-syntax, R/R.sublime-syntax, R/Rd (R Documentation).sublime-syntax
- bump v2
- add section headers
- add prototype contexts
- move vars to EOF
- add named contexts for numbers and constants
Co-authored-by: Michael B. Lyons <michaelblyons@users.noreply.github.com>
Co-authored-by: deathaxe <deathaxe@users.noreply.github.com>
=> [R] refactor of syntax files

Rust/Symbol List.tmPreferences, Rust/tests/symbols/syntax_test_symbols.rs
[Rust] add enum members to indexed symbol list to support Goto Definition etc.
=> [Rust] add enum members to indexed symbol list

PHP/Embeddings/SQL (for PHP Interpolated).sublime-syntax, PHP/tests/syntax_test_php.php, Rails/SQL (Rails).sublime-syntax, Rails/tests/syntax_test_rails.sql.erb, Ruby/Embeddings/SQL (for Ruby).sublime-syntax, Ruby/syntax_test_ruby.rb, SQL/MySQL.sublime-syntax, SQL/SQL (basic).sublime-syntax, SQL/tests/syntax/syntax_test_mysql.sql
=> [SQL] support comments in more places and MySQL LATERAL derived tables

C#/C#.sublime-syntax, C#/tests/syntax_test_Operators.cs, C#/tests/syntax_test_c#.cs
=> [C#] fix null coalescing operator followed by a space

Makefile/Makefile.sublime-syntax
Found this working on something else.
=> [Makefile] Fix invalid capture

C#/C#.sublime-syntax, C#/tests/syntax_test_c#.cs
=> [C#] correctly scope attributes inside event handler declarations

Objective-C/Symbol List - Hide.tmPreferences, Objective-C/syntax_test_objc++_symbols.mm, Objective-C/syntax_test_objc_symbols.m
=> [ObjC/ObjC++] Remove function arguments from symbol list

ShellScript/Zsh.sublime-syntax, ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 8
This commit teaches for statements to support multiple loop variables.
Note: Some syntax tests require #4245.
=> [ZSH] Fix for-loops with multiple variables

.github/workflows/ci.yml
=> CI: Enable syntax tests against stable ST build

SQL/MySQL.sublime-syntax, SQL/SQL (basic).sublime-syntax, SQL/tests/syntax/syntax_test_mysql.sql
=> [SQL] Fix ALTER TABLE ADD FOREIGN KEY

ShellScript/Zsh.sublime-syntax, ShellScript/Zsh/tests/syntax_test_scope.zsh
This commit addresses #4244 issue 16
=> [ZSH] Fix compound equal expansions

ShellScript/Bash.sublime-syntax, ShellScript/Zsh.sublime-syntax, ShellScript/Zsh/tests/syntax_test_scope.zsh
This commit addresses #4244 issue 6
=> [ZSH] Fix function definition identifiers

Go/Embeddings/SQL (for Go Embedded Backtick Strings).sublime-syntax, Go/tests/syntax_test_go.go, PHP/Embeddings/SQL (for PHP Interpolated).sublime-syntax, PHP/Embeddings/SQL (for PHP).sublime-syntax, Ruby/syntax_test_ruby.rb, SQL/PostgreSQL.sublime-syntax, SQL/SQL (basic).sublime-syntax, SQL/tests/syntax/syntax_test_postgres.psql
Fixes https://github.com/sublimehq/Packages/issues/4258
- don't scope `#` inside quoted identifiers as a line comment
- support function declarations containing quoted parameter names
- other misc fixes
=> [SQL] Postgre fixes

Clojure/Clojure.sublime-syntax, Clojure/Fold.tmPreferences, Clojure/tests/syntax_test_clojure.clj
This commit...
1. scopes to all expressions enclosed in braces/brackets/parentheses with according meta scopes
2. creates named contexts for expressions enclosed in bracket/braces
3. defines syntax based folding rules as meta scopes ensure proper tokenization of subsequent brackets.
=> [Clojure] Add syntax based folding

ShellScript/Bash.sublime-syntax, ShellScript/Zsh.sublime-syntax
=> [ShellScript] Add missing built-in variables

Markdown/Markdown.sublime-syntax, Markdown/tests/syntax_test_markdown.md
Fixes #4313
This PR fixes various issues with emphasis (bold, italic) text terminations, which can be achieved without branching.
=> [Markdown] Fix emphasis

Rails/Ruby (Rails).sublime-syntax
Add ActiveRecord `(before|after)_initialize` callbacks.
https://api.rubyonrails.org/classes/ActiveRecord/Callbacks/ClassMethods.html
=> [Rails] Add ActiveRecord missed callbacks

Python/Python.sublime-syntax, Python/tests/syntax_test_python.py
This commit adds various magic functions and variables, which have been supported by more or less recent versions of python.
=> [Python] Add various magic functions and variables

C#/C#.sublime-syntax, C#/tests/syntax_test_C#14.cs
https://devblogs.microsoft.com/dotnet/csharp-exploring-extension-members/
=> [C#] Support C#14 extension members

ShellScript/Bash.sublime-syntax, ShellScript/Bash/tests/syntax_test_scope.bash, ShellScript/Zsh/tests/syntax_test_scope.zsh
Resolves https://github.com/sublimehq/Packages/issues/4244#issuecomment-3312683851
=> [ShellScript] Fix command expansions in arithmetic expressions

Rust/Rust.sublime-syntax, Rust/tests/syntax_test_traits.rs
Fixes https://github.com/sublimehq/Packages/issues/4353
=> [Rust] support trait aliases
