sublimehq/Packages

- Makefile/Makefile Shell.sublime-syntax
- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
- ShellScript/Bash.sublime-syntax
- ShellScript/Shell-Unix-Generic.sublime-syntax
Fixes #2388
This commit creates an intermediate `Makefile Shell.sublime-syntax` as extended `Bash.sublime-syntax` with `variable-substitutions` from `Makefile.sublime-syntax` being added to proper contexts so that they are applied in a sane way, which respects the syntax structure of Bash.
The Makefile Shell.sublime-syntax is included into Makefile.sublime-syntax normally without `with_prototype`.
> [Makefile] Embed extended ShellScript

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
```php
$a = $b ?? 1;
//      ^^ keyword.operator.null-coalescing.php
```
It's weird that I didn't notice this one.
> [PHP] Add scope for null coalescing operator

- CSS/css_completions.py
Looks like python 3.8? requires a raw string to perform proper regexp replacement. The intention here is to replace `${1:param}` by `param` so the completion list displays named function arguments.
> [CSS] Fix <0x01> in completion labels

- Erlang/Erlang.sublime-syntax
- Erlang/syntax_test_erlang.erl
This PR updates Erlang.sublime-syntax to version 2.
- removes no longer required lookaheads
- uses `pop: 1` in favor of `pop: true`
- replaces all anonymous contexts which are used in multi-push and multi-set statements.
Notes:
1. This PR doesn't introduce any changes in behavior
2. Unfortunatelly commit https://github.com/sublimehq/Packages/commit/b00ace8f2b9a11dae6d816a9bedac2f09254ad27 and https://github.com/sublimehq/Packages/commit/a75fcc8705ba256c96b4855e9f42d152deea38d2 reduce parsing performance by about 15-30% depending on the used files. Benchmarks were made with all the files from the last rewrite. As those commits just reorganize anonymous contexts in named ones, the performance drop may be related with context name tracking?
The whole design and developement process included …
> [Erlang] sublime-syntax format version 2

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
Continued from https://github.com/sublimehq/Packages/pull/2446 but for setext-style headings. This PR makes the user be able to style the EOL (\n) char (such as adding a background color) just like it can already be done in atx-style headings.
> [Markdown] Add scope for EOL in setext headings

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
This PR proposes to adapt HEREDOC scopes to those of _Perl_ and _Bash_.
It uses `meta.tag.heredoc entity.name.tag` to scope opening and closing HEREDOC tags.
> [Ruby] Improve heredoc tag scoping

- HTML/Indentation Rules.tmPreferences
- HTML/syntax_test_html_indentation.html
This PR adds some basic indentation tests for the HTML package, and prevents unexpected indentation from occurring after a `doctype` directive. This follows [the PHP one](https://github.com/sublimehq/Packages/pull/2328), whereby we are only using the test file to make assertions about indentation, not scopes, to keep things simple. (IMO, it would be a fairly invasive style change to rework the existing syntax tests to also assert indentation doesn't change, so a separate test file keeps it neat and tidy.)
EDIT: note that due to the presence of multi-line comments in the test file, we can only assert `reindent-unchanged` and not `reindent-unindented` due to the default `preserveIndent` behavior as mentioned at https://github.com/sublimehq/sublime_text/issues/1271#issuecomment-231296051
> [HTML] don't indent after DOCTYPE, add indentation tests

- CSS/css_completions.py
This PR modifies css_completions to match the strategies and logic used by html_completions.
1. parse_css_data() is renamed into get_properties().
2. COMMON_VALUES and PROPERTIES_DICT is moved into get_properties() as global caching of uncompiled values which are cached in a compiled form in `CSSCompletions.props` is a waste of RAM.
3. Converts all function values into lists of the form [desc(), snippet] in order to be able to remove `re_trigger.sub()` which reduces
duration needed to provide value completions. (e.g.: filter: |; -> 33% faster).
4. Adds `@cached_property` to cache patterns and props.
5. Adds `@timing` for debugging and optimization purpose.
Benchmark:
------------------
Enter...
```
tr {
|
}
```
hit `ctrl+space` the first time (cold cache):
before: 6.6ms
after: 2.2ms
hit …
> [CSS] Optimize completions

- HTML/HTML.sublime-settings
- HTML/html_completions.py
This commit suggests to...
1. move main completion selector to a syntax specific `default_completions_selector` setting to make it easier for end users to customize it.
2. fix HTML completions not being provided within string interpolation by replacing `- meta.string` by `- string`. This issue was revealed when trying to auto complete html tags within Perl heredocs.
```Perl
$var <<HTML
<
HTML
```
3. simplify and increase readability of selectors by avoiding nested subtraction.
_Note: The same selector might be used within `auto_complete_triggers`_
```json
"auto_complete_triggers":
[
{
"characters": "<&",
"selector": "text.html - source - string - text.html.markdown, text.html.embedded - text.html.embedded source, markup.raw.code-fence text.html - markup.raw.code-fence text.html source, …
```
> [HTML] Default Completions Selector

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Applies `meta.number.<type> constant.numeric.[base|value|suffix]` to all numeric literals.
> [Python] Apply meta.number constant.numeric

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_bindings.js
- JavaScript/tests/syntax_test_jsx.jsx
- JavaScript/tests/syntax_test_typescript.ts
This PR is a proposal created from the latest discussion at #2460
It is to illustrate what it means to add meta.number scopes. It means to add one or up to 1 (2) additional capture groups per match pattern to assign meta.numbers.[base|value|suffix]. The complexity is the same for applying meta.numbers on top of below constant.numeric.
Note: It also contains the older more complex solutions for comparison.
> [JavaScript] Meta Numbers

- Matlab/Matlab.sublime-syntax
- Matlab/syntax_test_matlab.m
This implements the approach for meta scopes suggested in https://github.com/sublimehq/Packages/pull/2460#issuecomment-680957362. It is a different approach from #2462 and #2463, because here the number kind and base (radix) are moved to the `meta.number` scope, while the notation to denote the different parts of a number (`base|value|suffix`) is appended to `constant.numeric`.
> [Matlab] Meta Numbers

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
This PR is a proposal created from the latest discussion at #2460 
It is to illustrate what it means to add `meta.number` scopes. It means to add one or up to 3 additional capture groups per match pattern to assign `meta.numbers.[base|value|suffix]`. The complexity is the same for applying `meta.numbers` on top of below `constant.numeric`.
> [Ruby] Meta Numbers

- JavaScript/TypeScript.sublime-syntax
The rule in question is a no-op that's part of some conditional logic in the JS Custom TypeScript extension. Since the new TypeScript extension doesn't have that conditional logic, it doesn't need the no-op.
> [TypeScript] Remove vestigial match rule

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #2482
Alias identifiers may consist of any arbitrary character but meta chars.
Only `=` is accepted as assignment operator.
> [ShellScript] Fix alias command

- Erlang/Erlang.sublime-syntax
- Erlang/syntax_test_erlang.erl
Closes #2502
This commit adds underscore support in numeric literals according to http://erlang.org/doc/reference_manual/data_types.html#number
This language feature was added in ErlangOTP 23.0
see: https://www.erlang.org/news/140
> [Erlang] Add underscore support in numbers

- ShellScript/Bash.sublime-syntax
This commit removes `constant.numeric` from `%1` job identifiers as those already use `variable.language.job`.
Applying `meta.number constant.numeric` here would just be more odd.
> [ShellScript] Fix numeric job identifier

- HTML/HTML-Plain.sublime-syntax
- HTML/HTML.sublime-syntax
This PR suggests to move most basic HTML parts to HTML-Plain.sublime-syntax and inherit HTML.sublime-syntax from it.
This does not change any pattern or behavior of published HTML syntax, but provides a very basic HTML implementation to base work on, which doesn't need any of the embedded CSS/JS syntax definitions or all the different tag/attribute types available.
HTML-Plain is meant as base syntax for HTML supporting documentation comments or such kinds of template syntaxes.
The motivation for this step is JavaDoc, which can be inherit from HTML, but doesn't need CSS/JavaScript support. Injecting patterns to ignore leading asterisk punctuation in comments into HTML and all embedded syntaxes even creates unnecessary overhead and huge caches. It may even cause the context sanity limit to …
> [HTML] Split HTML syntax into plain vs. basic

- TCL/Tcl.sublime-syntax
- TCL/syntax_test_tcl.tcl
> [TCL] Update meta.number constant.numeric

- Batch File/Batch File.sublime-syntax
- Batch File/syntax_test_batch_file.bat
> [Batch File] Update meta.number constant.numeric

- SQL/SQL.sublime-syntax
This PR adds some missing storage types (bool, enum, longtext, tinytext) to improve the compatibility with MySQL/MariaDB.
> [SQL] Add storage types bool, enum, longtext and tinytext

- ASP/ASP.sublime-syntax
- ASP/syntax_test_asp.asp
Note: Hexadecimal literals may be enclosed into `&` which are scoped `punctuation.definition.numeric`.
> [ASP] Update meta.number constant.numeric

- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_block.yaml
This commit removes `integer.decimal` from indentation indicator literals as those sub scopes are no longer used.
As yaml version is scoped `constant.numeric.yaml-version`, `constant.numeric.decimal-indicator` should be sufficient here.
> [YAML] Update numeric indentation indicator

- C#/C#.sublime-syntax
- C#/tests/syntax_test_Generics.cs
Closes #2516
This commit replaces scopes of remaining numeric literals with old scope schemes for consistency reasons with the new guideline.
We may want to preserve numeric scopes in placeholder strings as their meaning may be compared to the formatting/substring operands in _Batch File_, which scopes them as numeric literals as well.
> [C#] Update missing meta.number constant.numeric

- Git Formats/Git Common.sublime-syntax
- Git Formats/syntax_test_git_config
Note: Do we really need all the `pretty-format` sub scopes everywhere?
> [Git Formats] Update meta.number constant.numeric

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #2515.
I think this should reliably distinguish function type arguments from the less than sign, except for one corner case:
```ts
foo < bar // end of file
```
Since there's apparently [no way to detect the end of the file](https://forum.sublimetext.com/t/sublime-syntax-regex-to-detect-end-of-file-as-opposed-to-end-of-line/35879), this is probably not fixable. (Any non-whitespace non-comment character after `bar` will allow it to highlight correctly.)
This PR also updates the code that detects when an identifier is a function being invoked. The implementation is simplistic and could be fooled, but it should work in basically all real-world scenarios and the failure mode isn't problematic.
> [TypeScript] Implement function call type arguments.

- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_flow-plain.yaml
- YAML/tests/syntax_test_types.yaml
This commit fixes decimal number values being scoped as `constant.numeric.base` by accident.
> [YAML] Fix constant.numeric of decimal numbers

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit adds `grid` keyword to the list of valid property names.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/grid
Also scopes `/` as keyword.operator.arithmetic in all property-values in order highlight it in grid related properties.
Note: If we want to limit `/` highlighting dedicated `grid` related contexts need to be created.
> [CSS] Fix `grid` property-name highlighting

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
Fixes #2356
This PR ...
1. adds `arithmetic` sub scope to all arithmetic operators.
2. scopes operators `invalid.illegal.operator` if
a) not sufficiently surrounded by white space between two numeric literals in calc() functions.
b) not followed by white space in color adjusting functions.
> [CSS] Fix arithmetic operator and calc() function

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
Fixes #2431
This PR...
1. splits the anonymous property-names context in `rule-list-body` into several named contexts, such as `counter-property`, `font-property`,  ... .
2. Moves `counter-(...)` patterns from `other-properties` to a dedicated context in order to apply special scoping to the first property value as it denotes a counter name.
> [CSS] Fix counter identifier

- SQL/SQL.sublime-syntax
This PR adds missing variations for INDEX (fulltext, spatial) and KEY (fulltext, unique) to improve the compatibility with MySQL/MariaDB.
> [SQL] Add INDEX and KEY variations to improve compatibility with MySQL/MariaDB

- SQL/syntax_test_sql.sql
Due to few syntax tests for the SQL language it is more likely to add regressions on modifications to the syntax file. This PR tries to address this issue. It adds syntax tests to preserve the status quo but also has SQL code which is not covered by the syntax definition file yet. To avoid failing tests that code parts have no scope annotations. Its like a collection of missing improvements for the syntax definition file. Some of them I will try to improve in the future.
> [SQL] Add various syntax tests to prevent regressions

- ShellScript/Bash.sublime-syntax
These two patterns for Gentoo packaging files should be treated as file extensions, not as full filenames.
> [ShellScript] Fix ebuild/eclass file extensions

- .github/workflows/ci.yml
Should resolve the CI failure in #2577.
> [GitHub Actions] Use build 4090 for CI.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Reported in https://github.com/sublimehq/Packages/pull/2574#issuecomment-722975089, but can be merged independently (especially since that PR may need more work).
In a type expression, an opening paren may indicate either a type in parentheses or the beginning of a function type. The TypeScript syntax uses branching to distinguish them. However, because `branch` is like `push`, after parsing the type the syntax was still in the `expression-begin` state instead of `expression-end`. Adding a `pop` to the `branch` rule will fix this so that the stack is correct after parsing the function type.
> [TypeScript] Fix bug at end of function types.

- Python/Snippets/New-Class.sublime-snippet
- Python/Snippets/Try-Except-Else-Finally.sublime-snippet
- Python/Snippets/Try-Except-Else.sublime-snippet
- Python/Snippets/Try-Except-Finally.sublime-snippet
- Python/Snippets/Try-Except.sublime-snippet
- Python/Snippets/__magic__.sublime-snippet
- Python/Snippets/for.sublime-snippet
- Python/Snippets/function.sublime-snippet
- Python/Snippets/if-__name__-==-'__main__'.sublime-snippet
- Python/Snippets/if.sublime-snippet
- Python/Snippets/method.sublime-snippet
- Python/Snippets/while.sublime-snippet
This PR suggests to prevent statement like snippets from being suggested in
- comments
- function parameter lists
- function call argument lists
- lists
- mappings
- sets
- statements (imports, if, while, ...)
- strings
They are not valid in those situations anyway.
> [Python] Fix snippet selectors

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
expression-end used to pop on any otherwise unrecognized character, but in the context of the expression context being pushed on the stack as part of a statement, this meant the expression was terminated unexpectedly early and the following keyword match, such as in `if … then` would fail to match and also exit early, resulting in an unfortunate context stack.
The introduced match just matches any unexpected characters and highlights them as invalid, while also not popping, so the match can resume after the character.
Closes #1939.
cc @Thom1729
> [Lua] Don't trip on unexpected characters

- Go/Go.sublime-syntax
- Go/syntax_test_go.go
ST needs all brackets scoped `string` or `comment`, which are to be ignored by bracket matching or goto matching bracket command.
Before this commit if the code contains `'}'` it was included into bracket matching causing false positives.
This commit therefore scopes "runes" as `string.quoted.single` with only the containing character assigned `constant.character.[literal|escape]`.
> [Go] Help ST with proper bracket matching

- Matlab/Matlab.sublime-syntax
- Matlab/syntax_test_matlab.m
This commit merges double-percentage and single-percentage comments.
The result is all types of comments beginning with an arbitrary number of percentage sign are accepted with highlighting all percentages as `punctuation.definition`.
> [Matlab] Merge percentage comment patterns

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #2580 
This PR 
1. adds a simple `\.` pattern to `qualified-name` context to match all remaining/trailing dots `punctuation.accessor`.
2. reworks import statement contexts to support trailing accessor dots, which have been highlighted invalid before as they were treated as relative import punctuation.
3. fixes an issue which causes import statements like `from foo. import` to break highlighting because `import` or `as` being marked illegal. It created a poor behavior while typing import library paths.
4. fixes several overlapping meta scope issues in import statements.
> [Python] Highlight trailing accessor

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Supersedes #2574. Built on top of the fixes and improvements in #2577.
Known issues:
- Invalid type expressions will not always be detected, which could lead to incorrect highlighting. I think this probably should be rare in practice. A perfect implementation is possible, but without something like https://github.com/sublimehq/sublime_text/issues/3494 it would require massive duplication of code.
- There are a lot of magical multi-pops in the arrow function branching code, though slightly fewer as a result of #2577. It should be possible to eliminate some more, but I've run into some infinite loops in the process. I have a hunch that https://github.com/sublimehq/sublime_text/issues/3732 might help here.
- If an arrow function (other than an async arrow function) has a return type, then …
> [TypeScript] Arrow function return types, take two.

- HTML/Symbol List - ID.tmPreferences
This PR proposes to remove symbol transformation from _Symbol List - ID_ as
1. the `ID:` is represented by the `i` symbol kind icon
2. the symbol's source (HTML) is displayed as hint on the right.
> [HTML] Remove ID symbol transformation

- CSS/Symbol List - Selector.tmPreferences
This PR proposes to remove symbol transformation from _Symbol List - Selector_ as the symbol's source (CSS) is displayed as hint on the right.
> [CSS] Remove 'CSS: ' from symbol transformation

- CSS/css_completions.py
As `var()` is supported everywhere, we also might want to have a global completion for it.
This commit adds `var()` to all property-value completions.
Note: It might be useful to also add it to function-argument completions in a future commit.
> [CSS] Add var() to global completions

- JavaScript/Comments.tmPreferences
- JavaScript/JSX Comments.tmPreferences
Not sure about the notation in `JSX Comments.tmPreferences`, but it works.
> Enable TSX toggle comment

- HTML/HTML.sublime-syntax
This commit intends to make it easier for an inherit HTML syntax to replace the plain `source.js` and `source.css` by inherit definitions.
A syntax such as ASP or JSP needs to inherit CSS and JS in order to extend them by ASP/JSP tag support. Those extended CSS/JS variants need to be embedded in HTML-ASP or HTML-JSP then.
The strategy may be compared to what Makefile does with Bash via Makefile Shell.sublime-syntax.
Unfortunately the `embed:` command doesn't accept variables which could be used to replace the scope name more easily/consistently. So the dedicated context is the only way to minimize required code duplication.
> [HTML] Add dedicated CSS/JS content contexts

- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_types.yaml
YAML 1.1 made the prominent mistake of accepting many aliases for boolean values that many parsers adopted. For 1.2, these aliases have been removed, but for accuracy with the older version and especially
considering how older parsers are still seeing use, we cannot simply remove matching them.
However, the short names "y" and "on" are fairly common in keys and having those highlighted as a boolean is annoying, so we only match for the 1.2 scalars in keys.
I believe this solution to be a satisfactory compromise for #1602, where this issue has been discussed at length.
Closes #1602.
> [YAML] Don't match controversial plain bools in keys

- CSS/CSS.sublime-syntax
- CSS/css_completions.py
- CSS/syntax_test_css.css
While the original intention of this PR was to upgrade the syntax definition to sublime-syntax version 2 and apply some related changes which might make sense:
1. sorting header contexts (see: #2430)
2. replacing `pop: true` by `pop: 1`
3. add some sections for logical grouping contexts
it more and more escalated to a major update with various other fixes and improvements.
1. Fixes #1017 by consequently matching all tokens case-insensitive (except. custom-element-tags). Some of them already were, others not.
2. Fixes #1100 by adding contexts to ensure bracket balancing, if unexpected tokens are matched. This change was made to comply with CSS specifications which ask to ensure balancing under all circumstances.
3. Improves bailout strategy from blocks and groups to ensure not to break …
> [CSS] Major Upgrade including syntax-version 2

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
This commit splits punctuation of arithmetic, command and parameter
expansion into:
a) `$` = punctuation.definition.variable
b) `{` = punctuation.section.interpolation.begin
Both used `punctuation.section.interpolation.begin` before.
While this is correct according to scope naming guidelines it causes
tokens of identical meaning to be highlighted differently.
**Example (Before):**
```
$var == ${var}
^^^^ meta.interpolation.parameter
^ punctuation.definition.variable
^^^^^^ meta.interpolation.parameter
^^ punctuation.section.interpolation.begin
```
**Example (After):**
```
$var == ${var}
^^^^ meta.interpolation.parameter
^ punctuation.definition.variable
^^^^^^ meta.interpolation.parameter
^ punctuation.definition.variable
^ punctuation.section.interpolation.begin
```
All `$` are scoped …
> [ShellScript] Tweak variable interpolation punctuation

- JavaScript/JavaScript.sublime-syntax
- JavaScript/Symbol List.tmPreferences
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_bindings.js
- JavaScript/tests/syntax_test_typescript.ts
Historically, the JavaScript syntax scoped the parts of a function before the body as `meta.function.declaration`. This is not a standard scope. In the past, it was used to populate the symbol list so that a function might appear in the list as `function foo (bar)`. However, with the new symbol list functionality, only the function name itself is shown in the symbol list, so the `meta.function.declaration` scope serves no purpose.
~~I've marked this WIP because I think it might conflict with #2590. If so, it would be a trivial fix, but it's better to apply that fix here rather than in the more complicated PR.~~
> [JavaScript] Remove meta.function.declaration scope.

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Resolves https://github.com/sublimehq/Packages/issues/2585
---
Add a workaround for dangling `$` in interpolated regex because it means EOL.
```php
$var = "foo";
$regex = "/$var $/";
^ not punctuation.definition.variable, but keyword.control.anchor.regexp
```
> [PHP] Greedily scope the $ as punctuation.definition.variable

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
Reported in https://github.com/sublimehq/Packages/pull/2591#issuecomment-725653172.
Scope function formal parameter list as `meta.function.parameters`. If an arrow function has a single bare parameter, that parameter will get `meta.function.parameters`.
> [JavaScript] Use meta.function.parameters scope.

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
This commit removes storage.type in patterns which already make use of keyword.declaration no avoid obsolete stacking of those scopes.
IIRC ST4 does scope forwarding now?
> [ShellScript] Remove storage.type scope

- Rails/syntax_test_rails.rb
- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
This commit removes storage.type in patterns which already make use of keyword.declaration no avoid obsolete stacking of those scopes.
> [Ruby] Remove storage.type scope

- R/R.sublime-syntax
- R/syntax_test_r.R
This commit replaces storage.type.function by keyword.declaration.function
> [R] Rename storage.type.function scope

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This commit removes storage.type in patterns which already make use of keyword.declaration no avoid obsolete stacking of those scopes.
> [Python] Remove storage.type scope

- Perl/Perl.sublime-syntax
- Perl/syntax_test_perl.pl
This commit removes storage.type in patterns which already make use of keyword.declaration no avoid obsolete stacking of those scopes.
> [Perl] Remove storage.type scope

- Pascal/Pascal.sublime-syntax
- Pascal/syntax_test.pas
This commit replaces storage.type.function by keyword.declaration.function
> [Pascal] Rename storage.type.function scope

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
This commit removes storage.type in patterns which already make use of
keyword.declaration no avoid obsolete stacking of those scopes.
> [Lua] Remove storage.type scope

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
- D/tests/syntax_test_old.d
This commit removes storage.type in patterns which already make use of
keyword.declaration no avoid obsolete stacking of those scopes.
> [D] Remove storage.type scope

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_GeneralStructure.cs
This commit removes storage.type in patterns which already make use of
keyword.declaration no avoid obsolete stacking of those scopes.
Note: `storage.type.variable` is interpreted as variant data type, so it
is not renamed to keyword.declaration.
> [C#] Remove storage.type scope

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_typescript.ts
@deathaxe 
Currently, `async` is still `storage.type` and the asterisk in a generator function is `keyword.generator.asterisk`. Either or both of these could be re-scoped if anyone has a suggestion.
> [JavaScript] Use keyword.declaration.function instead of storage.type.function

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
Example:
```js
foo.bar = () => {};
```
Previously, the JavaScript syntax would try to match the entire line with a complex lookahead, mark `foo` as `support.class` (instead of `variable.other`), and mark `bar` as `entity.name.function` (in addition to its usual scope). Marking `bar` makes sense, but marking `foo` probably doesn't, and lookahead was brittle.
This PR only tries to mark `bar`. This requires a simpler lookahead that's probably more reliable, and it allows for eliminating the special case code that would have marked `Foo`.
Function assignment detection should still probably be rewritten using branching (#2267), but this should make that simpler to implement.
> [JavaScript] Simplify function assignmment lookahead.

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
This commit renames some `storage.type` scopes into `keyword.declaration` to highlight keywords like `class`, `union`,
`template`, `typename`, `struct`, ... as declaration keywords rather than primitive/ordinary data types.
Note:
It is an as good as possible with least effort approach, which means some `class`, ... keywords to be scoped `keyword.declaration.[c|c++|...]` only due to existing patterns. Don't want to rework the syntax at this point by splitting those.
> [C/C++/Objective-C/Objective-C++] Keyword declaration

- ActionScript/ActionScript.sublime-syntax
This commit replaces
a) storage.type.[class|function] by keyword.declaration.[class|function]
b) storage.modifier.extends by keyword.declaration.extends
> [ActionScript] Rename storage.type scope

- R/R.sublime-syntax
- R/syntax_test_r.R
Not sure if a documentation comment should use `comment.line` or `comment.block`, but a more general scope like `documentation` is propably usefull in both cases.
> [R] Comment Documentation

- C#/C#.sublime-syntax
- C#/tests/syntax_test_Comments.cs
This PR changes the scope for single-line documentation comments (denoted by `///`) from `comment.block.documentation` to `comment.line.documentation`, because:
* They *are* line comments and not block comments
* The Microsoft C# documentation at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments explicitely distinguishes between *single-line-doc-comment* (starting with `///`) and *delimited-doc-comment* (starting with `/**`)
* There are several examples of such doc comments in the linked C# docs which indeed use only a single line, so they don't necessarily appear in blocks
* This is consistent with R, which also uses `comment.line` for line doc comments
* This complies with the scope naming guidelines, which recommends …
> [C#] Use comment.line scope for single-line doc comments

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #2608
This commit handles `() { ... }` as incomplete function definition in Bash, while it is valid anonymous function definition in ZSH.
> [ShellScript] Add anonymous functions

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Fixes #2558
Fixes #2567
Problem Description
D matches mapping keys globally in a general `value` context, which causes identifiers followed by colon such as `c :` to be matched as mapping key instead of variable followed by ternary operator or case label separator.
Thus ternary statements and switch case statements fail in such situations.
Solution
This commit creates intermediate contexts `value-condition` and `value-no-mapping-key` to avoid matching keys within ternary statements.
Case statements are fixed by `value-list-no-mapping-key`.
> [D] Fix conditional statements

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_jsx.jsx
If we encounter an unexpected reserved word while parsing an expression, bail out of the expression. This should improve highlighting while typing in some cases.
In strict mode, additional words are reserved, but handling this would require duplicating the expression contexts, so it's not worth it.
> [JavaScript] Improve handling of identifiers.

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_C#8.cs
- C#/tests/syntax_test_C#9.cs
- C#/tests/syntax_test_GeneralStructure.cs
- C#/tests/syntax_test_Generics.cs
- C#/tests/syntax_test_Using.cs
This commit scopes all remaining function declaration keywords `keyword.declaration.function`.
This commit scopes the `=>` as `keyword.declaration.function.anonymous`.
It was applied to C#, D recently and will be used in Java an Python as a common alternative to the existing variants of defining anonymous functions.
We currently have:
- keyword.declaration.function.anonymous
- keyword.declaration.function.arrow
- keyword.declaration.function.inline
- keyword.declaration.function.lambda
> [C#] Use keyword.declaration.function

- Python/Completion Rules.tmPreferences
Other object-oriented languages in the default packages only disable
completions for class/type names, because in object-oriented languages
you can make use of function overloading, including the commonly
defined dunder functions. Most notably, this allows auto-completion
plugins like LSP to function properly.
Aside from that, the regex was merely restructured.
Closes #2404.
> [Python] Don't cancel completions for function definitions

- Python/Python.sublime-syntax
Just a small cleanup pass on built-in matches, removing the barely-used `buffer` and restructuring the rest.
> [Python] Clean up built-ins

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Reported by rafal on Discord. The `punctuation.separator.accessor` scope is nonstandard and apparently interferes with completions.
> [TypeScript] Use correct scope for accessors in types.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
For #2634.
This is a quick fix. It should work most of the time and improve upon the previous behavior. However, it's still an approximate lookahead and there could be false positives and negatives. When it fails, the identifier will be highlighted wrong, but everything else should still work.
This is the same implementation that I attempted in #2574. However, I ran into problems there because the lookahead was used for other purposes. #2577 fixed that, so the lookahead is now only used for detection function assignments.
In the long term, I would still like to implement #2267. However, I have not yet found an implementation that would not involve a great deal of code duplication (see https://github.com/sublimehq/sublime_text/issues/3494).
> [TypeScript] Slightly improve function assignment detection.

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Addresses one issue of #2635
Bash knows about the special parameter `$#` (number of parameters)
see: https://www.gnu.org/software/bash/manual/bash.html#Special-Parameters
It may be written as parameter expansion `${#}`.
Before this commit the first `#` is always scoped `keyword.operator` as it is meant to be used with `${#foo}`, which returns the length of `foo`'s content.
This commit adds a special pattern to match `${#}` as expansion of a `variable.language`.
> [ShellScript] Fix variable parameter expansion

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
As described in #2630.
Note: I've also removed `exponent` scope to reduce capture groups and because they are not implemented in the majority of syntaxes.
> [D] Fix decimal point scope in floats

- Go/Go.sublime-syntax
- Go/syntax_test_go.go
Changed every occurrence of `storage.type.keyword` to `keyword.declaration` to accommodate this newer convention.
Additionally, corrected the scope order "non-meta meta" to "meta non-meta" for `go:` annotations. (Meta scopes usually go first.)
> [Go] use the `keyword.declaration` convention

- Clojure/Clojure.sublime-syntax
- Clojure/tests/syntax_test_clojure.clj
Addresses #2630
1. This commit applies `constant.numeric.value` to the whole value part of floating point numbers without interrupting by decimal point.
2. Scopes number signs as `keyword.operator.arithmetic` as this is the agreed scope to use.
> [Clojure] Fix floating point numbers and number signs

- OCaml/OCaml.sublime-syntax
- OCaml/syntax_test_ml.ml
Addresses #2630
This PR ...
1. This commit applies `constant.numeric.value` to the whole value part of floating point numbers without interrupting by decimal point.
2. Scopes number signs as `keyword.operator.arithmetic` as this is the agreed scope to use.
> [OCaml] Fix floating point numbers and number signs

- Scala/Scala.sublime-syntax
- Scala/syntax_test_scala.scala
Closes #2630
This commit applies `constant.numeric.value` to the whole value part of floating point numbers without interrupting by decimal point.
> [Scala] Fix floating point number scopes

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
This commit aligns syntax highlighting of urls with the implementation used in CSS.sublime-syntax, which scopes `/`, etc. as path separators.
> [HTML] Add scope for path separators

- Scala/Scala.sublime-syntax
- Scala/syntax_test_scala.scala
This PR modifies some keyword scopes to (hopefully) align them better to recently aggreed scope naming guidelines.
It mainly addresses `storage.type` vs. `keyword.declaration` use cases.
> [Scala] Tweak declaration keyword scopes

- HTML/HTML (Plain).sublime-syntax
- HTML/Snippets/html (begin tag).sublime-snippet
- HTML/Snippets/html.sublime-snippet
- HTML/syntax_test_html.html
This commit fixes an issue which caused ST's completion engine to fail selecting correct "HTML" snippet variant in some situations.
The result is an extra `<` in front of the added snippet content:
```
<<!DOCTYPE html>
...
```
**Steps to reproduce:**
1. Open a new view and set its syntax to HTML
2. Type `<`
3. Hit `ctrl+space`
=> ST selects html.sublime-snippet as its selector matches
4. Type `html`
5. Commit completion
Selectors of involved snippet files left a gap of confusion because a single less than sign is not scoped at all. Even if it would be scoped `punctuation.definition.tag.begin` the wrong html.sublime-snippet would be applied due to malformed selector.
As it is allowed to have single `<` within normal text (Firefox, Chrome don't complain about it), it can't be scoped …
> [HTML] Fix HTML snippet selectors

- Git Formats/Snippets/Git Config - Section.sublime-snippet
`source.git.config` must be outdated, because there's no occurence of it elsewhere in the repo.
> [Git Formats] Target the correct scope with the snippet

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
This commit fixes an issue with `;` in `test <expr> <op> <pattern>;` not terminating the statement correctly if it is not preceded by whitespace.
> [ShellScript] Fix test command termination

- ShellScript/Default.sublime-keymap
Fixes #2677
This PR proposes to add key bindings to...
1. Auto-pair command interpolation parentheses
```
$|         -> $(|)
"$|"       -> "$(|)"
foo$|baz   -> foo$(|)baz
"foo$|baz" -> "foo$(|)baz"
```
Note: Removing parens via backspace is handled by default bindings.
2. Auto-pair parameter interpolation braces
```
$|         -> ${|}
"$|"       -> "${|}"
foo$|baz   -> foo${|}baz
"foo$|baz" -> "foo${|}baz"
```
Note: Removing braces via backspace is handled by default bindings.
3. Auto-pair backtick quotes
```
|       -> `|`
"|"     -> "`|`"
foo|baz -> foo`|`baz
`|`      -> |
```
4. Expand interpolation brackets
```
(|)  -> ( | )
{|}  -> { | }
```
5. Collapse interpolation brackets
```
( | )  -> (|)
{ | }  -> {|}
```
**Notes:**
All bindings are limited to `source.shell` and …
> [ShellScript] Add key bindings for auto-pairing

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_C#8.cs
- C#/tests/syntax_test_C#9.cs
- C#/tests/syntax_test_GeneralStructure.cs
This PR renames lambda function declaration operator to `keyword.declaration.function.arrow` with regards to
https://github.com/sublimehq/Packages/pull/2617#issuecomment-759683664
Notes:
1. The function body is still scoped `meta.function.anonymous` because a lambda function is anonymous regardless the keyword or operator being used to declare it.
2. The sub-scope `anonymous` is chosen, because it may be used as common name for anonymous functions and variables such as `_` in python and others.
3. The main reason for this commit is to provide separate scopes for lambda function operators such as `->` and `=>` and declaration keywords like `lambda` (Python) or `fun` (Erlang).
Some users might want to assign different colors.
> [C#] Use keyword.declaration.function.arrow

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This PR fixes `async` not being scoped in a dictionary.
Resolves #2688
> [Python] Fix async not being scoped in a dictionary.

- AppleScript/AppleScript.sublime-syntax
Hallo And Happy New Year!
* http://alvinalexander.com/blog/post/mac-os-x/applescript-use-comments/
* https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/conceptual/ASLR_lexical_conventions.html#//apple_ref/doc/uid/TP40000983-CH214-SW8
Not the sequence ”#!“ but the single character ”#“ initiates an end-of-line comment.
”#“ is treated/handled as/like ”--“.
Ciao
> the “#“ alone initiates an end-of-line comment, but the “!“ does not

- AppleScript/Comments.tmPreferences
hej, see
https://github.com/sublimehq/Packages/pull/2683
> the “#“ alone initiates an end-of-line comment, but the “!“ does not. (Comments.tmP…)

- Markdown/Default.sublime-keymap
These keybindings will create a pair of asterisks, underscores or back ticks when you type a single one, or will surround the selection with asterisks, underscores or back ticks as appropriate.
This PR is solely concerned with making Markdown's surrounding asterisk, underscore and back tick characters behave similar to how surrounding quotation mark and brace characters work in other language files.
Fixes #2689
> [Markdown] Add keybindings for `, _ and *

- Lua/Lua.sublime-syntax
- Lua/Snippets/for-i-v-in-ipairs().sublime-snippet
- Lua/Snippets/for-i=1-10.sublime-snippet
- Lua/Snippets/for-k-v-in-pairs().sublime-snippet
- Lua/Snippets/function-(fun).sublime-snippet
- Lua/Snippets/function-(function).sublime-snippet
- Lua/Snippets/local-x-=-1.sublime-snippet
- Lua/Snippets/table.concat.sublime-snippet
- Lua/Snippets/table.sort.sublime-snippet
- Lua/tests/syntax_test_lua.lua
- Lua/tests/syntax_test_lua_support.lua
This PR
1. Adds support for the new [const](https://www.lua.org/manual/5.4/manual.html#3.3.7) and [to-be-closed](https://www.lua.org/manual/5.4/manual.html#3.3.8) variables, introduced in Lua 5.4. The syntax is a bit weird IMO, but it is what it is.
2. Previously, Lua used to have a 4th level scope to identify `true` vs `false` i.e. `constant.language.boolean.true` for `true` & `constant.language.boolean.true` for `false` (which is anyways wrong). Now, it reduces it to only `constant.language.boolean` since there is very little value in having the previous scopes. 
3. Adds `meta.string` scope to strings to comply with the scope naming guidelines. I have also reworked the string contexts to actually `push` or `set` into named contexts instead of anonymous contexts for a better debugging …
> [Lua] Add support for a few new syntax features introduced in Lua 5.4 and a couple improvements.

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This PR fixes an issue which caused rgb(), hsl() functions and friends being highlighted as keywords.
> [CSS] Fix color functions in blend()

- CSS/CSS.sublime-syntax
Fixes #2704
This PR...
1. Adds all property names returned by https://www.chromestatus.com at 2021 Jan. 28th except those which begin with `alias-` or `webkit-` in exact the order provided by the page.
2. Properties no longer returned by the web page are appended to that list in case those are still valid or used. They are considered to be of very low usage.
A comment was added as devider.
> [CSS] Update property names from referenced website

- Markdown/Code Block Syntaxes.sublime-completions
This PR adds a sublime-completions file with all supported syntax names for fenced code blocks supported by this package.
The goal is to help users supported syntax names quickly, when typing after the opening backticks of a fenced code block.
> [Markdown] Promote supported code fence syntax in completions

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_jsx.jsx
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Also noticed that, `<` is wrongly scoped as `keyword.operator.logical` while it should be `keyword.operator.relational`.
Fixes https://github.com/sublimehq/Packages/issues/2732
> [TypeScript] Fix scope for less (or equal) than operators

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
See https://tc39.es/proposal-logical-assignment/. Also supported in TypeScript [as of 4.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#short-circuiting-assignment-operators).
I didn't add the comments all the other operators have. I'm not sure why those exist in the first place. Probably they've been there since time immemorial.
> [JavaScript] Implement short-circuiting logical assignment operators.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types.
> [TypeScript] Implement key remapping in mapped types.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript_not_tsx.ts
In some cases, function call type argument detection is overly aggressive. I *think* this should do the right thing in all cases.
I also added JS Custom's old-style type assertion tests. I put them in a separate file so that we can run all of the other TypeScript syntax tests against the TSX syntax without worrying about spurious errors. (This allows JS Custom to run all applicable syntax tests against each syntax, which is how I spotted this bug and the last one.)
> [TypeScript] Fix bug in function call type arguments.

- JavaScript/tests/syntax_test_js.js
Introduced accidentally a couple months back. JSX and TSX do not like this.
> [JavaScript] Remove git garbage from syntax test.

- JavaScript/Symbol List.tmPreferences
Fix #2717.
The existing lines were redundant because the Default symbol list already provides them. (This is fortunate, because they were never updated for JSX, TypeScript, and TSX.)
> [TypeScript] Add interface names to symbol list.

- XML/XML.sublime-syntax
- XML/syntax_test_xml.xml
This PR applies some strategic changes to XML.sublime-syntax after the scheme of HTML.sublime-syntax which intend to help 3rd-party packages with inheriting XML and modifying single aspects of the syntax.
All changes are grouped and described in single commits.
Syntax tests are updated to
1. test for added `meta.string` scopes
2. test missing attribute name situations (only `="value"` present)
--- 
Note:
I wonder whether we also should rename contexts to add a `xml-` prefix. The idea is to make it obvious which contexts are inherit from XML or which are added by an extending syntax definition. It would also "look nice" next to the already existing `dtd-` contexts.
This change is **not** yet part of this PR and may be handled separately because it is a breaking change. PackageDev is known …
> [XML] Enhance inheritability

- CSS/Default.sublime-keymap
This PR proposes to improve auto-pairing user experience by automatically adding or removing space to the left and right of caret in new/empty block comments.
**Note:**
This keybinding could also be implemented in Default.sublime-package by just removing `source.css` from selector. The remaining `comment` would ensure the key binding is triggered only within block comments. This would enable this enhancement to all syntaxes which support this style of block cumments such as: C, C++, ObjC, ObjC++, Java, JavaScript, JSON and probably numerous more.
> [CSS] Add auto-pair keybindings to /*|*/ <=> /* | */

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
- PHP/tests/syntax_test_php.php
Fixes #2713
This PR removes strict lower-case custom tag highlighting.
Why?
https://html.spec.whatwg.org/multipage/syntax.html#start-tags doesn't mension custom elements but foreign elements only.
> In the HTML syntax, tag names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that, when converted to all-lowercase, matches the element's tag name; tag names are case-insensitive.
Actually Firefox, Chrome and VS Code accept those colons or seem to fail silently by ignoring the namespace part. Not sure how foreign tags such as SVG or MathML are handled in detail though. They may support namespaces as they are XML.
According to https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state all characters except ascii whitespace and some …
> [HTML] Fix foreign tags

- PHP/Indentation Rules.tmPreferences
- PHP/tests/syntax_test_indentation.php
Add some more indentation tests for PHP files, and ensure that an empty `for` statement (i.e. with a semi-colon at the end) doesn't indent the next line.
> [PHP] add some more indentation tests

- HTML/Indentation Rules.tmPreferences
- HTML/syntax_test_html_indentation.html
This commit fixes an issue which caused lines after self-closing curly braces such as template tags to be indented.
```
<p>
{{template}}
|             <- the indented caret
</p>
```
```
<p>
{{template}}
|               <- the un-indented caret
</p>
```
> [HTML] Fix curly braces indentation

- Diff/Diff.sublime-settings
When one diffs a file whose name contains a space character, the diff is generated with a trailing tab character at EOL so that the `patch` command line utility will be able to find the file properly. Prior to this PR, ST would automatically trim the trailing whitespace by default, preventing `patch` from working.
Real world example of a patch file which targets a file with a space in the name: https://github.com/sharkdp/bat/pull/1557/files#diff-e8ae3ce548991704395140abe884a9b871bd1a85759a349d50ac84f465a25683R3
> [Diff] Add setting to not trim trailing white space on save

- CSS/CSS.sublime-syntax
- CSS/css_completions.py
https://www.w3.org/TR/css-fonts-4/#font-display-desc
The "fallback" was in the syntax previously but removed in #2705 - an accident?
> [CSS] Add font-display constants

- CSS/CSS.sublime-syntax
- CSS/css_completions.py
- CSS/syntax_test_css.css
This commit adds conic-gradient() to the list of supported functions.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient()
_Note: Also sorts some values alphabetically in other gradient functions._
> [CSS] Add highlighting for conic-gradient()

- Python/Python.sublime-build
For the osx and linux platforms, we used to invoke the "python" executable. This
is for all practical purposes the same as invoking Python 2.7. Version 2 has
been EOL'd on January 1st, 2020.
> [Python] Change the default executable to invoke to "python3"

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This PR ...
1. adds support for clamp(), min() and max() functions. The patterns are added to `calc-functions` context.
2. The `calc-functions` context is included into all other function arguments contexts which are related with numeric values as MDN states:
```
The ... function can be used anywhere a <length>, <frequency>,
<angle>, <time>, <percentage>, <number>, or <integer> is allowed.
```
for all those functions.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()
> [CSS] Add clamp()/min()/max() functions

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This PR fixes commas in unpack expressions not being scoped.
> [Python] Fix comma scope in ordinary expressions

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
```lua
return 1 <= 2
return 1 << 2
local t = a >= b and b <= a
```
> [Lua] Fix left angle is treated as modifier in some cases

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_class.js
Remove a vestigial line that was messing up highlighting of methods named `async`. Reported by Mitranim on Discord.
> [JavaScript] Fix methods named 'async'.

- JavaScript/Symbol List - Exports.tmPreferences
Partial implementation for #2720. Handles e.g.:
```js
export const foo = 42;
```
`foo` will be added to the indexed symbol list, but not the local symbol list.
Function assignments are not affected:
```js
export const f = () => {};
```
`f` is still added to the local symbol list as well as the indexed symbol list.
Ordinary named exports are not implemented:
```js
export foo;
```
`foo` is not indexed. This will probably require a little extra scoping (in another PR).
> [JavaScript] Add exported variables to indexed symbol list

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Fixes #2764
It appears D already ensures `a *b` or `a* b` are scoped as arithmetic expressions ( in square brackets or parens ), except `for()` arguments.
This commit therefore refines `definitely_declaration_lookahead` to prefer declaration statements over arithmetic expressions in "statements" contexts and fixes the for arguments context to make sure to match declarations only befor the first semicolon.
With this PR merged, the provided example in issue #2764 looks like
> [D] Fix pointer and array type scopes in declarations

- PHP/tests/syntax_test_php.php
- SQL/SQL.sublime-syntax
- SQL/syntax_test_sql.sql
This PR...
1. scopes `*` `variable.language.wildcard.asterisk` for consistency with Java and Makefile
2. scopes `||` as `keyword.operator.concatenation` for consistency with Lua, D [and Perl].
3. renames `keyword.operator.math` to `keyword.operator.arithmetic` to comply with scope naming guidelines.
> [SQL] Scope consistency

- R/R.sublime-syntax
- R/syntax_test_r.R
Here's another tweak for operator scopes that I recently found.
Any R user here who knows what `<>` is used for and whether its scope name is correct, because I couldn't find it in the R documentation?
> [R] Fix scopes for comparison operators

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
`:matches` is officially renamed to `:is`.
https://developer.mozilla.org/en-US/docs/Web/CSS/:is
> [CSS] Add support for `:is` and `:where` pseudo class

- JavaScript/Comments.tmPreferences
- JavaScript/JSX Comments.tmPreferences
- JavaScript/JSX.sublime-syntax
- JavaScript/tests/syntax_test_jsx.jsx
Should fix #2461.
Given the following:
```js
<foo>
bar!
</foo>;
```
The `toggle_comment` command will comment the second line as follows:
```js
<foo>
{/*bar!*/}
</foo>;
```
But when you call it again to uncomment, you get:
```js
<foo>
{bar!}
</foo>;
```
…instead of the original, which we want. This is due to internal implementation details of `toggle_comment` — it won't remove `{/*`/`*/}`, even though they're specified in `JSX Comments.tmPreferences`, because the comment scope doesn't extend to the braces.
This PR adds a special case to JSX interpolations so that when an interpolation contains only a single block comment, the entire interpolation including the braces will get the `comment` scope, so that the `toggle_comment` command will do what we want. This is not really the correct …
> [JSX] Improve commenting behavior.

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_class.js
- JavaScript/tests/syntax_test_typescript.ts
For #2790.
Refactoring and improvements to handle modifiers like `static`, `readonly`, or `abstract`. This should fix various corner cases, including the one in the linked issue.
> [JavaScript] [TypeScript] Improve parsing of modifiers.

- Go/Indention Rules.tmPreferences
The XML declaration must be at the beginning of the file, before any comments. This PR fixes an error when parsing the file with `plistlib`.
> [Go] Fix XML error in indentation rules.

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This PR creates a dedicated context for @font-face properties and fills the list with all supported property names. Not all of them are supported globally.
Results:
1. Only valid property names are highlighted
2. Missing properties such as `ascent-override` are added.
3. `src` and `unicode-range` are removed from common property names as they are valid only in @font-face context.
> [CSS] Fix @font-face property names

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This PR adds a dedicated context for @counter-style property-lists. 
The goal is to tidy common/ordinary property lists from special at-rule stuff and highlight only those properties in at-rules which are valid.
A positive side effect is slightly improved parsing performance.
> [CSS] Fix @counter-style property names

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR enforces at least one whitespace after a hashtag to match a token as atx heading.
specification: https://spec.commonmark.org/0.29/#atx-headings
see also: 
- https://github.com/SublimeText-Markdown/MarkdownEditing/issues/572
- https://github.com/markedjs/marked/issues/201
> [Markdown] Fix ATX heading

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_control.js
When we changed variable declarations to use `keyword.declaration` instead of `storage.type`, apparently we forgot for loops.
> [JavaScript] Use keyword.declaration in for loops.

- Markdown/Markdown.sublime-syntax
This PR fixes the markdown YAML front matter ending to allow the use of `...` as well.
This is as per the YAML spec where the document ending could either be a `---` or a `...`
See: https://yaml.org/spec/1.2/spec.html#id2760395
P.S. I guess I can't write any tests for it because as per the current syntax definition, YAML front matter needs to be at the start of a file (which is also the case for the syntax test header, so conflicts).
> [Markdown] Fix YAML front matter ending to allow `...`.

- Python/Python.sublime-syntax
- Python/syntax_test_python_strings.py
This PR allows the use of dashes in unicode names.
```python
import unicodedata
unicodedata.lookup("black up-pointing triangle")
>>> '▲'
```
Fixes #2863
> [Python] Allow dashes in unicode names.

- Markdown/Code Block Syntaxes.sublime-completions
- Markdown/Markdown.sublime-syntax
Recently GitHub added support for
````
```rs
fn main() {}
```
````
code blocks rendering as Rust:
```rs
fn main() {}
```
where `rs` is a new alternative to the previous keyword `rust`.
I’m not sure what markdown flavor the syntax highlighting files in this repo are supposed to follow, but it this is wanted here’s a PR adding this ```` ```rs```` to highlighting and completions.
> [Markdown] Add `rs` for marking Rust code blocks

- Git Formats/Git Attributes.sublime-syntax
This PR adds some maintanance changes to _Git Attributes.sublime-syntax_
1. Fixes the `immediately-pop` context name
2. Excludes prototype from contexts which are not meant to receive one by inheriting syntaxes
3. Adds a named context for quoted `string-content` 
4. Scopes strings `meta.string` in case interpolation is desired at any time.
> [Git Formats] Git Attributes maintanance

- C++/C++.sublime-syntax
Fixes #2864
This change corrects the scope of the enum data-structure check.
> [C++] Correct the C++ data-structures enum scope

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
Fixes #2839
Fixes #2871
This commit matches the first `<<` after an identifier `keyword.operator` to prevent string assignments to be scoped as HEREDOC tags by accident.
> [Ruby] Fix << assignment operator scopes

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #2849
This commit scopes function identifiers as reference in commands like
`declare -f fun_name`
instead of scoping them definition.
_Note: Appears syntax caches contained several trailing spaces._
> [ShellScript] Fix declare/typedef function scopes

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
Fixes #2703
This commit scopes `/` directly followed by an operator as beginning of a regexp pattern.
It can't catch all edge cases though.
Patterns following a keyword keep unchanged as those still might be operators and there's no real solution to distinguish them from patterns.
Maybe `%r{...}` or friends should be used then.
> [Ruby] Improve classic multiline regexp patterns

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
Fixes #2859
Partly reverts f3f268b.
This commit matches `/pattern/` only after methods known to support it. Otherwise methods without parentheses may cause division operators to be matched as beginning of a pattern if another slash was found in the same line.
> [Ruby] Restrict regex to selected methods

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Fixes #2946
Once the `value-no-mapping-key` context is set on stack by case keyword any following list must continue to use this special value context.
Hence a new `value-list-after-no-mapping-key` is created, which is used by `value-list-no-mapping-key`.
> [D] Fix case statement with comma separated pattern

- ASP/ASP.sublime-syntax
- ASP/HTML (ASP).sublime-syntax
This commit assigns *.asa extension to HTML (ASP).sublime-syntax as it also requires to wrap VBScript into `<% %>` or `<script type="vbscript">` tags.
> [ASP] Fix *.asa file association

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
Fix fenced code blocks breaking syntax highlighting of block quotes
Example:
> ```
> content
> ```
Note:
Syntax highlighting within quoted fenced code blocks is not supported as it would require to extend any embedded syntax to properly scope leading quote punctuation. It wouldn't even be possible for more complex syntaxes.
> [Markdown] Fix fenced code blocks in block quotes

- HTML/Snippets/html (begin tag).sublime-snippet
- HTML/Snippets/html.sublime-snippet
> [HTML] add `viewport` meta tag to `html` snippet; fixes #2697

- Ruby/Symbol List - Classes, Modules.tmPreferences
Since https://github.com/sublimehq/Packages/pull/2156, `entity.name.namespace` is used instead of `entity.name.module`.
This fixes go to definition for such namespaces because `symbolIndexTransformation` is now applied properly.
> [Ruby] Fix module names in index

- XML/XML.sublime-syntax
XAML is an XML-based language and can use the same output format. This patch adds support for XAML files. Proposed in sharkdp/bat#1590 and sharkdp/bat#1655.
I have not modified the XML test file for now, because I am not too familiar with XAML. If anyone knows of XAML-specific features we can test for, I would be happy to add to the PR.
> [XML] Add support for XAML files

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #2944
This PR implements import statement according to https://docs.python.org/3.8/reference/grammar.html
Related BNF is:
```
import_stmt: import_name | import_from
import_name: 'import' dotted_as_names
import_from: ('from' (('.' | '...')* dotted_name | ('.' | '...')+)
'import' ('*' | '(' import_as_names ')' | import_as_names))
import_as_name: NAME ['as' NAME]
dotted_as_name: dotted_name ['as' NAME]
import_as_names: import_as_name (',' import_as_name)* [',']
dotted_as_names: dotted_as_name (',' dotted_as_name)*
dotted_name: NAME ('.' NAME)*
```
Before this PR ...
1. an `as` keyword set the alias-list context onto stack assuming all following commas to be a list of alias names, which is obviously wrong resulting in #2944.
2. line continuation operators (`\`) broke parenthesized …
> [Python] Fix import statements

- Markdown/Default.sublime-keymap
It appears the removed key binding behaves different depending on keyboard layout (deadkeys). This results in sub-optimal behavior for a reasonable number of users.
It may also jump in if one tries to add inline codeblocks at the beginning of a line.
Attempts to bind ``["`", "`", "`"]`` or tweak `context` have not been successful.
Adding syntax specific settings to gate this binding are probably not worth it.
Hence it's probably better to remove it.
see:
- https://forum.sublimetext.com/t/markdown-fenced-code-snippet/58261/3
- https://discord.com/channels/280102180189634562/280157083356233728/866850636083494963
> [Markdown] Remove keybinding for fenced codeblocks

- Markdown/Markdown.sublime-syntax
Fixes #2913. Not convinced a test can be added for it, however. :)
> [Markdown] fix trailing punctuation being part of autolink at last char of file

- Ruby/Symbol List - Constants.tmPreferences
Index constants and include them into the symbol list.
This enables go to definition for constants. As a side benefit, go to definition will now work for classes defined like this:
```ruby
Foo = Class.new do
def bar; end
end
```
> [Ruby] Index constants

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
Fix #2821.
Ordinarily, the syntax should handle statements without semicolons just fine — when it encounters an unexpected token in an expression, it will pop away the expression. However, when it sees `::`, it greedily matches the first colon as an accessor, which breaks things.
Simply fixing that rule doesn't do it because there's a catch-all rule in `expression-end` that's designed to keep this from happening to improve the highlighting of invalid code. Rather than making that rule more complicated, I added an extra rule specifically to handle `::`.
> [Lua] Fix bug with expressions that don't end in a semicolon.

- HTML/html_completions.py
If you type HTML attributes and these are inserted by the auto completion an empty attribute value is added automatically and the cursor jumps to the value so users can start typing.
For boolean attributes like "disabled" this is valid, but not necessary and I think most people use boolean attributes without a value.
This PR removes the value for boolean attributes. I got the list of boolean attributes from this Gist: https://gist.github.com/ArjanSchouten/0b8574a6ad7f5065a5e7#gistcomment-3231272
> [HTML] Add detection of boolean attributes to avoid empty attribute values

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
This is a valid constant definition in Ruby:
```ruby
CONSTANT ||= 'value'
```
Here's an example from Discourse: https://github.com/discourse/discourse/blob/599327658c4abb97a77aac22ff9c16ec8c7708e7/lib/discourse.rb#L693
> [Ruby] Identify constants defined with `||=`

- Regular Expressions/RegExp.sublime-syntax
- Regular Expressions/syntax_test_regexp.re
[Regular Expressions] Scope contents of `\Q`...`\E` as literal and allow quantifiers after `\E`. This is valid syntax in ST's Find panel.
> [Regular Expressions] Scope contents of \Q...\E as literal and allow quantifiers after \E

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
This PR assigns more specific scopes for boolean constants `true` & `false` from `constant.language` to `constant.language.boolean` & `nil` from `constant.language` to ~~`constant.language.nil`~~ `constant.language.null`.
Related PR's 
1. #2785
> [Ruby] More specific language constant scopes.

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
> [C#] Support tuples whose commas are not on the same line as the open paren

- CSS/css_completions.py
ST4's auto-completion system no longer picks up custom property names such as `--my-custom-property` from buffer. Thus they are no longer suggested in `var(--|)` functions for instance.
This PR extends `css_completions.py` to teach it providing custom properties defined in current file as completions in `var()` function arguments.
With ...
```CSS
html {
--my-custom1: foo;
--my-var2: bar;
}
```
... the following ...
```CSS
p {
property: var(--mv|);
}
```
... completes to ...
```CSS
p {
property: var(--my-var2|);
}
```
see: https://forum.sublimetext.com/t/css-variable-suggestions-gone-with-new-update/59431
> [CSS] Add custom property completions in var() functions

- ShellScript/Bash.sublime-syntax
This is a patch to `Bash.sublime-syntax` that adds support for shebangs explicitly calling for dash, e.g., `#!/usr/bin/env dash`. Proposed in sharkdp/bat#1654.
I have not modified the Bash syntax test file since the dash shell supports less features than Bash.
> [ShellScript] Add support for dash shebang

- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
If you add an attribute to a method (which in ObjC comes at the end) the highlight will break:
> [Objective-C] Allow __attribute__ in method declaration

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR applies CommonMark specification to ATX headings and reorganizes related contexts.
see: https://spec.commonmark.org/0.30/#atx-heading
Major changes:
1. allow up to 3 spaces in front of atx headings
2. closing punctuation must be preceded by at least one space or tab
3. limit "whitespace" to "tab" and "space"
4. add support for empty headings
> [Markdown] Fix atx headings

- HTML/HTML (Plain).sublime-syntax
- HTML/HTML.sublime-syntax
This commit adds some `meta_include_prototype: false` rules to attribute value contexts, which may contain unquoted values.
Without this rule any ordinary `prototype` context can be injected between assignment operator and beginning of an unquoted value. As a result the unquoted value starts after this injected context is popped or doesn't match anything anymore.
What we want is to first push into unquoted-value context and than let inherited syntaxes apply normal string interpolation to maintain proper value boundaries.
Note: It's hard to test without a inheriting syntax at hand.
It is discussed at https://discord.com/channels/280102180189634562/280157067396775936/867802732482920458
Created a Gist with an example at https://gist.github.com/deathaxe/dabcd7575951174d08882b46842dd44a
If …
> [HTML] Exclude prototypes from attribute value starts

- Haskell/Haskell.sublime-syntax
- Haskell/syntax_test_haskell.hs
> [Haskell] match (--*) in punctuation.definition.comment.haskell

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
```php
$sql = "SELECT";
//      ^^^^^^ - keyword.other.DML
```
Fixes https://github.com/sublimehq/Packages/issues/2956
> [PHP] Do not highlight plain SQL indicator as SQL

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Addresses https://github.com/sublimehq/sublime_text/issues/4763
Missing bailouts can cause large portions of or the whole document to be re-lexed if single expressions are incomplete during editing.
It may cause the whole application to freeze several seconds after each key stroke because of PHPs complexity.
This commit therefore adds a pattern, which causes any nested expression context to be popped off stack, once a token is matched which is known to start a new statement.
Note: The strategy of adding a 2nd-level bailout to limit broken syntax highlighting due to invalid/incomplete expressions is heavily made use of in "Java Rewrite" PR and other syntaxes such as Erlang, already.
> [PHP] Add expression bailouts

- Markdown/Default.sublime-keymap
Fixes #2973
This PR...
1. fixes wrong `preceding_text` context pattern, which was originally actually designed for auto-pairing asterisks.
2. adds `following_text` pattern to make sure to auto-pair backticks only when likely.
Auto pairing takes place if following conditions are met:
- caret is not located directly after a word or backtick
- caret is followed by
- whitespace
- closing bracket
- sentence punctuation (comma, full stop)
- end of line
> [Markdown] Fix backtick auto-pairing

- ASP/syntax_test_asp.asp
- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
Fixes #2322
Fixes sublimehq/sublime_text#4701
In order to enable comment toggling using rules of embedded syntax definitions it is important to maintain its main scope at the beginning of first and last line.
The challenge is to also support CSS/JS being wrapped into HTML comment markers.
Another goal is to keep as many implementation details away from contexts which may need to be overridden by inheriting syntax definitions such as ASP/JSP/PHP to keep dependencies low. Some little changes are required though at this point to accomplish that.
_Note: This commit includes the assumption that JavaScript won't contain a standalone `-->` on a single line._
Also note this PR may have infuence on implementation details in #2654, #2789 and #2797
> [HTML] Fix toggle html comments in css/js tags

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_C#8.cs
- C#/tests/syntax_test_C#9.cs
Change the meta and punctuation scopes used for tuples in the C# syntax to match the Python syntax definition - from `meta.group.tuple punctuation.section.group.begin` to `meta.sequence.tuple punctuation.section.sequence.begin` etc.
Suggested in https://github.com/sublimehq/Packages/pull/2838#discussion_r690632925
> [C#] rework tuple scopes to match Python

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
This PR fixes duplicated `meta.tag` scopes being applied to parts of style/script tag attributes.
> [HTML] Fix duplicated meta scopes in tag attributes

- LaTeX/Snippets/Chapter.sublime-snippet
- LaTeX/Snippets/Description.sublime-snippet
- LaTeX/Snippets/Enumerate.sublime-snippet
- LaTeX/Snippets/Item[description].sublime-snippet
- LaTeX/Snippets/Itemize.sublime-snippet
- LaTeX/Snippets/Paragraph.sublime-snippet
- LaTeX/Snippets/Part.sublime-snippet
- LaTeX/Snippets/Sub-Paragraph.sublime-snippet
- LaTeX/Snippets/Tabular.sublime-snippet
- LaTeX/Snippets/begin{}-end{}.sublime-snippet
- LaTeX/Snippets/section-..-(section).sublime-snippet
- LaTeX/Snippets/subsection-..-(sub).sublime-snippet
- LaTeX/Snippets/subsubsection-..-(ssub).sublime-snippet
Fixes #2730
This commit modifies `tabTrigger` of those snippets, whose committed content starts with exactly the same characters.
As a result both, typing:
a) `begin`
b) `\begin`
result in
```latex
\begin{env}
|
\end{env}
```
when hitting tab (twice?!)
Also removes escaped backslashes from content as those seem not to be needed. So \\begin becomes \begin.
> [LaTeX] Fix duplicated backslashes inserted by snippets

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR is part 2 to address https://github.com/sublimehq/sublime_text/issues/4763.
It refactors string related contexts in order to 
1. reduce application of branch_points and avoid as many context switches as possible.  
It results in huge performance improvements when recovering from incomplete quoted strings in large files.
While closing a quoted string at the beginning of a file of 500k lines took 16-19s before, it completes within 200-300ms with this PR merged.
2. apply proper `meta.string meta.interpolation` scopes as already done in other syntaxes.
Also loading such a huge file completes much faster as switching back to ST does after modifying the file externally.
While it required 16 seconds for ST do display again, it now completes nearly immediatelly.
> [PHP] Refactor string contexts

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR refactors SETEXT heading maching in order to comply with https://spec.commonmark.org/0.30/#setext-headings and provide proper bailouts. This should fix (or workaround) https://github.com/sublimehq/sublime_text/issues/4746.
Note: This PR causes some merge conflicts with #2925.
> [Markdown] Refactor SETEXT headings vs. paragraphs

- JavaScript/JSX.sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/TSX.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Fix https://github.com/sublimehq/Packages/issues/2660.
The implementation is a bit of a mess at the moment, largely due to https://github.com/sublimehq/sublime_text/issues/3494 hampering code reuse. 
The implementation differs between plain TypeScript and TSX because in TypeScript, a `<` in `expression-begin` indicates either an arrow function or an old-style type assersion, whereas in TSX it indicates either an arrow function or a JSX element. In ambiguous cases (e.g. `<T extends U>() => {}`), arrow functions seem to win. (Because TypeScript does not have a language spec, I had to reverse-engineer its behavior using AST Explorer. I'm fairly confident I got it right.)
> [TypeScript] Implement arrow function type parameters.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
Fix #2929.
In a case like `a ? (b) : …`, the colon can be either the second ternary operator (`a ? (b) : c`) or a type annotation (`a ? (b) : T => {} : c`). Whenever we see a colon after a (conjectured) parenthesized expression, we try to parse it as a type annotation. If it works, and we see `=>`, then we backtrack before the parenthesized expression. If it doesn't work, we backtrack before the colon. (Yes, unfortunately, we backtrack either way.)
Part of the reason this works is that value expressions and type expressions are similar enough that the parser won't “get lost” when speculatively parsing a value expression as a type expression. But the linked issue provides an example of a place where the parser does get lost:
```tsx
conditionalValue ? (x) : <div className={`${y}`} />;
``` …
> [TypeScript] Fix a bug when deciding whether a colon is a ternary operator or type annotation.

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_class.js
Static blocks are a Stage 3 proposal with an experimental implementation in Firefox. In addition, they're part of TypeScript 4.4, which is at the RC stage.
I use `keyword.declaration` for the `static` keyword in these blocks. I think this is more appropriate than `storage.modifier`, but I could be persuaded otherwise.
- https://github.com/tc39/proposal-class-static-block
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/
As part of this PR, I slightly reshuffled how class element modifiers work. This was necessary to avoid code duplication due to https://github.com/sublimehq/sublime_text/issues/3494.
> [JavaScript] [TypeScript] Implement static blocks.

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #2881
This PR fixes test pattern matching enclosed in parentheses.
Before this commit a group context wasn't popped as closing parenthesis was matched as part of pattern on the right hand side of the expression.
> [ShellScript] Fix test expressions with groups

- Git Formats/Git Log.sublime-syntax
- Git Formats/tests/syntax_test_git_log
This allows Sublime to highlight the Git Log more like "regular `git log`" output in the case of the HEAD entry.
First reported at https://github.com/sharkdp/bat/issues/1632
Honestly, I wasn't too sure about what scopes to use, so if someone with more experience with the Git Formats syntaxes could chime in, it'd be much appreciated. :)
> [Git Formats] Add support for Git Log HEAD line

- Ruby/Ruby.sublime-syntax
Was regressed by 359d42a7d2550040fe9c5840ced7419ca5179753
> [Ruby] Fix duplicated expressions import

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This allows us to remove the complicated lookaheads / `simple_expression` variable (which have terrible performance in Oniguruma, for non-ST use cases).
To keep the existing approach of detecting set vs dict by/at the first comma, I set away from the context with the `fail` instruction when we reach the comma or colon, which allows us to "succeed" the branch and keep the existing invalid highlighting hints when there's a colon in a set or a comma without a colon in a dict etc.
> [Python] use branching to detect set vs dict and for tuples vs expression

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This commit fixes missing strikethrough highlighting within bold or italic formatted text.
Some of the existing tests are moved to the new "Strikethrough Tests" section. Existing links to github are removed as those no longer point to correct examples. The existing tests keep otherwise unchanged.
> [Markdown] Fix strikethrough within bold or italic text

- Matlab/Default.sublime-keymap
A single quote directly following a dot `.'` is the transpose operator in Matlab and a single quoted string after a dot (without whitespace in between) would be syntax error afaik.
> [Matlab] Disable auto-pair of single quote when used as transpose operator

- LaTeX/LaTeX.sublime-syntax
- LaTeX/syntax_test_latex.tex
This allows to use character escapes and commands within braces in the array preamble, which might appear in special column specifier arguments, for example as provided by the dcolumn package.
Fixes #2238.
> [LaTeX] Allow character escapes and commands in array preamble

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This commit fixes scoping of numbered list bullets which end with parentheses.
see: https://spec.commonmark.org/0.30/#ordered-list-marker
> [Markdown] Fix parenthesized numbered lists

- LaTeX/Bibtex.sublime-syntax
- LaTeX/syntax_test_bibtex.bib
To follow the convention from JSON, Git config, and other syntaxes.
> [LaTeX] Apply meta.mapping scopes in BibTeX entries

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
- JavaScript/tests/syntax_test_typescript_not_tsx.ts
One of the new tests added in #2923 is correct for plain TypeScript, but wrong for TSX. (#3998 would have caught the bug.)
This PR modifies that test to also be valid for TSX and adds new tests for plain TypeScript and for TSX.
It also deletes some commented code that doesn't need to exist.
> [TypeScript] [TSX] Fix arrow function type parameter tests for TSX.

- Erlang/Erlang.sublime-syntax
- Graphviz/DOT.sublime-syntax
- Makefile/Makefile.sublime-syntax
- Python/Python.sublime-syntax
- R/R.sublime-syntax
As per discussions in https://github.com/sublimehq/Packages/pull/2916
Even on Linux/Mac, ST detects file extension in a case-insensitive manner.
> [Common] Remove duplicate case-insensitive extensions

- Perl/Perl.sublime-syntax
- Perl/syntax_test_perl.pl
This PR renames scope of `=~`, `!~` and `~~` pattern matching operators to `keyword.operator.comparison` as this is a more appropriate scope name which is already used by Ruby for those.
Note: The inconsistant naming was revealed while working on a fix for Bash's pattern matching.
> [Perl] Fix pattern matching operator scopes

- Git Formats/Git Link.sublime-syntax
- Git Formats/Git Log.sublime-syntax
- Git Formats/tests/syntax_test_git_link
- Git Formats/tests/syntax_test_git_log
first reported at https://github.com/sharkdp/bat/issues/1735
> [Git Formats] highlight diffs in Git Log syntax for `git show`

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #2988 
This PR ...
1. removes `numbers` from right hand side of pattern matching or comparison expressions.
2. scopes `=~` as `keyword.operator.comparison` to match Perl/Ruby.
Note:
According to the bash docs...
1. the `test ...` command doesn't support Perl like pattern matching via `=~` operator.
2. features differ between `[ ... ]`  and `[[ ... ]]` operators.
3. highlighting would probably need to be distinguished between string/pattern matching and arithmetic comparisons in case of `-eq` operators are present.
Those improvements may be part of future improvements.
> [ShellScript] Fix numbers breaking pattern matching it test expressions

- Perl/Perl.sublime-syntax
- Perl/syntax_test_perl.pl
Fixes #2896
This PR allows quoted heredoc tags to be arbitrary strings instead of just identifiers.
> [Perl] Fix heredocs with arbitrary quoted tags

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This commit fixes a syntax highlighting issue which causes inline links or references not to be highlighted correctly if those directly follow a footnote.
The footnote was highlighted as reference causing the reference description to be highlighted as url. The reference's url was not
highlighted at all.
The reason is footnotes not having an url-part. So they must be matched before literal references.
> [Markdown] Fix refs/links after footnotes

- CSS/Indentation Rules - Comments.tmPreferences
- CSS/Indentation Rules.tmPreferences
- CSS/syntax_test_indentation.css
Fixes #1267
This PR adds _Indentation Rules.tmPreferences_ to fix some issues with regards to comments after opening and closing brackets breaking correct indentation.
It borrows some strategies from C/C++ and Java to fully exclude block comments so normal CSS rules are indented correctly even after 
```
/**
* comment
**/
``` 
Before this PR all following rules got vertically aligned to `**/` which resulted in one column off.
It also overrides ST's default bracket indentation to make sure to indent after an opening bracket, even if it is followed by arbritary number of probably nested brackets, while ignoring any bracket in quoted strings.
Maybe some of those rules are rarely needed and probably won't appear in real life code, but the intention is to hopefully find some kind of common …
> [CSS] Add indentation rules

- PHP/PHP.sublime-syntax
This PR adds some prototype exclusions to ensure shebang comments to be highlighted at the very first line only.
Note:
The current PHP syntax doesn't use prototype, so the added directives are probably not required in first place, but as they are added to those contexts in various other syntaxes it might help to maintain formal consistency between them.
> [PHP] Restrict shebang highlighting to very first line

- Erlang/Erlang.sublime-syntax
This PR ...
1. adds some prototype exclusions to ensure shebang comments to be highlighted at the very first line only.
2. renames `comment` context to `comments` as it is non-popping.
3. adds a named `comment-body` context to keep in-line with the others.
> [Erlang] Restrict shebang highlighting to very first line

- Lua/Lua.sublime-syntax
This PR ...
1. adds some prototype exclusions to ensure shebang comments to be highlighted at the very first line only.
2. creates named comment contexts to keep in-line with other syntaxes and improve inheritability.
> [Lua] Restrict shebang highlighting to very first line

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Fix #3019.
Also scope the braces surrounding an object type as `punctuation.section.mapping` instead of `punctuation.section.block`. The braces around interfaces are unchanged.
N.B. The `ts-type-object` context was inadvertently unused. This PR fixes it up and uses it for object types.
> [TypeScript] Support quoted member names in object types.

- SQL/SQL.sublime-syntax
- SQL/syntax_test_sql.sql
Scope escape characters inside single quoted strings after a LIKE keyword. Also, scope `ESCAPE` and the character after it. Fixes https://github.com/sublimehq/Packages/issues/630#issuecomment-910532251.
We could improve on this in a follow-up PR to use branching to detect a strict set of escape characters (specifically, `\`) so that the scoping inside the `LIKE` string would be correct.
> [SQL] Improve handling of LIKE keyword

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Not sure if we see any progress on #2826 and release date is not too far in the future (3.10.0 final: Monday, 2021-10-04).
So here's another attempt to implement structural pattern matching.
Patterns differ from normal expressions slightly, so a complete new tree of contexts is created.
Some of the existing contexts are modified to re-use as much as possible.
> [Python] Add support for PEP 635 structural pattern matching

- Perl/Perl.sublime-syntax
- Perl/syntax_test_perl.pl
This PR...
1. restricts shebang highlighting to the very first line
2. adds some named contexts for comments (doesn't change behavior).
> [Perl] Fix shebang highlighting and restructure comment contexts

- Markdown/Code Block Syntaxes.sublime-completions
- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR proposes to 
1. add highlighting support for some more default syntaxes in fenced codeblocks.
2. sort all syntaxes alphabetically.
3. reorganize each syntax in a dedicated context for easier overriding etc. by inherited syntax definitions
4. avoid matching fenced codeblocks in situations they most likely don't appear (e.g. in link texts), which reduces parsing time slightly. It splits inline code-spans from fenced code-blocks.
5. moves fenced-code-blocks out of normal paragraphs as those are separate "leaf blocks" according to CommonMark spec. This fixes #2947.
> [Markdown] Refactor fenced code blocks

- ASP/HTML (ASP).sublime-syntax
- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
This PR...
1. fixes scopes of stray script and style tags, which didn't match those from tag pairs.
2. avoids multi-pushing into embedded script/style syntaxes to simplify the language a bit and improve parsing performance. Closing tags are consumed within `main` context now.
3. removes pushing `text.html.embedded.html` onto stack.
a) As `main` context is pushed, it is not required for highlighting.
b) The only thing we loose is the mentioned scope, which seems to be of little value.
c) It is required as change (2) would break boundaries of `text.html.embedded` otherwise.
d) The less contexts HTML pushes onto stack the better it is for most possible flexibility with regards to inheritance or re-use in
heavily context aware templating syntaxes such as JSP or PHP.
e) It slightly improves …
> [HTML] Fix scopes of stray script and style tags

- Markdown/Markdown.sublime-syntax
The `{{setext_escape}}` pattern is included in `bold-italic-trailing` context, which is also included in all anonymous contexts this commit removes the pattern from.
This PR doesn't change behavior.
> [Markdown] Remove duplicated setext_escape patterns

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR...
1. includes `paragraph-end` into `bold-italic-trailing` context
2. moves the `bold-italic-trailing` includes before `inline` includes to terminate inline formatting by fenced code blocks
3. renames `bold-italic-trailing` to `bold-italic-common` and moves the `inline` include into it.
Everything, which terminates a paragraph, now also terminates inline formatting.
A token, which starts with an inline-formatting character such as `_` or `*` but is terminated by a paragraph boundary is not rendered bold/italic/strikethrough by CommonMark.
It is still scoped/highlighted as such by this syntax. This PR only fixes paragraph boundaries which have been ignored in such situations before.
A future PR may work on fixing this by using branch points, but it requires way more considerations …
> [Markdown] Terminate inline formatting on paragraph boundaries

- OCaml/OCamlyacc.sublime-syntax
- OCaml/syntax_test_mly.mly
If the ocamlyacc file begins with a multiline comment (`/*`), the `include: ocaml` rule gets activated, and parses it as a `/` operator followed by more pure ocaml syntax. By moving the `include: comments` rule higher up, it will be given precedence.
Before:
After:
Test file: https://github.com/roehst/tapl-implementations/blob/master/recon/parser.mly
(Side note: It seems even the github syntax highlighter is broken - the comments aren't getting highlighted properly)
> [OCaml] Fix bug when ocamlyacc file starts with comment

- .github/ISSUE_TEMPLATE/01-bug-syntax-highlighting.yml
- .github/ISSUE_TEMPLATE/02-bug-file-indexing.yml
- .github/ISSUE_TEMPLATE/03-supporting-files.yml
This PR removes colons from issue titles as those are not required due to package name being wrapped into brackets.
> [meta] Fix issue template title

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR implements a re-interpreted version of CommonMark's statement:
>  The first word of the info string is typically used to specify the language of the code sample...
>
>  see: https://spec.commonmark.org/0.30/#fenced-code-blocks
A word is not only `[\w-]+` but a sequence of any non-whitespace character, except backticks, in this context.
This is why `C++` is an valid fenced code language identifier.
This commit expects a language identifier to start with a letter, in order to avoid confusion with e.g. attribute annotations such as `{key=value}` which some Markdown extension support.
This enables `C++` being scoped as `constant.other.language` in block quotes, for instance.
> [Markdown] Highlight any unknown fenced language identifier

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
`typedef`s of `struct|class|enum|union` are detected wiser, target defined types are recognized as types rather than nothing
Changes are applied to C, C++, ObjC, ObjC++ syntaxes
> [C/ObjC/C++/ObjC++] improved syntax, typedef detection improvement

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_jsx.jsx
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Fixes #2880
This PR implements  ...
1. shebang highlighting using the scheme of PHP/Java/ShellScript to ensure it being highlighted at the very first line, only.
2. xml highlighting in triple-slash comments in TS/TSX syntax according to Typescript specs, but with a more lazy/forgiving xml highlighting.
3. more forgiving comment punctuation highlighting in order to help ligatures for `//` or `///` to be displayed and to improve UX in case color schemes apply special highlighting to comment punctuation.
4. scopes trailing `//` in line comments `punctuation` for consistent highlighting.
5. adds various comment related test cases to illustrate changes and differences between syntaxes.
It feels odd to only highlight
-  `/*` and `*/` as punctuation in delimiters like …
> [JavaScript/TypeScript] Improve shebang and comments highlighting

- PHP/PHP Source.sublime-syntax
fixes https://github.com/sublimehq/Packages/issues/3043
https://www.php.net/manual/en/book.dom.php
The official docs uses all capital `DOM`. Duplicate ones can be removed safely as that regex is case-insensitive.
> [PHP] Remove duplicate built-in classes

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3049
This PR adds a dedicated `lambda-in-groups` context, which differs from normal `lambda` only by an additional bailout to pop contexts off stack in case of `for` keyword being matched.
Let the including context handle/consume it.
Duplication of contexts is required to maintain illegal highlighting of `for` keyword in top-level statements, if not surrounded by brackets.
> [Python] Fix lambdas inside list comprehensions

- Git Formats/Git Attributes.sublime-syntax
- Git Formats/Git Commit.sublime-syntax
- Git Formats/Git Common.sublime-syntax
- Git Formats/Git Config.sublime-syntax
- Git Formats/Git Ignore.sublime-syntax
- Git Formats/Git Link.sublime-syntax
- Git Formats/Git Log.sublime-syntax
- Git Formats/Git Mailmap.sublime-syntax
- Git Formats/tests/syntax_test_git_attributes
This PR...
1. updates all syntax definitions to version 2 syntax format
2. replaces pop: true by pop: 1
3. resorts main keys according to #2430
> [Git Formats] Update to sublime-syntax version 2

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3060.
The `abstract` and `declare` keywords were only handled in `statement`, not in the export stuff. This adds them to `export-extended`.
It might be a good idea to move all of the exportable declarations into a single new context in the future.
Also, the scopes on `enum` and `declare` should probably be updated in the future.
> [TypeScript] Support export declare enum/export abstract class.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix https://github.com/sublimehq/Packages/issues/3059#issue-1011995899.
Function types are parsed similarly to arrow functions — the content of the parentheses is parsed as a parenthesized type, and then if an arrow is found after the close paren, the parser backtracks and re-parses as a function type. But if parsing goes far wrong within the parens, then it can't find the arrow. This can happen because function type parameter lists are not necessarily valid parenthesized types. For arrow function literals, we account for this by making sure that the expression grammar “covers” the parameter list grammar. That doesn't work here because we need to be very strict with bailing out of invalid types. Instead, when we see that a parenthesized type has gone wrong, we immediately backtrack and …
> [TypeScript] Fix a bug in function type parsing.

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix https://github.com/sublimehq/Packages/issues/3059#issuecomment-931252137.
Having `set` there instead of `push` was effectively popping `ts-type-expression-end-no-line-terminator` before it could match the array modifier. `push` works fine.
I tried various silly examples to see whether parsing multiple type argument lists in a row would break anything, but it doesn't seem to. For your amusement:
```tsx
Foo<bar><baz>();//</baz> // This still works correctly.
class C extends Foo <T> < 42 {} // This isn't valid anyway, and it doesn't break too badly.
```
> [TypeScript] Fix array type modifier after generic.

- Python/Python.sublime-syntax
Built-in exception added in Python 3.6
> See : <https://docs.python.org/3.9/library/exceptions.html#ModuleNotFoundError>
---
Thanks, bye 👋
> [Python] Add support for `ModuleNotFoundError`

- JavaScript/JavaScript.sublime-syntax
This regexp is causing pathological backtracking in Oniguruma. The change is otherwise nonfunctional and shouldn't affect Sublime's highlighting or performance.
> [JavaScript] Optimize a regexp.

- Clojure/Clojure.sublime-syntax
- Clojure/tests/syntax_test_clojure.clj
This PR introduces 2 noticeable changes:
1. The current `push...with_prototype` solution is replaced by `embed...escape`
2. The main `source.regexp` syntax is embedded instead of `base-literal` in order to correctly highlight leading quantifiers illegal and to ensure to correctly apply all meta scopes of the regexp syntax.
Prepares for: #3078
> [Clojure] Embed regexp instead of push with_prototype

- Rails/Ruby on Rails.sublime-syntax
- Rails/syntax_test_rails.rb
ApplicationRecord was introduced some years ago with rails 5. In few words, it's the "new way" of inheriting from "ActiveRecord::Base"
> [Rails] Add meta.model.rails on classes that inherit from ApplicationRecord

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR scopes the text part of setext headings entity.name.section so ST assigns them the same kind info as it does for atx headings.
Note:
The final trailing newline character is also scoped `entity.name` for simplicity reasons. Headings may span multiple lines which requires newlines so excluding all newlines would result in multiple symbols per heading. Removing the final newline would require branching, but this seems not worth the effort and requires complicated solutions to escape from unclosed inline formatting contexts.
> [Markdown] Scope setext heading entity.name.section

- ShellScript/Bash.sublime-syntax
This commit excludes prototype context from some immediately popping contexts which exist to assign meta scopes only. This may help a bit in scenarios such as Makefile, which extends Bash.sublime-syntax to support Makefile's variable interpolation.
It's just a tiny optimization.
> [ShellScript] Exclude prototypes from meta scope only contexts

- C#/C#.sublime-syntax
- C#/tests/syntax_test_PreprocessorDirectives.cs
Ref: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/nullable-reference-types-specification#nullable-compiler-directives
> [C#] Add support for the #nullable compiler directive in C# 9.

- Markdown/Markdown.sublime-syntax
- Markdown/syntax_test_markdown.md
This PR proposes some fixes to improve CommonMark compliance with regards to when block quotes are terminated.
> [Markdown] Fix more block quote boundary issues

- Ruby/Embeddings/CSS (for Ruby).sublime-syntax
- Ruby/Embeddings/HTML (for Ruby).sublime-syntax
- Ruby/Embeddings/JavaScript (for Ruby).sublime-syntax
- Ruby/Embeddings/SQL (for Ruby).sublime-syntax
- Ruby/Embeddings/ShellScript (for Ruby).sublime-syntax
- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
Fixes #3124
This commit...
1. embeds external syntaxes in HEREDOCs to reduce Ruby's size and to ensure terminating HEREDOC tags are matched under all circumstances.
2. improves ruby interpolation in embedded syntaxes using inheritance.
> [Ruby] Fix HEREDOCs

- Git Formats/Git Common.sublime-syntax
- Git Formats/tests/syntax_test_git_commit
Fixes #3123
This commit enforces user name of at least 2 chars in auto-links of the form `user#issue` or `user@hash` to make sure not to highlight `C#7` or `F#7` etc.
> [Git Formats] Fix issue references

- ASP/HTML (ASP).sublime-syntax
- ASP/syntax_test_asp.asp
This commit adds `language="vbscript"` attribute to select syntax highlighting of script content.
see: https://forum.sublimetext.com/t/classic-asp-syntax-selection/60164/14
> [ASP] Add script language attribute

- Python/Python.sublime-syntax
This commit adds a dedicated context to scope the shebang line.
Some fonts like provide ligatures for the `#!` sign, thus need to ensure it is tokenized correctly.
The statements context is set onto stack if shebang matches but not after the next start of line or non-whitespace character. This is to make sure, the shebang is highlighted within fenced code blocks of Markdown.
> [Python] Add shebang

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR simplifies and improves some of the matching of heredoc tokens in PHP:
- Removes empty captures, like the two occurrences of `()` in `(()HTML())`. This has no effect on any tests or scoping, since these captures are always empty.
- Matches all heredoc tokens case-insensitively, since these are also valid PHP syntax. I updated one existing test to use `sql` instead of `SQL` to verify that this works as expected.
- Refer to the matched heredoc token using a numbered reference in the `escape` pattern, instead of repeating the token (e.g. `(?=^\s*\2\b)` instead of `(?=^\s*HTML\b)`). This is a bit less repetitive and makes it easier to update the token pattern itself if it changes.
- Add `JS` as a 'recognized' heredoc token (in addition to `JAVASCRIPT`) and apply JavaScript syntax …
> [PHP] Improve heredoc matching and add support for highlighting Yaml in heredocs

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
This commit removes some prototype-excludes to enable proper highlighting of qualified constants if block comments appear within the path.
> [Java] Fix qualified constants highlighting

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
XHTML supports wrapping script and style content into `<![CDATA[ ... ]]>` tags.
Found at https://github.com/liuchuo/JSP/blob/master/apache-tomcat-8.5.14/webapps/examples/websocket/echo.xhtml
> [HTML] Add support for script/style wrapped in CDATA

- Java/HTML (JSP).sublime-syntax
- Java/tests/syntax_test_jsp.jsp
XHTML supports wrapping script and style content into `<![CDATA[ ... ]]>` tags.
Found at https://github.com/liuchuo/JSP/blob/master/apache-tomcat-8.5.14/webapps/examples/websocket/echo.xhtml
> [Java/JSPX] Add support for script/style wrapped in CDATA

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3160
This commit prevents reserved words from being highlighted as functions after expressions such as tuples, lists, ... .
> [Python] Fix keyword highlighting after expressions

- C++/Indentation Rules.tmPreferences
- C++/tests/syntax_test_indent_classes.c++
- C++/tests/syntax_test_indent_common.c++
- C++/tests/syntax_test_indent_extern.hpp
Fixes #868
Fixes #3145
This commit copies indentation rules from Java and adds C/C++ specific rules/keywords as well as some indentation tests.
It can't solve all problems, but may help to improve some of the known issues.
> [C/C++/ObjC/ObjC++] Improve Indentation Rules

- Python/Python.sublime-syntax
Fixes #3172
This commit matches python minor version parts of two digits of length.
> [Python] Fix shebang highlighting for python 3.10+

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_bindings.js
This commit adds `dollar_identifier` to function parameter names to scope the leading `$` as `punctuation` the same way as for variables.
If the dollar is scoped punctuation, it should be everywhere.
> [JavaScript] Highlight dollar sign in function parameters

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
Closes #3176
This commit adds JSON to the list of supported syntaxes between script tags.
> [HTML] Add syntax highlighting support for JSON scripts

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_class.js
Reported by Mitranim on Discord.
Private and computed field names were not popping the `field-name` context, so if the next token were an identifier, it would highlight wrong. (Class fields are usually followed by initializers, type annotations, or semicolons, but they don't have to be.)
> [JavaScript] Fix bug when some class field names are not followed by a semicolon or initializer

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
Fixes #3161
This commit reworks import identifiers using branching in order to properly highlight all kinds of type and static imports in case insensitive manner.
The new sections `TYPE IMPORT` and `STATIC IMPORT` are copied from `CONSTANTS` section and simplified by removing the `unqualified-...` part.
_Note: The current implementation in master dates back to 2019 when branching was not yet available._
> [Java] Improve import statement identifiers

- JSON/JSON.sublime-syntax
GLTF is the JSON encoding of a widely used 3D scene file format. A separate extension `glb` is used for the binary format, the GLTF format is generally only useful for debugging - and is therefore opened often in my sublime.
Thought it might be helpful for others. Though I'm not sure how exhaustive these lists are intended to be.
> [JSON] Add GLTF to the list of file_extensions

- HTML/Indentation Rules.tmPreferences
If the `!doctype` tag isn't upper-case, it isn't recognised, and the following lines are indented. My changes make matching of doctype case-insensitive so it shall be recognised even if it isn't upper-case.
> [HTML] Make matching of doctype for indentation case-insensitive

- HTML/html_completions.py
This PR prevents to add illegal closing tags for [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) when expanding tag attributes:
> Void elements only have a start tag; end tags must not be specified for void elements.
For example, currently `hr.myruler` will expand to `<hr class="myruler"></hr>`, but after this change it will properly become `<hr class="myruler">`.
---
As an unrelated change, I removed two unnecessary allocations of `sublime.Region` in lines 469 and 477.
> [HTML] Prevent closing tag for void elements when expanding tag attributes

- Matlab/Default.sublime-keymap
The keybinding recently added to disable auto-pairing of the single quote, when used as transpose operator (after one of the characters `])}.`) inadvertently disabled the default keybinding to step over the closing punctuation of a string, if the string ends with one of these characters.
This commit excludes the string punctuation scope from the keybinding to fix it.
> [Matlab] Exclude strings from transpose operator keybinding

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR adds support for using the `readonly` keyword inside constructor-promoted properties.
This is valid PHP code:
```php
class Bar
{
public function __construct(
public readonly string $foo,
) {}
}
```
But Sublime currently doesn't scope that `readonly` correctly:
> [PHP] Support `readonly` with constructor property promotion

- JavaScript/Indentation Rules - Comments.tmPreferences
- JavaScript/Indentation Rules.tmPreferences
- JavaScript/tests/syntax_test_js_indent_common.js
Fixes #3212
This commit copies indentation rules from Java (also added to C/C++ via #3148).
It improves behavior related to comments and one-liner statements such as:
if (foo) return bar
It can't solve all problems, but may help to improve some of the known issues.
> [JavaScript] Improve Indentation Rules

- Python/Python.sublime-syntax
- Python/syntax_test_python_strings.py
> [Python] Fix debugging f-string replacements

- Java/HTML (JSP).sublime-syntax
- Java/JSTL Expression Language.sublime-completions
- Java/tests/syntax_test_jsp.jsp
This commit...
1. highlights ${expr} variable expansions everywhere in a document, not just in tag attribute values.
2. replaces the embedded Java syntax by a dedicated and more simple "EL" syntax, which is more or less a subset of Java. 
EL means "expression language"
Syntax is described in 
Book:     "Core JSTL: Mastering the JSP Standard Tag Library"
Chapter:  "The JSTL Expression Language"
see: https://www.informit.com/store/core-jstl-mastering-the-jsp-standard-tag-library-9780131001534?w_ptgrevartcl=The+JSTL+Expression+Language_30946
Implementation follows https://www.informit.com/articles/article.aspx?p=30946
Inspired by https://forum.sublimetext.com/t/import-in-custom-syntax-default-ones/61716/2 and the linked repo.
> [Java] Improve JSTL interpolation in Java Server Pages

- Matlab/Matlab.sublime-syntax
- Matlab/Symbol List.tmPreferences
- Matlab/syntax_test_matlab.matlab
Reference from the Matlab docs: https://www.mathworks.com/help/matlab/matlab_prog/create-and-run-sections.html
The scope `entity.name.section` is added to the section title, which is already used in R and gets a "navigation" kind icon in the Goto Symbol panel. Also the pattern was adjusted so that section comments should start on their own line.
> [Matlab] Add code section comments to symbol list

- C++/Indentation Rules.tmPreferences
- C++/tests/syntax_test_indent_common.c++
This commit restricts `bracketIndentNextLinePattern` to not match loops
if the loop condition expression spans multiple lines as it causes
breaks indentation of the following code block if the block's opening
brace directly follows the closing parenthesis on the same line.
The result was only the first line of the block being indented.
Fixes https://forum.sublimetext.com/t/the-indenting-of-a-c-for-loop-is-incorrect-under-certain-conditions/52634/4
> [C/C++/ObjC/ObjC++] Fix loop statement indentation

- Java/Java - Indentation Rules.tmPreferences
- Java/tests/syntax_test_java_indentation.java
This commit restricts `bracketIndentNextLinePattern` to not match loops
if the loop condition expression spans multiple lines as it causes
breaks indentation of the following code block if the block's opening
brace directly follows the closing parenthesis on the same line.
The result was only the first line of the block being indented.
Fixes https://forum.sublimetext.com/t/the-indenting-of-a-c-for-loop-is-incorrect-under-certain-conditions/52634/4
> [Java] Fix loop statement indentation

- JavaScript/Indentation Rules.tmPreferences
- JavaScript/tests/syntax_test_js_indent_common.js
This commit restricts `bracketIndentNextLinePattern` to not match loops
if the loop condition expression spans multiple lines as it causes
breaks indentation of the following code block if the block's opening
brace directly follows the closing parenthesis on the same line.
The result was only the first line of the block being indented.
Fixes https://forum.sublimetext.com/t/the-indenting-of-a-c-for-loop-is-incorrect-under-certain-conditions/52634/4
> [JavaScript] Fix loop statement indentation

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_import_export.js
- JavaScript/tests/syntax_test_typescript.ts
Use `punctuation.section.mapping` and `punctuation.section.sequence` where appropriate, including:
- Array and object literals.
- Array and object destructuring.
- TypeScript tuple types.
> [JavaScript] Use mapping and collection bracket scopes

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
The color escapes do not technically work in all string contexts, but I think the false-positive percentage is probably low.
> [Bash] Color escapes in strings

- Ruby/Ruby.sublime-syntax
RBI files are used by Sorbet: https://sorbet.org/docs/rbi. They use the same exact syntax as Ruby.
The only concern I have is that if we apply Ruby syntax to RBI files, RBI files will be linted by plugins like https://github.com/SublimeLinter/SublimeLinter-rubocop, which isn't necessary IMO.
> [Ruby] Use Ruby syntax for RBI files

- PHP/PHP Source.sublime-syntax
- PHP/PHP.sublime-completions
- PHP/PHP.sublime-syntax
- PHP/Snippets/php (begin tag).sublime-snippet
- PHP/Snippets/php.sublime-snippet
Resolves https://github.com/sublimehq/sublime_text/issues/5256
The fix consists of two parts:
1. Extending the completion's selector by 
- punctuation.section.embedded.begin
2. Making sure to highlight incomplete <?php tags
punctuation.section.embedded.begin
Note: If this isn't acceptable we might want to scope incomplete
tags using a `meta` scope and add this to the selector (1.) as well.
We just need to ensure ST sees the correct scope while typing the
opening php tag in order to not add those methods to the list of
available completions.
> [PHP] Suppress method completions when typing php tags

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3243
Pop `allow-unpack-operators` off stack directly at the beginning of a line if it doesn't begin with optional whitespace followed by asterisk or hashtag.
This is to ensure to correctly match `def` statements whose pattern requires to be matched at bol.
The new pattern is appended to keep performance impact as low as possible. It is matched upon newlines only.
> [Python] Fix implicit tuples termination

- PHP/tests/syntax_test_php.php
- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_block.yaml
- YAML/tests/syntax_test_flow.yaml
I've been wanting to do this for a while, as `entity.name.tag` was really just a hack for a lack of an appropriate scope name when I made this syntax. Now that JSON, JavaScript and Python (and probably other syntaxes) successfully use `meta.mapping.key`, YAML should not be exempted.
---
*(via https://github.com/sublimehq/Packages/pull/2564#pullrequestreview-894390337)*
Without addressing https://github.com/sublimehq/sublime_text/issues/3590, the UX of default color schemes with regards to highlighting keys differently from values will be *worse* but in line with JSON and the other languages using `meta.mapping.key` as the primary differntiator between keys and values.
The only thing needed for Mariana is something like:
```json
{
"name": "Mapping Key Names",
"scope": "meta.mapping.key …
```
> [YAML] Replace entity.name.tag with meta.mapping.key

- HTML/HTML.sublime-syntax
- HTML/html_completions.py
Fixes #3248
This commit...
1. adds 'onfocusin' and 'onfocusout' to completions and syntax
2. creates a variable to store the pattern of all known event names
> [HTML] Add 'onfocusin' and 'onfocusout' event names

- Java/JavaDoc.sublime-syntax
- Java/tests/syntax_test_java.java
This PR clears `meta.tag`, ... scopes for leading `*` punctuation in html tags and attribute values of JavaDoc comments.
> [Java] Tweak JavaDoc punctuation in html tags

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
Fix #3253.
Annotations used `left-expression-end`, but a left-expression can contain a bracketed property access while an annotation cannot.
Also slightly improve scoping for annotations with tagged templates.
> [JavaScript] Decorators can't have bracketed accesses.

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3252
A simple approach to fix highlighting of constants in class declarations.
> [Python] Fix constants highlighting in class declaration parameters

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This commit scopes assignment operators after constants illegal.
> [Python] Scope assignments after constants illegal

- PHP/Embeddings/SQL (for PHP Interpolation).sublime-syntax
- PHP/Embeddings/SQL (for PHP).sublime-syntax
- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #572
see: https://forum.sublimetext.com/t/color-of-sql-query-change-when-add-quotes/63178/2
This commit adds support for highlighting sql queries in all parts of a chained string.
```
$sql = "SELECT " . $col . " FROM " . $table . " WHERE foo is " . $bar ;
```
_Note: This PR may cause some conflicts with #3046. Depending on which one is merged first, we might need to tweak the one or the other slighly afterwards._
> [PHP] Fix SQL query concatenation 

- YAML/YAML.sublime-syntax
This PR intents to improve YAML's inherit-ability by making all
contexts accessible for inheriting syntaxes. That's required for
instance to properly support interpolations by clearing string scope
only in strings.
A possible use case are interpolated HEREDOCs in PHP.
Note: It doesn't change behavior besides adding `meta.string.yaml`.
> [YAML] Convert anonymous to named contexts

- Go/Go.sublime-syntax
- Go/syntax_test_go.go
This adds line and export directive syntax patterns and generalises the `//go:name` pattern for use in other contexts such as linter directives. It also fixes `//go:name` matching to avoid matching invalid directive comments.
~~It's not completely clear to me how to express the expectation in the tests (and some current tests expectation are incorrect; `//go` and `//go:` are invalid directives — so I expect tests to fail), so please let me know what I should add.~~
These should be marked as valid directives:
```
//go:linkname
//go:cgo_import_dynamic
//lint:ignore U1000 This is here for user documentation.
//lint:ignore-file Autogenerated.
//line file.rl:3732:45
//line :3732:45:45
//line :3732 :45:45
/*line file.rl:3732:45*/
/*line :3732:45:45*/
/*line :3732 :45:45*/
//export myfunc …
```
> [Go] Fix compiler directive syntax patterns

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This commit is a follow up or fix for e103d07, which prevents class or
function definitions directly following a constant from being scoped
illegal.
> [Python] Fix class/def declarations after constants

- CSS/Default.sublime-keymap
- CSS/css_completions.py
This commit is the 3rd alternative for #2886 and #2912.
It uses the default `auto_complete_trailing_spaces` setting to decide
whether to add a space after colons or not when completing properties.
Default behavior (`auto_complete_trailing_spaces`: true):
font-fam|    =>   font-family: |;
Custom behavior (`auto_complete_trailing_spaces`: false):
font-fam|    =>   font-family:|;
Default bindings no longer add space when typing `:` (colon):
font-family|    =>   font-family:|;
inspired by: https://github.com/sublimehq/Packages/pull/2886#issuecomment-922543383
> [CSS] Add space after colon only via `auto_complete_trailing_spaces`

- JSON/JSON.sublime-syntax
- JSON/syntax_test_json.json
> [JSON] Rename mapping separator scopes

- Python/Default.sublime-keymap
Fixes #2888
This commit improves auto-pairing of quotation marks and brackets in `source.python` scope.
To avoid interference all core defaults are overridden before creating new bindings. This is needed to prevent auto-pairing after escapes such as ( `\|` -> `\(|` ).
Auto-pairing is enabled in front of common separators `,`, `:`, `;` to improve editing experience of mappings, sets and lists. It follows behavior of JSON.
Auto-pairing parens/brackets/braces now works within strings and directly in front of quotation marks.
Several other language specific tweaks ...
Note:
A general scheme to order context keys is applied.
1. settings
2. main language selector
3. selection state
4. patterns (preceding_text, following_text)
> [Python] Improve auto-pairing behavior

- JavaScript/Indentation Rules.tmPreferences
- JavaScript/tests/syntax_test_js_indent_common.js
Fixes #3276
The culprit was `indentSquareBrackets` which works different than
expected.
This commit replaces that setting by explicit increase/decrease indent
patterns, which even fixes some edge cases left by eaeb678 and 937b646.
> [JavaScript] Fix bracket indentation

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3283.
It was pushing the inner context with the `fail` rather than the outer context with the `branch_point`, so when it tried to `fail`, nothing happened (and it got stuck there for the rest of the file).
> [TypeScript] Fix bug in old-style type assertion parsing.

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3290
This PR provides a quick fix to avoid assignment operators after type annotations to be highlighted illegal, if the type annotation is finalized by `None` type, without implementing full fledged type hint support.
> [Python] Fix default value assignment after union type annotation

- PHP/PHP Source.sublime-syntax
- PHP/Symbol List.tmPreferences
- PHP/tests/syntax_test_php.php
This commit...
1. adds some contexts/patterns to scope enumerated constants
`entity.name.constant`.
`entity.name.constant` vs. `constant.other` may enable
"Goto Reference" at some point.
2. Adds `entity.name.constant` to symbol list and index.
> [PHP] Add enum constants to symbol list/index

- C#/C#.sublime-syntax
- C#/Symbol List - Constants.tmPreferences
- C#/tests/syntax_test_GeneralStructure.cs
This commit...
1. rescopes enumerated constants from `constant.other.enum` to
`entity.name.constant` as the latter one is what scope naming
guidelines suggest for constant definitions.
`entity.name.constant` vs. `constant.other` may enable
"Goto Reference" at some point.
2. Adds `entity.name.constant` to symbol list and index.
> [C#] Add enum constants to symbol list/index

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_enum.rs
This commit rescopes enumerated constants from `constant.other` to
`entity.name.constant` as the latter one is what scope naming
guidelines suggest for constant definitions.
`entity.name.constant` vs. `constant.other` may enable
"Goto Reference" at some point.
> [Rust] Add enum constants to symbol list/index

- ShellScript/Default.sublime-keymap
This PR...
1. restricts auto-pairing backticks.  
Only add if followed by "metachar" `(space, | & < > ; ...)` which are known to finish expressions.
2. adds a binding to move caret over closing backtick.
see: https://forum.sublimetext.com/t/st4-issues-i-found-but-have-no-time-to-write-proper-bug-reports-yet/59226
> [ShellScript] Improve Automatching backticks

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
This PR restricts arguments allowed for `exec` command in order to prevent a quoted command from being scoped as argument by accident.
A real-world example for the current syntax failing can be found at https://github.com/eclipse/lemminx/blob/acbc29b71260eddc40a201f4b17bc2ec396f14f9/mvnw#L306-L310
> [ShellScript] Fix quoted exec commands

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
- ShellScript/test/syntax_test_shell_unix_generic.sh
This PR ...
1. scopes both `[` and `[[` `support.function.test.begin`.
2. ensures to scobe both `]` and `]]` `support.function.test.end` even if they are located directly at the beginning of a line.
> [ShellScript] fix conditional expressions

- Erlang/Erlang.sublime-syntax
This PR renames syntax's `hidden_extensions` key to `hidden_file_extensions` as the latter one is the one which is found in documentation.
> [Erlang] Fix hidden file extensions key

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
This commit fixes enum r-values from being scoped `entity.name.constant`.
> [C/C++/Objc/ObjC++] Tweak enumeration constant assignments

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR fixes an issue with class declarations in anonymous class instantiation statements not receiving proper scopes if `class` keyword is preceeded by a block comment or attribute.
> [PHP] Fix anonymous class instantiations

- HTML/HTML (Plain).sublime-syntax
- HTML/syntax_test_html.html
Fixes #3305
This commit adds `meta.string.html` to CDATA content so it uses the same scopes as CDATA in XML.
> [HTML] Add meta.string to CDATA content

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3295
The original implementation of assignment expressions follows the
behavior of python 3.8, which raises syntax error on expressions like
{ a := 1, b := 2 }
Python 3.10 however accepts it and so Python.sublime-syntax needs to.
> [Python] Fix assignment expressions in sets

- JavaScript/tests/syntax_test_typescript.ts
- JavaScript/tests/syntax_test_typescript_not_tsx.ts
Since these tests use the old-style assertion syntax, which doesn't work in TSX, these tests are causing test failures in JS Custom, which runs the TSX syntax against `syntax_test_typescript.ts`, but not `syntax_test_typescript_not_tsx.ts`.
See also https://github.com/sublimehq/sublime_text/issues/3998.
> [TypeScript] Move some syntax tests to the non-TSX file.

- JavaScript/TSX.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
There were no tests for the `match: (?=<)` /  `pop: 3` rule. I *think* it was there for cases like `true ? (a) : <foo />`. I've added a test for that, and a new fix compatible with generic function types, and then a new fix for that fix.
> [TypeScript] Implement generic function types

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR adds a bailout to continued SQL strings to ensure to pop
the expression part off stack if an unmatched token is found.
Note: Adding `else-pop` to `nested-expressions` doesn't yet work.
Some refactorings are required before.
> [PHP] Fix SQL string termination

- Haskell/Haskell.sublime-syntax
- Haskell/tests/syntax_test_haskell.hs
Fixes https://github.com/sublimehq/Packages/issues/3227#issuecomment-1030044243
1. scopes an imported namespace's alias name `variable.namespace` as
it doesn't introduce/declare anything new but another name for the
imported module.
2. escapes from `import` context as early as possible by using more
strictly sub-contexts which enforce certain order of terms to reduce
risk of failing to highlight following expressions correctly.
> [Haskell] Fix qualified import alias scope name

- Haskell/Indexed Reference List.tmPreferences
- Haskell/Indexed Symbol List.tmPreferences
Fixes #3322
This PR...
1. adds `entity.name.constant` to indexed symbols which enables `Goto Definition` for constructors
2. adds `storage type` to indexed references to enable `Goto Reference` for data types.
> [Haskell] Enable indexing of constructors and types

- Haskell/Haskell.sublime-syntax
- Haskell/tests/syntax_test_haskell.hs
This commit...
1. fixes an edge case related to multiple l-values not terminating a
type expression as expected.
Improve "new statement begins" detection on the following line,
beginning with lower case identifiers.
2. fixes constructor definition being broken if followed by assignment
or function.
Pop `constructor-body` off stack, gracefully if the end of the whole
type expression is detected via `declaration-end`.
A type expression context is popped off stack if an unexpected
operator or the beginning of a new statement is detected via
`declaration-end` context.
> [Haskell] Fix data definition termination

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
Resolves #3211.
This PR adds basic highlighting for [EmmyLua](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations) and [LDoc](https://stevedonovan.github.io/ldoc/manual/doc.md.html) documentation comments. They are not really part of the Lua language, so I don't know whether it is desired to be added (having the open PR for JSDoc types in mind, which seems to be stuck for some reason), but I think it would be useful to provide a PR. Also there are at least three competing standards for the scope name of `@tag` tags already used in the default syntaxes...
It is kept pretty basic with only `@tags` being highlighted, with two exceptions for `@section` and `@param`.
Ideally this should be tested by a regular Lua user, @jingyuexing maybe do you want to try it out?
> [Lua] Add support for EmmyLua and LDoc doc comments

- Rails/Ruby (Rails).sublime-settings
Set the default file extension to "rb" for new "Ruby (Rails)" files.
See https://github.com/sublimehq/sublime_text/issues/5373 for details.
The idea comes from @Ultra-Instinct-05 and @jfcherng .
Thanks for any feedback.
> [Rails] Set default_extension in sublime-settings

- Python/Python.sublime-syntax
This commit moves some those items into hidden_file_extensions, which
are unlikely to be used as normal file extensions.
> [Python] Hide non-file extensions

- Groovy/Groovy.sublime-syntax
This commit moves some those items into hidden_file_extensions, which
are unlikely to be used as normal file extensions.
> [Groovy] Hide non-file extensions

- Makefile/Makefile.sublime-syntax
This commit moves some those items into hidden_file_extensions, which
are unlikely to be used as normal file extensions.
Note: Moves `*.mk` to the beginning so it is the default extension being used.
> [Makefile] Hide non-file extensions

- C#/C#.sublime-syntax
- C#/tests/syntax_test_GeneralStructure.cs
This commit applies scope names to exception related keywords, which
have been applied in most other recently updated syntaxes.
> [C#] Scope try/catch/finally keyword.control.exception

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#10.cs
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_C#9.cs
- C#/tests/syntax_test_GeneralStructure.cs
- C#/tests/syntax_test_HelloWorld.cs
- C#/tests/syntax_test_c#.cs
This PR suggests to rename scope of special declaration keywords from `storage.type` to  `keyword.declaration`.
_This change has been made to several syntaxes in the past. C# is one of the remaining syntaxes, which have not been updated._
Note: Maybe scopes of more keywords such as `var` or `dynamic` should be renamed as well.
> [C#] Rename declaration keywords scopes

- C#/C#.sublime-syntax
- C#/tests/syntax_test_Using.cs
This commit applies same scheme of scopes to all kinds of namespaces,
so `global` is the only `support.namespace` in all contexts.
see: https://github.com/sublimehq/Packages/issues/1842#issuecomment-1100697757
> [C#] Unify namespace scopes

- R/R.sublime-syntax
This commit moves some those items into hidden_file_extensions, which
are unlikely to be used as normal file extensions.
RProfile is prefixed with a dot so .Rprofile files are assigned
correctly.
Some more environment related files are added from:
https://support.rstudio.com/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf
> [R] Reorganize file extensions

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
Fixes #3327
This commit renames `punctuation.section.generic` to
`punctuation.definition.generic` to comply with scope naming guidelines.
> [Java] Fix generics punctuation scopes

- C#/C#.sublime-syntax
This commit fixes a scope name for generic punctuation.
All other patterns already use punctuation.definition.generic.
> [C#] Fix generic punctuation scopes

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
This commit scopes qualifiers `variable.namespace` in annotations.
That's the scope already used for all other qualifiers.
_C# and PHP also use the normal qualifier scopes in attributes/annotations._
> [Java] Rename annotation namespace scope

- C++/C++.sublime-syntax
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/syntax_test_objc++.mm
This commit renames `punctuation.section.generic` to
`punctuation.definition.generic` to comply with scope naming guidelines.
> [C-Family] Fix generics punctuation scopes

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit renames `keyword.operator.logic` to
`keyword.operator.logical` to comply with scope naming guidelines.
> [CSS] Fix logical operator scope

- Erlang/Erlang.sublime-syntax
- Erlang/syntax_test_erlang.erl
This commit removes `.percentage` sub scope as no other language uses this level of detail.
> [Erlang] Simplify comment punctuation scope

- CSS/CSS.sublime-syntax
- CSS/completions/properties.py
- CSS/syntax_test_css.css
This commit adds `revert` and `revert-layer` to the list of global
property values. ... those which are valid in every property.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/revert
> [CSS] Add global property names

- C#/C#.sublime-syntax
- C#/tests/syntax_test_GeneralStructure.cs
- C#/tests/syntax_test_HelloWorld.cs
This commit improves qualified and unqualified identifier scopes in
namespace declaration statements.
1. Qualified identifiers are scoped `meta.path`.
2. Path elements are scoped `variable.namespace`.
3. Only the last element is scoped `entity.name.namespace.
Goal is to have same scoping as in Erlang, Java, Perl, PHP, ...
Note:
The current implementation still relies on normal push/pop patterns,
which works only for single-line identifiers. If support for multi-line
identifiers is desired, some contexts from Java might be of interest.
> [C#] Improve namespace declaration

- JavaScript/tests/syntax_test_typescript.ts
The test was moves to the TSX test file in #3311 but accidentally re-added in #3312.
> [TypeScript] Remove non-TSX test (again)

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit...
1. adds global constants to counter property values
2. fixes multiple counter values in `counter-set` properties
3. reorganizes `counter()` function accordingly as `counter-identifier`
context is now used by this function only.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set
> [CSS] Fix counter properties

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
To reduce scope of #3354 this commit cherry picks font/font-family related changes only.
It enables separate and dedicated discussion / decision about removing the large lists of known props/vals.
> [CSS] Improve font/font-family accuracy

- Markdown/Symbol List - Hide.tmPreferences
This PR hides symbols defined in fenced-code blocks from `Goto Symbol` quick panel and avoids them being indexed.
Same applies to `<tag id="hide-symbol"`> html `id` values.
The goals are:
1. reduce noise in Goto Symbol
2. avoid code snippets from being indexed, which are used for documentation purpose only.
> [Markdown] Hide embedded syntax's symbols

- Markdown/Markdown.sublime-syntax
- Markdown/MultiMarkdown.sublime-syntax
This commit...
1. sets `version: 2` tag in both, Markdown and MultiMarkdown
2. tweaks required scope rules to fix backward incompatible changes
- tables: replace `meta_content_scope` by `meta_scope`
- fenced-code-blocks: add embedded syntaxes' main scopes to
`embed_scope`
- bold-italics: add `meta.italic` to some `set` statements
3. replaces `pop: true` by `pop: 1`
> [Markdown] Update to sublime-syntax version 2

- HTML/HTML (Plain).sublime-syntax
This commit introduces a dedicated `html` context, which can easily be
re-used by any inheriting syntax definition.
This may be required if an inheriting syntax wants to treat `main`
context special (e.g. by pre-pending shebang, frontmatter, ...) but
still needs easy access to plain `html` context with prototype from
inheriting syntax being applied to them.
Example:
```yml
scope: text.html.foo
contexts:
prototype:
- include: foo-embedded
main:
- match: ''
set: [html, shebang]
shebang:
...
foo-embedded:
...
```
Without this commit each inheriting syntax needs to copy content from
HTML (PLain).sublime-syntax's `main` context like so:
```yml
html:
- include: preprocessor
- include: doctype
- include: comment
- include: cdata
- include: tag
- include: entities
```
With this commmit, such copy …
> [HTML] Add dedicated html context

- CSS/CSS.sublime-syntax
- CSS/css_completions.py
- CSS/syntax_test_css.css
This commit ensures...
1. not to trigger property-name completions in front of property lists.
.selector|{}
2. to trigger property-value completions between colon and closing
braces.
.selector{font:|}
3. to prevent property-name completions in nested rule lists
@media display {
.selector | {}
}
inspired by: https://github.com/sublimehq/sublime_text/issues/5398
> [CSS] Fix property completion selectors

- CSS/CSS.sublime-syntax
This commit restores `common-operators` context as it is used by `Tailwind CSS` package.
https://github.com/SublimeText/TailwindCSS/blob/5d6b4297bb90b5d18903576814be660281b3fa75/Tailwind%20CSS.sublime-syntax#L41
> [CSS] Fix backward compatibility issue

- CSS/CSS.sublime-syntax
- CSS/Reference Index.tmPreferences
- CSS/Symbol List - Layers.tmPreferences
- CSS/syntax_test_css.css
Fixes #3363 
Fixes #3364 
This PR adds support for...
1. `@layer`
2. `selector()` function in `@support` rules
3. `supports()` and `layer()` functions in in `@import` rules.
see:
- https://developer.mozilla.org/en-US/docs/Web/CSS/@import
- https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
> [CSS] Add layer support and update @import

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3384.
Object literals are implemented to assume that an identifier is a regular key first. If it sees an open paren after the identifier, that means that it's a method and it should backtrack. However, in TypeScript, it might also be followed by type parameters. This PR makes it backtrack if it sees a less-than.
> [TypeScript] Support generic methods in object literals

- CSS/syntax_test_css.css
Commit 727a8a198d0d6970e468aee8639752dc0ceca52c changed boundaries of `meta.selector` and was merged before #3366 which contains detailed (but outdated) checks for that scope.
This commit fixes syntax tests to comply with new `meta.selector` boundaries.
> [CSS] Fix syntax tests

- HTML/html_completions.py
This commit...
1. prevents attribute-completions within attribute values
(aka. strings)
<div attrib="|">   <- don't suggest attribute names
2. prevents abbreviation expansion within tags
<div | >  <- don't expand `tag.attrib`
> [HTML] Prevent completions in inappropriate contexts

- Markdown/Markdown.sublime-syntax
This commit adds an alias context meant for use by external syntaxes, which want to embed Markdown.
The motivation is to avoid using `list-block-content` as it leaks too many implementation details.
_Note: This commit doesn't change behavior of Markdown syntax._
> [Markdown] Add public context for embedding by 3rd-party syntaxes

- C#/C#.sublime-syntax
nint and nuint are base types included in dotnet
[Documentation about this memory types](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/nint-nuint)
> [C#] Added memory-based types

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #3407 by adding back support for short arrow function return types.
> [PHP] Fix regression in PHP arrow function return type scoping

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Fixes #3390
This commit adds support for `value-list` in the first `mixin()` expression of a statement.
_Note: `mixin` in `value` context does so already._
> [D] Fix mixin() arguments lists

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
I'd like to propose a few small pull request to standardize / unify some scope names between syntaxes. They should have little or no impact for syntax highlighting, but make it is easier for color schemes to define simple rules if they want to target certain tokens in all languages.
---
This one proposes to adjust the scope for the [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) to `keyword.operator.null-coalescing`, which is already used in the PHP syntax. An alternative could be `keyword.operator.logical.null-coalescing`, since it is described as a special form of logical operator in the linked MDN docs, but I think the scope from the PHP syntax is better, because I would expect logical operators to …
> [JavaScript] Standardize scope name for null-coalescing operator

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#8.cs
- C#/tests/syntax_test_C#9.cs
* Standardize scope name for null coalescing operator as used in PHP syntax
* Use `keyword.operator.assignment.augmented` for augmented assignments, as already used in various other syntaxes
> [C#] Standardize some operator scope names

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Attempting to standardize the scope name for throwaway variables (usually underscore).
See also: https://github.com/SublimeText/ScopeNamingGuidelines/issues/5
I've chosen the scope name `variable.language.anonymous`, because this scope is already used in Erlang, Haskell, Matlab & Java.
This allows to highlight `_` differently from for example `self`.
> [Python] Standardize scope name for throwaway variables

- Go/Go.sublime-syntax
- Go/syntax_test_go.go
Align with the scope name from various other syntaxes.
> [Go] Standardize scope name for throwaway variables

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
Fixes #3369
Some enumeration constants have been detected as MACROS due to heuristics in `expressions`. This commit therefore restricts related contexts to match valid enumeration constants only.
_Note: enum constants between preprocessor directives like `#ifdef ... #endif` are still not highlighted as such, but fixing that is way too much for a quick hotfix. It would be addessed not before a rewrite._
> [C/C++] Exclude macros from enumeration constants

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Inspired by the syntaxes for e.g. Java and PHP.
**Before**:
**After**:
> [Python] Adjust scope for module name in qualified base class

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
An old oversight I keep forgetting to fix.
> [TypeScript] Allow number literals as object/interface type keys

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_shebang.js
- JavaScript/tests/syntax_test_shebang.ts
This commit adds `ts-node` and `ts-node-script` to `first_line_match`
and highlights it via shebang-body context.
References
`ts-node`: https://www.npmjs.com/package/ts-node#shebang
`ts-node-script`: https://deepkit.io/documentation/framework
> [TypeScript] Adjust shebang

- Git Formats/Git Config.sublime-syntax
- Git Formats/tests/syntax_test_git_config
This PR renames scope of `=` in git config files from `keyword.operator.assignment` to `punctuation.separator.key-value`
as those are scoped `meta.mapping` already.
> [Git Formats] Fix key-value punctuation in git config

- JavaScript/JSX.sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/Regular Expressions (JavaScript).sublime-syntax
- JavaScript/TSX.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
JavaScript uses sublime-syntax `version: 2` and makes use of `pop: 2` in 2 contexts. Thus it might be consistent to use explicit `pop: 1` instead of legacy `pop: true`.
This commit doesn't change behavior.
> [JavaScript] Replace pop: true by pop: 1

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit adds `list-setext-headings-or-paragraphs` contexts which are a modified copy of `setext-headings-or-paragraphs` to support setext headings within list items.
Note: It may also be useful if markdown is to be embedded into 3rd-party syntaxes (e.g.: Astro) with lazy indentation handling.
---
1. Heading
===
1. List Item
===
- nested list
with heading
---
and paragraph
> [Markdown] Add support for setext headings in list-blocks

- Git Formats/Git Commit.sublime-syntax
- Git Formats/tests/syntax_test_git_commit
Not sure whether it's worth being added but anyway, a PR is here.
---
It's used in [Gerrit Code Review](https://en.wikipedia.org/wiki/Gerrit_(software)).
For people who use Gerrit Code Review, their commit messages usually look like the following.
The `Change-Id` attribute is necessary for submitting a code review.
```
This is the commit subject.
Here are the commit details line 1.
Here are the commit details line 2.
......
Change-Id: I3b3613e336397febf02cd8e5c14c53d493343e93
Signed-off-by: Foo Bar <foo.bar@example.com>
```
> [Git Formats] Highlight "Change-Id:" in commit msg

- Java/Fold.tmPreferences
Despite syntax tests containing incomplete statements, which cause
syntax based folding to fail, the overall syntax carefully tracks
parentheses. So its safe to enable syntax based folding for groups.
Note:
Syntax based folding might fail in JSP syntax in situations of heavy
inline mixture between html and java code. That's the case for all
sorts of brackets however.
> [Java] Add support for syntax based folding of groups/parentheses

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
REM comments out only the content on the same line, except being directly followed by `^`. Only the following line is commented out then.
see: https://github.com/sublimehq/sublime_text/issues/5512
> [Batch File] Fix REM multi-line comment highlighting

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3441.
Currently, when `ts-type-expression-begin` sees an open paren, it tries to parse it as a parenthesized type, and then, if it sees `=>` after the close paren, it backtracks and tries to parse a function type instead. (This mirrors the behavior with expressions: `expression-begin` tries to parse an open paren as a parenthesized expression, then falls back to an arrow function if it sees the arrow. This makes sense because parenthesized expressions are more common, so this leads to less backtracking.)
This approach fails for arrow function return types. If an arrow function return type is a parenthesized type, then it will see the following arrow and assume that it's supposed to be a function type — but that arrow could be part of the arrow function itself, not the return type. …
> [TypeScript] Fix bug when arrow function return type is parenthesized

- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
This commit improves parsing performance by 75% mainly by simplifying lookaheads of rule vs. assignment expression detection.
That's mainly possible due to pushing into `expect-rule` context, which can't contain nested rules. So it's clear, after a rule name was consumed only variable assignments follow.
Benchmark:
```
syntax_test_makefile.mak
before: 8.2ms
after: 2.8ms
diff: -76%
linux-5.19 Makefile
before: 32.2ms
after: 7.3ms
diff: -77%
```
> [Makefile] Optimize performance

- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
The `main` context directly includes `variable-definitions` context. If `override` is consumed an anonymous context is set onto stack, overriding `main`. This context is popped at eol, causing a potential context-stack underflow. Presumably only ST's safety mechanisms prevent bad things from happening here.
As the pushed context also includes `variable-definitions` things start to become even more suspicious. Hence the whole construct is removed.
The only change needed to maintain behavior is to include `line-continuation` in main.
> [Makefile] Fix possible stack underflow

- Rails/HAML.sublime-syntax
- Rails/HTML (for HAML).sublime-syntax
- Rails/Markdown (for HAML).sublime-syntax
- Rails/tests/syntax_test_rails.haml
This PR adds support for markdown highlighting within HAML filters.
~~~haml
:markdown
```c
void foo() {}
```
- list #{@item}
<style  lang="#{@style_type}"> p { font-family: #{@font_name}; } </style>
~~~
> [Rails] Add HAML Markdown Filter highlighting

- Markdown/Markdown.sublime-syntax
That extension is used by [Ikiwiki](https://ikiwiki.info/) and [other applications](https://superuser.com/a/285878), and it's recognized by GitHub as Markdown.
> Add .mdwn as a markdown extension

- Erlang/Erlang.sublime-syntax
http://erlang.org moved to https://www.erlang.org
This commit doesn't change any functionality.
> [Erlang] Adjust syntax reference urls

- Matlab/Indentation Rules - Unindent.tmPreferences
- Matlab/Indentation Rules.tmPreferences
- Matlab/Matlab.sublime-syntax
- Matlab/syntax_test_matlab.matlab
Inspired by #3464.
There is still no test case for it in the `syntax_test_indentation.matlab` file, because the closing `end` keyword is expected to be unindented by two levels for the switch/case statement, and afaik this isn't possible to achieve with indentation rules.
> [Matlab] Improve indentation rules for switch/case statement

- HTML/html_completions.py
This commit prevents full tag snippets from applying within tags.
Before:
`<di|style></style>` expands to `<div>|</div>style></style>`
After:
`<di|style></style>` expands to `<div|style></style>`
Notes:
1) That's possible because `<>` is scoped `meta.tag.incomplete`.
2) The result might not be syntactical correct as well, but it doesn't
at leas cause a stray `>` to be added. In the example `style` could
easily be modified or wanted to be turned into an attribute.
> [HTML] Fix tag name completions

- Python/Dedentation Rules.tmPreferences
- Python/Indentation Rules - Case.tmPreferences
- Python/Indentation Rules.tmPreferences
- Python/Python.sublime-syntax
- Python/syntax_test_python.py
- Python/tests/syntax_test_indentation_case.py
Fixes #3456 
This PR...
1. adds an `expect-first-case-statement` context to scope first case
statement `meta.disable-dedentation.python`.
> **Note**
>  An extra pattern is added which doesn't `fail` any branches.
2. adds `Indentation Rules - Case.tmPreferences` to decrease
indentation level of all but the first case keywords.
> **Note**
>  As `case` can also be a variable, dedicated indentation rules
>  are used to avoid decreasing indentation level in normal
>  assignment expressions.
> **Note**
>  Indentation rules are not applied if a case pattern spans
>  multiple lines, because `case` is not scoped keyword before final
>  `:` is inserted. ST applies indentation rules per line only.
3. scopes whitespace after `:` `meta.statement.conditional.case` as it
is required for ST to reliably …
> [Python] Improve case statement indentation rules

- Markdown/MultiMarkdown.sublime-syntax
- Markdown/tests/syntax_test_multimarkdown.md
- Markdown/tests/syntax_test_multimarkdown_frontmatter.md
- Markdown/tests/syntax_test_multimarkdown_no_frontmatter.md
This PR:
1. adds support for YAML like frontmatter in MultiMarkdown
If a document starts with `---` MultiMarkdown 6 interprets it as
beginning of meta-data for compatibility with YAML frontmatter,
if not run in compatibility mode (-c flag).
It does not support YAML though! Content is limited to same simple
key-value pairs as in classical multimarkdown header format.
2. scopes all kinds of headers `meta.frontmatter.multimarkdown`
3. scopes key-value pairs `meta.mapping`
4. supports HTML in frontmatter values. Therefore `string` scope is
removed.
Implementation uses `embed` to ensure correct bailouts without too many context duplication.
inspired by: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/690
---
> [Markdown] Improve MultiMarkdown frontmatter

- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_block.yaml
This commit addresses #3395 by terminating explicit mapping keys by lines which
1. start with `:` or 
2. are indented less or equal to the opeing `?`
It doesn't introduce special handling of `!!set` values so far. Those are still scoped explicit key without value as it is what spec calls them, too.
_Note: Appends `-11` to contexts which have `-12` counter parts._
> [YAML] Fix bailout from explicit keys without value

- HTML/html_completions.py
Fixes #3490
This commit adds some new? <img> attributes from MDN.
see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-referrerpolicy
> [HTML] Add missing img attribute completions

- Markdown/Markdown.sublime-syntax
Fixes #3494
The hard-line-breaks context causes deadlock in setext-or-paragraph context maybe caused by in-accurate rewinding or back-and-forth of branches while typing.
Same issue was found while working on Markdonw's MathML support.
This commit implements the same workaround by just consuming some tokens in 2nd and 3rd branch to avoid ST from trying the 1st one again.
> [Markdown] Fix deadlock with SETEXT headings

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR mainly optimizes parsing performance of type hints and makes them somewhat more robust with regards to incomplete expressions.
10k lines of:
```php
<?
function unionTypeFunction(int | string $param0, Foo | \Foo\Bar | ?int $param1, Foo|\Foo\Bar|?int $param2, (?A|B)&(C|?D)&?E $param2, string $param3, $param4): Foo|\Foo\Bar|?int|static {}
```
| ST4137 | this PR | delta
|--------|---------|--------
| 207ms  | 178ms   | -14%
10k lines of:
```php
<?
class Foo {
public $var = 0; public int | string $param0; public Foo | \Foo\Bar | ?int $param1; public Foo|\Foo\Bar|?int $param2; public (?A|B)&(C|?D)&?E $param2; public string $param3; public $param4;
}
```
| ST4137 | this PR | delta
|--------|---------|--------
| 304ms  | 277ms   | -9%
> [PHP] Improve type hints

- Git Formats/Git Rebase.sublime-syntax
- Git Formats/tests/syntax_test_git_rebase
git v2.38.0 adds the new branch command "update-ref". The format is
```
update-ref refs/heads/feature-branch
```
> [Git Formats] Add update-ref command to interactive rebase

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#10.cs
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_C#9.cs
- C#/tests/syntax_test_HelloWorld.cs
Fixes https://github.com/sublimehq/Packages/issues/3489
1. fixes `data_type_body` (now `data_type_expect_block`) to be popped off stack too early.
2. fixes meta scopes of record parameter lists, which used to be `meta.method.parameters`. Now using `meta.class.record.parameters`.
3. improves overall meta scope boundaries for record definitions.
> [C#] Fix nested record definitions

- Go/Fold.tmPreferences
- Go/Go.sublime-completions
- Go/Go.sublime-syntax
- Go/syntax_test_go.go
Features:
* Support for `~`.
* Support for `any` and `comparable`.
* Support for type unions.
* Support for general interfaces (with type unions).
* Support for type parameters in generic functions.
* Support for type parameters in method receivers of generic types.
* Support for type arguments following type names.
* Support for type parameters in type declarations.
* Support for embedded parametrized types in struct definitions.
* Support for type arguments between function name and function arguments.
* Support for `invalid.illegal` for dangling `)]}`.
* Slightly better meta scopes in type definitions.
Known regressions:
* Embedded interfaces are no longer scoped as "inherited class", due to ambiguities.
* "Namespace" idents such as `ident.` no longer support a comment between …
> [Go] preliminary support for Go 1.18

- LaTeX/LaTeX.sublime-syntax
- LaTeX/syntax_test_latex.tex
In addition to `\newcommand` and `\renewcommand`, LaTeX offers also a `\providecommand` primitive that allows to define new commands. Its syntax is the same as the other two, it only differs in how it handles the case if the same command already exists.
https://latexref.xyz/_005cprovidecommand.html
> [LaTeX] extend syntax to recognize \providecommand as a variant of \newcommand

- Rails/Ruby (Rails).sublime-syntax
Add the `validates_with` pre-defined validation helper to `support.function.activerecord.rails` scope.
> [Rails] Add `validates_with` pre-defined helper

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_macros.rs
`tokio::join!()` wasn't highlighted before.
> [Rust] Highlight macro usage in paths

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Use ~`meta.variable.parameters.annotation.python`~ `meta.variable.annotation.python` to mark annotation blocks when assigning.
This closely follows the `meta.function.parameters.annotation.python` we have in the function signatures.
> [Python] Mark variable annotation with a `meta.` block

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3486
This commit copies some lines from function parameter lists' contexts to fix the PEP 604 highlighting issues.
> [Python] Fix PEP-604 union type hints

- LaTeX/LaTeX.sublime-syntax
- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_latex.tex
This adds a large number of symbols to be recognized in TeX's math mode, in addition to the greek letters.
I've based the list of added matchings on https://www.math.brown.edu/johsilve/ReferenceCards/TeXRefCard.v1.5.pdf,
it may not be exhaustive.
I've also changed the `keyword.other.greek.math.tex` to `keyword.other.math.greek.tex`, so that we can have proper scoping with other math-type keywords. For now, I've left the old scope there additionally, if you think this is fine to remove I'd agree with that, though.
> [LaTeX] add TeX math symbols to be recognized by TeX and LaTeX syntax

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Fixes #3513
This commit uses branching to render inline code spans only if they are properly closed.
> [Markdown] Fix inline raw code spans

- LaTeX/LaTeX.sublime-syntax
- LaTeX/TeX.sublime-syntax
Following the discussion in #3508, this is a small PR that removes quotation marks around match patterns in (La)TeX's syntax definition.
> [LaTeX] removed superfluous quotation marks in syntax definition

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
Improvements:
* Added better scoping for argument specifications of `\def`
* Allowed `\def` also for backslash+nonletter type commands
* Accept `\def`, `\edef`, `\gdef`, and `\xdef`
* Started a `syntax-test-tex.tex` file
I've tried to implement this like the LaTeX `\newcommand` #3508, i.e. with multiple pushes, but could not get the scopes to work, so right now this is a chain of `set`s.
The `\edef` and `\xdef` variations are slightly different in terms of TeX, as they do not accept arguments, but based on the not-a-linter argument I've decided to go with the simpler implementation that treats all these as the same. For correct code, this does not make a difference.
> [TeX] improved support for \def and friends

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
As requested by @michaelblyons , some more fine-grained scoping for control structures in TeX.
Q: How important is it that these scopes are balanced? In the examples in the test, 
the `keyword.control.conditional.if.tex` never has any corresponding `end` scope, because the loop-ending `repeat` closes both the `loop`, and the `if` as part of the loop condition.
And the conditions `\if@director` would be using a custom-defined if condition. So we have `else` and `fi` without a corresponding start of that scope. I'm not sure if this can be fixed. Maybe we can assume that all commands that start with the sequence `\if` and are not followed by brace-enclosed arguments probably constitute the beginning of an `if`, but I'm not sure how many false positives (or false negatives) this would bring.
> [TeX] extended control flow matches and scopes

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #3539
The token `%'.u` is a valid format-string placeholder according to https://www.php.net/manual/en/function.printf.php
The `'` needs to be escaped in single quoted strings to avoid it being parsed as end of string.
Example: `"%'.u"` vs. `'%\'.u'`
> [PHP] Fix placeholders in single quoted strings

- LaTeX/Symbol List - Commands.tmPreferences
- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
This PR adds highlighting for registers, as well as for register allocation functions. Registers created with `\new...` functions will be visible in the symbol list.
> [TeX] Initial support for registers

- Diff/diff.py
The `codecs` module is is removed as it is not used.
The `os.path` import is replaced by `os` to fix linter issues caused by calling `os.stat()` in `DiffFilesCommand.run()`.
> [Diff] Cleanup imports of diff module

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #3549
This commit re-categorizes `yield` from control flow statement to ordinary expression keyword to enable its usage within groups/brackets.
That's required as PHP supports bi-directional communication between generators and their controllers.
see: https://sof3.github.io/await-generator/master/generators.html#sending-data-intoout-of-the-generator
> [PHP] Fix yield keyword category

- JavaScript/Completion Rules.tmPreferences
Fixes #1480
This commit removes function definitions from the pattern of canceled completions. Other syntaxes such as Python or Java don't restrict it this way, too.
> [JavaScript] Allow completions in function definitions

- C#/Build.sublime-syntax
Fixes #1862
This commit unassignes `build` file extension from NAnt Build File syntax as it is a too generic extension used by many syntaxes.
With this change `*.build` files need to be assigned to NAnt Build File manually if desired.
> [C#] Drop "build" file extension assignment

- Diff/Diff.sublime-settings
This commit converts the boolean value to its string counter-part, which is used by recent ST builds.
> [Diff] Fix trim trailing whitespace value

- LaTeX/LaTeX.sublime-syntax
- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_latex.tex
- LaTeX/syntax_test_tex.tex
This PR performs a slight reorganization of the macro-braces context, and increases the amount of constructs that are highlighted within. This also unifies (to the extend possible) the handling of "function bodies" in TeX and LaTeX.
Most importantly, now we have highlighting for the replacement-placeholders.
> [TeX] Improved highlighting in macro definition bodies

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Fixes #3564
This commit adds some undocumented punctuation to the set of terminating autolink characters.
> [Markdown] Fix GFM auto-link termination

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
extends the range of commands that will be highlighted to also include math, delimiter, and upper/lower case codes, allows for more forms of specifying the target character and the assigned number.
> [TeX] improved handling of (cat)code family of commands

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
This adds scoping/highlighting for the built-in constant-like objects in TeX.
The decision which control sequences to include here is based more on expected usage, than on how this is defined in the underlying language. I think for a macro-processing system like TeX, this is probably the best approach. 
Thus I've considered as constants in this sense:
* The underlying parameters of the TeX typesetting algorithm. 
* Registers with pre-defined meaning
* simple macros (i.e. without parameters) that insert a fixed element into the typesetting
In particular, a parameterless macro that a) assigns to some internal value, or b) changes how subsequent input tokens will be interpreted are not considered constants here.
The typesetting parameters and registers can be assigned-to, though for most of …
> [TeX] added scoping of "constants"

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
Added the \relax command to control sequence. As its usage is similar to python's `pass`, if used the same scoping, i.e. as a special  `keyword.control.flow`
> [TeX] added \relax command

- LaTeX/LaTeX Log.sublime-syntax
This commit adds named contexts and a missing EOL pop for strings.
> [TeX] refactor LaTeX Log syntax

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
This commit...
1. converts anonymous to named context for inline for statement body
2. renames `target-list` to `target-lists` to express non-popping behavior
3. removes some duplicate patterns for comma and name within target-list tuples
4. rename `target-list` scope to `tuple` and add corresponding `meta.sequence.tuple`
> [Python] Refactor inline for statements

- HTML/html_completions.py
This commit modifies completion for <style> tags to make in behave like <script> tag completions.
This way hitting tab key twice enables a user to completely remove the type attribute.
inspired by https://forum.sublimetext.com/t/how-to-customize-auto-complete-for-html-tags/66116
> [HTML] optional style tag attribute completions

- C#/C#.sublime-syntax
- C#/Fold.tmPreferences
- C#/tests/syntax_test_PreprocessorDirectives.cs
This adds the ability to fold `#region` preprocessor directives in C\#.
I've noticed one small occasion where it doesn't work correctly:
If there are nested regions with the same (meta-)scope, and the inner region is folded, then the folding range of the outer region erroneously stops at the end of the folded inner region too. However, if the inner region is not folded and you only fold the outer region, then everything works as expected.
For example, this works fine for any folding order (the inner regions are inside the meta-scope from the class):
```cs
#region Outer
public class MyClass {
#region Inner 1
// Hello
#endregion
#region Inner 2
// World
#endregion
}
#endregion
```
But the following example doesn't work correctly for the outer region if one of the inner regions was folded …
> [C#] Add folding rule for #region directive

- LaTeX/LaTeX.sublime-syntax
- LaTeX/syntax_test_latex.tex
Thanks @deathaxe for cleaning up the newcommand contexts.
Here are some small adjustments, using the {{cmdname}} variable to cover both commands based on a sequence of letters, and commands of a single non-letter.
> [LaTeX] Fixups for command names

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
This adds scoping for the `outer`, `global`, and `long` modifiers available to alter the behaviour of TeXs `\def` command.
> [TeX] Modifiers for \def's

- LaTeX/TeX.sublime-syntax
- LaTeX/syntax_test_tex.tex
Now that we have scopes for numbers and dimensions, we can also easily add scoping for assignment to registers.
I've re-ordered the TeX scopes a bit here, to improve the grouping.
> [TeX] register assignment

- Haskell/Embeddings/HTML (for HSX).sublime-syntax
- Haskell/Haskell.sublime-syntax
- Haskell/tests/syntax_test_haskell.hs
This PR proposes to add support for `[hsx|...|]` quasi-quotes in Haskell.
HSX supports XML content, but this commit embedds HTML instead as it is
what other editors seem to use. It's probably the most common use case
for Haskell Web Devs.
see: https://hackage.haskell.org/package/hsx
> [Haskell] Add HSX support

- JSON/JSON.sublime-syntax
This commit binds jsonc file extension to JSON.sublime-syntax.
see: https://github.com/SublimeText/AFileIcon/issues/63
> [JSON] Bind jsonc extension by default

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fixes #3598
This commit refactors anonymous type functions to...
1. ensure one of type-function or type-group to be applied. Old implementation may have caused both branches to fail, which can cause an infinite loop.
2. ensures not to invoke `fail` command in generic type functions, which are not part of a branch point.
3. add named contexts to differentiate generic from normal type functions and all their different parts.
_Note: The syntax needs to be applied to Sublime Merge in order to use it for review. Otherwise it will end up in the endless loop, caused by the test case which verifies the bug is fixed._
> [TypeScript] Fix deadlock caused by type expressions

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_types.rs
- Fixes highlighting of unknown generic types
- Adds stacking of `storage.type` under `support.type`
> [Rust] More small tweaks to type matching

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_attributes.rs
This form is used by the `thiserror` package.
Also name a few anonymous contexts and add an `s` to the `attribute` context name.
> [Rust] Match attributes in struct tuple constructors

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_closures.rs
The `symbols` context used to swallow the comma that we need to match for this.
> [Rust] Detect closures when they are used as the second argument

- ShellScript/Bash.sublime-syntax
All zsh completions found in /usr/share/zsh/ start with a magic word `#compdef` or `#autoload`, the exact format of which is documented in ZSHCOMPSYS(1) man page:
> The # is part of the tag name and no white space is allowed after it.
> The #compdef tags use the compdef function described below; the main
> difference is that the name of the function is supplied implicitly.
> Add support for zsh completions

- LaTeX/TeX.sublime-syntax
- LaTeX/tests/syntax_test_tex.tex
This PR does a first step at generalizing and unifying the handling of integers. 
It provides a general context that matches decimal, octal, hexadecimal, and "based on character" integers. I've not yet used this for the definition of dimensions, because here we currently enter different scopes based on whether we've matched an integer or a float.
The syntax specified here assumes that everything will be written on one line. It also does not handle the case of multiple leading signs.
> [TeX] Improved integer handling

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit adds support for pandoc style inline attributes in reference definition blocks.
This kind of attributes is already supported by inline links and images.
See: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/712
> [Markdown] Fix inline reference definition attributes

- Python/Python.sublime-syntax
Lookahead patterns don't consume anything and thus assigning scopes is nonsense.
> [Python] Remove unapplied scope from lookahead pattern

- Git Formats/Git Attributes.sublime-syntax
- Git Formats/Git Code Owners.sublime-syntax
- Git Formats/Git Commit.sublime-syntax
- Git Formats/Git Config.sublime-syntax
- Git Formats/Git Ignore.sublime-syntax
- Git Formats/Git Mailmap.sublime-syntax
- Git Formats/Git Rebase.sublime-syntax
This commit moves all full file names to `hidden_file_extensions` in order to not suggest them as possible extension in _Save as..._ dialog.
> [Git Formats] Adjust file extensions and hidden file extensions

- ASP/HTML (ASP).sublime-syntax
- ASP/syntax_test_asp.asp
- HTML/HTML (Plain).sublime-syntax
- Haskell/Embeddings/HTML (for HSX).sublime-syntax
- Java/HTML (JSP).sublime-syntax
- Java/tests/syntax_test_jsp.jsp
- PHP/PHP.sublime-syntax
- PHP/tests/syntax_test_php.php
- Rails/HTML (Rails).sublime-syntax
- Rails/HTML (for HAML).sublime-syntax
- Rails/tests/syntax_test_rails.haml
- Rails/tests/syntax_test_rails.html.erb
This commit clears `string` scope from embedded/interpolated code within <![CDATA[...]]> tags to bring scoping/highlighting inline with tag attribute values and other kinds of quoted or unquoted strings in HTML like syntaxes.
1. HTML (Plain) is modified to enforce inheriting syntaxes to treat CDATA as string by adding `meta_include_prototype: false` to `cdata-content`.
2. HSX, JSP, PHP already implement CDATA string interpolation. So obsolete `meta_include_prototype: false` is removed, only.
3. ASP and Rails are adjusted to follow the others.
4. some contexts are re-ordered to be inline across syntaxes.
5. Scope names keep unchanged.
6. Tests are added to verify correct scoping.
> [HTML] Treat CDATA as string with regards to interpolation

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3619
This commit uses branching to distinguish parenthesized and plain with argument lists.
If a parenthesized expression directly following a `with` keyword is not followed by colon it is scoped as part of a plain arguments list.
_Note: All that effort just to satisfy all the pseudo-linting like illegal highlighting._
> [Python] Fix with statements

- PHP/PHP.sublime-syntax
This PR...
1. excludes `prototype` from event/style attribute values as PHP is already handled by included js/css syntax.
2. splits value contexts into `-body` and `-content` so inheriting syntax can replace included js/css without touching low-level string patterns.  
_An alternative would be: https://github.com/sublimehq/sublime_text/issues/3787._
> [PHP] Improve event/style attribute value contexts

- Rust/Fold.tmPreferences
You can continue multi-line strings by ending a line within the string with a single backslash.
> [Rust] Add string punctuation scope fold rules

- Makefile/Makefile Shell.sublime-syntax
- Makefile/syntax_test_makefile.mak
- ShellScript/Bash.sublime-syntax
This PR excludes `prototype` context from quoted strings by default in order to enforce extra treatment by inheriting syntaxes.
It is to make sure string scope is cleared by interpolations.
A `string-prototype` context is introduced as common entry point for inheriting syntaxes to inject interpolation.
Possible use cases:
1. String interpolations in Makefile syntax
2. https://github.com/nk9/just_sublime/pull/2
Note: Makefile makes use of new `string-prototype` context, but seriously implementing string interpolation seems to be a more sophisticated task especially as some scope naming changes with regards to punctuation might be needed. Hence that's probably better handled in a separate PR.
> [ShellScript] Enforce string interpolation

- .github/workflows/ci.yml
This commit...
1. avoids moving files around by checking out syntax repository into a directory the test runner is directly extracted to afterwards.
2. uses new "latest" url to reduce maintenance effort after each dev build being released.
> [meta] Refactor syntax test CI workflows

- Python/Python.sublime-syntax
Fixes #3462
This PR contains structural changes to enable 3rd-party syntaxes to support more syntaxes within strings.
_Note: Python is still sublime-syntax V1, which may change in a future commit and will therefore require adjustments in each 3rd-party syntax which is going to extend it._
> [Python] Refactor string contexts to support inheritance

- HTML/HTML (Plain).sublime-syntax
- HTML/HTML.sublime-syntax
- PHP/tests/syntax_test_php.php
This PR excludes `prototype` from all tag related contexts, which
are not intended to be extended in a generic manner.
If an inheriting syntax wants to add more attribute types, it should do
so by explicitly extending `tag-attributes` context.
Rational
--------
An inheriting syntax is expected to use `prototype` context to inject
patterns which customize scoping of tag attribute names and values.
Therefore `generic-attribute-name` is designed to push a separate
context on stack, which can include patterns from `prototype`.
Same is true for most attribute values, except those which embed an
external syntax.
This expectation however has not been met until this commit, because
`prototype` context was directly prepended to each tag content context.
Hence those never matched within attribute …
> [HTML] Exclude prototype from tag content

- Lisp/Lisp.sublime-syntax
The Scheme r7rs community has adopted `.sld` as an extension for libraries (in part to distinguish them from r6rs libraries). 
Supporting references:
- Guile 3.0.1 added support: https://lists.gnu.org/archive/html/guile-devel/2020-03/msg00012.html
- Chibi Module system naming: https://synthcode.com/scheme/chibi/#h3_ModuleSystem
- various r7rs-supporting SRFI, e.g. SRFI 133 https://github.com/scheme-requests-for-implementation/srfi-133
- widely used Scheme tools, e.g. https://github.com/drewc/drewc-r7rs-swank
> [Lisp] Add sld file extension for rsr7 libraries

- PHP/Snippets/php (begin tag).sublime-snippet
- PHP/Snippets/php-$this.sublime-snippet
- PHP/Snippets/php-echo-$this.sublime-snippet
- PHP/Snippets/php-echo-___.sublime-snippet
- PHP/Snippets/php-echo-htmlentities(___).sublime-snippet
- PHP/Snippets/php-else.sublime-snippet
- PHP/Snippets/php-foreach-(___)-___-php-endforeach.sublime-snippet
- PHP/Snippets/php-if-(___)-___-php-else-___-php-endif.sublime-snippet
- PHP/Snippets/php-if-(___)-___-php-endif.sublime-snippet
- PHP/Snippets/php.sublime-snippet
This commit adds `text.html.php` to those snippets which are currently triggered by `embedding.php - source.php` only.
The goal is to enable those snippets in inherit syntax such as Laravel Blade, which don't use `embedding.php` but will probably be scoped `text.html.php.blade`.
> **Note**
> 
> Basically `embedding.php` is maintained only in order to enable those snippets in an empty document, as `text.html.php` is added to stack not before the first character is typed.
> [PHP] Adjust snippet selectors

- Graphviz/DOT.sublime-syntax
- Graphviz/syntax_test_dot.dot
Fixes #3627
1. includes HTML source into Graphviz to be able to correctly terminate it if an otherwise stray `>` is matched.
2. fixes embedded scope to `meta.embedded.dot text.html.embedded.dot`
> [Graphviz] Fix embedded html termination

- ShellScript/Bash.sublime-syntax
Much like `PKGBUILD`s, `APKBUILD`s are essentially shell scripts.
> [ShellScript] Add APKBUILD to list of filenames

- LaTeX/LaTeX.sublime-syntax
- LaTeX/tests/syntax_test_latex.tex
The PR reworks the handling of text formatting commands in LaTeX. In particular, in cases where there are commands within formatted text, e.g. `\textbf{\TeX in bold}`, we no longer format the command names. 
One challenge is that there are several font properties that can be changed independently: Font family (roman, sans serif, typewriter), font weight (bold, medium, (possibly) light), and font shape (upright, italic, slanted, small-caps). Most of these do not have any corresponding `markup` scopes and highlighting rules (at least with default color schemes). At this point, only a subset of nesting of these properties is actually handled: Bold/italic combination, and nested \emph emphasize, as well as ensuring that all the commands that do not change one of these properties still typeset …
> [LaTeX] Text formatting

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
This makes it much easier to visualize e.g. setting the `PATH` env var in scripts because the `:` can be highlighted as a separate color to the rest of the string.
> [ShellScript] scope colon as a path separator inside quoted strings

- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
This commit adds `text/babel` to the list of supported MIME types to enable JavaScript highlighting within <script type="text/babel"> tags.
see: https://github.com/vuejs/vue-syntax-highlight/issues/218
Other templating syntaxes may be effected as well, so fixing it in default HTML might help all of them.
> [HTML] Add support for `text/babel` MIME-type

- C#/Indentation Rules.tmPreferences
- C#/tests/syntax_test_indentation.cs
[C#] add indentation tests, always unindent if closing brace is the first non-whitespace character on the line, regardless of what follows it
Fixes #3653
> [C#] add indentation tests, always unindent if closing brace begins line

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
Works around: https://github.com/sublimehq/sublime_text/issues/5813 and https://github.com/sublimehq/sublime_text/issues/5853
ST locks up on certain text manipulation operations, which seem to cause syntax engine to bring into an invalid state causing a deadlock or infinite loop.
The two related branch points are used to peak into the next line to decide whether the current context's expression continues. If not the current context is to be popped off stack (immediately).
"Immediately" is what causes ST to lock up, on certain text manipulations if the context/branch is nested in another branch.
This PR works around this bug by popping the fallback branch at the same text point as the main branch failed at, using the same pattern to pop. As a result tokens which are matched by …
> [JavaScript] Fix syntax engine deadlock

- Matlab/Matlab.sublime-syntax
- Matlab/syntax_test_matlab.matlab
This PR proposes to add a heuristic to pop the `meta.function` scope when another `function` keyword appears at the start of a line, which unlikely indicates a nested function.
When I rewrote the Matlab syntax (#2650), I added the `meta.function` scope to a function body, beginning with the `function` keyword to the corresponding `end` keyword (inclusive). Similar to e.g. Python, Matlab supports [nested functions](https://www.mathworks.com/help/matlab/matlab_prog/nested-functions.html), and as you would expect, the `meta.function` scope gets stacked in that case.
But unlike Python, Matlab is not sensitive to whitespace/indentation, and especially it is also relatively common to *not* indent the function body (with nested function being an exception, but afaik it's not required to indent …
> [Matlab] Add heuristic to pop function context for not-nested functions without end keyword

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #3553
If pattern matching or regexp substitution is performed within parameter expansions (e.g.: `${^pattern}`) braces must be escaped in order to not terminate the variable expansion.
Braces don't need to be escaped if pattern matching is not part of a parameter expansions.
This commit therefore introduces `expansions-parameter-pattern` context to ensure any unescaped `}` pops a context so parameter expansions are properly terminated.
> [ShellScript] Fix pattern termination in parameter expansions

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Implement the `satisfies` operator from TypeScript 4.9.
This implementation does allow `x satisfies const`. I don't think that's valid, but there's no spec, so who's to say? (My usual answer is “AST Explorer”, but it doesn't seem to have updated to 4.9 yet.) Either way, it shouldn't do any harm.
> [TypeScript] Implement satisfies operator

- .github/workflows/ci.yml
- Go/Go.sublime-syntax
- Go/syntax_test_go.go
Scope Golang's [struct tags](https://pkg.go.dev/reflect#StructTag) as annotations.
Further reading:
- https://www.digitalocean.com/community/tutorials/how-to-use-struct-tags-in-go
- https://stackoverflow.com/a/30889373/4473405
~~I have kept the original `string.quoted.backtick` scoping as well for backwards compatibility with users whom might prefer these to stay highlighted as before.~~
> [Go] Scope struct tags as annotations

- ASP/Embeddings/CSS (for ASP).sublime-syntax
- ASP/Embeddings/JavaScript (for ASP).sublime-syntax
- ASP/HTML (ASP).sublime-syntax
- ASP/syntax_test_asp.asp
Fixes https://forum.sublimetext.com/t/syntax-highlighting-in-classic-asp-doesnt-work-at-all/67203/3
This commit applies common strategy of supporting template tags in embedded CSS/JS to HTML (ASP).
> [ASP] Fix ASP tag highlighting in CSS/JS

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_class.js
- JavaScript/tests/syntax_test_typescript.ts
It's another TypeScript 4.9 feature, but apparently it's actually buried in the TC39 decorator spec, which is at Stage 3.
> [JavaScript] Implement accessor modifier

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
- Python/syntax_test_python_strings.py
Fixes #2763
Fixes #2796
This PR...
1. mostely reorganizes/reorders existing syntaxes to apply a common top-down scheme of grouped contexts, which has proven to help improving maintainability of syntaxes
2. applies a common naming scheme to all contexts (several PRs have caused a mix of different schemes)
3. updates the syntax to sublime-syntax version 2
4. fixes various overlapping or missing meta scopes
5. ensures to apply ligatures correctly to all kinds of operators by re-ordering related patterns
6. fixes some edge cases with regards to expression assignment operators
> [Python] Refactor syntax and update to version 2

- JavaScript/JavaScript.sublime-syntax
.cjs files are CommonJS files and should be syntax highlighted as Javascript. The .cjs extension is being used to discern between .mjs (ES6 modules) and .cjs (commonJS) files. The traditional .js doesn't give this information.
> Syntax higlight for .CJS files as JAVASCRIPT

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
New feature in [TypeScript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#const-type-parameters), which is at the release candidate stage.
> [TypeScript] Implement const type parameters

- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
- Makefile variable substitutions were all `variable.parameter` - i.e. the punctuation and substitution, not just the variable name, which made everything one color
- text inside an escaped $ followed by an open paren was also treated as `variable.parameter` instead of correctly being highlighted as Shell script
> [Makefile] fix scoping of shell interpolation

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3682
1. fixes an issue with raw docstrings using the same context as normal docstrings.
2. adjusts context architecture of single quoted docstrings to the one of double quoted ones, to start summary line scope at the first non- whitespace character.
> [Python] Fix raw docstring highlighting

- Rails/Ruby (Rails).sublime-syntax
Adds `redirect_back_or_to` method to the syntax.
https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_back_or_to
> [Rails] Add `redirect_back_or_to` to syntax

- JSON/JSON.sublime-syntax
Apache Avro is written in a subset of JSON, and the existing JSON sublime-syntax works well for this. It would be nice to have this default to JSON syntax.
https://avro.apache.org/docs/1.11.1/specification/#schema-declaration
> [JSON] Add Apache Avro files to JSON extensions

- CSS/Fold.tmPreferences
This commit re-enables indentation based folding in CSS to fix an issue which causes `<style>` tags not being foldable in HTML syntax anymore.
As `source.css` begins immediately after the style tag, CSS's folding settings start ot apply directly after a style tag. ST therefore disables indentation based folding of `<style>` tags.
reported at:
- https://forum.sublimetext.com/t/can-no-longer-fold-html-style-tags/66219
- https://forum.sublimetext.com/t/code-folding-doesnt-work-js-go-html-maybe-more/66250/7
- https://forum.sublimetext.com/t/css-code-folding/66404
Other users reported folding issues in scenarious they use indentation to organize complex CSS sources. Hence it's probably a bad idea in general to disable indentation based folding.
> [CSS] Fix html style tag folding not working

- CSS/Fold.tmPreferences
This commit makes closing brackets to directly follow a folded region instead of keeping them at the beginning of the next line.
The explicit rule is required as default behavior of ST has recently changed.
see also: #3686
> [CSS] Exclude trailing newline from folding regions

- CSS/CSS.sublime-syntax
The `url-content` context already includes `string-content`.
This commit does not have any effect on how CSS is highlighted.
> [CSS] Fix duplicated string-content

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit introduces a tiny optimization to avoid duplicate `meta.selector` scope in pseudo classes such as `:not( ... )`.
> [CSS] Fix duplicate meta.selector scope in pseudo classes

- JSON/Fold.tmPreferences
This commit makes closing brackets to directly follow a folded region instead of keeping them at the beginning of the next line.
The explicit rule is required as default behavior of ST has recently changed.
> [JSON] Tweak folding rules

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
Closes #3483
This PR adds support for
1. JEP 394: Pattern Matching for instanceof
2. JEP 405: Record Patterns (Preview)
3. JEP 427: Pattern Matching for switch (preview 3)
JEP 394 has already been added in Java 16, but highlighting hasn't failed badly, so has not been handled in this syntax definition.
With support for JEP 405 type patterns however need a special treatment to correctly handle nested record structure patterns.
JEP 427 builds on top of JEP 394/405 and implements pattern matching for swich-case statements/expressions.
> [Java] Add support for Java 19

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_control.js
- JavaScript/tests/syntax_test_typescript.ts
Fix #3702. Supersedes #3703.
The original `catch` implementation used `parenthesized-expression` for the catch variable binging. This was technically incorrect, but it should be very hard to notice — even if you used a destructuring pattern, it would be highlighted as an object literal and look more or less correct.
However, in TypeScript this caused a problem. To begin with, it wouldn't highlight any type annotation on the catch variable. But also, in TypeScript the `parenthesized-expression` specifically looks for a type annotation and fails the `arrow-function` branch. This is especially bad here because the catch binding doesn't actually branch on `arrow-function`, so if the catch block is in an arrow function it will fail that outer arrow function and probably break highlighting in a …
> [JavaScript] Catch variable should be a binding pattern

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
The syntax seems to be mentioned only in the release notes for 4.7 and not anywhere else in the documentation. Thanks, Microsoft.
> [TypeScript] Implement type variance annotations

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Reported in https://github.com/Thom1729/Sublime-JS-Custom/issues/138.
In non-TSX TypeScript, a `<` at the beginning of an expression is either an old-style type assertion or an arrow function with type parameters. In ambiguous cases (and good golly are there ambiguous cases), I'm pretty sure it's always an arrow function. (I would check the spec, if there was one.) In the syntax definition, this is implemented by trying to parse an old-style type assertion, then reusing the regular parenthesized expression code, which will detect an arrow function and fail to the appropriate branch.
This was failing in cases like `<T = U<V>>() => {}`. The reason for this is that the old-type type assertion code didn't know how to parse the default, and eventually it got to the first `>` and ended the …
> [TypeScript] Fix bug in arrow function type parameters

- Python/Python.sublime-syntax
- Python/syntax_test_python.py
Fixes #3711
This commit...
1. fixes an issue with unpack operators not being matched in case they are followed by an empty line.
2. scopes single asterisk parameter in function signatures as named-parameters only storage modifier, which is the counter-part of `/` being scoped as positional-only parameters.
> [Python] Add support for named-only-parameters operators

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#11.cs
- C#/tests/syntax_test_Generics.cs
C#11 supports triple quoted strings using double quotes i.e. `"""`. It also handles interpolation inside them if they begin with one or more dollar signs. Each additional dollar sign represents that an extra curly brace should be used to denote the interpolation start/end markers. An `@` before the dollar signs/quotes represents the string will be literal, i.e. `\n` wouldn't be expanded.
This is therefore going to be quite tricky to handle all cases, and what I have in this PR is mainly a bare minimum prototype which ideally needs some clean up but I don't have time for it now.
C#11 also removes the requirement for interpolations to be single-line only.
> [C#] support raw string literals

- Git Formats/Git Blame Ignore Revisions.sublime-settings
- Git Formats/Git Blame Ignore Revisions.sublime-syntax
- Git Formats/tests/syntax_test_git_blame_ignore_revs
Git Blame Ignore Revisions file consists of a list of object names (i.e. one unabbreviated SHA-1 per line) that should be excluded from the blame view using git's `git blame --ignore-revs-file <file>` command or, on GitHub, by committing a `.git-blame-ignore-revs` file to the root directory of a repository. Versions of git 2.20 and higher permit comments (`#`), empty lines and trailing/leading whitespace; older versions error on everything but a SHA-1 per line.
I believe the syntax of these files is simple enough to warrant including support for them in the default package without placing much (to be honest, any) potential maintenance burden.
Included syntax tests take an average of 0.3ms over 10 runs here.
> [Git Formats] Support `.git-blame-ignore-revs` files

- C++/Snippets/$1.begin()-$1.end()-(beginend).sublime-snippet
The correct spelling that actually works in the general case is `std::begin($1), std::end($1)`, but that was axed in #3713: kill this too
> Kill $1.begin(), $1.end() snippet

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
This PR fixes following issues with escape sequences:
1. The `^` does not have special meaning within quoted arguments. 
2. The `^^` sequence in unquoted arguments denotes a literal `^`.
`^^!` is not a escape sequence, but only the first 2 chars are.
Many thank's for reporting to: @mataha
> [Batch File] Fix escaped characters in quoted arguments

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit adds a missing include to `atx-heading-content`, which caused html tags from not being highlighted.
> [Markdown] Fix html tag higlighting in ATX headings

- JavaScript/JSX.sublime-syntax
- JavaScript/tests/syntax_test_jsx.jsx
- JavaScript/tests/syntax_test_tsx.tsx
This commit fixes an issue which caused `/` in self-closing tags being scoped `meta.tag.attributes`.
> [JavaScript] Fix JSX attribute meta scopes

- ASP/syntax_test_asp.asp
- CSS/CSS.sublime-syntax
- HTML/HTML.sublime-syntax
- HTML/syntax_test_html.html
- Markdown/tests/syntax_test_markdown.md
- Rails/tests/syntax_test_rails.html.erb
This PR proposes to apply tag name variables from CSS.sublime-syntax to HTML.sublime-syntax to get both syntaxes inline. Some html5 tags such as `del`, `ins`, `slot` etc. have been missing.
Variables are grouped into `html_block_tags` and `html_inline_tags` to maintain current scoping (`meta.tag.[structure|block|inline]`) of HTML.
> The main purpose of those variables is to better keep track of possible changes on MDN.
A dedicated named context is created for each kind of tag content in case an inheriting syntax wants to replace or extend one of them.
Dedicated pattern for `<a...>` tags is removed as it doesn't push into any special context nor is the scope used in completions or snippets.
Variable names and formatting is adjusted in CSS. Word boundary checks are removed as tag names …
> [HTML] Sync known html tag names with CSS

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit adds `:` as valid language name terminator.
The following code block
~~~md
```jsx:file.jsx
import Router from 'next/router'
function MyComponent() {
const [show, setShow] = useState(false)
useEffect(() => {
console.log(2)
}, [])
return <>...</>
}
~~~
renders as:
```jsx:file.jsx
import Router from 'next/router'
function MyComponent() {
const [show, setShow] = useState(false)
useEffect(() => {
console.log(2)
}, [])
return <>...</>
}
```
see: https://github.com/withastro/astro/blob/main/examples/with-markdown-plugins/src/pages/index.md
Note: CommonMark writes the "first word" is used as language identifier, so there may be more valid separator chars.
> [Markdown] Add language separator for fenced code blocks

- LaTeX/DocStrip.sublime-syntax
- LaTeX/syntax_test_docstrip.ins
This PR adds support for the `DocStrip` format of TeX, used by many LaTeX packages to specify their installation. 
https://www.texlive.info/CTAN/macros/latex/base/docstrip.pdf
I've inherited from the base `TeX` syntax, and just prepended the new commands to the `main` context. This is not quite accurate, in the sense that many `plainTeX` constructs would simply be invalid in a docstrip file -- as there is no typesetting to be done, typesetting and math commands don't really make sense. But I think it is OK to highlight these commands, and probably better to handle things like this, because if we manually select the subset that is supported, and later on add something new in `TeX` that also works in `DocStrip`, we might forget to change `DocStrips` `main` context.
In general, `DocStrip` …
> [TeX.DocStrip] Basic DocStrip support

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
This commit...
1. assigns correct scopes to 16bit vs. 32bit unicode escapes. They were swapped.
2. shortens the scope a bit. `.16bit` and `.32bit` should be enough.
> [Python] Fix escaped unicode scopes

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
This PR proposes to change scope of classes to `support.class`.
Java decided to use `storage.type.class` as `support` scopes are said to be used for types provided by (standard) libraries only. Thus `storage.type` would be the scope for all user defined data types.
The truth according to TextMate's is exactly vice versa.
`storage.type` is meant for basic builtin data types of a language, such as `int`, `char`, ...
`support.class`, `support.type`, ... however are meant for all kinds of custom or user defined data types - not only those from standard libraries.
As such it makes very much sense most (all) other syntaxes use `support.class` for `ClassTypes`.
This commit intents to make Java follow those rules, too, again.
> [Java] Rename class scopes

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
This PR fixes an issue which caused a path pattern to be popped off stack too early, because of an heuristic used in `for /r [path] %%f` statements to make sure to match `%%f` as for variable if `[path]` is absent.
The heuristic is now restricted to for statements only, instead of being applied to all path patterns globally.
> [Batch File] Fix escaped percentage not being detected

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
An optional numeric handle consists of **exactly one** number between 0 and 9.
In action:
```batchfile
~\Packages$ rem `set 12 ^>nul`, not `set 1 2^>nul`
~\Packages$ set 12>nul
Environment variable 12 not defined
```
Unofficial source for reference: https://ss64.com/nt/syntax-redirection.html
> [Batch File] Fix interpretation of numeric handles

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
Fixes #3748
This commit adds `calc()` function to `function-arguments-prototype` so it is highlighted in all function arguments. The function is valid in majority of function calls. Maybe not everywhere, but we don't want to be a linter - or at least reduce those habits.
A first step to a somewhat more lazy parsing of CSS.
> [CSS] Highlight calc() in all function arguments

- Rails/HTML (Rails) - Comments.tmPreferences
Fixes #3756
This PR adds definition for ERB comments to be added/removed when toggling comments in ERB templates.
> [Rails] Toggle ERB instead of HTML comments

- Matlab/Completion Rules.tmPreferences
This allows to press the <kbd>Enter</kbd> key in order to insert a linebreak after a keyword at the end of the line, without accidentally inserting the 2nd best completion match (see #3648). It should improve the behavior while typing, if the default value for the `"auto_complete_commit_on_tab"` setting is used.
If I didn't miss anything, the keywords which could in practice appear at EOL are `arguments`, `break`, `catch`, `continue`, `else`, `end`, `enumeration`, `events`, `methods`, `otherwise`, `properties`, `return`, `spmd`, `try`.
But I think it doesn't hurt to also close the completion popup after other keywords.
> [Matlab] Cancel completions after keywords at EOL

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3772.
Simplify some of the function parameter list code to make it work more consistently between different contexts that use it.
> [TypeScript] Simplify function parameter list implementation to support this parameter in function types

- Lua/Comments.tmPreferences
This is how comments in Lua work:
```Lua
-- This is a comment
--[[This is block comment
spanning over multiple lines]]
```
I've personally never seen `--]]` used to end block comments.
> [Lua] Fix block comment end

- Git Formats/Git Common.sublime-syntax
- Git Formats/Git Link.sublime-syntax
- Git Formats/tests/syntax_test_git_attributes
- Git Formats/tests/syntax_test_git_codeowners
- Git Formats/tests/syntax_test_git_ignore
- Git Formats/tests/syntax_test_git_link
1. Wildcards are scoped `keyword.operator.wildcard`
2. All path separators are scoped `punctuation.separator.path`. All other sub scopes are removed.
> [Git Formats] Change wildcard and path separator scopes

- Git Formats/Git Attributes.sublime-syntax
- Git Formats/Git Code Owners.sublime-syntax
- Git Formats/Git Common.sublime-syntax
- Git Formats/Git Ignore.sublime-syntax
- Git Formats/tests/syntax_test_git_codeowners
Fixes #3767
This commit distinguishes between quoted and unquoted file patterns to determine last period in file names or patterns.
> [Git Formats] Fix file extension separator highlighting

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- Python/tests/syntax_test_python_strings.py
Supersedes #1925
This PR proposes to add dedicated contexts for type hints.
It provides highlighting for type comments including feedback from #1925.
Existing type annotations are refactored to ~~make use of `type-expressions` and~~ follow a common scope naming scheme for type hints. It is inspired by PHP, TS and TSX, which use `meta.type` to scope type hint expressions.
Known type classes from typing module are scoped as `support.class.typing`.
> [Python] Add support for type comments and annotations

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #3761
This commit adds more detailed implementation of for statement arguments to correctly scope word lists and number ranges after `in` keyword.
> [ShellScript] Improve FOR LOOP highlighting

- C#/C#.sublime-syntax
The two regexps exhibit pathological behavior under Oniguruma, though Sublime's engine handles them fine. Removing the redundant `+` quantifier fixes the problem. Performance in Sublime should be unaffected.
> [C#] Fix pathological regexps

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #3801
This commit changes array item index scope to `string.unquoted`.
> [ShellScript] Fix array item index scope

- Batch File/Batch File (Compound).sublime-syntax
- Batch File/Batch File.sublime-syntax
- Batch File/Indexed Reference List.tmPreferences
- Batch File/tests/syntax_test_batch_file.bat
This PR modifies behavior of Batch File.sublime-syntax to treat redirections as normal command arguments. That's what Bash also does.
Up to this commit, redirections have been expected, with some exceptions, to appear at the end of a command only. Thus they terminated statements.
This commit therefore applies following changes:
1. `<` and `>` are removed from command terminator patterns
2. a new `redirection_or_eoc` variable is introduced to terminate tokens, which are known not to contain redirections.
3. the `metachar` variable and some of its children are tweaked, mostly to reduce duplicated characters and to clarify dependencies.
4. `redirections` context is included into all relevant contexts
5. various remaining issues related to unquoted vs. quoted escape sequences and …
> [Batch File] Fix escape sequences, word boundaries and redirections

- ASP/syntax_test_asp.asp
- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
- HTML/syntax_test_html.html
- Haskell/tests/syntax_test_haskell.hs
- Java/tests/syntax_test_jsp.jsp
- PHP/tests/syntax_test_php.php
- Rails/tests/syntax_test_rails.css.erb
- Rails/tests/syntax_test_rails.haml
- Ruby/Embeddings/CSS (for Ruby).sublime-syntax
- Ruby/syntax_test_ruby.rb
Resolves #3688
This commit implements support for nested selectors and rule lists according to current draft specification at https://drafts.csswg.org/css-nesting-1.
> [CSS] Add nested rules support

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
Fixes #3649
This PR closely implements python's format string syntax specification.
see: https://docs.python.org/3.11/library/string.html#format-string-syntax
Only valid qualified identifiers are matched as replacement field names in order to reduce chance of false positives, even though python syntactically resolves all kinds of key names. _It appears to be an implementation detail instead of desired behaviour._
Replacement field termination is handled separately for each kind of quotation to ensure to correctly terminate replacement fields at the end of a string.
Format specs are handled more lazily following f-string implementation to better support time formats.
Parsing performance is not effected noticeably.
Checked with 10k lines of differently complex templates:
```py
"From {} to …
```
> [Python] Fix string replacement fields

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Fixes #3808
This commit restricts HEREDOC end tag indentation to `\t`.
If any other whitespace is found, a HEREDOC end tag does not match.
> [ShellScript] Fix indented HEREDOC termination

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
- Git Formats/Git Common.sublime-syntax
- Git Formats/Git Link.sublime-syntax
- Git Formats/tests/syntax_test_git_attributes
- Git Formats/tests/syntax_test_git_codeowners
- Git Formats/tests/syntax_test_git_ignore
- Git Formats/tests/syntax_test_git_link
- Haskell/Cabal.sublime-syntax
- Haskell/tests/syntax_test_cabal.cabal
- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
- PHP/tests/syntax_test_php.php
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- Rails/tests/syntax_test_rails.sql.erb
- Regular Expressions/File Pattern.sublime-syntax
- Regular Expressions/syntax_test.sublime-file-patterns
- SQL/SQL.sublime-syntax
- SQL/syntax_test_sql.sql
This PR implements RFC #3766 by ...
1. adjusting path wildcard scopes to `variable.language.wildcard`
2. modifying scopes of `.` to `variable.langauge.self`
3. modifying scopes of `..` to `variable.langauge.parent`
The current scopes are chosen ...
1. to fullfill requirements outlined in https://github.com/sublimehq/Packages/issues/3766#issuecomment-1554226973
2. because `variable.language.wildcard` has been used by majority of syntaxes for quite a while 
3. as they fit into a common naming scheme
```
variable
language
anonymous      - empty throwaway variables (e.g. `_`)
self           - `self`, `this`, `.`, ...
parent         - `super`, `..`, `&` in CSS, ...
wildcard       - `*`, `?`, ...
```
Those scopes may be used by path like tokens such as path strings or qualified identifiers as …
> [Common] Adjust wildcard scopes

- Go/Snippets/Template/block-end.sublime-snippet
- Go/Snippets/Template/block.sublime-snippet
- Go/Snippets/Template/break.sublime-snippet
- Go/Snippets/Template/continue.sublime-snippet
- Go/Snippets/Template/define.sublime-snippet
- Go/Snippets/Template/else if.sublime-snippet
- Go/Snippets/Template/else.sublime-snippet
- Go/Snippets/Template/end.sublime-snippet
- Go/Snippets/Template/if-end.sublime-snippet
- Go/Snippets/Template/if.sublime-snippet
- Go/Snippets/Template/partial.sublime-snippet
- Go/Snippets/Template/range-end.sublime-snippet
- Go/Snippets/Template/range.sublime-snippet
- Go/Snippets/Template/template.sublime-snippet
- Go/Snippets/Template/var.sublime-snippet
- Go/Snippets/Template/with-end.sublime-snippet
- Go/Snippets/Template/with.sublime-snippet
- Go/Template.tmPreferences
This PR proposes to add basic snippets for Go templates.
tif      => {{ if | }}
tifend   => {{ if | }} ... {{ end }}
telse    => {{ else }}
Triggers follow the scheme to prefix each valid template keyword with `t`.
We basically don't want to add new snippets, so an alternative would be to publish them as separate package, but I always found some helpers to add template tags very helpful.
Thoughts?
> [Go] Add Template Snippets

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_union.rs
> [Rust] fix highlighting when calling a function named "union"

- PHP/PHP Source.sublime-syntax
- PHP/PHP.sublime-completions
- PHP/tests/syntax_test_php.php
PHP 8.3 is scheduled to be 
- first alpha on `Jun 08 2023`
- feature freeze on `Jul 18 2023`
- stable release on `Nov 23 2023`
**References**:
- PHP RFCs: https://wiki.php.net/rfc#php_83
- PHP milestone: https://github.com/php/php-src/milestone/5?closed=1
- PHP release schedule: https://wiki.php.net/todo/php83
> [PHP] PHP 8.3 new syntax

- AppleScript/AppleScript.sublime-syntax
> [AppleScript] stop treating JXA-shebanged files as AS

- Python/Embeddings/RegExp (for Python).sublime-syntax
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
Fixes #3834
This commit fixes an issue with regexp quantifiers being scoped illegal after string replacements in raw-f-strings:
1. skip illegal leading quantifier checks by directly pushing to `#base-literal`
2. prefer range-quantifiers over python interpolations so `{2,3}` keeps scoped correctly.
> **Note**
>
> Support for interpolation within ranged quantifiers (e.g.: `{{begin},{end}}`) is not planned.
> [Python] Fix f-string regexp quantifier highlighting

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
The TypeScript syntax uses the `.js` suffix, but there were a couple of places where a `.ts` slipped through.
Also strip the `.js` suffix from the tests, as is convention.
> [TypeScript] Standardize on .js suffix

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_support_builtin.js
- JavaScript/tests/syntax_test_js_support_console.js
- PHP/tests/syntax_test_php.php
Fix #3790.
The scope naming guidelines recommend giving e.g. all of `foo.bar.baz()` the scope `meta.function-call`. For reasons discussed in #3790 and in #2575, this is quite difficult to implement in a reliable manner. Currently, the JavaScript syntax definition tries to do this using lookaheads, but it is far from reliable, leading to observable highlighting bugs such as #3790.
This PR rips out the existing code scoping function call paths and instead just scopes the function/method identifier and arguments. This should be sufficient for any of the actual use cases discussed in the linked issues while also being much more reliable. Notes:
- It's still not *perfectly* reliable, because we're still detecting the function parens (and in TS, type arguments) via a lookahead, but at least …
> [JavaScript] Don't try to scope entire call paths

- C++/C.sublime-syntax
- C++/syntax_test_c.c
Test screenshot:
All three forms are in use in the wild. The __-prefixed versions two have been available for a long time. The plain `typeof()` and `typeof_unqual()` is [new in C23](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf).
Derived from the C++ decltype code.
> [C] Add typeof[_unqual]() handling

- ShellScript/Bash.sublime-syntax
- ShellScript/test/syntax_test_bash.sh
Resolves #3009
Fixes #3825
This PR ...
1. refactors [Pattern Matching](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html) and implements [Posix Extended Regular Expressions](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html) to improve highlighting accuracy.
2. refactors test expressions to distinguish different feature levels and behaviors of `test ...`, builtin test expressions `[ ... ]` and compound test command `[[ ... ]]`. Only the last one supports pattern matching after `==` or `!=` operators as well as extended regular expressions after `=~` operator.
It is a somewhat larger commit, but mainly due to various "duplications" needed to handle different sorts of bailout requirements, depending on the context pattern matching appears in. …
> [ShellScript] Improve test expression and pattern matching highlighting

- JavaScript/JavaScript.sublime-syntax
This commit updates `first_line_match` and shebang scope to automatically apply JavaScript syntax to apple scripts with:
#!osascript -l JavaScript
This is a follow-up of #3829.
> [JavaScript] Add osascript to shebang

- Python/Comments.tmPreferences
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
Sphinx (the most common Python documentation tool) uses `#:` comments to signal documentation comments for its "autodoc" module.
There is no known overlap with other comment punctuation, so this should be a safe addition.
`TM_COMMENT_START_2` is also added to be able to undo the comment using `toggle_comment`, but unfortunately it does not work like this currently because `Default/comment.py` does not prioritize the longest prefix match of all available comment styles.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute
Discovered via https://github.com/sublimehq/sublime_text/issues/5587#issuecomment-1259180246
> [Python] Add syntax support for sphinx-style doc comments

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_bindings.js
- JavaScript/tests/syntax_test_js_control.js
- JavaScript/tests/syntax_test_js_support_builtin.js
[This feature](https://github.com/tc39/proposal-explicit-resource-management) is currently in Stage 3 of the TC39 process. In addition, it is part of [TypeScript 5.2](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management), which was released last week.
The lookaheads are exact (unless I made a mistake). Since `using` is not a reserved word, the proposal spec has to restrict line endings between `using` and the variable name to ensure backward-compatibility.
As part of this PR, I rewrote `for` loop handling. JavaScript basically has two different kinds of for loops: C-style (e.g. `for (let i = 0; i < len; i++) {}`) and `in`/`of` (e.g. `for (const item of list) {}`). The existing implementation predates branching, so it …
> [JavaScript] Support explicit resource management proposal (and rewrite for loops in the process)

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
LSP output, such as is displayed in tooltips, truncated long types with syntax like the following:
```ts
type T = Foo | ... 100 more ... | Bar;
```
This is not valid TypeScript syntax, but LSP highlights tooltips using the core TS syntax, and this causes highlighting to break. (The TS type expression syntax is deliberately rigid to prevent false positives.)
This PR adds support for the `... 100 more ...` bit to the TS syntax definition. Ordinarily, I'd hesitate to put something that's not actually TS syntax in the core definition, but in this case I think it makes sense — given the tight coupling between the language and the language server, I'm not concerned about this conflicting with other syntax extensions.
I used a comment scope, though not for any particular reasons. The regexp …
> [TypeScript] Support placeholder in LSP type output

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Highlighting gets wonky while typing e.g.:
```ts
interface // cursor position
class Foo {}
```
This PR fixes that by adding a couple of else-pops, and by ensuring that only valid (i.e. non-reserved) identifiers are matched as the names of interfaces, type aliases, and namespaces.
> [TypeScript] Better highlighting while typing declarations

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
E.g. `type Rational = [numerator: bigint, denominator: bigint];`
Introduced in [TypeScript 4.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements) more than three years ago, but documented nowhere outside those release notes (plus the recent [5.2 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#named-and-anonymous-tuple-elements)).
I used the scope `meta.mapping.key` for the labels, which doesn't seem quite right but I don't know what would be more right.
The implementation uses branching because a lookahead would have to span multiple lines. I initially intended to use a cover grammar approach, but that would be a mess if the label were the name of a type operator (which you would think wouldn't be …
> [TypeScript] Implement labeled tuple members

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
Fixes #3215
This PR improves comment punctuation highlighting to support arbitrary number of opening and closing punctuation chars.
This helps to keep line comment punctuation consistent when performing hard line wrapping.
The new contexts are copied from JavaScript (see #3018) and adjusted to match C's scopes and maintain the existing "banner comments".
> [C/C++/ObjC/ObjC++] Improve comments punctuation

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_import_export.js
- JavaScript/tests/syntax_test_typescript.ts
The existing code handling export declarations was weirdly overbroad, explicitly handling cases that aren't proper syntax. (Probably this is the legacy of copy-pasting from the import declaration code.) On the other hand, it failed to support at least one case involving strings in place of identifiers. In addition, `export type {}` wan't properly supported in TypeScript, which is how I started on this.
This PR fixes the known export bugs/missing features and generally cleans up the code. It also removes a test that's invalid syntax, and fixes the semicolon scoping on a test that wasn't correct.
I should probably give the import declaration code a good cleaning as well, but I'll put that off until after this PR.
> [JavaScript] [TypeScript] Clean up export code and support more cases

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
The code for the contents of object and interface types has grown as new TypeScript features were added. This PR rewrites the `ts-type-members` context to handle things in a more robust and coherent fashion. Specific notes:
- Previously, a bracketed member name was taken to be a mapped type member or indexed type member. But instead of a mapped/indexed member, you can have any arbitrary type in the brackets. This worked by coincidence in most practical cases, but it failed to highlight e.g. `[Symbol.iterator]`, which is how I started on this whole thing. The new implementation branches, tries to match a mapped/indexed member, and if that fails matches a type expression.
- The previous implementation had separate handling for call signatures, construction signatures, mapped/indexed …
> [TypeScript] Fix bugs in object/interface types

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_import_export.js
- JavaScript/tests/syntax_test_typescript.ts
- Consolidate `import/export-brace` and `import/export-item`. They're not identical in the grammar, but they're close enough and they don't conflict.
- Handle `import type from 'somewhere';` in TypeScript. (`import type` and `export type` cannot share an implementation because they have different corner cases.)
- Use the new more-specific scope for wildcards.
- Support the `with` keyword for import assertions. This is a breaking change in the import assertions proposal. Currently, TypeScript supports both, but `assert` is deprecated; this PR supports both.
- Support import assertions in re-exports.
> [JavaScript] Clean up imports

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
Fixes #3820
This PR...
1. adds separate contexts for nested at-rules.
Global at-rules push [&lt;style-blocks&gt;](https://www.w3.org/TR/css-syntax-3/#typedef-style-block) on stack while nested at-rules push [&lt;rule-lists&gt;](https://www.w3.org/TR/css-syntax-3/#typedef-rule-list) represented by `property-lists` context.
2. refactors at-rules to make use of multi-push statements so more general purpose contexts can be created and re-used more often, which reduces syntax cache size and should limit amount of special purpose contexts, which might need to be addressed by inheriting 3rd-party syntaxes.
3. replaces `at-rule-end` by `else-pop` to follow a fail as early as possible approach, which may help to bail-out from statements more reliably.
e.g. at-rules with missing semi-colon suffered …
> [CSS] Fix nested at-rules highlighting

- C++/C.sublime-syntax
- C++/syntax_test_c.c
This was broken by e4e5273d8ca764ebcd79b2ecfbed592036944265
> [C/C++/ObjC/ObjC++] Fix javadoc comment word wrap

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
This commit adds scoping for leading asterisks in (normal) block comments so ST's word_wrap command can add them to each wrapped line, if present in the first one.
Notes:
This change aligns JavaScript with Java and C/C++.
Related with #3855
> [JavaScript] Fix block comment punctuation

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Fixes #3844
Brackets and parentheses don't have special meaning nor do they group expressions within token strings. They may appear in unbalanced numbers.
This commit therefore removes pushing dedicated contexts on stack if ( or [ is matched.
According to https://dlang.org/spec/lex.html#token_strings nested braces are however valid. Thus keep pushing a context if { is matched.
> [D] Fix token strings

- PHP/PHP Source.sublime-syntax
- PHP/PHP.sublime-completions
array_is_list 
array_key_first 
array_key_last
cli_get_process_title
cli_set_process_title
gc_mem_caches 
gc_status
> [PHP] Add built-in function

- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Fix #3862.
Originally, type arguments were part of the regular type expression structure, so the syntax would try to highlight type arguments after any type. But actually, only ordinary named types can get them. In the linked issue, this was causing problems with `as`-style type assertions — when followed by a `<`, the type expression was eating it and trying to parse type arguments, even when the preceding type does not accept them.
According to the spec — I'm kidding, we all know the drill by now, actually after a bunch of futzing around in AST Explorer — this should work correctly in all cases I can think of.
In order for this to work in all cases, it's necessary to ensure that all specially keyworded types are accounted for, so this PR also adds the `true` and `false` singleton types.
> [TypeScript] Keyword types can't be generic

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- Python/tests/syntax_test_python_strings.py
Fixes #3860
Escaped quotation marks do not terminate raw strings, despite escaping being widely disabled.
> [Python] Fix escaped quotes in raw strings

- Markdown/Fold.tmPreferences
- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit adjusts fenced code block related patterns to scope EOL `meta.fold`, to provide reliable single char tokens for syntax based folding and adjusts fold rules accordingly.
Reported at https://github.com/SublimeText-Markdown/MarkdownEditing/issues/733
> [Markdown] Fix syntax based folding of fenced code blocks

- Go/HTML (Go).sublime-syntax
Go templates use `*.tmpl` file extension by default according to https://docs.gomplate.ca/usage/.
> [Go] Assign .tmpl extension to Go templates

- Batch File/Comments.tmPreferences
This commit introduces two changes:
- `@rem` (silenced `rem`) and `:::` (safe equivalent of `::`) have been added
- `rem` and its silent equivalent `@rem` now use `TM_COMMENT_CASE_INSENSITIVE` introduced in Sublime Text 4153, which allows collapsing comments casefold
> [Batch File] Tweak comment collapsing

- JSON/JSON.sublime-syntax
- JSON/syntax_test_json.json
1. fixes missing closing `punctuation.definition` scopes
2. renames a `.js` final scope to `.json`
3. adjusts leading asterisk scoping according to #3855 and #3856.
4. refactors comment related contexts to use only named contexts.
reported at: https://discord.com/channels/280102180189634562/280157121897562114/1175037871011418222
> [JSON] Fix comment punctuation scopes

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_literals.rs
Rust 1.76 has added C-string literal syntax.
> [Rust] Add C-string literals

- Python/Fold.tmPreferences
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
> [Python] Fix type parameter punctuation scope

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
This PR fixes a copy&paste error, which caused `block` scope to having been found its way to normal double quoted u-strings.
> [Python] Fix double quoted u-string scope

- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript.ts
Fix #3890.
I figured out what I was thinking. I added the `!` postfix operator to `dot_accessor` because it kept things like function call detection working without further alteration. This PR tweaks a few contexts to make everything work without wrongly marking the `!` in `!.` as an accessor.
I also changed a few contexts to use literal `?.` instead of the `dot_accessor` variable when just a dot wouldn't be valid anyway. And I moved the `!` postfix operator to `left-expression-end`. I have to imagine that having it in `expression-end` instead might have caused some subtle bugs, but I'm not sufficiently motivated to track those down (if indeed they ever existed).
> [TypeScript] Non-null assertion is not an accessor

- Markdown/Markdown.sublime-syntax
- Markdown/Symbol List - Heading.tmPreferences
- Markdown/tests/syntax_test_markdown.md
Resolves #3891
This PR proposes to add support for syntax highlighting of GitHub alerts as proposed by #3891.
This PR uses dedicated scopes `markup.heading.alert` and `markup.quote.alert` to avoid unwanted negative impacts on highlighting in conjunction with legacy color schemes. Dedicated highlighting requires to opt-in via new color scheme rules. Otherwise those blocks keep highlighting as normal block quotes except `[!...]` marker being highlighted as normal heading.
> [Markdown] Add GitHub Alerts syntax

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Fixes https://github.com/sublimehq/Packages/pull/3892#issuecomment-1872549074
Follow up commit for #3892.
> [Markdown] Fix premature block quote termination

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_attributes.rs
- Rust/tests/syntax_test_closures.rs
- Rust/tests/syntax_test_dyn.rs
- Rust/tests/syntax_test_enum.rs
- Rust/tests/syntax_test_functions.rs
- Rust/tests/syntax_test_generics.rs
- Rust/tests/syntax_test_identifiers.rs
- Rust/tests/syntax_test_macros.rs
- Rust/tests/syntax_test_modules.rs
- Rust/tests/syntax_test_raw.rs
- Rust/tests/syntax_test_struct.rs
- Rust/tests/syntax_test_traits.rs
- Rust/tests/syntax_test_types.rs
- Rust/tests/syntax_test_union.rs
See the individual commits for details.
In this PR, I have rewritten path matching in Rust to
- fix application of `support.function` scopes in function calls
- also in annotations
- unify handling of identifiers, function calls and types, even inside paths (e.g. `f32::from(…)`)
- make `meta.path` span the entire "path", as specified in the scope naming docs
- make `meta.generic` not span the type it is being generic over
- be more resilient against whitespaces
- consistently apply `punctuation.accessor` for sub-path access
Fixes a few outstanding issues from #2305 (such as https://github.com/sublimehq/Packages/pull/2305#issuecomment-739496138, highlighting of `union` as a function name, which is a soft-keyword).
In addition, the syntax definition file has been restructured a bit by …
> [Rust] Refactor path matching

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#9.cs
> [C#] fix using top level statements when using a type instead of "var"

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_attributes.rs
- Rust/tests/syntax_test_control_flow.rs
- Rust/tests/syntax_test_enum.rs
- Rust/tests/syntax_test_expr.rs
- Rust/tests/syntax_test_functions.rs
- Rust/tests/syntax_test_generics.rs
- Rust/tests/syntax_test_literals.rs
- Rust/tests/syntax_test_macros.rs
- Rust/tests/syntax_test_modules.rs
- Rust/tests/syntax_test_struct.rs
- Rust/tests/syntax_test_traits.rs
- Rust/tests/syntax_test_types.rs
- Rust/tests/syntax_test_union.rs
- Rust/tests/syntax_test_visibility.rs
Following the example of Java, we're replacing the `storage.type` scope
with `keyword.declaration` without keeping the `storage.type` for
compatibility. Also, like in Java, the `use` keyword gets a
`keyword.declaration.import` scope to signal that it is introducing
names into the current namespace.
`type` aliases have slightly been refactored to properly match `where`
clauses. (I did a bit of work twice here because I forgot to `git pull`
before and included the remainder …)
Closes #3640.
> [Rust] Use `keyword.declaration` scope

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
Fixes #3902
This commit ensures to highlight `type` more context sensitively.
It may have the following meanings:
1. built-in `type()` function
2. type alias declaration keyword: `type Alias`
3. ordinary variable used in many data classes
The built-in function (1.) most likely appears in r-value expressions, such as
`my_type = type(var)`
At beginning of statements this commit prefers scoping `type` as keyword (2.) or variable (3.) as this is the most likely use case.
The implementation ensures to start `meta` scope of alias declarations at bol as class or function declarations do.
> [Python] Improve type alias definitions

- XML/XML.sublime-syntax
https://draw.io is a famous open-sourced flow chart maker. And its own file format is XML with `.drawio` as the filename extension.
> [XML] Add .drawio extension

- YAML/YAML.sublime-syntax
This PR...
1. replaces `pop: true` by `pop: 1` as this is prefered style in `version: 2` syntaxes
2. reorganizes contexts, beginning with comments, followed by blocks and flow contexts
3. adds various section header contexts to partition syntax definition and improve readability
Notes: 
1. This PR does not change behavior, it is just a maintanance PR to clean up code style.
2. Context names keep unchanged to not break any 3rd-party packages.
> [YAML] Reorganize contexts

- YAML/YAML.sublime-syntax
- YAML/tests/syntax_test_flow.yaml
Fixes #1026
This PR scopes tokens after closing quotation mark illegal to discover unbalanced quotation marks.
> [YAML] Fix unbalanced quoted scalars

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
Resolves #3897
This commit implements relaxed syntax for nested style rules according to https://www.w3.org/TR/css-nesting-1/#nested-style-rule.
In general it means, nested selectors of nested style rules no longer need to start with `&` operator to denote html tags.
The implementation adopts `properties-or-selectors` context from Less syntax to achieve reliable distinction between declarations and selectors without loosing support for interpolation.
> [CSS] Relaxed Nesting Support

- Diff/Diff.sublime-settings
- Diff/Diff.sublime-syntax
- Diff/syntax_test_diff.diff
Resolves #1304
This PR...
1. ~~sets syntax specific setting `"draw_white_space": ["trailing_all"]` so trailing spaces are rendered by default.~~
2. scopes trailing spaces `meta.whitespace.trailing` in inserted/removed/modified lines, so color schemes can address them and possibly apply background color.
```jsonc
{
"scope": "markup.changed.diff meta.whitespace",
"background": "color(var(orange) alpha(0.15))",
},
{
"scope": "markup.deleted.diff meta.whitespace",
"background": "color(var(red2) alpha(0.15))",
},
{
"scope": "markup.inserted.diff meta.whitespace",
"background": "color(var(green2) alpha(0.15))",
},
```
> [Diff] Scope trailing spaces

- YAML/YAML.sublime-syntax
This PR proposes some changes to improve parsing performance by about 18-20%
Syntax cache size drops from 58kB to 41kB (-30%).
> [YAML] Improve Performance

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#10.cs
- C#/tests/syntax_test_C#11.cs
- C#/tests/syntax_test_C#7.cs
Resolves #3926
This commit adds `required` modifier which has been added by C#11.
see: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required
It adjusts `readonly` related patterns to ensure both can appear next to each other.
> [C#] Add required modifier

- ASP/Embeddings/JSON (for ASP).sublime-syntax
- ASP/HTML (ASP).sublime-syntax
- ASP/syntax_test_asp.asp
- Go/Embeddings/HTML (for Go Embedded Backtick Strings).sublime-syntax
- Go/Embeddings/JSON (for Go Embedded Backtick Strings).sublime-syntax
- Go/HTML (Go).sublime-syntax
- Go/JSON (Go).sublime-syntax
- Go/tests/syntax_test_template.html
- JSON/JSON.sublime-syntax
- JSON/syntax_test_json.json
- Java/Embeddings/JSON (for JSP).sublime-syntax
- Java/HTML (JSP).sublime-syntax
- Java/tests/syntax_test_jsp.jsp
- PHP/JSON (PHP).sublime-syntax
- PHP/PHP.sublime-syntax
- PHP/tests/syntax_test_php.php
- Rails/Embeddings/JSON (for HAML).sublime-syntax
- Rails/HAML.sublime-syntax
- Rails/HTML (Rails).sublime-syntax
- Rails/JSON (Rails).sublime-syntax
- Rails/tests/syntax_test_rails.haml
- Rails/tests/syntax_test_rails.html.erb
This PR...
1. renames contexts to express popping/non-popping behavior via singular/plural.
2. adds named contexts for nearly everything, so it can be addressed by inherit syntaxes.
... while keeping behavior and highlighting as simple and fast as it is without bloating the package.
required for https://github.com/SublimeText/Liquid/issues/10
The new syntax is inherit in ASP, JSP, PHP, ERB and HAML to support JSON highlighting in templates.
Without this PR syntax highlighting errors occur, within `<script type="application/json">` tags due to lack of interpolation support of JSON syntax, which is already embedded in HTML.sublime-syntax.
> [JSON] Add support for inheritance

- Python/Fold.tmPreferences
1. includes trailing whitespace into most fold regions. As a result closing brackets don't stay at a separate line anymore.
Exception: function parameters ; as folding multi-line parameters should work independently from folding code blocks (by indentation).
2. add fold rules for triple quoted block strings.
| what | before | after
|---   |---     |---
| decorators | ![grafik](https://github.com/sublimehq/Packages/assets/16542113/40a5a58c-81ae-4337-acaa-6cd6e24e52e9) | ![grafik](https://github.com/sublimehq/Packages/assets/16542113/77b739ca-d950-43fa-8119-d7f8253a395f) 
| function calls | ![grafik](https://github.com/sublimehq/Packages/assets/16542113/10ee3e39-180d-4d9a-9429-33a15beef10f) | ![grafik](https://github.com/sublimehq/Packages/assets/16542113/43533b15-9519-4388-b …
> [Python] Adjust fold rules

- PHP/PHP.sublime-build
I'm not sure if this is the right convention since I see no other default build systems differentiating between "Run" and "Lint" but I find this to be very useful, more so than trying to mess with some buggy Python plugins.
> [PHP] Add build systems

- Diff/Context.sublime-menu
This commit adds `id: diff` to context menu to group it with default items from Default/Context.sublime-menu.
> [Diff] Add context menu id

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #3936
This commit fixes function calls not being scoped as such, if identifier is an array variable.
> [PHP] Fix function calls with array identifiers

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
Fixes #3939
This commit ensures to pop `line-continuation-body` off stack immediately after consuming a string.
To achieve that, all exiting `string` related contexts are converted to immediatelly pop themself off stack and new gatekeeper contexts are created to push those on stack.
As a positive side-effect syntax cache size is reduced from 546kB to about 477kB and parsing performance seem to be slightly better (a little only).
> [Python] Fix assignment after line continuation

- JavaScript/JavaScript.sublime-syntax
example `#!/usr/bin/env bun` on nodejs cli files should syntax highlight to javascript
> [JavaScript] Support bun in shebang for syntax highlighting

- Markdown/Markdown.sublime-syntax
This commit renames scopes of `---` frontmatter markers, so they follow common scope naming schema:
```
meta.frontmatter punctuation.section.frontmatter
```
> [Markdown] Simplify frontmatter punctuation scopes

- YAML/YAML.sublime-syntax
https://citation-file-format.github.io/
Also see https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md which states that the file must be named exactly `CITATION.cff` and that it is YAML.
> [YAML] Add CITATION.cff file extension

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit adds interpolation support to
a) unquoted font family names
b) langaage ranges
c) unquoted urls
from: https://github.com/braver/Sass/pull/96/commits/cf20d5fbe89b6cc50036c0f3f4f64c1200b78d65
> [CSS] Improve language constant interpolation support

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- Python/tests/syntax_test_python_strings.py
Fixes #3954
This PR...
1. extends escape pattern of raw strings by `\\` to prevent unwanted consuming of `\"` in `\\"`.
2. drops scoping `\\`, `\"` or `\'` with `constant.character.escape` in raw strings as those tokens are treated literal - printed as is.
They remain scoped escapes in regexp strings though as scoping of embedded
syntax applies.
> [Python] Fix raw-string termination

- OCaml/OCaml.sublime-syntax
- OCaml/syntax_test_ml.ml
Resolves #3958
This commit...
1. moves record definition blocks into a named context and includes it after `strings` context, to give `{|` precedence over `{`.
2. adds patterns for `{| ... |}` strings.
> [OCaml] Add support for brace quoted strings

- LaTeX/Bibtex.sublime-syntax
- LaTeX/Symbol List - Commands.tmPreferences
- LaTeX/Symbol List - Constants.tmPreferences
- LaTeX/Symbol List - Sections.tmPreferences
- LaTeX/tests/syntax_test_bibtex.bib
This commit...
1. rewrites BibTeX using named contexts only.
2. adjusts symbol lists
A major intent is to provide stacked meta scopes for 
a) #3952 and
b) enable syntax based folding.
> [!NOTE]
>
> It appears #3952 is not related with how meta and punctuation scopes are organized. Changed syntax can't fix it.
> [LaTeX] Rewrite BibTex

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
- D/tests/syntax_test_old.d
Changes:
- Separated built-in type-aliases (e.g. `size_t`, `string`) from built-in types (e.g. `int`, `float`) so that their identifiers aren't treated as reserved (they aren't, e.g. you can make your own `string`), and so that they can be highlighted separately.
> [D] Separate built-in type-aliases from built-in types

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Fixes #3968
This commit...
1. removes `invalid.deprecated` scope from single backticks in table cells
2. fixes code spans treatment in tables. Codespans require balanced backticks in a single line not containing a `|` cell separator are found.
> [Markdown] Fix backticks and code-spans in table cells

- D/D.sublime-syntax
- D/tests/syntax_test_d.d
Changes:
- Valid `__traits` are highlighted with `constant.other.d`.
- Invalid `__traits` now trigger `invalid.illegal.d`, because they cause compile errors.
- Highlight known pragmas with `constant.other.d`. Invalid pragmas are not *meant* to cause compile errors in D (currently they do, but it's being fixed), so they do NOT trigger `invalid.illegal.d`.
> [D] Add highlighting for recognised __traits/pragmas

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Otherwise it misses the end of a code span if there are multiple in a single cell.
> [Markdown] Make table_codespan_content non-greedy

- ASP/HTML (ASP).sublime-syntax
- ASP/syntax_test_asp.asp
- Go/CSS (Go).sublime-syntax
- Go/Embeddings/CSS (for Go Embedded Backtick Strings).sublime-syntax
- Go/Embeddings/HTML (for Go Embedded Backtick Strings).sublime-syntax
- Go/HTML (Go).sublime-syntax
- Go/tests/syntax_test_template.html
- HTML/HTML (Plain).sublime-syntax
- HTML/HTML.sublime-syntax
- Haskell/Embeddings/HTML (for HSX).sublime-syntax
- Haskell/tests/syntax_test_haskell.hs
- Java/HTML (JSP).sublime-syntax
- Java/tests/syntax_test_jsp.jsp
- PHP/Embeddings/HTML (for PHP Interpolated).sublime-syntax
- PHP/PHP.sublime-syntax
- PHP/tests/syntax_test_php.php
- Rails/HTML (Rails).sublime-syntax
- Rails/tests/syntax_test_rails.html.erb
This commit adds a `tag_name_start` variable to represent a custom tag's first character across syntax definitions instead of hard-coding `[A-Za-z]`.
It enables template syntaxes to override such tags' names easier, if they begin with a template interpolation.
Example:
<{{tag_name}} ...>
To scope `{{tag_name}}` entity.name.tag, a template syntax has needed to extend the `tag-other` context before this commit with something like:
tag-other:
- meta_prepend: true
- match: </?(?={{) 
scope: punctuation.definition.tag.begin.html 
push:
- tag-other-content
- tag-other-name
even though `{{ ... }}` tags are already part of the `prototype` context.
With this commit it is enough to override the `tag_name_start` to add the template begin punctuation in order to achieve the same outcome.
variables: …
> [HTML] Add variable for custom tag start character

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_control.js
Fixes #3985
This PR sets `expression` instead of `expression-no-comma` onto stack after ternary expressions, so they can appear in the middle of sequences.
> [JavaScript] Fix comma after ternary expression

- ShellScript/test/syntax_test_bash.sh
This maintenance PR rearranges bash syntax tests by 
- strictly following given structure of https://www.gnu.org/software/bash/manual/bash.html 
- and by addding related chapter links to keep track between tests and specification
The main goals are
1. more easily ensure not to forget tests for certain features especially when cross checking with other/new shell dialects/syntaxes.
2. separate this pure re-arrangement from upcomming real behavior changing or bugfixing modifications, which modify both syntax definition and syntax tests.
This PR adds some tests (for positional parameters) but does not remove any existing ones.
> [ShellScript] reorganize syntax tests

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
Fixes  #3997
This commit excluded linefeed from set of illegal operators within for loops.
> [Batch File] Fix newline scoped illegal in for loop sets

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
Multiple colons immediately followed by a non-empty line cause said line
to be scoped as a comment:
```batchfile
::: Set some variables
:::
set WSL_UTF8=1
```
> [Batch File] Fix comment scope around newlines

- JavaScript/JavaScript.sublime-syntax
Fixes https://github.com/sublimehq/sublime_text/issues/6416
Regressed by #3836
This commit refactors for loop conditions to prevent ST's syntax engine to run into an infinite loop, if multiple nested for loops appear within branches, such as arrow functions.
The issue seems to be triggered by
```yml
for-condition-contents:
- match: ''
branch_point: for-in-of
branch:
- for-in-of
- for-oldstyle
pop: 1
```
in conjunction with newlines.
Note: It somewhat reorganizes expressions contexts a little bit.
> [JavaScript] Fix ST freezing

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
This commit applies the following rule:
If `^` appears at the end of a line, the linefeed is stripped and the next character is escaped or uses its special meaning, if any. If the next character is also a linefeed, it is treated literal.
REM command seems to be working special by line continuation working only directly after the first token.
> [Batch File] Fix line continuation

- CSS/CSS.sublime-syntax
This commit adds `:global(selector)` and `:local(selector)` pseudo-class support. The former is used by CSS Modules, Less and Astro framework. The ladder is used by CSS Modules only, but is added for completeness.
It is no default CSS feature, but appears to be specific enough to not cause any conflicts.
Adding it to core CSS would avoid the need to extend CSS for Astro, just for this single reason.
Vue.js also uses `:global` (see: https://vuejs.org/api/sfc-css-features.html#global-selectors).
> [CSS] Add :global() and :local() pseudo-classes

- Markdown/Code Block Syntaxes.sublime-completions
- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
Mainly because `batchfile` didn't work for batch files...
This commit adds most of Linguist (GH language detector - [source][1]) aliases for languages for which fenced code block contexts exist in Markdown grammar.
I've omitted a few aliases because these name separate languages with their own third-party packages (notably `cake`, `octave` and some `sh` variants).
I've left ActionScript alone as I wasn't sure whether the grammar covers as3.
[1]: https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml
> [Markdown] Match code block syntax names with Linguist aliases

- Rust/Cargo.sublime-build
Closes #4004
I've added some variants for building, running, and checking using Rust's short message format, which gives a nicer inline error than Rust's default output.
I'm not familiar with the conventions of this codebase though around naming, preferred use of regex features etc, so if it's easier to just redo this in a more idiomatic way than it is to explain it then feel free to close :slightly_smiling_face:
> [Rust] Add variants for short message formats

- JavaScript/Symbol List.tmPreferences
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript_declarations.d.ts
Fixes #4010
This commit...
1. adds support for unquoted identifiers in module declarations
2. scopes quoted identifiers entity.name.modules, instead of "string".
3. adds module declaration names to symbol list and global symbol index.
4. removes possible leading and trailing quotes from symbols.
> [JavaScript] Fix module declaration

- Go/Go.sublime-syntax
- Go/Snippets/Template/block-end.sublime-snippet
- Go/Snippets/Template/block.sublime-snippet
- Go/Snippets/Template/break.sublime-snippet
- Go/Snippets/Template/continue.sublime-snippet
- Go/Snippets/Template/define.sublime-snippet
- Go/Snippets/Template/else if.sublime-snippet
- Go/Snippets/Template/else.sublime-snippet
- Go/Snippets/Template/end.sublime-snippet
- Go/Snippets/Template/if-end.sublime-snippet
- Go/Snippets/Template/if.sublime-snippet
- Go/Snippets/Template/partial.sublime-snippet
- Go/Snippets/Template/range-end.sublime-snippet
- Go/Snippets/Template/range.sublime-snippet
- Go/Snippets/Template/template.sublime-snippet
- Go/Snippets/Template/var.sublime-snippet
- Go/Snippets/Template/with-end.sublime-snippet
- Go/Snippets/Template/with.sublime-snippet
- Go/Template.tmPreferences
- Go/YAML (Go).sublime-syntax
- Go/tests/syntax_test_template.html
- Go/tests/syntax_test_template.md
- Go/tests/syntax_test_template.yaml
This PR...
1. fixes missing `source.json.go` scope in snippet selectors
2. adds _YAML (Go).sublime-syntax_ with YAML highlighted Go Templates
> [Go] Add support for YAML Go templates

- .github/workflows/ci.yml
This change is required for #4015 to succeed.
We can re-enable stable tests, once the next stable release is made.
> [CI] Disable tests against ST4169

- JavaScript/Embeddings/CSS (for JS template).sublime-syntax
- JavaScript/Embeddings/HTML (for JS template).sublime-syntax
- JavaScript/Embeddings/JSON (JS template).sublime-syntax
- JavaScript/Embeddings/JavaScript (JS template).sublime-syntax
- JavaScript/Indentation Rules.tmPreferences
- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_indent_common.js
- JavaScript/tests/syntax_test_js_template.js
Resolves #179
This commit adds support for syntax highlighting of CSS/JS/JSON/HTML within tagged template strings.
JavaScript embeds extended syntax definitions to enable `${...}` interpolation in highlighted template tags, very much like most other template syntaxes (e.g.: Go Templates, Jinja2, Liquid, ...).
As templates are embedded, impact on syntax cache size and complexity of JavaScript itself is negligible. They are loaded on demand and thus shouldn't effect other template languages, significantly.
Compatibility notes:
1. Template syntaxes such as Jinja or Liquid need to take action, if they want to support their own interpolations such as `{{ ... }}` within tagged template tags.
2. This PR might affect _JS Custom_, which also supports adding syntax highlighted tagged template tags. …
> [JavaScript] Basic support for syntax highlighting in tagged templates

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js.js
- JavaScript/tests/syntax_test_js_control.js
This PR fixes a regression, introduced by #3986, which breaks syntax highlighting in objects, as comma is no longer consumed as key-value-pair separator.
It's not the ternary expression, which allows commas, but the for statement, which allows multiple expressions, separated by comma after `in` keyword.
for (var in <expr>, <expr>, ...)
expr: any valid expression, maybe ternary, maybe function-call
The change to ternary expressions is reverted and for-condition context is modified instead to allow multiple expressions after `in` keyword.
Also scope `;` invalid if there are too many.
> [JavaScript] Fix regression with ternary operators

- PHP/PHP Source.sublime-syntax
- PHP/tests/syntax_test_php.php
Fixes #4026
Implements RFC https://wiki.php.net/rfc/throw_expression
Note: Creates an `expression_keywords` variable to group it together with other expression-level keywords.
> [PHP] Modify `throw` to an expression keyword

- Batch File/Batch File (Compound).sublime-syntax
- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
This PR applies tokenization rules from https://stackoverflow.com/questions/4094699/how-does-the-windows-command-interpreter-cmd-exe-parse-scripts/4095133#4095133 to labels and common command arguments.
As a result invalid labels are scoped "ignored" even without dedicated comment contexts and less special-casing patterns. They are however kept to maintain `comment.line` scopes for now.
Delimiter characters such as `=` are ignored, which fixes scoping of somewhat uncommon but valid labels like `:=== label ===`.
Delimiter chars are scoped `punctuation.separator` if not having any other special meaning (e.g.: `=` `keyword.operator.assignment`) depending on context.
Accuracy of various tokens - including some odds of batch - is increased to match highlighting better to interpreter's …
> [Batch File] Refactor labels and label-like comments

- JavaScript/Default.sublime-keymap
- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_template.js
This PR...
1. scopes tagged template strings `meta.string.template` to give all of them a common scope without regards of used syntax highlighting
2. uses that scope in key bindings' selectors to enable them in syntax highlighted tagged templates.
3. restrict ` to JavaScript strings by enforcing scope order in selectors in binding 1 and 2
4. merge "selector" keys in binding 3 and 4
It fixes no longer working key bindings in syntax highlighted tagged templates, regressed by #4019.
> [JavaScript] fix tagged template string key bindings regression

- CSS/Default.sublime-keymap
This command matches the *Edit > Text > Insert Line After* menu item and so it will show the incorrect keybinding (`enter` instead of `ctrl+enter`).
To fix this we can simply make the command not match the one in the menu. The `"hide_from_menu"` is not functional.
> [CSS] Don't show incorrect keybinding in menu

- ASP/syntax_test_asp.asp
- HTML/HTML.sublime-syntax
- HTML/Indentation Rules - Comments.tmPreferences
- HTML/Indentation Rules.tmPreferences
- HTML/syntax_test_html.html
- HTML/syntax_test_html_indentation.html
- Rails/tests/syntax_test_rails.html.erb
This PR...
1. teaches HTML to consume
- any trailing whitespace until end of line after opening script/style tags or optionally following `` punctuation.
to not apply embedded syntax's scope after standalone opening or in front of standalone closing tags.
This change makes sure to ...
- always apply HTML specific indentation rules to enclosing script/style tags or comment punctuation.
- apply custom background highlighting of embedded syntaxes only on full lines, but not after or in front of standalone tags.
2. modifies indentation rules for HTML comments to ignore indentation of comments' content.
This is primarily required to correctly handle indentation of embedded script/style source code, if it is enclosed in HTML comments. In such cases, additional indentation level is probably …
> [HTML] Tweak embedded script/style code boundaries and comment indentation

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#11.cs
See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/file
The `file` is the keyword of type modifier as the type visibility.
> [CSharp] Add the C# 11 type modifier `file` feature support

- JavaScript/Embeddings/CSS (for TS template).sublime-syntax
- JavaScript/Embeddings/HTML (for TS template).sublime-syntax
- JavaScript/Embeddings/JSON (TS template).sublime-syntax
- JavaScript/Embeddings/JavaScript (TS template).sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_typescript_template.ts
This PR...
1. creates separate embedded syntaxes for tagged template strings, used in TypeScript to ensure TypeScript being used in interpolations.
2. improves extensibility of tagged template strings by providing a single context to add further variants of tagged templates to. This may help 3rd-party packages to more easily add features.
> [JavaScript] Separate tagged template strings for TypeScript

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
This commit removes `invalid.illegal` scope from unsupported escape sequences.
Actually `\` is interpreted literal if it doesn't start a supported escape sequence.
The following is a valid string without illegals:
```java
new Source("src\main\java\com\example\application\views\HomeView.java")
```
> [Java] Fix literal backslash in strings

- JavaScript/Indentation Rules - JSX.tmPreferences
- JavaScript/Indentation Rules.tmPreferences
- JavaScript/tests/syntax_test_jsx_indent.jsx
This commit adds dedicated JSX indentation rules inspired by those from HTML, but with some simplifications and adjustments required for JavaScript.
> [JavaScript] Add JSX indentation rules

- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_control.js
Fixes #4042
This commit ensures, `expression` contexts starts with first non-whitespace.
> [JavaScript] Fix expression starts

- Go/Go.sublime-syntax
- Go/tests/syntax_test_go.go
Fixes #4044
This commit improves format string placeholder pattern precision to reduce risk of false positives by strictly following language specifications.
Note: It also restricts supported `verbs` to those found at https://pkg.go.dev/fmt.
> [Go] Fix string placeholders

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit adds scopes for `e`, `pi`, `infinity` and `NaN` constants in calc().
see: https://developer.mozilla.org/en-US/docs/Web/CSS/calc#formal_syntax
> [CSS] Add patterns to scope calc() language constants

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit adds scopes to highlight round() strategies.
Note:
round() uses common `calc-function-arguments-content` context, so these keywords are also highlighted in other functions, they don't have special meaning in.
IMHO, chances to run into conflicts are however too low to justify a new dedicated context for round() arguments.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/round#rounding-strategy
> [CSS] Add rounding strategy keywords

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This commit fixes custom property definitions with declaration-list values.
Custom properties...
1. can take all sorts of values.
2. never start a selector.
Without this commit, leading `--` is ignored and custom property name being consumed as html tag, starting a selector.
> [CSS] Fix custom property definitions

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
This commit scopes `cls` and `self` special in parameter lists, to enable highlighting them as their references in function bodies.
> [Python] Scope self and cls in function parameter lists

- JavaScript/TypeScript.sublime-syntax
This commit adds counter-parts for JavaScript's `*.cjs` and `*.mjs` file extensions to Typescript.
> [JavaScript] Assign typescript to *.cts and *.mts extensions

- PHP/Embeddings/CSS (for PHP double-quoted).sublime-syntax
- PHP/Embeddings/CSS (for PHP single-quoted).sublime-syntax
- PHP/Embeddings/JavaScript (for PHP double-quoted).sublime-syntax
- PHP/Embeddings/JavaScript (for PHP single-quoted).sublime-syntax
This PR makes sure to pop CSS/JS contexts off stack, if quotation mark is matched by customizing relevant CSS/JS contexts only.
By not injecting required lookahead into each context via `prototype`, compiled syntax cache size is reduced by round about 200kB as more contexts share same patterns.
Modified syntax definitions are designed for being included into inline event and style attributes of HTML tags.
Note: This commit does not change behavior, just saves some RAM.
> [PHP] Optimize embedded CSS/JS syntax definitions

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/Completion Rules.tmPreferences
- C++/syntax_test_c.c
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc.m
This adds support for the new #elifdef and #elifndef preprocessor directives that are a combination of #else with #ifdef or #ifndef.
C++, Objective-C, and Objective-C++ are also updated because they derive from the C syntax family as well.
This has already made it into recent C and C++ compilers and is part of the C23 and C++23 standards.
> [C] Add support for new preprocessor directives

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc.m
This adds support for the new #embed preprocessor directive that can be used to directly include binary files into program variables without the use of external code generators.
C++, Objective-C, and Objective-C++ are also updated because they derive from the C syntax family as well.
This has already made it into recent C and C++ compilers and is also part of the C23 standard.
> [C] Add support for binary file inclusion preprocessor directive

- JavaScript/JSX.sublime-syntax
- JavaScript/TSX.sublime-syntax
Addresses https://github.com/sublimehq/sublime_text/issues/6498
This commit restricts JSX tag matching to avoid infinite loops, caused by invalid syntax, which is still recognized as potential JSX content, but may cause heavy backtracking due to unmatched tags.
With this commit `<` is expected to be followed by either a valid jsx-tag-name or tag-end punctuation on the same line to be consumed as jsx tag.
> [JavaScript] Fix infinite loop caused by diff conflict markers

- C++/C.sublime-syntax
- C++/syntax_test_c.c
It was added in C23 and is effectively an alias for the NULL macro already in use, so it is just treated as an alias for the existing null constant.
> [C] Add support for nullptr keyword

- C++/C.sublime-syntax
- C++/syntax_test_c.c
This was first added in C11 but has since been revised by C23. It functions like sizeof in that it takes an argument as if it were a function so we implement it as an extension of sizeof.
> [C] Add support for static_assert and its aliases

- C++/C.sublime-syntax
This was added in C23 alongside binary integer constant support, which is already implemented though this was still missing.
> [C] Add %b scanf/printf support

- C++/C Standard Includes.sublime-completions
There's two new headers defined C23, stdbit.h and stdckdint.h.
> [C] Add completions for C23 headers

- C++/C.sublime-syntax
I overlooked this previously but I believe this is an optimization for sizeof that would also apply these two that I previously added.
> [C] Update keywords-parens for alignof and static_assert

- XML/Snippets/xml-cdata.sublime-snippet
- XML/Snippets/xml-declaration.sublime-snippet
- XML/Snippets/xml-long-tag.sublime-snippet
- XML/Snippets/xml-model.sublime-snippet
- XML/Snippets/xml-short-tag.sublime-snippet
- XML/Snippets/xml-stylesheet.sublime-snippet
This commit makes sure to only provide XML tag snippets in top-level contexts by excluding them from `meta.tag`, comments, strings and possible embedded or interpolated expressions.
Inspired by PR #4056
> [XML] Restrict tag snippets

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
This adds the types defined by stddef.h, wchar.h, and uchar.h. Some of these types were first defined by C++ but are now defined by C11 or C23 so we will defer to C instead now.
> [C] Add more standard types from ISO C

- C++/C.sublime-syntax
- C++/syntax_test_c.c
This was originally added in C11. It is an optional feature but is often available due to being related to threads. It can be as a type qualifier like const or as a type specifier like typeof. It is implemented under both syntax rules to reflect this.
> [C] Add C11 _Atomic type qualifier and specifier

- HTML/html_completions.py
This commit modifies `script` and `style` tag completions by removing automatic insertion of `type=""` attributes.
Motivation:
HTML5 treats content of script tags as JavaScript and those of style tags CSS by default, if optional `type` attribute is missing.
With completions for attributes and type attribute value being available, it is probably better not bother users with obsolete attributes, which are most likely removed anyway.
> [HTML] Simple script and style completions

- C++/C.sublime-syntax
- C++/syntax_test_c.c
This is implemented like typeof() because it can only be used with ()s to indicate how many bits the resulting integer type will have.
While I was at it, I also added support for the new suffixes for _BitInt integer constants.
> [C] Add support for C23 _BitInt type

- C++/C.sublime-syntax
- C++/syntax_test_c.c
These were first defined in stdatomic.h in C11 and expanded on in C23. They're just atomic type aliases for a bunch of standard integer types.
> [C] Add atomic type aliases

- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This commit fixes an syntax highlighting issue with `$#var` in ZSH.
In Bash `${#var}` is required to return length os a variable. 
In Zsh however `$#var` overrides special `$#` expansion.
> [ShellScript] Fix variable length expansions

- C++/C.sublime-syntax
- C++/syntax_test_c.c
This includes most typedefs or macro type aliases from ISO C headers from C99, C11, and C23. A few from time.h were not included because they're just structs and not typedefs.
> [C] Add more ISO C types

- C++/C.sublime-syntax
- C++/syntax_test_c.c
- Objective-C/syntax_test_objc.m
This was introduced in C23 and adds support for the new type keywords, the new suffixes for the new types, and the new length modifiers for printf and scanf.
Furthermore, the existing matching rules for floats was changed to remove the possibility of '1f' being classified as a floating point literal. This is actually considered to be an integral literal with an invalid suffix instead of a floating point literal by all compilers that I know of and such produces compiler errors if such code is compiled.
> [C] Add support for decimal floating-point types

- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
In batch scripts (but not on the command line itself), `%` is only escaped by another `%`
You can test this by making a bat file that reads:
```
@echo off
setlocal
set var=A
if ^A==A echo test1
if ^%var%==A echo test2
if "^A"==^"^^A^" echo test3
if "^%var%"==^"^^%var%^" echo test4
if "^%%var%%"==^"^^%%var%%^" echo test5
endlocal
pause
```
> [batch] prevent ^ from counting as an escape for %

- C++/C++.sublime-syntax
- C++/C.sublime-syntax
- C++/syntax_test_c.c
- C++/syntax_test_cpp.cpp
- Objective-C/Objective-C++.sublime-syntax
- Objective-C/Objective-C.sublime-syntax
- Objective-C/syntax_test_objc++.mm
- Objective-C/syntax_test_objc.m
Function parameter names are now optional in C and C++. Previously the syntax highlighting rules would assume that the last identifier found in a parameter was the parameter name but this was making it impossible to properly highlight parameters without a parameter name.
The only solution I could find was to include the specific types and modifiers before the more general match for the parameter name. With this, the types and modifiers are no longer mistaken for a parameter name.
> [C] Make function parameter names optional

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This PR...
1. fixes image tags not being recognized if name contains
- backslashes
- code spans with content like ``` `` ```
2. optimizes patterns and fixes some possible backtracking issues 
Syntax test file is parsed 7% faster.
caused by https://github.com/SublimeText-Markdown/MarkdownEditing/issues/778
> [Markdown] Fix image tags

- JavaScript/Embeddings/SQL (for JS template).sublime-syntax
- JavaScript/Embeddings/SQL (for TS template).sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_js_template.js
- JavaScript/tests/syntax_test_typescript_template.ts
This is useful for server-side JS.
Especially using one of the following libraries:
https://github.com/felixfbecker/node-sql-template-strings
https://github.com/blakeembrey/sql-template-tag
https://github.com/XeCycle/pg-template-tag
Using `version: 1` for the Embedding syntaxes since they need to match the inherited `SQL.sublime-syntax`.
It does not currently handle interpolation inside SQL strings.
--- 
~~The SQL template is detected but the SQL syntax highlighting is not performed (`source.sql.embedded.js` is the deepest scope anything within the template string gets).~~
**Edit:** If I change `extends: Packages/SQL/SQL.sublime-syntax` to `CSS.sublime-syntax` in `SQL (JS template).sublime-syntax`, it highlights as CSS correctly.
**Edit2** It was caused by a differing version.
> [JavaScript] Add SQL embedding

- ShellScript/Bash.sublime-syntax
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This commit implements different sets of case clause terminators supported by each shell script dialect:
- Bash: `;;`, `;&` and `;;&`
- ZSH:  `;;`, `;&` and `;|`
> [ShellScript] Fix ZSH case clause termination

- README.md
add advice to use ST's entire package replacement feature of having an Installed Package with the same name as a shipped package to avoid confusing problems where out-of-date files are still unexpectedly picked up by ST.
> [README] add tip to fix confusing problems when renaming/removing files

- C++/C.sublime-syntax
This updates hexadecimal floats to follow a design similar to the new decimal float syntax. As a byproduct of the update, it also now matches the latest suffixes added in more recent C standards.
> [C] Revise hexadecimal floats

- HTML/Snippets/html (begin tag).sublime-snippet
- HTML/Snippets/html.sublime-snippet
This PR disables `html` snippet in ...
- comments
- literal or interpolated strings
- embedded or interpolated code blocks (from template languages)
- HTML tags
- Markdown files (but not in fenced code blocks)
Using `- text.html <scope>` in order to only exclude scopes belonging to possibly embedded HTML code block in question.
This is required to enable snippets if HTML is embedded in `source` code,
source.astro text.html
but disable it in embedded CSS/JS or any other source code.
text.html source.css
This PR is related with and triggered by https://github.com/SublimeText/Astro/issues/10 as an example of why it is important to correctly prefix negative scopes.
> [HTML] Restrict main HTML snippet

- Go/Go.sublime-syntax
- Go/tests/syntax_test_go.go
Addresses some issues described in #3512 with least effort.
It may not address all theoretical edge cases though.
Especially Go's meta scopes don't follow guidelines by any means, so seriously fixing issues would probably end up in significant refactoring, which is not scope of this PR.
Primary goal is to support nested generics to certain amount of complexity and correctly highlight generic function/method calls, which are visually most obvious issues.
> [Go] Improve generic type support

- SQL/MySQL.sublime-syntax
- SQL/PostgreSQL.sublime-syntax
- SQL/SQL (basic).sublime-syntax
- SQL/TSQL.sublime-syntax
This commit excludes `prototype` from various contexts which expect special tokens. It's unlikely or even unwanted to match arbitrary patterns there. It finally saves a couple of bytes in compiled inherited syntaxes.
> [SQL] Exclude prototype from more contexts

- .github/workflows/ci.yml
Workaround for https://github.com/sublimehq/sublime_text/issues/6539 until it is fixed upstream.
> [CI] Lock syntax test runner to build 4183

- Graphviz/DOT.sublime-syntax
`.dot` is shared with Microsoft Word. `.gv` is less ambiguous.
The downside is people who (conceivably) have created build systems where the specific Graphviz renderer used is picked by the file extension. But this doesn't stop those people from saving with their various extensions, mapping them to the Graphviz syntax, and they'll load correctly.
> [Graphviz] Set default file extension to .gv

- C++/C.sublime-syntax
- C++/syntax_test_c.c
- Objective-C/syntax_test_objc.m
C23 added this feature previously available in C++. This should close #3972 as well as both C and C++ now have syntax support for the ' digit separator.
This was implemented by just copying the digit variables from the C++ syntax file as it is the same construct in the end. The existing tests were updated to fix the part of the existing tests were broken by this new feature.
Furthermore, some tests from C++ were adapted for C to add better testing for the new digit seperator. I also included tests for the newer base 2 integer contants. The C file did not have any tests for that yet.
> [C] Add digit separator like is already implemented for C++

- .github/workflows/ci.yml
This reverts commit f99e167a923ce278569b1138733af9b2a6c4fd2c.
ST4185 fixed symbol test failures.
> [CI] Re-enable using latest syntax test runner (#4107)"

- .gitignore
This commit...
1. excludes Default/ and User/ packages
That's useful if whole repository is cloned to `${stdatadir}/Packages` to test/develop all bundled packages in a single ST instance.
Make sure never to add a package with such special name to this repo.
2. excludes known python cache files as they are never to be published, if auto-created by any tool by accident.
> [Common] Add more items to .gitignore

- JavaScript/JSX.sublime-syntax
- JavaScript/tests/syntax_test_jsx.jsx
This PR...
1. scopes jsx string interpolation punctuation `punctuation.section.interpolation`.
2. converts jsx interpolation related anonymous into named contexts.
> [JavaScript] Fix JSX interpolation scopes

- SQL/MySQL.sublime-syntax
- SQL/tests/syntax/syntax_test_mysql.sql
[SQL] [MySQL] support for REPLACE
https://dev.mysql.com/doc/refman/8.4/en/replace.html
also support for INSERT without INTO
https://dev.mysql.com/doc/refman/8.4/en/insert.html
> [SQL] [MySQL] support for REPLACE

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
The safe navigation operator was [added in Ruby 2.3.0](https://docs.ruby-lang.org/en/master/NEWS/NEWS-2_3_0.html#label-Language+changes). (See second bullet. They don't have direct links to each change.) More [usage samples](https://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/).
Fixes #3813
> [Ruby] Safe accessor

- HTML/HTML.sublime-settings
This PR updates default HTML completions selector to...
1. enable auto completions if HTML is embedded in source code
Current `text.html - source` disables completions if HTML is embedded, resulting in a scope like `source.astro text.html`.
2. but still disable them in embedded CSS/JS/JSON/... source code
by `text.html - text.html source`
3. disable them in embedded/interpolated template tags
4. merge Markdown specific selectors into first line
by `text.html ... - (text.html.markdown - markup.raw.code-fence text.html)`
in order to avoid duplicating all negative selectors again.
For those who want HTML tag completions in Markdown, they can remove that part.
This PR addresses https://github.com/SublimeText/Astro/issues/10 as an example of why it is important to correctly prefix negative …
> [HTML] Fix auto completion selectors

- JavaScript/JSX.sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/TSX.sublime-syntax
- JavaScript/TypeScript.sublime-syntax
- JavaScript/tests/syntax_test_jsx.jsx
- JavaScript/tests/syntax_test_tsx.tsx
- JavaScript/tests/syntax_test_typescript.ts
Fixes #4112
This PR refactors JSX/TSX tag related contexts and arrow function detection to improve reliability, maintainability and fix some possible causes of former lockups as well as a conflict with generic arrow functions using constant type parameters.
It's a bit of fixing and cleaning.
Parsing performance is more or less unaffected.
> [JavaScript] Fix const arrow functions in TSX 

- Rust/Rust.sublime-syntax
- Move patterns to variables.
- Split types (struct, enum) vs traits vs enum instances.
- Add missing types from 2021 prelude.
- Add more commonly used types and traits of the std lib (which are maintained in separate variables).
> [Rust] Revise list of default types

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#11.cs
.NET 7 introduced the [`GeneratedRegex` attribute](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators#source-generation). This PR highlights the first string argument to this attribute as a regular expression.
> [C#] Add support for highlighting GeneratedRegex attributes

- C++/C++.sublime-syntax
- C++/syntax_test_cpp.cpp
Codebases such as Qt or GCC use macros to annotate some class/struct/union.
This patch teaches the C++ syntax highlighter about such constructs, and fixes https://github.com/sublimehq/Packages/issues/3883.
> [C++] Fix issue 3883

- README.md
Since I just had to do this and it's not as straight forward as you'd expect, I added instructions for this to the README, seeing how this repo is the only one where such a hack would be relevant.
> README: Add instructions on how to create an empty zip file

- Python/Embeddings/RegExp (for Python).sublime-syntax
- Python/tests/syntax_test_python_strings.py
Centralizes named capture group identifiers in a variable. Adds support for capital letters one place they were missing. Adds support for `\g<...>` backref style.
[Relevant documentation in v3.12](https://docs.python.org/3.12/library/re.html#index-18)
Previously included (but now removed) deprecation scopes for non-ASCII capture group identifiers.
> [Python] Regexp backref identifiers

- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#12.cs
- C#/tests/syntax_test_C#8.cs
fixes #4119 
plus converts some anonymous contexts into named contexts
> [C#] support class definitions without a body

- Python/Embeddings/RegExp (for Python).sublime-syntax
- Python/tests/syntax_test_python_strings.py
This commit scopes stray brackets normally as those may appear in partial patterns. Correct parentheses matching is not always possible and causes valid closing brackets to be scoped illegal.
> [Python] no stray parentheses in regexp patterns

- LaTeX/LaTeX.sublime-syntax
- LaTeX/tests/syntax_test_latex.tex
This commit
1. adds support for `\begin{IEEEeqnarray}` math environments. 
specified by: https://moser-isi.ethz.ch/docs/typeset_equations.pdf 
inspired by: https://github.com/SublimeText/LaTeXTools/issues/1413
2. fixes `meta.environment.math.block` scope by removing incomplete `.be`.
3. fixes `\\end` scope using `keyword.control.flow.end.latex`.
> [LaTeX] Add support for IEEEarray environments

- LaTeX/Bibtex.sublime-syntax
- LaTeX/tests/syntax_test_bibtex.bib
This PR fixes `@comment` keyword pattern to consume it case-insentitive as all other `@`-keywords are.
> [LaTeX] Fix case-insensitive comment keyword

- C++/C++.sublime-syntax
- C++/syntax_test_cpp.cpp
Adds long-needed concept/constraint support to C++
> [C++] Concept Syntax Highlighting

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
Test file:
```lua
-- SYNTAX TEST "Packages/Lua/Lua.sublime-syntax"
--- doccomment
--[=[
--^ comment.block punctuation.definition.comment.begin
commented
--^ comment.block
]=]
--<- comment.block punctuation.definition.comment.end
local a
--    ^ variable.other
```
> [Lua] Fix block comments after doc comments

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua_support.lua
`_ENV` was new in Lua 5.2.
`__name` was new in Lua 5.3.
`warn` and `__close` were new in 5.4.
> [Lua] Add more builtins

- JavaScript/Embeddings/HTML (for JS template).sublime-syntax
- JavaScript/Embeddings/HTML (for TS template).sublime-syntax
- JavaScript/Embeddings/JavaScript (for JS template).sublime-syntax
- JavaScript/Embeddings/JavaScript (for TS template).sublime-syntax
- JavaScript/JavaScript.sublime-syntax
- JavaScript/tests/syntax_test_js_template.js
This commit...
1. ensures to terminate syntax highlighted tagged template string only by non-escaped backticks.
2. removes syntax highlighting from nested tagged template strings as it can't be correctly handled using `embed..escape`.
A "nested tagged template string" is a template string enclosed by escaped backticks.
Note: tagged template strings can't really be nested.
3. Drop shebang from dedicated tagged template JS syntax as it is not needed
4. Restrict inline JS syntax in HTML to "expressions".
Goal is to reduce risk to break syntax highlighting caused by embedded html/js syntax adding tagged template strings.
> [JavaScript] No highlighting in nested tagged template strings

- Markdown/Markdown.sublime-syntax
- Markdown/tests/syntax_test_markdown.md
This commit fixes github alerts not being scoped as such, if heading is indented by more than one space.
Heading may be indented by up to _1 + 3 spaces_ or _1 space + 3 tabs_.
> [Markdown] Fix Github alert heading indentation

- CSS/CSS.sublime-syntax
- CSS/syntax_test_css.css
This PR ...
1. fixes #4151, caused by premature termination of identifiers with escaped characters
2. fixes ascii alphanumeric patterns in identifiers (as `[:alpha:]` consumes all unicode alphanumerics)
> [CSS] Fix escaped identifiers

- HTML/HTML (Plain).sublime-syntax
This PR uses `{{tag_name_start}}` variable in _HTML (Plain)_ in favor of hard coded patterns to enable extending syntaxes to override it.
> [HTML] Use variable for tag name lookaheads

- SQL/MySQL.sublime-syntax
- SQL/SQL (basic).sublime-syntax
- SQL/tests/syntax/syntax_test_mysql.sql
- support charset in return types
- support $$ as a statement terminator
- support `SET` ... `:=` syntax
- support `SET` with system variable assignment
> [SQL] improve MySQL syntax

- JavaScript/Snippets/Get-Elements.sublime-snippet
- JavaScript/Snippets/Object-Method.sublime-snippet
- JavaScript/Snippets/Object-Value-JS.sublime-snippet
- JavaScript/Snippets/Object-key-key-value.sublime-snippet
- JavaScript/Snippets/Prototype-(proto).sublime-snippet
- JavaScript/Snippets/for-()-{}-(faster).sublime-snippet
- JavaScript/Snippets/for-()-{}.sublime-snippet
- JavaScript/Snippets/function-(fun).sublime-snippet
- JavaScript/Snippets/function.sublime-snippet
- JavaScript/Snippets/if-else.sublime-snippet
- JavaScript/Snippets/if.sublime-snippet
- JavaScript/Snippets/setTimeout-function.sublime-snippet
Fixes #4157
This commit...
1. enables JS snippets for TypeScript and JSX/TSX.
2. renames if-else snippet file to remove long underscores
> [JavaScript] Enable snippets for all dialects

- Java/Java.sublime-syntax
- Java/tests/syntax_test_java.java
Fixes #4162
This commit avoids contextual keyword `record` being matched in unappropriated context. It is a valid keyword only in record declarations.
A record declaration is treated as valid if it starts with `record ident`, terminated by a `{..}` block. Anything in between is treated optional.
see: https://docs.oracle.com/javase/specs/jls/se23/html/jls-3.html#jls-3.9
> [Java] Restrict contextual keyword `record`

- Diff/Diff.sublime-syntax
- Diff/tests/syntax_test_diff.diff
This PR...
1. restricts merge conflict markers to exactly 7 consecutive chars (e.g. `<<<<<<<` or `>>>>>>>`) according to https://www.gnu.org/software/diffutils/manual/diffutils.html#Generating-the-Merged-Output-Directly
If less chars, it's not invalid, but just no conflict marker.
2. ensure reference names are separated from markers by at least one whitespace
These changes are required to reduce risk of ambiguities with headings in Markdown and Restructured Text.
This is an attempt to avoid existing syntax tests failing, when merging current master into #4047.
> [Diff] Fix conflict markers

- Git Formats/Git Commit.sublime-syntax
- Git Formats/Git Diff.sublime-syntax
- Git Formats/tests/syntax_test_git_commit
This commit...
1. uses _Git Diff.sublime-syntax_ to highlight verbose diffs at the end of commit messages (fixes #4172)
2. adds support for c/ i/ and w/ path prefixes (fixes #4173)
> [Git Commit] Fix verbose diff highlighting

- PHP/Indentation Rules.tmPreferences
- PHP/tests/syntax_test_indentation.php
This PR...
1. fixes indentation after `else if ():` as follow-up for #1932
2. removes unsupported `indentNextLinePattern` rule
3. tweaks comment positions
revealed while trying to re-produce https://forum.sublimetext.com/t/php-syntax-html-in-if-else-reindent-problem/70376/2
> [PHP] Fix indentation rules

- Lua/Lua.sublime-syntax
- Lua/tests/syntax_test_lua.lua
The syntax now handles multi-global statements correctly.
```lua
a, b = c, d
--   ^ punctuation.separator.comma
--          ^ punctuation.separator.comma
```
> [Lua] Handle multi-global statements

- Git Formats/Git Config - Fold.tmPreferences
- Git Formats/Git Config - Symbol List.tmPreferences
- Git Formats/Git Config.sublime-syntax
- Git Formats/tests/syntax_test_git_config
This PR...
1. simplifies `meta.section` scope, by only applying it to `[...]` lines
2. changes section bracket scopes to `punctuation.section.brackets` to comply with scope naming guidelines
3. changes key scopes to `meta.mapping.key string.unquoted`
Note: Sub-sections are also scoped `entity.name.section string`, which is something we are facing with TOML as well. Luckily `key` question is easier here as only unqualified unquoted keys are allowed.
> [Git Config] Some scope tweaks

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
fixes #4184
This commit removes `source.python.embedded` scope from f-string replacements as this causes ST to treat it as external syntax, which prevents word-completions of e.g. variables from being suggested.
> [Python] Fix completions in f-string replacement

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_generics.rs
This adds support for the `+ use<>` precise capture syntax to Rust which was introduced in Rust 1.82.
[Documentation](https://doc.rust-lang.org/nightly/reference/trait-bounds.html)
> [Rust] Add `+ use<>` syntax

- Go/Go.sublime-syntax
- Go/tests/syntax_test_go.go
Fixes #4188
This commit adds back `%w` placeholder, which is a special kind of `%v` and pretty well hidden in official syntax specs.
> [Go] Fix %w format string

- OCaml/OCaml.sublime-syntax
- OCaml/syntax_test_ml.ml
Fixes #1756
This PR proposes to partly apply the change proposed in the issue to fix infix operator definitions as it seems safe enough not to break something.
_Note: The first mentioned issue about function definitions seems to work in ST 4131._
> [Ocaml] Fix infix definitions

- Python/Python.sublime-syntax
This will work for the mostly UNIX-compatible way of specifying multiple arguments via `env -S` and then using the new inline script metadata PEP that uv implements.
Most widely used variant:
#!/usr/bin/env -S uv run --script
See also https://docs.astral.sh/uv/reference/cli/#uv-run
Note that apparently Windows users can also use this with the `py` launcher and a slightly different shebang, or at least I have seen examples of this online. All examples I've seen include `\buv\b` though.
> [Python] Recognize shebangs with `uv`

- Scala/Scala.sublime-syntax
- Scala/syntax_test_scala.scala
- Scala/syntax_test_scala3.scala
This commit tweaks string and interpolation related scopes after the scheme of Python and ShellScript.
1. from python use `meta.string.interpolated` and `string.quoted.double.block`
2. from shell use interpolation scopes.
Scope guidelines request `punctuation.section.interpolation.[begin|end]`, but `$` variables are historically scoped `punctuation.definition.variable`.
This commit (as shellscript) attempt to satisfy both.
Hence `$` in `${}` is scoped punctuation.definition.variable, which may appear odd in the first place.
Actually `$` is some sort of expansion operator, which adds a variable's or expression's result into containing string. Perl calls it dereferencing operator.
Most core syntaxes supporting that kind of syntax struggle with it, currently.
_TL;TR This commit aligns scopes …
> [Scala] Tweak string and interpolation scopes

- C++/C++.sublime-syntax
This adds support for Arduino `.ino` files which share the same syntax definition as `C++`.
> [C++] Add support for Arduino `.ino` files

- Perl/Perl.sublime-syntax
- Perl/syntax_test_perl.pl
Fixes #4204
This commit implements:
1. https://perldoc.perl.org/perlref#Postfix-Dereference-Syntax
2. https://perldoc.perl.org/perlref#Postfix-Reference-Slicing
> [Perl] Add postfix dereference syntax

- Markdown/Markdown.sublime-syntax
This commit renames TOML frontmatter punctuation scopes to align them with the other types.
_Note: This was a copy & paste error when transferring patterns from MarkdownEditing._
> [Markdown] Fix frontmatter punctuation scope

- Python/Python.sublime-syntax
- Python/tests/syntax_test_python_strings.py
This PR modifies raw triple-quoted string related contexts to automatically use/include regular expressions with extended mode enabled.
It assumes triple-quoted (multi-line) strings mainly containing sophisticated patterns used in conjunction with `re.X` flag.
_Notes:_
This PR follows a simpler proposal to handle all triple-quoted strings the same to avoid adding too much complexity.
Another smart proposal to only enable extended mode, if patterns start at the line after opening triple quotes, adds a reasonable amount of extra complexity, while probably not increasing chance to guess right mode enough. Patterns could still start right after opening quotes but still span multiple lines, being targeted for use with `re.X` as well. It would require another lookahead to check for closing …
> [Python] Multi-line string extended regexp mode

- ASP/ASP.sublime-syntax
- ASP/syntax_test_asp.asp
- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_GeneralStructure.cs
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- R/R.sublime-syntax
- R/syntax_test_r.R
- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This PR scopes `in` keywords in loop statements `keyword.operator.iteration`.
Uses "iteration" rather than "iterator" as it is more aligned with "assignment" or "comparison".
This commit is part of an attempt to introduce a single scope for that keyword as various (3rd-party) packages use different ones, like:
-  `keyword.control.flow`
-  `keyword.control.loop.for.in`
-  `keyword.operator`
-  `keyword.operator.logical`
-  `keyword.operator.in`
-  `keyword.operator.iterator`
-  `keyword.operator.iteration`
-  `keyword.other.in`
3rd-party packages known to already use proposed scope:
- CoffeeScript
- Jinja2
- Liquid
- Ngx HTML
- PostCSS
- Sass
- Twig
- XSL
> [Common] Scope `in` iteration

- Python/Python.sublime-syntax
- Python/tests/syntax_test_scope_tstrings.py
This PR implements [PEP750](https://peps.python.org/pep-0750/) t-strings, which are a generalization of [PEP701](https://peps.python.org/pep-0701/) f-strings and share same syntax.
> [Python] Add support for PEP750 t-strings

- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 4
This PR removes special treatment of `autoload´ command as arguments can be any kind of glob string. Any effort to support globs while maintaining proper function name highlighting is probably beyond what's useful.
> [ZSH] Fix globs in autoload arguments

- ShellScript/Bash.sublime-syntax
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 1
This commit fixes parameter/variable identifier patterns to comply with section 15.1 of ZSH language specification.
A parameter has a name, a value, and a number of attributes. A name may be
any sequence of alphanumeric characters and underscores, or the single
characters ‘*’, ‘@’, ‘#’, ‘?’, ‘-’, ‘$’, or ‘!’. A parameter whose name
begins with an alphanumeric or underscore is also referred to as a
variable.
Variables consist of alphanumeric characters and thus can even start with
numeric characters.
Bash's `identifier` and `variable` patterns are tweaked in order to be able to implement different ZSH behavior by overriding a single variable, only.
Various tests are added to verify this pattern not only in variable assignment statements but also parameter …
> [ZSH] Fix parameter identifier pattern

- ShellScript/Bash.sublime-syntax
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 2 and 5
This PR...
1. removes normal interpolation/expansions within parameter expansion flags' arguments
2. adds limited variable expansion within flag arguments if `p`-flag is set
3. fixes `q+` and `q-` flags
> [ZSH] Fix expansion in parameter expansion flags

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This PR...
1. adds support for binary numbers (`0b` prefix) in ZSH
2. properly scopes `base#` in Bash and ZSH.
> [ShellScript] Improve number base prefixes

- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This PR addresses #4244 issue 11
The `##` returns following literal character to its numeric representation.
The `#` returns numeric representation of (immediately) following variable's first character.
Valid only within arithmetic expressions.
> [ZSH] Add operator for numeric representation of characters

- SQL/PostgreSQL.sublime-syntax
- SQL/tests/syntax/syntax_test_postgres.psql
[reported on the forum](https://forum.sublimetext.com/t/sql-syntax-highlighting-doesnt-recognize-double-dash-with-no-space-after-it-as-comments/76241?u=kingkeith)
> [SQL] Fix: Postgre comments don't need a space after the double dash

- ASP/ASP.sublime-syntax
- ASP/syntax_test_asp.asp
- Batch File/Batch File.sublime-syntax
- Batch File/tests/syntax_test_batch_file.bat
- C#/C#.sublime-syntax
- C#/tests/syntax_test_C#7.cs
- C#/tests/syntax_test_GeneralStructure.cs
- Python/Python.sublime-syntax
- Python/tests/syntax_test_python.py
- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh/tests/syntax_test_scope.zsh
This is a follow-up to #4227 (1e76a91), which introduced this new
unified `keyword.operator.iteration.in` scope. However, this `in` is a
keyword that is used in loop statements and not an operator and should
thus be scoped similar to `keyword.control.loop.for`. I opted to simply
replace `for` with `in` in the above as it allows for sufficient context
of the (loop-related control flow) keyword while not binding it to the
`for` like it was used in some instances before.
This "new" scope is already used by the Terraform third-party package:
https://github.com/SublimeText/Terraform/pull/86
> [Common] Scope `in` as `keyword.control` again

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
This commit fixes first `~` after `==` or `!=` operator not being scoped tilde-expansion.
Verified with following code by replacing `username` with current user.
```
a=/home/username/Bin
[ $a = ~/Bin ] && echo yes
```
> [ShellScript] Fix missing tilde expansion in test expressions

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 3
This PR...
1. implements subscripts with branching to heuristically distinguish indexed array item access from key based access of associative array items.
Branches try to ...
1. match subscript flags followed by patterns or plain text (only ZSH)
2. match valid arithmetic expressions
3. fallback to plain string subscripts
Expressions related contexts have been slightly refactored to re-use most
parts in subscripts while accounting for unique bailout requirements aka.
failing related branch in case of illegal syntax being found.
2. restricts patterns to consume at most one subscript bracket pair after each parameter name to comply with language behavior.
This change involves pushing a dedicated context to consume simple variable expansions (e.g. `$var`) onto stack …
> [ShellScript] Add Zsh subscript flags

- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 10
This PR ensures to properly terminate Zsh glob flag arguments' expressions as soon as the matching quotation character is consumed.
Luckily `embed` can be used to ensure proper bailout with least efforts.
Note: An additional `immediately-pop` context is pushed onto stack together with `zsh-modifier-expression` to workaround ST core issue https://github.com/sublimehq/sublime_text/issues/4069 and properly apply parent meta scopes to tokens consumed by `escape_captures` pattern.
> [ZSH] Fix glob flag argument bailout

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4272 / no bare glob qualifiers in compound tests
This PR refactors built-in `test ...` and `[ ... ]` as well as compound `[[ ... ]]` test expressions to apply more detailed parsing rules, which follow more closely closely to language specifications and shell parsing behavior.
This fixes various edge cases and enables more fine gained and accurate highlighting.
Parsing performance isn't affected by this change, syntax cache size is also nearly unchanged.
For details, please refer to commit messages.
Some highlights:
- highlight math expressions before and after `-eq` and friends
- support some of Bash/Zsh's insanity
- compare two redirections
- fix arbitrarily nested groups in expressions
- no bare globs in compound tests
- various other fixes
> [ShellScript] Improve built-in and compound test expressions

- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Addresses #4244 issue 9
This PR pushes dedicated contexts onto stack to ensure braces are balanced in shell words, thus `hello{world}` is consumed as single word without final `}` being scoped stray.
Note:
ZSH treats `{` and `}` as "metachar", which terminate shell words. Additionally it tracks balanced braces within words. Thus `Hello{world}` is a single word, but final closing brace in `Hello{world}}` is stray.
This rule has already been applied to glob flags/qualifiers and subscripts. This commit extends implementation to all other shell word handling contexts.
> [ZSH] Ensure balanced braces in shell words

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
- ShellScript/Zsh.sublime-syntax
- ShellScript/Zsh/tests/syntax_test_scope.zsh
Resolves #4301
This PR adds support for
1. zsh specific array arithmetic
- ${name:|arrayname}
- ${name:*arrayname}
- ${name:^arrayname}
- ${name:^^arrayname}
2. zsh specific substitution operator `:/`
- ${parameter:/pattern/repl}
3. bash specific case toggle operator `~` and `~~`
- ${parameter~pattern}
- ${parameter~~pattern}
see: https://flokoe.github.io/bash-hackers-wiki/syntax/pe/#case-modification
4. removes tilde expansion in case conversion patterns
> [ShellScript] Add missing parameter expansion substitution operator

- ShellScript/Bash.sublime-syntax
- ShellScript/Bash/tests/syntax_test_scope.bash
> [ShellScript] Fix comments after line continuation

- Git Formats/Git Rebase.sublime-syntax
- Git Formats/tests/syntax_test_git_rebase
Resolves #4311
This PR overhauls git rebase command related contexts.
1. All use same implementation scheme. 
2. Lines with unknown or invalid commands are no longer highlighted as any assumption about structure may be wrong.
3. A simple command keyword is enough to start highlighting a line, regardless valid arguments being fully present. May improve UX while editing commands.
4. Commit subject text after commands like `pick 12b32` are scoped comment as changing them doesn't effect commit messages when rebasing.
5. Each command line is terminated by a dedicated simple comment context, which ensures not to scope help commands etc. by accident.
6. Reference names' highlighting is extended by scoping `/` path separators and various illegal chars.
> [Git Formats] Refactor git rebase commands

- Rust/Rust.sublime-syntax
- Rust/tests/syntax_test_control_flow.rs
```rust
'r#break: {
break 'r#break;
}
```
compare: https://doc.rust-lang.org/stable/reference/tokens.html#lifetimes-and-loop-labels
> [Rust] Add raw-identifier label and lifetime

- HTML/HTML (Plain).sublime-syntax
- HTML/HTML.sublime-syntax
- HTML/tests/syntax_test_scope.html
This commit...
1. adds lazy support for `xml-model`, `xml-stylesheet`, ... prolog tags, primarily because... a) HTML syntax may be used by 3rd-party syntaxes targetting XML processing. b) a prolog tag was found breaking a Markdown document's highlighting.
2. makes prolog tag termination pattern more error resilient by also matching plain `>` as tag close punctuation. This also targets 1b)
3. removes `string` include from prolog tag attributes context, because those behave like normal xml tag attribute contexts - not supporting plain strings.
> [HTML] Fix xml prolog tag scopes

- Markdown/Markdown.sublime-syntax
- Markdown/Symbol List - Reference Link.tmPreferences
- Markdown/tests/syntax_test_markdown.md
This PR...
1. fixes an issue which causes multiple subsequent reference definitions to be listed as one item in Goto Symbol quick panel.
Meta scopes of subsequent reference definitions are separated by excluding each definition's final linefeed from `meta.link.reference.def` scopes, so ST sees them as separate regions.
Implementation requires branching to overcome ST's line blindness, first pushing a context to check next line's content. In case of required termination, context is rolled back to current line's eol before popping its context. That's quite some song and dance, but there's no other solution.
2. aligns reference definitions' implementations in block quotes and other paragraphs, so they exactly match with regards to features and structure.
3. removes possible block quote …
> [Markdown] Fix reference definition symbols

- SQL/MySQL.sublime-syntax
- SQL/tests/syntax/syntax_test_mysql.sql
- ``show table status``  support
- ``json_table`` support
- correctly scope `=` after `set` as an assignment instead of a comparison
> [SQL] various MySQL improvements

- Makefile/Makefile.sublime-syntax
- Makefile/syntax_test_makefile.mak
This fixes syntax highlighting for makefiles (such as [this one](https://github.com/jart/blink/blob/98f95e8383d1032eb4d2dc6aae937b23539e915e/Makefile)) which use `undefine`, which was broken due to partial matching of `define` (missing `\b`).
> [Makefile] avoid partial keyword matches; add `undefine`

- Regular Expressions/RegExp.sublime-syntax
- Regular Expressions/tests/syntax_test_regexp.re
This commit adds support for (?R) operator, which is actually supported by ST's regexp find engine.
> [Regular Expressions] Add pattern for (?R) recursions

- CSS/Indentation Rules.tmPreferences
- CSS/tests/syntax_test_indentation.css
Resolves #4344.
This commit removes attempts to be too smart with regards to finding unbalanced brackets, as it doesn't work reliable enough using single patterns.
Instead just accept trailing block comments after an opening bracket to indent line after.
> [CSS] Simplify indentation rules

- Ruby/Ruby.sublime-syntax
- Ruby/syntax_test_ruby.rb
It was being highlighted as `variable.other.constant.ruby` previously. ~~The Ruby interpreter also allows whitespace after `__END__` (but not before).~~
*edit: I was actually totally wrong about that last part, I had just set up my editor to automatically remove trailing whitespace when testing...*
> [Ruby] fix highlighting of __END__

- Python/Python.sublime-syntax
This is a maintenance commit to avoid unnecessary context switches and reduce syntax size by removing some lookaheads, which are no longer needed in version 2 syntax definitions.
> [Python] Simplify import context structure

- LaTeX/LaTeX.sublime-syntax
- LaTeX/TeX.sublime-syntax
Normalize all section header comments to a length of 80 chars.
> [LaTeX] Fix section header lengths
