sublimehq/Packages

HTML/html_completions.py

This aims at adding the HTML `figure` and `figcaption` elements to the completion file. This is merely a draft, because I have some questions.
According to the Mozilla Developer Network, both elements ([figure](https://developer.mozilla.org/en/docs/Web/HTML/Element/figure#Attributes), [figcaption](https://developer.mozilla.org/en/docs/Web/HTML/Element/figcaption#Attributes)) only include the [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)
I included the ones not marked as experimental but I left out all the event handler attributes, because that would add quite a mess and I'm not sure what's the policy here.
That said, there evolves a bigger question.
> Global attributes are attributes common to all HTML elements; they can be used on all elements, …

Add figure and figcaption HTML elements to completion

---

Batch File/Batch File.sublime-settings
Batch File/Batch File.tmLanguage

In short,
1. Add `cmd` into file extensions.
1. A batch file only works under Windows so we use `\r\n` as the default line ending.
1. It's usual to use `REM` as a comment in a batch file.
Three forum threads are referenced.
http://www.sublimetext.com/forum/viewtopic.php?f=2&p=52597
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=12139
http://www.sublimetext.com/forum/viewtopic.php?f=2&t=13935

Refinement for Batch.

---

Scala/Scala.tmLanguage

This PR adds an assortment of fixes for the Scala mode (including one performance bug fix!).  I've been running with this mode as my primary mode for Scala across several non-trivial codebases for quite some time now, and it works much better than the original.  The exact features are split out into individual commits, so if you don't want one (or more), we can rebase some things away.  I do recommend taking the whole package though.
- `self` isn't a keyword in Scala, though `super` and `this` are
- Type lambdas (e.g. `({ type λ[α] = EitherT[Task, Throwable, α] })#λ`) are a very common pattern in highly abstracted Scala.  I added a bit of syntax highlighting which parses out the boilerplate and highlights it as a comment, while highlighting the rest as a type definition.  This makes …

Scala fixes and features

---

HTML/html_completions.py

**Changes made to html_completions.py**
Changes made to the file are mainly based upon the [HTML element reference](https://developer.mozilla.org/en/docs/Web/HTML/Element) from the Mozilla Developer Network. I did not make changes to tags and/or attributes that are marked as *obsolete* (I did neither remove any obsolete attributes nor add missing ones).
I tested whether the completion works for all tags inside `normal_tags` and it does.
- Adding new/missing tags: `main`, `content`, `data`, `datalist`, `details`, `element`, `embed`, `output`, `picture` (:rocket:), `progress`, `rp`, `rt`, `rtc`, `ruby`, `shadow`, `summary` and `video`
- Adding tags to `get_tag_to_attributes` map (so they get the global attributes)
- Adding HTML5 attributes (`download`, `media`, `ping`, etc.) if applicable
- …

Bring HTML completions to the year 2015 :rocket:

---

YAML/YAML.sublime-syntax
YAML/syntax_test_yaml.yaml

Use first non-empty line to extract indentation level
Empty line inside a block do not pop out of the block

[YAML] Fix end of block detection

---

Ruby/Ruby.sublime-syntax

- Added `fail` keyword
- Allow the regex end punctuation to still include the parent `string.regexp` scope
- Make sure the end `|` in block variable gets a scope. Also added a `meta.variable.block.ruby` scope to the whole block variable section

Improvements to Ruby syntax

---

JavaScript/for-()-{}-(faster).sublime-snippet
JavaScript/for-()-{}.sublime-snippet
JavaScript/function-(fun).sublime-snippet
JavaScript/function.sublime-snippet
JavaScript/if-___-else.sublime-snippet
JavaScript/if.sublime-snippet

- Remove unnecessary semicolons for `for`, `if` & `function()` snippets
- Also ensure consistent code style
This PR should be used instead of #34

Improve some Javascript snippets

---

Lua/Lua.tmLanguage

- Only valid single character escape sequences are now highlighted
- Decimal, hexadecimal, newline, Unicode now all highlight correctly
- Function calls with strings and no whitespace between the argument now highlight correctly
- Hexadecimal literals with decimal places & binary exponents now highlight correctly

Multiple fixes to Lua syntax definition

---

Scala/Scala.tmLanguage

Fixes highlighting issues with triple interpreted strings in scala, eg:
`val foo = s"""Hello, ${friend}"""`
Prior to this fix ST uses the same rules for triple quotes as it does
for single quotes, which means that multi-lines show an error, and you
can trivially break it by adding another quote into the String:
`val bar = s"""Highlighting will " escape"""`
Currently the highlighting breaks like this:
With this change it looks like this:

Support for interpreted triple strings in Scala

---

ActionScript/ActionScript.sublime-syntax
AppleScript/AppleScript.sublime-syntax
C#/Build.sublime-syntax
C#/C#.sublime-syntax
C++/C.sublime-syntax
D/D.sublime-syntax
Erlang/HTML (Erlang).sublime-syntax
Go/Go.sublime-syntax
Graphviz/DOT.sublime-syntax
Groovy/Groovy.sublime-syntax
Haskell/Haskell.sublime-syntax
Haskell/Literate Haskell.sublime-syntax
Java/Java Server Pages (JSP).sublime-syntax
Java/Java.sublime-syntax
Java/JavaProperties.sublime-syntax
LaTeX/LaTeX.sublime-syntax
Markdown/Markdown.sublime-syntax
Matlab/Matlab.sublime-syntax
Objective-C/Objective-C.sublime-syntax
Pascal/Pascal.sublime-syntax
Perl/Perl.sublime-syntax
RestructuredText/reStructuredText.sublime-syntax
ShellScript/Shell-Unix-Generic.sublime-syntax
Textile/Textile.sublime-syntax

As explained in #56, the converter did not consider copying the "captures" dict to the pop pattern that is pushed onto the stack. I altered the conversion script (and made it suitable for command-line use because there were a few flaws with it). For convenience, it's now possible to pass entire directories.
Fixes #56, closes #57.
---
Changes to `Default/convert_syntax.py`:
```diff
--- C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\Default\convert_syntax.py   Tue Jun  2 11:04:30 2015
+++ C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\Default\convert_syntax.py   Mon Jul  6 00:16:43 2015
@@ -1,3 +1,5 @@
+#!/usr/bin/env python3
+
import plistlib
import os
import sys
@@ -9,6 +11,7 @@
def needs_yaml_quoting(s):
return (s == "" or s[0] in "\"'%-:?@`&*!,#|>0123456789="
+ …
```

Add missing captures to pop patterns

---

Ruby/Ruby.sublime-syntax

So that we have have reserved keywords as symbol names like
{
begin: 'begin'
end:   'end'
}
fixes #53

[Ruby] giving symbols a higher precedence than ruby keywords

---

HTML/HTML.sublime-syntax

- Adding scope for the pop rule
- Fixing capture number
I guess the convertor has a bug when calculating the capture numbers in case of 
Regex options like `(?i)`
I've not investigated this though. It's just a guess! 
Example: 
```
- match: (?i:DOCTYPE)
```
Shouldn't have a capture index of 1.

[HTML] Doctype scopes

---

Java/Java.sublime-syntax

ie: In test for anonymous-classes-and-new, ignore 'new' when prefixed with two colons. Fixes problems when using eg: `stream.collect(Collectors.toCollection(ArrayList::new));`

Fix issue #140: Don't match keyword new when used as method reference.

---

PHP/PHP Source.sublime-syntax

The language file for PHP doesn't seem to support the "new" bracket syntax for arrays introduced on PHP 5.4 (http://php.net/manual/en/migration54.new-features.php).
Fortunately, the colouring still mostly works anyway; except when a function argument is typehinted.
This regex change appears to be successful in fixing it on my tests.
Note that I've tried the changes on the tm version; not the sublime one, but the regexes are the same.

Fixes regex parse fail of bracket array syntax.

---

Regular Expressions/RegExp.sublime-syntax

Fixing a bug where the ^ and $ anchors were incorrectly highlighted only when preceded with a backslash

[RegEx] Anchor highlighting bug fix

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Ref: https://github.com/SublimeTextIssues/DefaultPackages/issues/172 which has screenshots etc.
This commit ensures the RHS of an assignment statement is handled as per the code: context, preventing mis-identification of e.g.: method *calls* as if they were method *definitions* when outside of a method.
Also removes a special-case exemption for the keyword `new` as a method name in a method definition, as the new, more conceptually consistent, way should make that unnecessary.

issue 172 - ensure assignment RHS is handled as code

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Fix for issue #118: Restrict the use of the `meta.assignment.rhs.java` scope to the `class-body:` context, by having a separate `class-body-keywords:` context containing a restricted set of keyword matches for use in class-body only (as opposed to generally in code). Then the assignment operator in *there* can have the `meta.assignment.rhs.java` scope and the assignment operator in `keywords:` can revert to what it was before.
Currently `class-body-keywords:` only contains matches for the assignment operator and the semicolon terminator as none of the other matched keywords should appear outside of methods *except* in an assignment RHS.

Fix for issue #118. class-body-keywords context for subset of keyword matches outside methods.

---

README.md

Junctions can be used to selectively override packages.

add info about overriding packages on Windows

---

Groovy/Groovy.sublime-syntax

Gradle [1] is a build system that uses Groovy as its DSL.
[1] http://gradle.org/

Add .gradle files to the list of Groovy extensions

---

Ruby/Ruby.sublime-syntax

Rubyists like their DSLs
see https://github.com/textmate/ruby.tmbundle/blob/master/Syntaxes/Ruby.plist#L40
Yes, View > Syntax > Open all with current extension as... works, but IMO these are common enough to include.
note: prawn is used as *.pdf.prawn

Ruby file extensions

---

PHP/PHP.sublime-completions

There was a missing function for PHP in auto-complete named 'array_column' which is added now.

Added array_column auto-complete

---

HTML/html_completions.py

Some [empty elements](https://developer.mozilla.org/en-US/docs/Glossary/empty_element) are completing with a closing element.
For example `area` is currently completing to:
```html
<area></area>
```
When it should be completing to:
```html
<area>
```
This will fix completions for: `<area>`, `<col>`, `<base>`, `<meta>`, `<hr>`, `<br>`, `<wbr>`, `<input>`.
`meta`'s completion will render as:
```html
<meta charset="utf-8">
^-------------^
Selected Text
```
Which means a `tab` keypress will jump to after the `>`, completing the example or a `delete` keypress will remove the example and allow for another attribute input. This way it's easier to input something other than just the default.

[HTML] Improve completions for empty elements

---

SQL/SQL.sublime-syntax

Hi SublimeHQ! I'm aware that this is a little deficient with respect to pull request guidelines, but I didn't see a sql syntax test to start from. I defer to greater experts than myself on SQL or Sublime as to whether I've done this right, but my goal was to highlight the word "with" as a keyword, and that appears to be working locally over here.

[SQL] Add WITH as a sql keyword

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

Previously, the XML syntax was capturing tag ends for XML Declaration, DOCTYPE, and Entity Declaration but not applying any scopes to them. This patch corrects these occurrences by applying a `punctuation.definition.tag.end` scope before the contexts are popped.

[XML] Add missing scopes for captures

---

Pascal/Pascal.sublime-syntax

dpr files are created by Delphi to store the initial unit, same syntax as pas files, so it should be included.

[Pascal] Added dpr extension

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp

Highlighting digit separators and binary literals per the C++14 standard. Also, highlighting user-defined literals per the C++11 standard. This includes units defined in the STL (h, min, s, etc.) and custom literals defined by users.

[C++] C++14 Digit Separators, Binary Literals, and Units

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

**Renames Quasi literal to Template literal**  
- Renamed literal-quasi definition to literal-string-template
- Renamed all occurences of quasi in scopes to template
- Added test cases
- Scope name changes

[JavaScript] Renames Quasi literal to Template literal

---

Groovy/Comments.tmPreferences

Sublime Text has had a long-standing issue where comments in Groovy
code cannot be toggled with Ctrl+/. The workaround has been to copy
the comments preferences from the Java package and change the
source.java to source.groovy.
One source for the fix:
http://stackoverflow.com/questions/24567263/how-to-enable-groovy-comments-in-sublimetext-3-on-a-mac

[Groovy] Support comment toggling

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

In relation to this question/issue https://github.com/sublimehq/Packages/issues/220
Adds scope for class attribute/value. This should help 3rd party plugins add class completions within HTML files.

[HTML] Adds scope for class attribute/value

---

Rails/Ruby on Rails.sublime-syntax
Rails/syntax_test_rails.rb
Ruby/Ruby.sublime-syntax
Ruby/Snippets/def_initialize.sublime-snippet
Ruby/Snippets/service_object.sublime-snippet
Ruby/syntax_test_ruby.rb

* Add support for some Rails 4 special methods (e.g. `before_action`)
* Fix highlighting when special methods are used as symbols
* Add pattern for constant definitions, apply `entity.name.type` so Go To Definition finds it
* Fix logical operators highlighting: `and`, `or`, `not` could be methods and in that case should not be highlighted.
* Add `prepend` as a special method. It is very similar to `include`.
* Add support for `%I` and `%i`: symbol arrays
* Remove `%S` and `%R` as they are not valid percent expressions
* Block variables can have modifiers (`*` and `&`), recognize these with the same scope as in methods.
* Add support for string formatting literals. E.g. `%s` or `%f`. Code copied for the Go syntax definition.

[Ruby][Rails] Syntax improvements

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

According to the [Custom Elements specification](https://www.w3.org/TR/custom-elements/#concepts), custom element tag names are required to contain a HYPEN-MINUS character.
This pull request adds the ability to match such custom elements properly.
Technically, the specification also requires that the tag names are lower-case, but I guess that would just cause further problems, so it’s easier to just allow dashes in upper- or mixed-case tag names as well.
I hope the weird indentation in the test is not a problem.

[HTML] Add support for custom tags

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css
HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Turns out I didn’t test the custom tag names well enough in #233 and #236. Custom tags that start with a otherwise known tag are not correctly recognized (e.g. `<form-group>`). I’ve added more tests for these cases, and fixed the syntax definitions to give priority to custom tag names first (otherwise I would have to change every other tag name definition).

[HTML/CSS] Fix custom tag names

---

JavaScript/JavaScript.sublime-syntax

Adds the missing `connected` and `release` objects from the process Node.js module.
The contents of the capture group were also sorted.
Both objects are supported in the latest Node.js LTS & Stable releases.
- [process.connected - Node 4.4.0 LTS](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_connected) 
- [process.connected - Node 5.9.0 Stable](https://nodejs.org/dist/latest-v5.x/docs/api/process.html#process_process_connected) 
- [process.release- Node 4.4.0 LTS](https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_release) 
- [process.release- Node 5.9.0 Stable](https://nodejs.org/dist/latest-v5.x/docs/api/process.html#process_process_release)

[JavaScript] Add missing Node.js process objects

---

AppleScript/AppleScript.sublime-syntax
C#/C#.sublime-syntax
CSS/CSS.sublime-syntax
Clojure/Clojure.sublime-syntax
Go/Go.sublime-syntax
Groovy/Groovy.sublime-syntax
Java/Java.sublime-syntax
JavaScript/JavaScript.sublime-syntax
LaTeX/LaTeX.sublime-syntax
Markdown/Markdown.sublime-syntax
Matlab/Matlab.sublime-syntax
OCaml/OCamlyacc.sublime-syntax
PHP/PHP Source.sublime-syntax
Ruby/Ruby.sublime-syntax
Rust/Rust.sublime-syntax
YAML/YAML.sublime-syntax

Fixed all the typos and misspellings that I could find.
Some of them affected scopes while others were located within comments.

Fix Typos and Misspellings

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

https://doc.rust-lang.org/reference.html#macros states
> The Kleene star operator consists of $ and parentheses, optionally followed by a separator token, followed by * or +. 
so the operator should not be required and should be optionally anything except * or +

[Rust] Kleene star operator is optional

---

Diff/Diff.sublime-syntax
Diff/syntax_test_diff.diff

The previous Diff syntax was scoping `changed` & `deleted` punctuation as `inserted`. These changes fix these issues and adds tests.

[Diff] Fix Changed & Deleted Punctuation

---

C++/C.sublime-syntax
C++/syntax_test_cpp.cpp

I made the following changes:
* Fixed issue where some octal escape sequences were highlighted as invalid
* Allowing hexadecimal escape sequences to be more that 2 digits long
* No longer highlighting \p (this is not a valid escape sequence in the C or C++ standards)
I followed the specification found [here](http://en.cppreference.com/w/cpp/language/escape). The only difference is I still highlight \e. This is not part of the C or C++ standards, but is supported by some compilers (I tested with Clang).

[C/C++] String escape sequence improvements

---

CSS/CSS.sublime-syntax

Added support for the following 88 pseudo elements.
There are currently around 300 total pseudo elements but the ones below are:
1. Currently supported
2. In use in some capacity
```
::-moz-button-content
::-moz-color-swatch
::-moz-focus-outer
::-moz-list-bullet
::-moz-list-number
::-moz-meter-bar
::-moz-meter-optimum
::-moz-meter-sub-optimum
::-moz-meter-sub-sub-optimum
::-moz-number-spin-box
::-moz-number-spin-down
::-moz-number-spin-up
::-moz-page
::-moz-page-sequence
::-moz-progress-bar
::-moz-range-progress
::-moz-range-thumb
::-moz-range-track
::-moz-scrolled-page-sequence
::-moz-tree-cell
::-moz-tree-cell-text
::-moz-tree-checkbox
::-moz-tree-column
::-moz-tree-drop-feedback
::-moz-tree-image
::-moz-tree-indentation
::-moz-tree-line
::-moz-tree-progressmeter
::-moz-tree-row …
```

[CSS] Update pseudo elements

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

Allow support for `a{3}` in addition to the existing `a{3,}`, `a{2,3}`, and `a{,3}`. If it is a problem that this makes `a{}` a "valid" regex, let me know, and I'll fix it up.

[RegExp] Support non-range numeric quantifiers

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

* Converted the class definition to a reusable context (`class-definition`)
* Added some tests for standard class definition/instantiation (to avoid regressions)
* Added support for anonymous classes (http://php.net/manual/en/language.oop5.anonymous.php)

[PHP] Add support for anonymous classes

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

At the end of a parameter list PHP 7 now supports a colon to indicate a return type follows (either scalar or a class/interface)
http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration

[PHP] Add support for return types

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

A new unicode codepoint escape syntax was added to PHP 7
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.unicode-codepoint-escape-syntax
Also added tests for some of the other string interpolation features

[PHP] Add support for unicode codepoint escape syntax

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Previously, the uppercase portion of a camelCase variable was matched as
a constant. Adding a simple `\b` to the match rule should fix this.
Before
After

[Ruby] Do not match camelCase as a constant

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

In `Symbol === x` Symbol is now treated as a constant and not a constant definition.

[Ruby] Fix: account for equality with constants

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

All whitespace until the first non-whitespace character was not
correctly scoped and will be visible for color schemes with a background
color for strings.
Fixes what I mentioned [here](https://github.com/sublimehq/Packages/commit/76c4d5fcf31956c41d061b4daaef60c1ad4b67a3#commitcomment-16871122).

[Python] Fix string block scope starting with ws

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Attribute selectors now support namespaces & flags.
`string` scope inclusions were re-organized in the process

[CSS] Improved attribute selectors

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

for consistency with the HTML syntax
fixes #309

[XML] assign scope to attribute equals sign and support attributes beginning on a new line

---

Python/Python.sublime-syntax

I couldn't stand just looking at it ...
There are also countless other strings that use quotation marks without needing them, but it seems pointless to change multiple hundred lines just for that when it works "just fine" right now.

[Python] Simplify single quotes regexps

---

Python/Python.sublime-build

ST would try to read output as utf-8, but Python (by default) uses the
system's OEM encoding, which can differ greatly (cp850 for Western
Europe). Telling the Python runner to always use utf-8 for output makes
this work fine.
Test code to run with this build system:
```
print(u"\uFFFD")
```
Fixes https://github.com/SublimeTextIssues/Core/issues/926 (which also has some other relevant/related information).
---
I would also like to change the command on Windows to use the `py` executable that gets installed in the Windows folder, but it's not installed with Python 2 automatically unfortunately and wouldn't work then. Maybe we could a the Python 2-compatible cmd (using `python`) as a variant?

[Python] Fix encoding issues on Windows

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

I thought I would share my solution for issue #315.
It is not perfect in my opinion, because it's not DRY, so I would be interested to see if anyone has a better solution :) EDIT: this has since been corrected :+1: 
Other improvements:
- it scopes literal characters as `meta.literal.regexp`
- it also scopes the `.` character as `keyword.other.any.regexp` as per #314 
- correctly scope mode modifiers i.e. `(?x)` or `(?-i)` as `meta.mode-modifier.regexp`
(if you don't like any of the scope names, we can change them)
Regular expressions don't tend to get that big, but I did a performance measurement anyway on a 400 byte file:
- Before my changes:
> Syntax "Packages/Regular Expressions/RegExp.sublime-syntax" took an average of 0.1ms over 10 runs
- After my changes:
> Syntax "Packages/Regular …

[Regular Expressions] scope invalid quantifiers

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Simple change that adds support for Unicode code point escape sequences within strings.

[CSS] Support unicode escapes within strings

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Added support for numeric values and the keywords `from` & `to` within keyframes at-rules.
As a side effect, class and id selectors now follow the spec more closely

[CSS] Added support for keyframe selectors

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

As I mentioned in this other PR (https://github.com/sublimehq/Packages/pull/316#issuecomment-215554171), the definiting puntuation of inline-comments `(?#` and `)` were not highlighted as part of the comment.
I also changed the scope name to `comment.block` instead of `comment.line`.

[RegExp] Highlight comment punctuation

---

Clojure/Clojure.sublime-syntax
Clojure/syntax_test_clojure.clj
Regular Expressions/RegExp.sublime-syntax

[Regular Expressions] fix #332 and [Clojure] fix and add tests

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Not all functions were previously supported and those that were implemented were supporting keywords or values that are not compatible as an argument for that function.
For example:
1. the `cubic-bezier()` timing function was matching the keywords `end` & `start` which are only supported by the `steps()` timing function
2. `url()` was matching the property values `min-content` & `max-content` which are only supported by the `repeat()` and `minmax()` functions
---------
This PR changes some existing implementations:
1. **color functions** - `rgb(), rgba(), hsl(), hsla()`
color function arguments no longer have specific scopes. *ie*: `constant.other.color.hsl-value.css` is now just `constant.numeric.css`. This seems more fitting as the arguments themselves are just numeric values.
2. **hex …

[CSS] Refined function support

---

Python/Python.sublime-build

According to the docs for `sys.std{in,err,out}`:
>The character encoding is platform-dependent. Under Windows, if the stream is interactive (that is, if its isatty() method returns True), the console codepage is used, otherwise the ANSI code page. Under other platforms, the locale encoding is used (see locale.getpreferredencoding()).
Thus, PYTHONIOENCODING should be set for all platforms.
Iterates on https://github.com/sublimehq/Packages/pull/295.

[Python] Set PYTHONIOENCODING for all platforms

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Use the already defined `ident` variable in places where the spec calls for it.

[CSS] Use `ident` variable in more places

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

1. pseudo classes & elements are now scoped as `entity.other.pseudo-{class/element}.css` instead of `entity.other.attribute-name.pseudo-{class/element}.css`
2. Functional pseudo-classes are handled uniquely while all others are handled generally. It is no longer necessary to list all pseudo classes in order to match them
I left the functional pseudo-class names scoped as `entity.other.pseudo-class.css` to maintain consistency with other pseudo-classes. They could however be scoped as `support.function.pseudo-class.css` to maintain consistency with other functions.

[CSS] Improve pseudo class & element matching

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Browsers support `percentage` values in some functions even though the spec doesn't call for it. I added support for these instances.
I also added the `inset` property value

[CSS] Added percentage types to more functions

---

Batch File/Batch File.sublime-syntax
Batch File/syntax_test_batch_file.bat

Fixes
- runaway scoping when REM is immediately followed by a newline
- Incorrect illegal characters within REM (the [docs](https://technet.microsoft.com/en-us/library/bb490986.aspx) say `(|)` are not allowed but the tests I did say otherwise)
- Allow : and a space to start a line comment

[Batch] Fix comments

---

Batch File/Batch File.sublime-syntax
Batch File/syntax_test_batch_file.bat

Further improvement for #374. 
Ensures colon comments are only scoped in the proper places:
- When used on a line by itself
- When preceded by the `&` operator <sup><a href="http://stackoverflow.com/questions/11269338/how-can-i-comment-out-a-section-or-add-comments-in-a-batch-file#comment60622945_16839602">1</a></sup> <sup><a href="http://stackoverflow.com/a/12408045">2</a></sup> <sup><a href="http://ss64.com/nt/rem.html">3</a></sup>

[Batch] Restrict colon comment matching

---

Scala/Scala.sublime-syntax

sbt follows a subset of scala syntax now.
So it makes sense to honor scala syntax in sbt files.

Add sbt to the list of supported file extensions

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

...otherwise they are just normal method names. fixes #404

[JavaScript] get and set must be followed by a method name to be an accessor

---

C++/Indentation Rules.tmPreferences

Lines matching ^\s+\*.*$ in multi-line block comments previously triggered a
matching indention on lines following it (even if e.g. preprocessor statements
were in between).
For example:
```
/*
* Copyright ...
*/
^--- this line is indented by one space
#include <stdlib.h>
^--- this line too
```
Fixes #417.

[C++] Ignore indention of multi-line block comments

---

Python/Miscellaneous.tmPreferences

Fixes #419 by adding support for auto-indenting `async` `def`, `for`, and `with`.

[Python] Auto-indent async functions, for, & with

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

Make XML block comment punctuation scope more consistent with other syntaxes (added missing scope for `-->` and appended `.begin` to `<!--`)
Also added more test coverage.

[XML] correctly scope beginning and ending of comments

---

Batch File/Batch File.sublime-syntax
Batch File/syntax_test_batch_file.bat

- `IF` statements get an optional `NOT`.
+ Tests to ensure that `ECHO foo not` doesn't match.
- Fix and add test for `==` not working as a comparator.
- Add minor test to ensure that future updates to `FOR` (which needs some love) do not clobber highlighting of its `IN` clause.

[Batch File] Add NOT to IF. Fix == never matched.

---

PHP/syntax_test_php.php

I just thought I would extend the PHP test coverage slightly:
- to prove that PHP inside HTML attribute values is still recognized as being part of that attribute value etc. and that the HTML `meta.tag` scope still applies
- to prove that HTML tags are still recognized when nested deeply in PHP blocks - the tags were already there but the tests weren't.

[PHP] expand test coverage

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

I finally ~~found the time~~ made some time to work on this. There is still things left to be done, but especially keyword matching is greatly improved now for keywords that only occur in conjunction with other keywords (in statements, e.g. `for ... in ...:`). Additionally, list comprehensions are more properly matched and only where applicale and highlighting of `print` and `exec` is smarter.
While I was working on it, I also 
- allowed dots in dotted_names to be surrounded by spaces,
- made set literals have an appearance
- unified context formatting (underscores and separated with empty lines)
- added scopes for annotations, default values and all commas
- made assignments in expressions illegal, as well as storage modifiers
- made semicolons get matched
- more...?
---
**Performance …

[Python] Improvements on highlighting with focus on keywords

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

changed class name scope from `entity.name.type.class.js` to `entity.name.class.js` as per https://github.com/sublimehq/Packages/issues/445

[JavaScript] Update class name scope

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

in a non-raw string, having something after the ``\`` that isn't a recognized escape sequence was causing the entire rest of the line to be marked as illegal. i.e. `\s`
this fixes that.

[Python] fix \ chars in strings being always treated as line cont

---

Batch File/Batch File.sublime-syntax

Previously, `/A num*=5` would get highlighted although the `SET` command was missing.
`SET /A` contexts should now only be pushed when the `SET` command is encountered.

[Batch File] Ensure SET /A contexts are correctly pushed

---

C++/C++.sublime-syntax

The XOR character in the operator overload regex is incorrect. It looks like a caret, but it's not.

[C++] Fixing incorrect XOR character

---

Rails/Ruby Haml.sublime-syntax

I found this while investigating all the scopes in the repo where order mattered and this was the only one. Turns out it is a mistake and this should match the one in the Ruby syntax file.
So fun fact: in all the default syntaxes order of the scope doesn't matter when checking equality. Not sure if this is true for all prefixes yet though.
@wbond

Fix scope mismatch between Ruby syntax and Haml

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This will be merged right before we ship 3115 since it uses new functionality

[Ruby] Support code on same line as heredoc begin token

---

PHP/PHP Source.sublime-syntax
PHP/PHP.sublime-syntax
PHP/syntax_test_php.php

This effectively reverts cd7f8c24ef8c785fc9ff01c1c157beadb35278d8, and will be merged right before we ship 3115 since it uses new functionality.
It has the side effect of also allowing literal HTML output inside of anonymous class methods and closures.

[PHP] Use clear_scopes to implement proper HTML nesting inside of PHP blocks

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Pretty self-explanatory. Single-line change in `sublime-syntax` file, two tests added, passes with flying colors.

[Python] fix for keyword.operator.assignment/keyword.operator.comparison issue #508

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

Fix bug when method name begins in a magic name but the identifier continues, so it shouldn't be counted as magic

[PHP] fix magic method detection

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

Some of the recent changes meant that the leading slash was not scoped with the class name, this meant tooling was unable to tell if the code was using a local `Exception` class or the global `\Exception` class.
This pr fixes that, along with scoping the entire namespace as the class too

[PHP] Ensure namespace elements and separators are scoped with their class

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

A small change to fix the highlighting of the default keyword in the Go syntax.

[Go] Stops the default keyword from becoming entity.name.label

---

PHP/syntax_test_php.php

Using invalid PHP in the tests seems like something that would trip people up when writing tests and changing syntax rules.
* The reserved keyword 'namespace' cannot be used as a sub-namespace
* Add missing semi-colons
* ~~Complex expressions within strings are not supported, eg "{$a . $b}" is not valid PHP~~
* Empty if() statements are not valid
* Remove duplicated function/class names

[PHP] Tidy up of the example code to ensure it's valid PHP

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

I implemented comment parsing for the regular expression syntax. This required tracking the extended mode state within groups and I had to duplicate a lot of base\* and group\* contexts, but it's working very nicely now.
Additionally, I changed a few minor things such as a more appropriate scope name for mode modifiers.

[RegExp] Comments in extended mode and scope adjustments

---

Scala/syntax_test_scala.scala

Doesn't change anything other than codifying most of what is currently there.  Some things aren't tested (such as the invalid string newline thing) since the test framework isn't quite able to handle it (so far as I can tell).

[Scala] Added tests for existing Scala syntax support

---

CSS/css_completions.py
HTML/HTML.sublime-syntax
HTML/html_completions.py
HTML/syntax_test_html.html

- don't suggest HTML attribute names when typing inside a HTML attribute value string
- suggest CSS when typing at the end of a HTML style attribute, just before the closing quote
EDIT: also:
- make `style="..."` and `style='...'` consistent in HTML - previously, the single quotes were being scoped as `source.css`, which is incorrect.

[HTML] and [CSS] completions improvements

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

`\g` allows to use `-` for previous capture groups
`(?\d)` allows to use `-` for previous capture groups and `+` for next capture groups
example:
> hellohellowowwow
would be matched by:
(hello)\g-1(?+1)(wow)

[Regular Expressions] support relative capture groups

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

[Python] scope escaped { and } characters in strings

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Also match `{:>3}` and other padding formats. Match `strftime` formats separately and simply.
It's a little weird not seeing the `{!a}` format in the spec (which I discovered when the existing test failed), but I tried it in a Python3 interpreter, and it does indeed work. It is somewhat unclear to me where the `!` can fall, and under what circumstances.
If this change breaks existing code highlighting, please give me examples in syntax test format.
https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting
https://docs.python.org/3/library/string.html#format-specification-mini-language
http://strftime.org/

[Python] Stricter string placeholders

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

- Adds the at-rules `@document`, `@supports`, & `@counter-style`
- Re-organizes at-rule constructs
- Adds `@document` supporting functions: `domain()`, `regexp()`, & `url-prefix()`

[CSS] Add document, supports, & counter-style at-rules

---

Scala/Scala.sublime-syntax
Scala/Symbols.tmPreferences
Scala/syntax_test_scala.scala

Scala's variable definition syntax is quite rich, and Sublime doesn't (currently) handle it very well.  Additionally, several special syntactic forms are available in both `val` declarations and `case` pattern matches (the syntax is actually identical) which are not highlighted at all by Sublime.  Finally, complex patterns in `val` declarations and *any* patterns in `case` pattern matches are not currently considered for "go to definition", which is annoying.
This PR fixes all that.
- ![case example](http://i.imgur.com/qvOpC0d.png)
- ![val examples](http://i.imgur.com/M0WkCuM.png)
The orange italic parameters in the above are both considered for symbol matching, which enables go to definition jumping into pattern match extractors, as well as provides more accurate auto-complete.
There is …

[Scala] Pattern match highlighting for case, val and for

---

Go/Go.sublime-syntax

The keyword `panel` should instead be `panic`.

[Go] Fix builtin typo for syntax highlighting

---

Python/Regular Expressions (Python).sublime-syntax
Python/syntax_test_python.py

Added a few punctuation symbols, none of which is a regex meta-character.
Also, I suppose dash should be escaped, because `[!-:]` actually means `[!"#$%&'()*+,\-./0123456789:]`.

[Python] Relax regex comments a bit

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

Text inside the \path command was not treated special. This broke highlighting if the path contained special characters (e.g. $).
I'm not sure if there are multiple \path commands in different packages that behave differently. I am using the one from the hyperref package to typeset file paths. In my case, they sometimes contain environment variables, starting with $. Unlike for the \url command, which is highlighted correctly, a $ inside a \path would lead to the following text being highlighted as if it was set in math mode. This pull request fixes this.

[LaTeX] Add match for \path command to make it behave like \url and \href

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

This PR adds scoping of backtracking control verbs, as per http://www.boost.org/doc/libs/1_61_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html#boost_regex.syntax.perl_syntax.backtracking_control_verbs
All tested in ST3's find panel and confirmed to be recognized, including the `(*F)` shorthand form of `(*FAIL)`, which isn't mentioned in the boost docs for some reason.

[Regular Expressions] support backtracking control verbs

---

Haskell/Haskell.sublime-syntax

The GHC Haskell compiler [allows the use of unicode symbols](https://downloads.haskell.org/~ghc/7.2.1/docs/html/users_guide/syntax-extns.html) for some keywords when the UnicodeSyntax extension is enabled.
This commit adds support for the following symbols:
* `→` for `->`
* `⇒` for `=>`
* `∷` for `::`
The other characters demand deeper changes on the syntax definition but could be added. The symbols above comprise everything needed for type declarations, though.

[Haskell] Add UnicodeSyntax symbols for type definitions

---

Scala/Scala.sublime-syntax
Scala/Symbols.tmPreferences
Scala/syntax_test_scala.scala

Several adjustments, fixes, enhancements and general better-ness:
- Indexing
+ `for`/`case` variables are no longer indexed
+ Initialization (i.e. `new`) are no longer erroneously indexed (#560)
+ Upper-case `val` declarations are indexed in base position, and considered constants in more complex patterns
- Type expressions are identified and parsed (subsumes #549)
+ Upper-case identifiers are now highlighted as constant references
+ Upper-case types are now highlighted as class references
+ Symbols in type position are highlighted as types
+ Underscores in type position… don't have a highlighting
+ Bounds (`<:`, `>:`, `<%`, `+`, `-` and `:`) are highlighted as special operators in type position
+ Dereferencing is identified (`#` and `.`)
+ Type lambdas are more stable now
+ `.type` is …

[Scala] Significant Improvements

---

LaTeX/Snippets/begin{}-end{}.sublime-snippet

This issue has been raised in https://github.com/SublimeText/LaTeXTools/issues/817
Previously the snippet for begin{}-end{} added `item` instead of `\item` in list environments (enumerate, itemize, list, description)

[LaTeX] Escaped backslash before item in begin{}-end{} snippet

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

This resolves https://github.com/sublimehq/Packages/issues/568 as @merlinthered is right and `\lstinline{...}` is an experimental feature, see [listings documentation sec 4.2](https://www.ctan.org/pkg/listings).

[LaTeX] Support braces in `\lstinline`

---

Scala/Scala.sublime-syntax
Scala/Symbols.tmPreferences
Scala/syntax_test_scala.scala

This fixes #552.  To be clear:
```scala
package stuff    // not indexed
package stuff2 {
// indexed
}
```
I'm using the scopes `entity.name.namespace.header` and `entity.name.namespace.scoped`.

[Scala] Only index scoped packages

---

Pascal/Pascal.sublime-syntax
Pascal/syntax_test.pas

One line comments grab the final `\n` which is apparently needed for matching a `\b` if there's a keyword right on the next line (with no trailing space). This is visually annoying and breaks jumping to symbols for functions/procedures that have a comment right before them.

[Pascal] Fixed one line comments eating keywords from next line

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Lambda lookahead didn't correctly identify the following scenario:
```scala
x: List[Int] => ???
```
This is now using the same hack that I had to use for parentheses matched lookahead, which means it will break with over 3 levels of bracket nesting.

[Scala] Fixed lambda lookahead for bare ascriptions with type parameters

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

I have no idea why the match had previously enforced that the `*/` was the last thing on the line, but there's no reason for it and it breaks stuff.

[Scala] Fixed scaladoc termination prior to EOL

---

YAML/YAML.sublime-syntax

Previously, a whitespace character was required to be matched (e.g. a `\n` newline) after a key, but when at EOF there is no character to be consumed.
Due to the nature of this change, it is impossible to test, but I verified that the fix works.

[YAML] Fix highlighting of keys at EOF

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Scala allows nested comment blocks.  We correctly handle this for regular comments, but scaladoc is (still) sort of a mess and we weren't correctly nesting the scopes.  Fixed.

[Scala] Fixed nested scaladoc

---

C#/C#.sublime-syntax
C#/syntax_test_c#.cs

The numeric suffixes included many types that aren't valid C# suffixes and did not include suffixes for double and decimal.  This provides a proper list according to the MSDN docs:
Decimal (M, m): https://msdn.microsoft.com/en-us/library/364x0z75.aspx
Double (D, d): https://msdn.microsoft.com/en-us/library/678hzkk9.aspx
Float (F, f): https://msdn.microsoft.com/en-us/library/b1e65aza.aspx
Long (L, l): https://msdn.microsoft.com/en-us/library/ctetwysk.aspx
ULong (U, u, UL, ul, Ul, uL, LU, lu, Lu, lU): https://msdn.microsoft.com/en-us/library/t98873t4.aspx
There is nothing for int, byte, sbyte, short, and ushort.

[C#] Fix numeric suffixes

---

Scala/Scala.sublime-syntax

Newlines are not allowed in backtick identifiers

[Scala] Bail out on backticks in patmat if hitting EOL

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

- It is legal to have a full (delimited) type expression within a pattern match parenthetical
- Greedy matching caused us to miss a few accessor cases and incorrectly highlight them as bindings

[Scala] Some minor refinements/bugfixes in patmat highlighting

---

Scala/Scala.sublime-syntax

It's just a bit annoying typing `case` and seeing the rest of the file get eaten by `pattern-match` context.  This just checks for `\}` (which is guaranteed surrounding a case expression) or a `case` (i.e. we're typing not-the-last pattern in a block) and bails out there.
The only case this doesn't handle now is typing `case class`, which still behaves a bit unintuitively, but it's not as actively annoying as the case that I've fixed.

[Scala] Added emergency bailout from pattern match mode

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

In master, `<` (by itself) is not considered a valid identifier.  This PR fixes this case while respecting XML literals.  Note that there is one situation that will be improperly highlighted at present.  Consider the following:
```scala
x<y
x< y
x <y
x < y
```
The first of the four will be improperly highlighted (it will assume that `<` indicates an XML literal, rather than an operator).  All of the remaining three will be handled correctly by the syntax highlighting, including the third (which *correctly* identifies `<` as part of an XML literal).  I'm not sure how to handle the first one without some combinations of contortions or lookbehind, and it's super-rare anyway – as demonstrated by the fact that Martin Odersky was one of two people (total!) to correctly identify the parsing …

[Scala] < is a valid operator (when not followed by alphabeticals)

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

As mentioned in #588 unicode escaped characters were improperly highlighted.
I also added support for octal characters, and check for improper escape sequences.
```scala
"escaped chars: \u1221 \125 \n"
//                ^^^^^^ constant.character.escape.scala
//                        ^^^ constant.character.escape.scala
//                            ^^ constant.character.escape.scala
"bad escaping: \p"
//               ^ invalid.illegal.lone-escape.scala
"""escaped in triple: \u1221 \125 \n"""
//                      ^^^^^^ constant.character.escape.scala
//                             ^^^ - constant.character.escape.scala
//                                  ^^ - constant.character.escape.scala
```
I also added support for "f-string" with a "printf" like escaping. I'm not sure which scope …

[Scala] improve string highlighting

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

It's a bit boilerplatey, but I believe it more effectively emulates Scala's actual semicolon inference in declarations.

[Scala] Fixed multi-line decls for classes/traits/objects and functions

---

LaTeX/LaTeX.sublime-syntax

The current syntax had problems recognizing braces in optional arguments as for example in 
````latex
\begin{defn}[{\parencite[Definition]{Article}}]
\begin{figure}[caption={Action of \( S^1 \) by rotation on \( \R^2 \).}]
````
This is fixed with this PR.
I found the `syntax_test_latex.tex` where you apparently collect tests. But I didn't understand the "test syntax" in order to create a test for this PR.

Improve optional arguments in LaTeX syntax

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

The new double-newline detection stuff was a bit broken w.r.t. abstract function declarations, resulting in syntax highlighting being effectively disabled for large chunks of files.  Also, operator boundary detection in lookahead was a bit too overaggressive on function `=` operators (probably similarly on `val`/`var`, but I haven't checked yet).  Lambdas with bare parameters ascribed with fully-quantified types were not detected by the lookahead.  Finally, there was a missing punctuation scope on interpolated non-triple strings.

[Scala] Misc fixes to functions and lambdas

---

Ruby/Ruby.sublime-syntax

When saving new files, the suggested extension is `.Appraisals`, apparently because its first in the list -- a regression introduced by 84396b2cfc7ad2ddb289c3d5bfecf4ae6a1a4f7d.
Moving `.rb` to the top solves this issue

[Ruby] make `.rb` the default file extension

---

ASP/ASP.sublime-syntax
ASP/syntax_test_asp.asp

In ASP, a method could be defined like:
Sub Test1 (expect_array)
Response.Write expect_array(1)
End Sub
and it could also be defined like:
Sub Test2 (expect_array())
Response.Write(expect_array(1))
End Sub
This PR is to ensure the latter case is highlighted correctly, as it is valid. (Interestingly, even in this case, ASP doesn't actually enforce that an array has to be passed, so it is mainly just a visual clue for the developer...)

[ASP] support method definitions containing explicit array parens

---

Markdown/MultiMarkdown.sublime-syntax

Recently I received an issue about a `first_line_match` compiling error [here](https://github.com/jfcherng/Sublime-AutoSetSyntax/issues/6) hence I make this PR.
The `first_line_match` in `MultiMarkdown.sublime-syntax`:
- Cannot be compiled with Python's `re` module.
```python
>>> re.compile(r'^Format:\s*(?i:complete)\s*$')
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "./python3.3/re.py", line 214, in compile
File "./python3.3/re.py", line 283, in _compile
File "./python3.3/sre_compile.py", line 491, in compile
File "./python3.3/sre_parse.py", line 747, in parse
File "./python3.3/sre_parse.py", line 359, in _parse_sub
File "./python3.3/sre_parse.py", line 708, in _parse
sre_constants.error: unknown extension
```
- According to …

[Markdown] Fix invalid first_line_match in MultiMarkdown.sublime-syntax

---

Matlab/Matlab.sublime-syntax
Matlab/Miscellaneous.tmPreferences
Matlab/syntax_test_matlab.m

Originaly pointed out on: 
1. https://forum.sublimetext.com/t/matlab-syntax-highlighting-error-on-mac-10-11-4-build-3114/23429/2
Tests results after this work:
1. ![image](https://cloud.githubusercontent.com/assets/5332158/19008459/c06ad3b4-8741-11e6-9f86-15b98d0bde3c.png)

[Matlab] Fixed the block comment scope for the Matlab syntax

---

Rust/Cargo.sublime-build

The error format from Cargo changed
https://github.com/rust-lang/sublime-rust/issues/84
so updating this package to match the new format. maybe should do both?

[Rust] Cargo error format update

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

- Fixes additional cases mentioned in #500.
- Also fixes #699 (print statement).
- Also adds highlighting for keyword arguments in class inheritance, notably `metaclass`.
Thanks to @pdknsk for the reports.

[Python] Context exiting fixes (+ minor additions)

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Follow-up on #397.
Also, raw strings don't have any escape sequences.

[Python] Fix line-continuations in strings for real

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

Currently we are using the same match for the <?xml ... ?> prolog at the start of a file, and <?other ... ?> processing instructions in document content. They look similar, but they're separate in the XML syntax and PIs don't have attribute/quoted-value constructs inside them.
Match <?xml with the current handling, and add simpler handling for processing instructions which doesn't look for attr-like structure in the content. This prevents eg stray apostrophes in PI content from triggering invalidity.
Exclude any targets beginning with XML (case insensitive) from being PIs as per the PITarget production, so they don't match the prolog. Tweak spaces to better match spec: ban space after <? for both prolog and PI; require space after <?xml, and require either space after PITarget or empty …

[XML] Handle prolog and PIs separately

---

LaTeX/LaTeX.sublime-syntax

breqn package is very popular together with amsmath for mathematical typesetting in LaTeX

[LaTeX] Support for breqn environments

---

LaTeX/Comments.tmPreferences

Currently comment toggling only works in LaTeX and not in pure TeX (https://github.com/SublimeText/LaTeXTools/issues/949).

[LaTeX] Enable percent sign comments in pure TeX

---

YAML/YAML.sublime-syntax
YAML/tests/syntax_test_general.yaml

Just realized I had this branch lying around without opening a PR.
Should be self-explanatory.

[YAML] Don't scope leading whitespace as comment

---

Python/Regular Expressions (Python).sublime-syntax
Python/syntax_test_python.py

For some reason, the entire main context would push (and pop) an anonymous context for non-whitespace characters and exit it again for whitespace characters. That means that including the main context could lead to the including context not being able to pop out of its context properly, causing issues like #656.
Additionally, I made a quick pass over punctuation scope names and added "begin" and "end" scope leafs.
Fixes #656.

[Python] Fix regex syntax

---

LaTeX/TeX.sublime-syntax
LaTeX/syntax_test_latex.tex

the `\iota` and `\Iota` are missing.

[LaTeX] missing iota and Iota commands

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

Added `entity.name.capture-group` and `variable.other.backref-and-recursion` scopes.
Tests where kinda all around the place, so I grouped them a little like in the Python tests.

Regexp scopes

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

Greater-than is actually valid in both text content and attribute values (see CharData and AttValue productions in XML 1.0 spec). Change should-be-entity pattern to reflect this.
The exception is that the sequence ]]> must not appear in text content (but it's OK in an attribute value, for some reason). Add missing-entity detection for that inside text content.

[XML] Permit unescaped > in content

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Scala supports a C#-like syntax for declaring anonymous inner classes with structural types that extend `AnyRef`.  Like so:
```scala
val x = new {
def foo = 42
}
x.foo  // => 42
```
This syntax is very rarely used, because it's quite slow to evaluate, but it does exist.  We were previously scoping this incorrectly, since the braces were considered part of a valid single-line type declaration.  This meant that the class body was scoped as a type, which is obviously incorrect.  It is now fixed.
Amusingly, as you can see from the above snippet, we weren't the only ones to forget about this construct when building a syntax highlighting for Scala.

[Scala] Corrected issue with anonymous AnyRef inner class scoping

---

LaTeX/syntax_test_latex.tex

For the general-*-arguments, the context is popped by the match '\}',  the non-space are not necessary
In other places, `set` was used in the match argument, those non-space matches are also not needed
PS: the test for `\parbox` is also improved.

[LaTeX] improve tests for parbox and makebox

---

ASP/ASP.sublime-syntax
ASP/syntax_test_asp.asp

scope member access just like PHP does (for `var->member`), in ASP the syntax is `var.member`
previously, ASP was scoping the `member` part as `variable.other.asp`, now it is more specific, as `variable.other.member.asp`, to make it consistent with the PHP syntax, and the scope naming guidelines at http://www.sublimetext.com/docs/3/scope_naming.html#variable

[ASP] scope member access

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

For example;
```scala
class Foo { val bar = 42 }
```
The `{` was not properly detected, and so the entire line was considered part of the class meta definition, meaning that the `val`, the `42` and so on were not properly highlighted by the `main` context.

[Scala] Fixed single-line class declarations with bodies

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

As mentioned in #588, I propose to add support for annotations.
I based myself on http://www.scala-lang.org/files/archive/spec/2.11/11-annotations.html .
I used the scope `storage.modifier.annotation.scala` on annotations.
This provide coloring in most themes due to `storage.modifier`and is easily customizable.
``` scala
@deprecated("Use D", "1.0") class C { ... }
// ^^ storage.modifier.annotation
//            ^^ string
@transient @volatile var m: Int
// ^^ storage.modifier.annotation
String @local
//     ^^ storage.modifier.annotation
(e: @unchecked) match { ... }
//  ^^ storage.modifier.annotation
//              ^^^^^ keyword.control.flow.scala
// more complex:
@scala.beans.BeanProperty
//  ^^^^^^^^^^^^^^^^^^^^^ storage.modifier.annotation
(e: Int @unchecked) match { ... }
//  ^^ …
```

[Scala] add support for annotations

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Scala has a very rich class declaration syntax with some constraints (such as you cannot use `with` before `extends`, and cannot use multiple `extends`).  For this reason, we have long punted on this and just popped out as soon as we saw those sorts of contexts, which led to certain things being highlighted sub-optimally.  Additionally, it outright prevented ever accurately assigning the `meta.class.body` scope.
This is now fixed, and the meta scope is applied.  Additionally, support has been added for flagging certain completely-invalid syntaxes as `invalid`.  I additionally fixed some low-hanging meta scoping in other areas.  Lots more work to do here.

[Scala] Stateful class declaration and some meta scopes

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Adds support for the largest syntax addition to Python 3.6. Normal string placeholders have also been revised.
See #694.

[Python] f-strings

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Lots of stuff.  In no particular order:
- Removed all of the lookbehind (updates #481)
- Added support for lambdas (I'm pretty sure anyway…)
- Fixed scoping of `?`, `extends` and `super` inside of generics
- Removed a metric boatload of `storage.type`
- Fixed some random punctuation scoping that was incorrect (including `.`)
- Added kitchy `invalid` scoping on primitive-instantiated generics (it's pretty safe to say these will always be invalid, given how generics are implemented on the JVM)
- Implemented full-state field declaration parsing
There's a bit of a question here though, and I don't know the answer.  Specifically:
```java
private String memberString = "Hello";
```
What should the scope of `String` be?  Clearly, if we replace `String` with `int`, the answer is …

[Java] More fixes!

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Found this in my unpushed branches~
Imo it's a good idea to incldue the puncutation character in this scope name, similar to the comment punctuation. People might want different colors for `::` scopes in C++/Rust than for `->` in C or Php. Similarly, dots deserve their own scope name.

[Python] Use punctuation.accessor.dot

---

YAML/YAML.sublime-syntax
YAML/tests/syntax_test_block.yaml

Also from my unpushed branches.
`keyword.control.flow` and `storage.modifier` seem more appropriate and the characters are important enough to warrant a colored scope.

[YAML] Change block scalar indicator scopes

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

This is the last PR remaining for proper Python 3.6 support.
Important additions in this PR are `__bool__` and `__all__` (bugfix). The others will hardly get used.

[Python] Update magic identifiers

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Random best practice that's worth documenting somewhere…  When you have any sort of stateful context chain, make sure each link in the chain *ends* with the following:
```yaml
- match: (?=\S)
pop: true
```
Anything you don't recognize, you should just bail on.
Another best practice: don't accidentally match on double word boundary by having a trailing pipe character.

[Scala] Various stateful bailout bugs

---

Markdown/Markdown.sublime-syntax

Requesting feedback from Sublime Text and other users.
The vast majority of Markdown files I see use .md; GitHub and BitBucket default to .md; Wikipedia lists .md first. Unless I'm in a bubble, .md seems to be much more common. Changing the default to the more common value will save time typing names for new files, and occasionally prevent the mistake of leaving it at the wrong value.

Change default Markdown file extension from "mdown" to "md"

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Following my own advice…  Here's an example of where this is broken on master:
```scala
class Foo extends Bar with {
import Foo._
}
```
The `import` is scoped as an inherited class, rather than a keyword, and the `Foo` isn't scoped at all.

[Scala] Some more bail-out double-checks on stateful class decls

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

`val` was using an older technique for operator lookaround, which has now been fixed.

[Scala] Fixed bug in val body lookahead

---

Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc.m

This request fixes #781 for Objective-C (and Objective-C++ by extension) by including an extra match for the relevant specifier while processing an Objective-C specific string.
I included two extra syntax tests in order to verify that this works only inside of a constant object string and not in a standard C string.

[Objective-C] Add support for Objective-C specific format specifier

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

This updates the Rust syntax to scope the newline after line comments, and the punctuation that begins and ends comments, in line with the other syntaxes.

[Rust] improved comment scoping

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

https://doc.rust-lang.org/book/strings.html 
> String literals can span multiple lines. There are two forms. The first will include the newline and the leading spaces:
> 
> ```rust
> let s = "foo
>     bar";
> 
> assert_eq!("foo\n    bar", s);Run
> ```
> 
> The second, with a `\`, trims the spaces and the newline:
> 
> ```rust
> let s = "foo\
>     bar";
> 
> assert_eq!("foobar", s);
> ```
This PR scopes the `\` the same way Python does.

[Rust] scope simple string line continuation characters

---

Rust/Rust.sublime-syntax

[Rust] remove empty match (too many | chars) from operator pattern

---

JavaScript/JSON.sublime-syntax
JavaScript/syntax_test_json.json

- strings are not allowed to contain new line characters, so mark them as unterminated and pop from the string context when a new line is reached. See http://stackoverflow.com/a/16690186/4473405 for clarification
- update comment block detection to match the JavaScript syntax and fix an empty block comment not being seen as closed
- scope dictionary keys so they can be targeted by color schemes  #421

[JSON] strings can't span multiple lines, fix comment block detection

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

This PR simplifies a few contexts, removes a few incompatible regexs (mainly `\G`) and adds support for lists in blockquotes, plus includes a few more tests.

[Markdown] support lists in blockquotes, code fences, multiline inline code and multiline emphasis

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

While reading some C++ headers (_cffi_include.h) I recently found some blocks
not being highlighted at all. Everything from the second `__cplusplus` to the
the final `}` keeps unhighlighted.
```C++
#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus       // THE LAST HIGHLIGHTED LINE
typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
#endif
#ifdef __cplusplus
}                        // HIGHLIGHTED AGAIN
#endif
```
With `#ifdef __cplusplus` within an `extern "C" {` block an empty scope is set
to stack causing this issue. This issue is fixed by removing this block at all.
So the `global` and `global-preprocessor` scopes are used within external C blocks
for highlighting.

[C++] Fix none highlighted preprocessor definitions in extern C blocks.

---

ASP/ASP.sublime-syntax
ASP/Symbol List.tmPreferences
ASP/syntax_test_asp.asp

This fixes a small symbol transformation edge case in the ASP package.
The edge case was a method definition without arguments & parens, where the method name was in square brackets and contained an open paren - before this fix it got cut off at the open paren.
i.e. `function [test_abc-def#123)_(ghgh]`

[ASP] fix small symbol transformation edge case

---

CSS/css_completions.py
HTML/HTML.sublime-syntax
HTML/html_completions.py
HTML/syntax_test_html.html

[HTML] meta.tag scopes were missing on style and script tags.
suggest [CSS] completions immediately before `</style>`. This was suggested at https://github.com/sublimehq/Packages/pull/532#issuecomment-240342983
Note: this change will still require auto-completion to be triggered manually when the cursor is just before `</style>` (when using ST without any modifications). This is just like the other PR, whereby typing just before the closing `"` in a style attribute also requires a manual trigger.  There are a few reasons for this:
- when ST checks scopes [for autocompletion], it checks at the character after the caret, which would be `<` in this case, with the scope `text.html.basic meta.tag.style.html punctuation.definition.tag.begin.html`
- In the default `auto_complete_selector` …

[HTML] [CSS] completions before </style> and [HTML] meta.tag scope

---

CSS/css_completions.py

This fixes #794, whereby `|` was being treated as a property name to be included in completions suggestions, when it shouldn't be.

[CSS] don't treat a pipe (|) char as a valid prop name for completions

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

The escape sequences includes went into the wrong match sub-context.

[Python] Fix single-quoted f-strings

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

Tighten up XML comment scoping to indicate when invalid characters (double hyphens that don't close the comment) are used inside the comment.
From https://www.w3.org/TR/REC-xml/#sec-comments:
> `Comment	   ::=   	''`
> Note that the grammar does not allow a comment ending in `--->`. The following example is not well-formed.
>
> ``

[XML] scope double hyphens in comments as invalid

---

XML/XML.sublime-syntax

Quite often, when working with web services and web service logs, the XML declaration is omitted. Rather than add more file extensions, I thought it would be a good idea to try to match a [SOAP envelope](http://schemas.xmlsoap.org/soap/envelope/) on the first line of the file to know that it is an XML document, and make the out-of-box experience better for web service developers. :)
(We could, if we wanted, detect any valid XML element (with a namespace, to avoid false positives), but I think just detecting SOAP is enough for now.)
This also tweaks the XML declaration first line match slightly, because the following is valid, as is a tab immediately after `<?xml`:
```xml
<?xml
version="1.0" encoding="UTF-8"?>
```

[XML] first line match SOAP Envelope

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

We were scoping `entity.other.inherited-class` without lookahead, which meant that any qualified identifiers ended up with the *leading* token scoped as the `inherited-class` while any trailing qualifiers (which were the actual class) were unscoped in master and outright broken with my other PR branches.
Leading qualifiers are now scoped as `support.constant`, which is basically accurate.  They may be a package name, but packages and objects in Scala are semantically almost identical, and objects are scoped as `support.constant`.  From the standpoint of the language specification, the only constraint is that the identifier is "stable" (which is to say, basically a constant).
As a random note, the scoping behavior changes when parentheses are introduced.  For example:
```scala
class Foo …
```

[Scala] Fixed incorrect scoping on qualified inheritence

---

HTML/Miscellaneous.tmPreferences

solves the problem with HTML unexpectedly unindenting as you type, and allows indentation to be increased and decreased as expected while typing HTML tags (previously one had to rely on pressing <kbd>Enter</kbd> inside an empty tag or using batch reindentation) - https://github.com/SublimeTextIssues/Core/issues/1583

[HTML] merged batch indentation rules to normal rules and annotated them

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

This PR correctly allows non-word characters in capture group names, and scopes the punctuation surrounding the capture group names, so that color schemes can target it to make the punctuation visually stand out from the name.

[Regular Expressions] better named capture group support

---

C#/C#.sublime-syntax
C#/tests/syntax_test_Generics.cs

Highlight `string.Format` replacements for `@"..."` strings, too.

[C#] Placeholders in multiline strings

---

LaTeX/LaTeX.sublime-syntax

- fix typo in verbatim environment
- remove duplicate scope in tabular environment

[LaTeX] Minor scope fixing

---

Python/syntax_test_python_strings.py

As I read through #715, I noticed I didn't add any tests for punctuation in interpolated sections, so that's what this PR is for.

[Python] Add tests for interpolation punctuation

---

Markdown/MultiMarkdown.sublime-syntax
Markdown/syntax_test_multimarkdown.md

This PR adds better header support to the MultiMarkdown syntax, and adds a syntax test for it. The rules for the header were taken from http://fletcher.github.io/peg-multimarkdown/index
This fixes https://github.com/SublimeTextIssues/DefaultPackages/issues/162

[Markdown] MultiMarkdown: better header support

---

PHP/Indentation Rules.tmPreferences

fixes #140 and makes PHP indentation consistent with HTML indentation when the PHP tag isn't closed before the end of the line.

[PHP] indentation improvements

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

fixes #789 and also ensures that the "speak-as" property is scoped correctly

[CSS] support "at rules" where the open brace is on a separate line

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Just like with methods, it is valid to wrap a type alias definition onto the next line without delimiters.

[Scala] Fixed type alias declarations with leading newlines

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

this PR adds table support to the Markdown syntax, as per https://github.github.com/gfm/#tables-extension-

[Markdown] add table support

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

This enhances the Markdown syntax by adding support for autolinks as defined by the GitHub Formatted Markdown specification: https://github.github.com/gfm/#autolinks-extension-

[Markdown] support GFM autolinks

---

Markdown/Indent%3A Raw.tmPreferences
Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

tweaks the scopes for lists inside block quotes to be consistent with the lists outside block quotes

[Markdown] improvements for lists in block quotes

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

Which had previously been mistaken for object literal keys. The fix entails
adding a new form of method declaration, using a string method name; and
giving that precedence over object literal key matching.
Fixes https://github.com/sublimehq/Packages/issues/861.

[JavaScript] Add support for string ES6 method definitions

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

to prevent highlighting breaking after `id.class` due to `class` being treated as a class definition, match the identifier if it isn't a function call (though it currently doesn't scope it, but this is existing behavior). This ensures that function calls are still handled correctly.

[Java] handle dot access to fields named "class"

---

C#/C#.sublime-syntax
C#/syntax_test_c#.cs

You can use `@` to tell C# that a normally-reserved word is not to be used in its normal context. [MSDN reference.][msdn]
```cs
var group = MakeGroup();
// Current syntax gets this right.
var contents1 = group.GetContents();
// Current syntax marks `group` as 'keyword.other.sql.cs',
// which is not technically correct because the code compiles
// fine, but it doesn't bother me too much.
var contents2 = @group.GetContents();
// Current syntax marks `group` as 'keyword.other.sql.cs'
// and `@` as 'invalid.illegal.reserved-char.cs', which is wrong.
```
I notice that `@void` already does what it ought to, and added tests for those, too.
[msdn]: https://msdn.microsoft.com/en-us/library/x53a06bb.aspx
[l40]: https://github.com/sublimehq/Packages/blob/master/C%23/C%23.sublime-syntax#L40
[l1122]: …

[C#] @ escapes reserved words

---

C#/C#.sublime-syntax
C#/tests/syntax_test_Generics.cs

This PR changes the unclosed string behavior in the C# syntax to match that of the other syntaxes, like Python, which scopes the new line character as invalid, which is less jarring than having the whole string appear as invalid.

[C#] use standard unclosed-string behavior

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

**Requires https://github.com/SublimeTextIssues/Core/issues/1190 to be fixed before merging!**
---
When trying to implement proper scoping according to #709 and #737, I noticed that I would have to rebuild almost the entire `function-calls` scope for decorators only with different scope names. Since I religiously hate duplicated code (especially considering I would have to duplicate it *twice*), I worked on refactoring how qualified names are matched instead and `qualified-name-until-leaf` was born. 
Unfortunately, it is affected by the bug described in https://github.com/SublimeTextIssues/Core/issues/1190 and thus is not ready to be merged yet. The following 17 failing tests should be fixed when this bug is fixed:
```
Packages/Python/syntax_test_python.py:102:2: [meta.qualified-name …
```

[Python] Decorator refactoring

---

Markdown/Markdown.sublime-syntax

this PR reduces the number of backtracking possibilities for regex engines like Oniguruma that use backtracking, and also explains the regex patterns better.
a simple Markdown snippet with a missing end backtick like
``he`lloworld`
will now fail in 73 steps rather than over 5000!

[Markdown] reduce backtracking possibilities

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Previously, for example, `- - test` would have both `-`s scoped as punctuation

[Markdown] don't scope consecutive bullet points that start a list

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

Non-Sublime implementations of sublime-syntax that use Oniguruma take exponential time to parse `impl SomeIdentifier {` lines without this change. See https://github.com/trishume/syntect/issues/33.
I'm pretty sure syntect is the only non-Sublime project that uses these files so I understand if you'd prefer not to merge this PR. I'm just submitting this to ask if you are open to it. I notice some other syntaxes use possessive quantifiers for speed, but those are probably left over from before sregex.
Otherwise I'll probably have to add hacky patches to the version of sublimehq/Packages I bundle with syntect.
@wbond

[Rust] Patch for catastrophic backtracking

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Follow-up on https://github.com/sublimehq/Packages/pull/743. Since this is also runs into https://github.com/SublimeTextIssues/Core/issues/1190, please confirm locally that the tests pass as I can't.
Fixes #773.

[Python] Match unpacking operators

---

PHP/Indentation Rules.tmPreferences

don't unindent on `else` or `elseif` [unless a colon is at the end of the line](http://php.net/manual/en/control-structures.alternative-syntax.php) (optionally followed by whitespace or a comment) - leave it for the closing brace rules to match instead. This fixes #901

[PHP] don't unindent on else or elseif unless a colon is at the end of the line

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

this updates the scope used for labels in C# to the same as that used in e.g. the Batch File syntax, `entity.name.label`.

[C#] fix label scoping

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

fixes #902 
prior to this, the syntax only coped with 2 part identifiers following the `case` keyword - now it supports everything, including expressions, casts, etc.

[C#] fix case expression scoping

---

C#/Symbol List Classes.tmPreferences
C#/Symbol List Constructors.tmPreferences
C#/Symbol List Enums.tmPreferences
C#/Symbol List Index Constructors.tmPreferences
C#/Symbol List Inner Function.tmPreferences
C#/Symbol List Interfaces.tmPreferences

removed usages of `symbolIndexTransformation` because it prevents Goto Definition from working properly
re: https://github.com/sublimehq/Packages/pull/910#discussion_r112312960

[C#] fix symbol index

---

HTML/Miscellaneous.tmPreferences
PHP/Indentation Rules.tmPreferences

fixes #915
- allow text (i.e. excluding angle brackets) preceding the close tag for unindent rule. (note: it won't unindent when there are more closing tags than opening tags on the line e.g. `<span>example</span>test</div>`, but it is better than the current implementation.)
- indent the next line if there is an unclosed open tag on the line. (note: it can be fooled by nested tags that are the same i.e. `<div>test<div>example</div>` won't create a new line, despite the unclosed `div`, but it is better than the current implementation.)
- use `\k` rather than `\g` to reference the previously captured named group because (in Oniguruma,) the latter recurses the expression and not the match.

[HTML] indentation rule improvements

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

For #889. Fixes the following test:
```js
{{foo}}
// ^ meta.block meta.block variable.other.readwrite
```

[JavaScript] Remove Mustache templating from JavaScript syntax.

---

Markdown/Markdown.sublime-syntax

...by correcting `((example)+)*` style patterns to `((example)+)?`
(originally discovered at https://github.com/google/fancy-regex/issues/14)

[Markdown] improve backtracking on non-sregex engines like Oniguruma

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

Add support for "repeated N times" in array preamble and improve robustness of array preamble by matching unexpected nested braces.
This improves #708 and fixes https://github.com/SublimeText/LaTeXTools/issues/1124

[LaTeX] Improve support for array package

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

fixes https://github.com/SublimeTextIssues/DefaultPackages/issues/176 (problems with autocompletion when typing `</` when a non-standard tag is used that is self-closing)

[HTML] support self-closing other/custom tags

---

CSS/CSS.sublime-syntax
CSS/css_completions.py

- Add `border-box`, `text-before-edge`, `text-after-edge`, `ruby-base`, `ruby-text`, `run-in`, `ruby-base-container`, and `ruby-text-container` to CSS syntax for correct highlighting, these already exist in _css_completions.py_
- Add `user-select` to completions. Although this still needs a prefix in most browsers (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) and [Caniuse](http://caniuse.com/#search=user-select)), having this part of the completions would be great as most users are probably using Autoprefixer

[CSS] Update missing values/properties

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

use the same scope for parameter separators in lambdas as for normal methods, for consistent highlighting.
Fix bug with lambdas with multiple parameters and no curly braces, similar to https://github.com/sublimehq/Packages/pull/788

[C#] make lambda parameter separator scope more specific

---

XML/XML.sublime-syntax
XML/syntax_test_xml.xml

this adds support for the `xml-model` preprocessor instruction, just like we added for `xml-stylesheet`: https://github.com/sublimehq/Packages/issues/882
https://www.w3.org/TR/xml-model/#the-xml-model-processing-instruction

[XML] support xml-model preprocessor instructions

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html
JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

For #889. Removes support for HTML comments in JavaScript, removes old tests, and adds new one.
When JavaScript was first introduced, not all browsers supported `<script>` tags. If such a browser encountered a `<script>` tag, it would usually display its contents on the page. In order to avoid this, an accepted practice was to wrap the interior of the `<script>` tag with HTML comment markers ``.
Now, `<script>` tags cannot contain HTML comments -- anything inside them will be interpreted as JavaScript code. In browsers that support JavaScript (i.e. every browser today), these HTML comments are interpreted as either valid syntax (e.g. `a --> b`) or a syntax error (` y;
//^^ keyword.operator.arithmetic.js
//  ^ keyword.operator.relational.js
```
It seems to be that correctly highlighting …
```

[JavaScript][HTML] Removed HTML comments from JavaScript.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

For #929. "Option 1": removing conditional compilation entirely.

[JavaScript] Removed IE conditional compilation. Added test to cover old bug.

---

Diff/diff.py

Pretty self-explanatory. Happens a lot when opening resource files that don't exist on the file system at the location that ST maps them to.
Closes https://github.com/SublimeTextIssues/DefaultPackages/issues/96.

[Diff] Handle non-existant files

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Part of my `SashaClassy.css` file:
```css
.SashaClass {
color: #a1b2c3d4;
}
.SashaClass {
color: #E5F6A7B8;
}
```
[**RGBA Hexadecimal**](https://en.wikipedia.org/wiki/RGBA_color_space#RGBA_hexadecimal_.28word-order.29) support.
```python
Success: 2266 assertions in 1 files passed
[Finished]
```
Thanks.

[CSS][Add] Scope for RGBA hexadecimal

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

The complex format string look-ahead disregarded string boundaries.
Fixes #1022.

[Python] Format strings don't extend past strings

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Notably: groups, function calls and function/class definitions.
Fixes #1018.

[Python] Parse line continuations in more places

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

This is not directly LaTeX syntax, but a suggestion to improve the handling of not directly supported behaviors by keeping the error local.
There have been a lot of issues of people opening math environments inside commands and not closing them, because it is not required with that specific command (but this specific command is not supported by the syntax definition). https://github.com/sublimehq/Packages/issues/544 https://github.com/sublimehq/Packages/issues/937 https://github.com/sublimehq/Packages/issues/472 https://github.com/SublimeText/LaTeXTools/issues/1124 https://github.com/SublimeText/LaTeXTools/issues/1104 https://github.com/SublimeText/LaTeXTools/issues/921 [tex.stackexchange#371105](https://tex.stackexchange.com/questions/371105/sublime-thinks-my-whole-text-is-an-equation) …

[LaTeX] Pop math environment on unmatched closing brace

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

They really don't make sense semantically, since the result will be a stringified generator, but they are valid syntax.

[Python] Allow generators inside f-strings

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

Comments (and other potential prototypes) should be disabled inside `\verb`-commands as done in this PR.
Fix https://github.com/SublimeText/LaTeXTools/issues/1135

[LaTeX] Disable prototype inside the verb command

---

C++/C++.sublime-syntax
C++/C.sublime-syntax
C++/syntax_test_accessor.c
C++/syntax_test_accessor.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_accessor.m
Objective-C/syntax_test_accessor.mm

For implementations of `on_query_completions` in event listeners, it'd be nice to check if the user wants to get completions for a member variable or member function. I think the most aesthetic way would be to do
```python
def on_query_completions(self, prefix, locations):
point = locations[0]
if self.view.match_selector(point - 1, 'punctuation.accessor'):
```
Now observe that:
* `->` is scoped greedily as an accessor, even when there's no identifier after it. 💯 
* `::` in C++ is scoped greedily as an accessor, even when there's no identifier after it. 💯 
* `.` in C and C++ is not scoped as an accessor when there's no identifier after it. 👎 
This forces plugin writers to use hacks:
```python
def on_query_completions(self, prefix, locations):
point = locations[0]
if …
```

[C] [C++] Greedily scope the "dot" as punctuation.accessor

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

(This PR formerly known as #1003)
The default JavaScript syntax definition is descended from an old `.tmLanguage`. Since its transition to a `.sublime-syntax`, it has largely modernized, but signs remain of its history.
One such sign is that the syntax definition does not use the new `prototype` feature for comments. Instead, the `comments` context is included manually. There are many dozens of contexts in the definition and somewhere between many and most of them should have manually included `comments`. An unknown number of those did not, resulting in at least one bug (#885, first test case).
In addition, the tests did not include any negative tests to ensure that comments were *not* included where they should not have been. No related bugs are known.
I have moved the `comments` include …

[JavaScript] Use prototype for comments

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

(This PR formerly known as #1004)
Fixes #874 and #894. Adds the test cases from #894; they seem to be comprehensive.

[JavaScript] Fix regex lookahead

---

C#/Indentation.tmPreferences

This PR describes (with comments) the indentation rules used for the C# syntax, and fixes it so that the following gets reindented properly:
```cs
new [] {
new Point {
X = 5,
Y = 10
},
new Point {
X = 7,
Y = 9
},
}
```
(previously, the `},` wouldn't have it's indentation decreased...
I also removed a rule that said to decrease indentation on lines that only contain whitespace followed by `{}` because it doesn't make any sense.

[C#] describe indentation rules and fix when a comma comes after a `}`

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

When initializing the members of a class in the initializer list of
the constructor, it may happen that variables are initialized with
an opening brace. This confused the syntax. This commit fixes that.
In response to https://github.com/sublimehq/Packages/issues/979.

[C++] [ObjC++] Fix uniform init in constructor init list

---

Scala/Scala.sublime-syntax

I legit have no idea how this ever worked.  My only guess is that if you `pop: true` when there is only a single context on the stack, Sublime will treat it as a `set: main`.
This fixes https://github.com/SublimeText-Markdown/MarkdownEditing/issues/430, and probably some other issues that I didn't know about.  Wasn't quite sure how to write a test for it, unfortunately.

[Scala] Fixed incorrect class decl state management

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

this makes it easier to find syntax errors in C# files by scoping stray closing braces as illegal, just like Python does. Previously the C# syntax did this, but only for curly braces and only at root level - i.e. when not inside a class or method etc.

[C#] more stray brace handling

---

Objective-C/Objective-C++.sublime-syntax

Some scopes ended in the c++ suffix instead of the objc++ suffix.

[Objective-C] Fix accidental *.c++ suffixes

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

this fixes a bug with text like `(see/visit http://www.link/)` where the `)` was being treated as part of the autolink when it shouldn't be:
https://github.github.com/gfm/#autolinks-extension-
> When an autolink ends in ), we scan the entire autolink for the total number of parentheses. If there is a greater number of closing parentheses than opening ones, we don’t consider the last character part of the autolink, in order to facilitate including an autolink inside a parenthesis
(Prior to this fix, it worked only if at least one open paren was in the link - it would correctly detect that there are more closing parens. But it didn't handle when no open parens were used. This fixes that.)

[Markdown] fix ) being treated as part of an autolink when it shouldn't

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

https://github.com/sublimehq/Packages/pull/1038 missed a case of stray braces in function calls. This corrects that, while limiting the amount of invalid highlighting, to help developers find the bug quickly without any extra distractions.

[C#] more stray brace detection

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

The context was never pushed off the stack.

[Python] Fix unclosed raw strings

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

fixes https://github.com/sublimehq/Packages/issues/992 - some property names are shorter versions of other valid property names, and were being matched first - thus preventing the longer names from matching. These have now been reordered to fix this.

[CSS] reorder some property matches to fix bugs

---

C#/C#.sublime-syntax
C#/tests/syntax_test_Comments.cs

...so scope the whole word at a time instead to workaround it
originally reported/discovered at https://forum.sublimetext.com/t/gwenzek-all-autocomplete-broken-in-st3-dev-for-c-mode/29925

[C#] individually scoped chars are not included in autocompletion

---

YAML/YAML.sublime-syntax

While `\p{XDigit}` works, alternate regex engines might interpret it
according to [UTS #18](http://www.unicode.org/reports/tr18/#Compatibility_Properties), which contains more than just the ASCII
characters, or not even implement it at all.
The YAML spec only contains the ASCII characters, see here:
http://yaml.org/spec/1.2/spec.html#id2775468

[YAML] Use non-ambiguous syntax for xdigit class

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Occasionally, there are method definitions like these:
```ruby
def bar(arg1,         # some comment
arg2,         # some other comment
opt1: 'foo',  # some other comment
opt2: 'bar')
```
This PR prevents sublime from confusing inline comments with method arguments/values.

[Ruby] inline comments in multiline parameter list

---

Go/Snippets/Type Function.sublime-snippet
Go/Snippets/func.sublime-snippet

[Go uses camelCase, not snake_case](https://golang.org/doc/effective_go.html#mixed-caps). In the `func` and `tfunc` snippets, the placeholder text for the function name was `func_name`. I replaced this with just `name`. The fact that it's a function name is implied.

[Go] Remove snake_case from placeholder text in Go func snippets

---

PHP/Snippets/Start-Docblock.sublime-snippet

Recently, a change was made to not trigger snippets in comments; however, this breaks the StartDocBlock snippet because it by-definition exists within a comment. Reverted that change on this snippet.

Revert broken change in StartDocBlock snippet.

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

[C#] fix for delegates with spaces between the name and paren bug

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

close #923 
close #933 
close #1006 
close #1136 
The issue was looking ahead pattern cannot be popped immediately, see https://github.com/SublimeTextIssues/Core/issues/1906#issuecomment-329536967

[Ruby] match /<regex>/ syntax explictly

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

For comments with an odd number of hyphens on the closing tag such as ``, the hyphens are marked invalid but everything in the entire file after the closing tag becomes highlighted as a comment.
This update fixes that bug, and also improves how invalid comments are marked, to match exactly in accordance with the W3 validator.
Preview of bug and invalid comment marks before this fix:

[HTML] fix invalid comment syntax highlighting bug

---

Markdown/Markdown.sublime-syntax
Markdown/Symbol List - Heading.tmPreferences
Markdown/syntax_test_markdown.md

This follows from a report on the forum. If two headers appear directly after each other, the first will eat the next and it will appear incorrectly in the symbols list:
https://forum.sublimetext.com/t/a-bug-of-markdowns-ctrl-r-panel/30872
This solves that by capturing the newline character and removing it from the symbol.
Questions:
- Originally the match was for `\n?`but I can't seem to get Sublime to capture the `\n` if I also use the `?`quantifier. Perhaps I'm missing something?
- Is `meta.whitespace.newline.markdown` a good scope? I couldn't find any examples.
Possible future improvements:
- Change it to lookahead for the newline and not capture it. I think it's a bit odd to capture it, but ¯\_(ツ)_/¯ . It would simplify things, but perhaps it breaks something somewhere. (something …

[Markdown] following headers appear incorrect in goto

---

Ruby/Miscellaneous.tmPreferences

fixes #1123
the biggest problem with indentation and unindentation rules are that they need to mirror/complement each other, otherwise you end up in exactly this situation where for e.g. `{` indents the line, but the corresponding `}` doesn't unindent it, or more rarely that a line gets unindented when nothing triggered an indentation previously. (Tweaks were also made to HTML to this effect a while ago: https://github.com/sublimehq/Packages/issues/915)
So for Ruby, a `{` or `[` anywhere on the line not followed by the respective closing token would cause indentation to be increased, but it would only then be decreased again for `}` or `]` if it was the only non-whitespace token on the line - this PR changes that to decrease the indentation when it is the first non-whitespace token on the …

[Ruby] unindent on closing curly brace or square bracket at bol

---

C#/C#.sublime-syntax
C#/tests/syntax_test_Strings.cs

* `\u` needs to be followed by 4 hex digits, `\U` by 8
* `\x` needs at least one hex digit
* Add missing escapes `\a` and `\v`
See spec: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#character-literals
(CC @trishume and @keith-hall)

[C#] Fix character escape sequences and add tests

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

The string was not recognized before, so with something like:
#[test = "foo ] bar"]
The first `]` would close the annotation, and the code/lines following
the second " would be recognized as a string.
Screenshot of the problem from Sublime Text 3:
Here's the documentation about attributes in Rust: https://doc.rust-lang.org/reference/attributes.html
CC @keith-hall and @trishume

[Rust] Fix handling of `#[attribute = "value"]` attributes

---

Python/Regular Expressions (Python).sublime-syntax

They *use* a variable and don't define it.

[Python] Don't scope conditionals as entities

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

[Markdown] don't treat emphasized pipes as the start of a table

---

Regular Expressions/RegExp.sublime-syntax
Regular Expressions/syntax_test_regexp.re

add GNU word bounaries `\<` and `\>` as these are used by Boost, which ST uses in the Find panel, which is highlighted using this syntax.
see also http://www.regular-expressions.info/wordboundaries.html#gnu

[Regular Expressions] add GNU word bounaries \< and \>

---

Rails/Snippets/assert_rjs.sublime-snippet
Rails/Snippets/find(%3Aall).sublime-snippet
Rails/Snippets/find(%3Afirst).sublime-snippet
Rails/Snippets/page_hide-(%2Aids).sublime-snippet
Rails/Snippets/page_insert_html-(position-id-partial).sublime-snippet
Rails/Snippets/page_replace-(id-partial).sublime-snippet
Rails/Snippets/page_replace_html-(id-partial).sublime-snippet
Rails/Snippets/page_show-(%2Aids).sublime-snippet
Rails/Snippets/page_toggle-(%2Aids).sublime-snippet
Rails/Snippets/page_visual_effect-(effect-id).sublime-snippet

Delete RJS-related snippets – not a thing since Rails 3.1
Delete `find(:all)` and `find(:first)` – dropped in Rails 3.? in favour of .all and .first

[Rails] Drop legacy snippets

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Prior to this PR, the following HTML gets reindented incorrectly:
- new tab
- set syntax to HTML
- `html` <kbd>Tab</kbd>
- type `<sty` <kbd>Tab</kbd><kbd>Enter</kbd>
- looks fine, but reindent it =
```html
<!DOCTYPE html>
<html>
<head>
<title></title>
<style type="text/css">
</style>
</head>
<body>
</body>
</html>
```
this PR fixes that by capturing the whitespace (specifically the newline) after the `<style>` tag, so that it doesn't get a CSS (`source.css`) scope, which was causing the CSS indentation rules take over, and thus not indenting after `<style>\n`. Which was a problem, because it unindents after `</style>` (due to the newline after that having the html scope), and thus the indentation was getting out of kilter.

[HTML] fix reindentation of style tag

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

fix #1066 and https://github.com/sublimehq/Packages/issues/1100

[CSS] support 0 lengths i.e. for translateZ function and var function in other transform functions

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Prior to this PR, the HTML comment blocks had no scope at all applied to the closing comment punctuation (`-->`), and the opening comment punctuation (`<!--`) was missing the `.begin` that is common to all comment blocks. This PR fixes that, and brings it in line with all the other packages, which will allow color schemes to color said punctuation properly, and plugins to make proper use of it too.

[HTML] correctly scope comment punctuation

---

Ruby/Miscellaneous.tmPreferences

[Ruby] indent def when an access modifier preceeds it

---

Graphviz/DOT.sublime-syntax
Graphviz/Indentation Rules.tmPreferences
Graphviz/Symbol List.tmPreferences
Graphviz/syntax_test_dot.dot

- Add scopes for lots of punctuation.
- Add `.gv` as additional file extension.
- Add graph names to file indexing.
- Steal some indentation code that I don't understand particularly well.
- If there's some documentation I should look at, please feel free to point me at it.
- Add basic support for HTML labels. This is a little buggy, but still much more functional than it used to be.
If there are comments on the scopes, I'm happy to change them. Particular attention should be paid to [these lines](https://github.com/michaelblyons/SublimeText-Packages/blob/3fc25bd5cba0a2db6b9ca517cc8a6fa29a368a16/Graphviz/DOT.sublime-syntax#L15-L19) where I picked an arbitrary scope both for what a `graph` _is_ and also what the `cluster` prefix means for `subgraph`. I absolutely think the `cluster` prefix …

[Graphviz] improvements

---

HTML/html_completions.py
PHP/PHP.sublime-completions

allow HTML autocompletion inside PHP HTML heredoc strings
i.e.
```
<?php echo <<<HTML
HTML;
?>
```

[HTML] allow HTML autocompletion inside PHP HTML heredoc strings

---

Makefile/Comments.tmPreferences
Makefile/Makefile.sublime-settings
Makefile/Makefile.sublime-syntax
Makefile/Miscellaneous.tmPreferences
Makefile/syntax_test_makefile.mak

Fixes both https://github.com/sublimehq/Packages/issues/968 as well as https://github.com/sublimehq/Packages/issues/903. Also see https://github.com/sublimehq/Packages/issues/481.
The current syntax has a collection of problems:
1. It has various positive lookbehinds. This caused problems (https://github.com/sublimehq/Packages/issues/903).
2. It forces you to use tabs for indenting recipes.
3. It cannot detect wether something is the body of a recipe, or just regular indentation for an `ifeq/else/endif` block.
4. It has its own little subset of a shell-like syntax. This is used for highlighting recipe lines.
1. This refactoring has **zero look behinds**. Everything is done with look aheads.
2. You can use tabs or spaces for indenting recipe lines. It can detect recipes with mixed …

[Makefile] Big refactor

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

If we're inside backticks, we should look ahead for a backtick and then pop. Forgot to account for this after an end-of-options token. [See this forum post for reference](https://forum.sublimetext.com/t/bug-broken-highlighting-with-bash/32402).

[ShellScript] Fix not popping backtick after end-of-options token

---

ShellScript/Indentation.tmPreferences

This makes `then` keyword to have the same indentation level as the corresponding `if` and also makes the code following `then` be indented one level deeper.
See this topic: https://forum.sublimetext.com/t/incorrect-auto-indentation-for-bash-if-then/

[ShellScript] Fix if/then indentation

---

C++/Default.sublime-keymap
Objective-C/Default.sublime-keymap

This has annoyed me for several years, but I never got around to fixing it. I also assumed someone else would do this :-). Anyway, this does what it says on the tin: auto-pairing of "<>" inside meta.preprocessor.include scopes.
For instance, if you type this now:
```c
#include <|
```
(the `|` represents the cursor), Then it'll insert the `>` automatically now:
```c
#include <|>
```
When you then type `>`, the cursor will just move over the existing `>`:
```c
#include <>|
```
This functionality is already present in the default keybindings and well-known by everyone for e.g. double-quotes. I just copied that and adjusted it accordingly.

[C++] [Objective-C] Auto-pair "<" and ">" inside meta.preprocessor.include

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

Fixes #1104 (commit 62f0be2).
Also:
- Use punctuation.section for parens, brackets and braces,
- Use variable.function for function calls instead of entity.name.function,
- Remove redundant single quotes around various regexes,
- Use "scope: ..." instead of a single "captures: 1: ...",
- Add syntax test file.

[Erlang] Fix issue 1104, and cosmetics, and start on syntax file

---

C++/C Standard Includes.sublime-completions
C++/C++ Standard Includes.sublime-completions
Objective-C/Objective-C++.sublime-syntax
Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m

What this does: it presents the standard libraries in the completion widget when you're inside of an `#include <...>`.
I had to adjust the way the ObjC syntax scopes "#import ..." for this. It used to assign a meta scope of `meta.preprocessor.include`, but it now assigns a meta scope of `meta.preprocessor.import`. The "#include ..." statements still receive `meta.preprocessor.include` for their meta scope. This is done so that the completions only trigger for an #include and not for an #import.
This works great in conjunction with https://github.com/sublimehq/Packages/pull/1094.

[C++] [Objective-C] Add standard library include completions

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

- Annotations can only contain alphabetical ids
- Tricky over-disambiguation issues on ids starting with `=` and containing a `>`

[Scala] Minor symbolic id bugs

---

C++/C++.sublime-syntax
C++/C.sublime-syntax
C++/syntax_test_c.c
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m

Fix for https://github.com/sublimehq/Packages/issues/1041.
Commit 3eabef5 is separate because Objective-C was missing a bunch of declspec handling. This made me wonder wether this was intentional or not. If it's intentional, then it's easy to revert that commit now.

[C++] [Objective-C] Fix declspec highlighting

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

- Use the generic_lookahead variable to scout ahead for a closing ">" when
encountering an opening "<" for member variables/methods. [From here](https://github.com/pybind/pybind11/blob/1e6172d4055d654df466f32b8327de7145bc9ea3/include/pybind11/cast.h#L292).
- Inside of a template parameter list, make sure we match "<=" first, before
we push another template scope. [From here](https://github.com/pybind/pybind11/blob/1e6172d4055d654df466f32b8327de7145bc9ea3/include/pybind11/cast.h#L928).

[C++] [Objective-C] Fix too greedy template bracket matchings

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs
C#/tests/syntax_test_GeneralStructure.cs

This PR adds much better C#7 support:
- [`out` variables](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#out-variables)
- [Tuples](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#tuples)
- [`ref` locals and returns](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#ref-locals-and-returns)
- [local functions](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#local-functions) (prior to this PR, it worked for functions that didn't return generic types)
NOTE: [numeric literal improvements](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#numeric-literal-syntax-improvements) remain in https://github.com/sublimehq/Packages/pull/1047

[C#] better C#7 support

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

...so that the function declaration scope is continuous. Fixes #1230

[JavaScript] scope whitespace between function name and parameters

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Discovered randomly while investigating some code base a few weeks ago.
A string on the continued line would cause the pop pattern not being
matched, which in return meant the line continuation context wasn't
exited and whitespaces until the first non-string character were
consumed, which in return caused def and class statements to match as
invalid, since those require to be written on their own line.
(What a nice sentence.)
Previously failing test:

[Python] Fix line continuation not popping properly

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

The string prefixes are not part of the actual string, so they shouldn't be scoped as such. Should ease the life of BracketHighlighter, for example (cc @facelessuser).

[Python] Exclude string type from string scope

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Fixes:
1. `==`, `<<`,  `>>`, `*=` and similar not being drawn with ligature.
2. `|`, `&`, `^` and `~` not being treated as operators.
Before:
After:

[Java] Add scopes for all operators

---

RestructuredText/reStructuredText.sublime-syntax
RestructuredText/syntax_test_restructuredtext.rst

In reStructured Text, comments are multiline if they are indented after the initial `..`. Hence we need to capture up to, but not including the first non-whitespace character on a subsequent line.
See http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#comments.

[RST] Support multi-line comments

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

```php
<?php
$foo::BAZ;
$foo->bar::BAZ;
$foo->bar['x']::BAZ;
```
It look like GitHub's code highlight doesn't highlight it well either.

[PHP] Fix the static accessor (::) is not scoped

---

XML/XML.sublime-settings

I've found myself working with .NET Core 2 a bit recently, and I noticed that the [`csproj` format](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) is XML but never includes a the XML declaration prolog. Therefore, the first line match regex pattern never matches, and one has to assign the XML syntax highlighting manually. 
I figured other people would also benefit from ST recognizing `.csproj` files as XML, so I've added it to the `hidden_extensions` in the `XML.sublime-settings` file (which already caters for`vcproj` files this way).

[XML] add csproj as a hidden extension

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

`==` is an equality check, not an assignment, but prior to this PR, it was being scoped incorrectly in method calls. This also meant that some arguments to the method had different scopes and colors to other arguments, which was wrong.
i.e. `Console.WriteLine(hello == true, world);` - `hello` and `world` are both just normal variables and should be scoped the same, and the `==` is not an assignment but an equality check.

[C#] fix bug whereby == was being scoped as an assignment in a func call

---

Graphviz/DOT.sublime-syntax
Graphviz/syntax_test_dot.dot

This PR updates the Graphviz syntax to use the new `embed`/`escape` action for embedded HTML and updates the `comments` context to use the preferred style of pushing into a context and pushing at the end of the line (instead of matching the comment start token and the rest of the line in one pattern).

[Graphviz] use new embed action for embedded HTML and tidy up comments

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Assign meta and punctuation scopes.
Fixes https://github.com/sublimehq/Packages/issues/703.

[Python] Properly match all block statements

---

Lisp/Lisp.sublime-syntax

`.clisp` is a common file extension for common-lisp files.

Add .clisp file extension for 'lisp' syntax

---

Python/Snippets/New-Property.sublime-snippet

fixes #1264
Due to scope changes the "New-Property" snippet was no longer available to end users.
Therefore the snippet scope needs to be changed to `meta.annotation`, too.

[Python] Fix New-Property snippet not being suggested

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

fix the issue mentioned in https://github.com/sublimehq/Packages/pull/1142#issuecomment-335493118

[ruby] need to pop the context earlier to match regex

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

However, still do highlight them for `import str` to indicate potential naming collisions with built-in types.
Also highlight invalid relative imports (i.e. `import .anything`).
Fixes #1250.

[Python] Don't highlight types in `from` lists

---

C#/C#.sublime-syntax
C#/tests/syntax_test_Using.cs

some support for namespace aliases already existed in the C# syntax definition, but it was missing for `using` directives. This PR adds that, and thus fixes #1283. It also marks the `;` as a terminator instead of invalid when namespaces are expected but missing.

[C#] support namespace aliases in using directives

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

based on a discussion on Discord, this allows plugins (and color schemes, if so desired) to tell where the number begins and ends, compared to the punctuation that isn't part of the number, but specifies what base the number is in.
(There is also a PR for C# that does the same: https://github.com/sublimehq/Packages/pull/1047)

[Python] scope numeric punctuation that marks which base to use

---

Batch File/Batch File.sublime-syntax
Batch File/syntax_test_batch_file.bat

Issue:
1. https://github.com/sublimehq/Packages/issues/1090

[batch] Fixes comments last line character is not scoped

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

fix #1220 
After merging this PR and https://github.com/sublimehq/Packages/pull/1225, [this file](https://github.com/llvm-mirror/llvm/blob/master/cmake/config.guess) should highlight correctly. The problematic regions are [here](https://github.com/llvm-mirror/llvm/blob/0446db2b0e822bb1abb094bf3ff3eda824ddc457/cmake/config.guess#L138-L141) and [here](https://github.com/llvm-mirror/llvm/blob/0446db2b0e822bb1abb094bf3ff3eda824ddc457/cmake/config.guess#L438-L458).

[ShellScript] Split up compound statement into backticks and non-backticks version

---

PHP/Indentation Rules - heredoc end.tmPreferences
PHP/Indentation Rules.tmPreferences
PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

Previously, having code like
```php
<?php
function test () {
echo <<<HTML
<table class="table table-bordered table-striped sup1em" id="tableResponsive">
<thead>
<tr>
<th class="text-center linhaStatus">ID Pedido</th>
<th class="text-center">Cliente / Destino</th>
<th class="text-center">Pedido</th>
<th class="text-center linhaStatus">Gerenciar</th>
</tr>
</thead>
</table>
HTML;
}
?>
```
and then doing a full "Reindent" would cause the `HTML;` to be indented and thus no longer close the HEREDOC. This PR fixes that by:
- scoping the semi-colon and newline after the heredoc (if present) with a meta scope
- targeting that meta scope with some indentation rules (this required the specificity of the main PHP indentation rules to be tweaked slightly) to:
- ignore lines ending with this meta …

[PHP] always keep the closing heredoc keyword unindented

---

ShellScript/Snippets/#!-usr-bin-env-(!env).sublime-snippet

Fix #1118. The `#!/usr/bin/env` snippet didn't have a scope, so it would always be offered, even if the current syntax wasn't `Shell Script (Bash)`.

[ShellScript] Add scopes to #!/usr/bin/env snippet

---

Java/Symbol List%3A Constants.tmPreferences

Now that the java syntax has been updated we can add the constants to the symbol list.

Java: Add constant entities to symbol list

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

and prevent the newline from getting scoped as entity.name.function.
For example, before this commit we got this
```
function foo
{
echo 'hello from foo'
}
```
but this is now corrected:
```
function foo
{
echo 'hello from foo'
}
```
Moreover, functions in functions are correctly recognized now:
```
function foo {
function bar {
echo 'hello from bar'
}
bar
}
foo
```
closes https://github.com/SublimeTextIssues/DefaultPackages/issues/178

[ShellScript] Allow functions in functions

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Missed this when I added the normal matrix multiplication operator.

[Python] Augmented assignment for matrix multi

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

```php
$var2 = -123e10;
//       ^^^^^^ constant.numeric.float.decimal
```

[PHP] Fix scopes for scientific number notation

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

They were deprecated in 3.6 and will eventually become a SyntaxError in
a future version.
This shouldn't be used in your code anyway, so highlighting them will make it easier to spot that you're specifying Windows paths without proper escaping or not within a raw string, for example.
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

[Python] Mark invalid character escapes as deprecated

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

As raised in https://github.com/sublimehq/Packages/issues/458, this PR adds highlighting of "constant variables" in SCREAM_CASE. I tried to add a little heuristic in requiring at least 3 upper case characters for normal names to be recognized as a constant, in case people were using smaller ones such as `A` or `B` for class names. Dotted names only need one upper case letter because of enums and the like.
Function calls and decorators are not covered by this, since those already have `variable.function`.
I chose `variable.other.constant` based on its usage in other syntaxes, notably JavaScript, Ruby and OCaml.
https://github.com/sublimehq/Packages/search?utf8=%E2%9C%93&q=%22variable.other.constant%22&type=
`entity.name.constant` and indexing for assignments will be added at a later time …

[Python] Add highlighting for "variable" constants

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

`_` in itself does not have a special meaning, but it is a
conventionally used identifier much like `self` and `cls` for when you
don't want to store a value into a variable but are required to do so
syntactically.
This is usually the case for unpacking/pattern matching tuples or lists,
or in for loops.
Additionally, `_` has a special meaning in an interactive session where
it refers to the value returned by the last expression executed.

[Python] Highlight `_` as language variable

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

New regex for numbers. Old one was definitely C-inspired as Java doesn't have `U` modifier.
New one handles underscores in numbers (like `123_45_6`) and binary numbers (`0b00110101`).

[Java] Better handling of numbers

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

```php
try {
// ...
} catch (/* comment */ Exception $e) {
//       ^^^^^^^^^^^^^ comment.block
}
```

[PHP] Fix comments scope inside "catch" parentheses

---

LaTeX/LaTeX.sublime-syntax

The LaTeX syntax does not assign the correct scope to the cite function `\citeyearpar`.` \citeyearpar` has the scope `support.function.general.latex` but should be `support.function.cite.latex` (like all other cite function).

[LaTeX] Correct scope for \citeyearpar cite command

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Also highlight invalid names in the `from` section.
Fixes #1300.

[Python] Fix `from . import` relative imports

---

CSS/css_completions.py

Most auto-completion packages provide basic information about their suggestions as hints right next to each item, which distinguishes auto-completion items very clearly from word-completions.
CSS disables word-completions, but it is not obvious to the end user.
Therefore this commit adds a hint to each returned completion item to allow the end user to clearly see it is a valid value from a database but not something ST might have caught from anywhere in the text.

[CSS] Add a hint to each completion item

---

CSS/css_completions.py

The `find` seems a bit more expensive than using `x in list`. After this commit collecting completions for "padding" values was reduced from 70ms to 50ms on each first run. The time savings vary very much but seem smaller in most cases.

[CSS] Avoid calling find

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Other syntax files already have this, why not add it to Java.
Match rules are copied from js syntax.

[Java] 'invalid.illegal' for strings without closing quote

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Prior to this commit the globally valid keyword @counter-style was highlighted as `entity.name.tag.custom` if no style-name is provided between it and the next `{`.
Even though the style-name is required the keyword must/should be scoped correctly if it is missing in order to avoid confusion.
Therefore this commit marks the style-name as optional to fix scoping of incomplete counter-style rules.

[CSS] Fix @counter-style not scoped correctly if name is missing

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

1. If a default value in annotation's definition is a string it is not highlighted:
2. Annotation's definition only works after an access modifier:
3. Annotations are not highlighted when used as parameters to other annotations:

[Java] Annotation-related fixes

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

It was `storage.modifier` for some reason.

[Java] Fix 'throws' keyword has a wrong scope

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

Implements the [class fields proposal](https://github.com/tc39/proposal-class-fields). See #1269 for more discussion. Also resolves #1238 and partially resolves #876.
Outline of changes:
- No longer recognize the `static` keyword in object literals. It should be interpreted as an identifier.
- In classes, rescope `static` as `storage.modifier`. It was previously scoped as `storage.type`.
- Recognize class property declarations and initializers in class bodies.
- Recognize private class properties in expressions.
Relevant to https://github.com/tc39/proposal-class-fields/issues/57.

[JavaScript] Add support for class fields

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

Implements the [BigInt](https://github.com/tc39/proposal-bigint) and [Numeric Separators](https://github.com/tc39/proposal-numeric-separator) proposals. See #1269.

[JavaScript] Add BigInt suffix and Numeric Separators

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

You should now be able to directly export function and class declarations. Added tests to verify.
Fixes #1322.

[JavaScript] Support `export function|class` form

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

For #1305. Fixes the below cases.
```html
<div
title = "description"></div>
<div title=
"description"></div>
<div title
="description"></div>
```
This is a bulkier change than I'd like because it wasn't possible to reuse most of the contexts due to minor scope differences. I'm not convinced of the utility of scopes like `meta.attribute-with-value.event.html`, but I left them in.
All attributes will now get the `meta.attribute-with-value` scope. In general, it is not possible to tell whether an attribute has a value without looking over line boundaries. If we really want to maintain the distinction for some reason, it should be possible to make some good guesses at the expense of considerable complexity. I'm generally skeptical about this sort of thing. If we don't want to maintain the …

[HTML] Fixed most problems with whitespace in attributes.

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs

https://blogs.msdn.microsoft.com/mazhou/2017/11/21/c-7-series-part-6-read-only-structs/

[C#] support readonly structs

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

`yield` and `await` now work inside expressions:
```js
x = yield;
//      ^^^^^ keyword.control.flow
x = yield * 42;
//      ^^^^^ keyword.control.flow
//            ^ keyword.generator.asterisk
x = yield
function f() {}
[];
//  ^^ meta.sequence - meta.brackets
x = yield*
function f() {}
[];
//  ^^ meta.brackets - meta.sequence
y = await 42;
//      ^^^^^ keyword.control.flow
```
This does introduce a bug in that `yield` and `await` should be valid identifiers outside generator and async functions, respectively. The ECMAScript formal syntax represents this by using weird EBNF with parameterized productions. The equivalent implementation for JavaScript would be to have four near-complete copies of the syntax, one for async generators, one for non-async generators, one for async …

[JavaScript] `yield` and `await` expressions

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

```js
for await (const item of list) {}
```

[JavaScript] Implemented `for await`.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

```js
debugger;
// <- keyword.other.debugger
debugger
[]
// <- meta.sequence
```

[JavaScript] Debugger statement is no longer an expression. Improved scope.

---

D/D.sublime-syntax
D/syntax_test_d.d

Since recently (http://forum.dlang.org/post/esjclvbebspqkekjmwki@forum.dlang.org) the `do` keyword can be used in place of the `body` keyword in function declarations with contracts.

Upate D.sublime-syntax for new function contracts.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

In JavaScript, a class can extend an arbitrary expression.
```js
class Foo extends React.Component {}
//                      ^^^^^^^^^ entity.other.inherited-class
class Foo extends
//        ^^^^^^^ storage.modifier.extends
Bar {}
class Foo extends getSomeClass() {}
//                ^^^^^^^^^^^^ meta.function-call variable.function - entity.other.inherited-class
```

[JavaScript] Arbitrary expressions in `extend`.

---

Java/Java.sublime-syntax
Java/JavaDoc.sublime-syntax
Java/syntax_test_java.java

Javadoc's syntax hasn't been changed since tmLanguage era and there are so many things wrong with it so I just redid it from the scratch.
'Strategic' changes:
1. Syntax is now hidden. It is part of Java, by itself it's pointless.
2. It is not included anymore, it now relies on new `embed`/`escape` functionality. This fixes issue #1216.
3. URL's highlighting was removed. It isn't part of the javadoc, links are defined with html's `<a>` tag (which is already highlighted).
Fixes/improvements:
1. One-line javadocs now work.
2. Leading html tag doesn't turn off the highlighting.
3. Lines without leading asterisk are not treated as invalid anymore. The asterisk is optional since 2002.
4. All inline tags can now be multiline. They do not re-highlight the leading asterisk.
5. 'code' tag now …

[Java] Refactor javadoc

---

JavaScript/JavaScript.sublime-syntax
JavaScript/syntax_test_js.js

Implemented object literal [spread properties](https://github.com/tc39/proposal-object-rest-spread). (Stage 3, widely used, very stable.)
Also fixed inconsistencies with computed property names:
The square brackets were sometimes `punctuation.section.brackets` and sometimes `punctuation.definition.symbol`. The latter seems clearly wrong, so I standardized on the former.
When the value of a property is a function expression (determined by lookahead), we generally try to scope the property name as `entity.name.function`. This works fine with literal property names, mostly fine with string and number property names, and not at all for computed property names. Consider the following:
```js
({
[foo.bar]: function() {}
})
```
The string `foo.bar` was scoped `entity.name.function`. But this is …

[JavaScript] Added spread operator and made computed property names consistent.

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Fully qualified name (FQN) is mentioned in issue #736.
Here is the way FQN is scoped now:
```
com.example.component.ClassName
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ support.class
^ punctuation.accessor.dot
```
My problem with that is that only last dot is scoped and has its own color. Instead it should be scoped like this:
```
com.example.component.ClassName
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.path
^^^ support.type.package
^ punctuation.accessor.dot
^^^^^^^ support.type.package
...
^ punctuation.accessor.dot
^^^^^^^^^ support.class
```
To achieve this I completely redid name's matching. I also heavily modified contexts that are mostly something around an FQN (like generics and import statements) and tweaked some others. Unfortunately the deeper you dig the more broken stuff you find. …

[Java] Fully Qualified Name

---

Groovy/Groovy.sublime-syntax
Groovy/tests/syntax_test_Strings.groovy

- Highlight triple quoted strings
- Highlight "dollar slashy strings"
- Highlight unclosed strings
- Highlight erroneous newlines in single line strings
- Highlight invalid identifiers in interpolated strings
- Highlight interpolation in slashy strings ("regexp")
- Enable full language highlighting inside interpolation
- Only include the proper unicode ranges in identifiers (variables)
inside string interpolation.
- Only match valid escape sequences (instead of any character at all);
note that the different kinds of strings don't share all of the same
escape sequences.
- Add a whole bunch of tests for strings
Note: Technically "slashy strings" (scoped as "regexp" here) allow
newlines as well, but I think more work needs to be done before
removing the lookahead expression on the opening …

[Groovy] Improve string syntax highlighting

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Currently, when the JavaScript syntax sees an unexpected close paren mid-expression, it marks it as invalid in a very eager fashion. This can disrupt highlighting when typing a line. For instance, the following test fails:
```js
myArray.map(element => /* typing here */)
{}
// <- meta.block - meta.object-literal
```
Because this syntax is invalid, we can choose to highlight it whatever way is convenient. In this case, I would prefer that the invalid close paren be interpreted as ending the arrow function and the `map` function call. This will preserve highlighting of subsequent code; it won't "flicker" while you're typing.
All tests pass. New tests have been added for error cases that were not present in the original tests.

[JavaScript] Improved handling of unexpected close punctuation.

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

- Redirections may occur *before* a command. For example: `2>&1 echo foo`.
- Redirections may occur *after* a variable assignment. For example: `LC_ALL=C 2> /dev/null`.
Related (but doesn't close): https://github.com/sublimehq/Packages/issues/1358

[ShellScript] Refactor redirection handling

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

You can have functions defined *inside* command substitutions. e.g.
```bash
foo=$(
func() {
echo bar
}
func
)
echo $foo # prints "bar"
```
Related to, but doesn't close, https://github.com/sublimehq/Packages/issues/1358

[ShellScript] Fix: func defs in command substitutions are allowed

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

You can define variables inside sub shells, e.g.
```
#!/bin/bash
(foo=bar)
```
Related to, but doesn't close, https://github.com/sublimehq/Packages/issues/1358

[ShellScript] Fix: lookahead for (more) metachars in variable assignments

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

For example:
```bash
#!/bin/bash
foo=" #bar"
echo ${foo# #} # prints "bar"
```
Related to https://github.com/sublimehq/Packages/issues/1358.

[ShellScript] Fix: Unescaped hash inside parameter expansion breaks file

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

Related: https://github.com/sublimehq/Packages/issues/1358
These constructs should not break highlighting anymore:
```bash
[[ a == [abc[]* ]]
: ${foo//[abc[]/x}
if [[ ' foobar' == [\ ]foo* ]]; then
:
fi
```

[ShellScript] Fix: regex set handling

---

Java/Comments - Properties.tmPreferences
Java/JavaProperties.sublime-syntax
Java/Symbol List - Properties.tmPreferences
Java/syntax_test_java_properties.properties

Another remnant of the TextMate era. The format is really simple but has its own 'hidden features'.
Changes:
1. Property key and value are now scoped as `entity.name.key` and `string.unquoted` respectively. Key's scope is added to symbols' list.
2. Line continuation and escapes are recognized.
3. `tmPreferences` with settings for line comments.
4. Block comments were removed as there is no such thing.

[Java] Refactor Java Properties

---

Regular Expressions/Comments.tmPreferences

This PR adds the required `tmPreferences` metadata file to enable support for the "toggle block comment" functionality in ST. Maybe in future we will want to get fancy and allow line comments to be toggled when in extended mode, but this PR simply uses the `(?#...)` block style comments in all situations.

[Regular Expressions] enable toggle block comment support

---

R/R.sublime-syntax
R/syntax_test_r.R

In some cases, parameters are wrongly detected as `entity.name`

[R] fix bug in detecting function parameters

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs

this PR adds support for `ValueTuples` in generic type declarations - prior to this, tuples were scoped correctly as part of normal method declarations but not when the method is declared as a generic `Func`.
More info on ValueTuples can be found at https://blogs.msdn.microsoft.com/mazhou/2017/05/26/c-7-series-part-1-value-tuples/.

[C#] support value tuples in generic types

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

[PHPDoc Tags](https://docs.phpdoc.org/guides/docblocks.html#tags) are a type of specialized information (meta-data) about the associated element.
A tag always starts on a new line with an at-sign (@) followed by the name of the tag. Between the start of the line and the tag’s name (including at-sign) there may be one or more spaces or tabs. The following is an example of a simple tag:
```
/**
* @source
*/
```
In addition to their name each tag may have arguments that can provide additional context specific for that tag. The most common example of this is the @param tag, with which the argument of a method or function is documented:
```
/**
* @param string $argument1 This is the description.
*/
```
In the example above we can see that the @param tag features an argument that tells you that …

[PHP] Add highlight support for multiple phpdoc tags with tests

---

ActionScript/ActionScript.sublime-build

While ActionScript might no longer have much of an significance in 2017, I thought it should at least come with a build-system.

Add build-system for ActionScript

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Should fix [this bug](https://forum.sublimetext.com/t/goto-symbol-broken-for-js-coffee/35145), as well as another bug where whitespace after function parameter lists was double-scoped.

[JavaScript] Removed meta.function.declaration scopes in wrong places.

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

This PR adds support for [Rust's raw pointers](https://doc.rust-lang.org/book/first-edition/raw-pointers.html), and fixes #1279.

[Rust] support raw pointers

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

In HTML, `<script>` tags usually contain JavaScript code and `<style>` tags usually contain CSS. However, if the tag's `type` attribute is set to a value other than `text/javascript` or `text/css` (respectively), the tag's contents will not be processed. The default HTML syntax handles this with a lookahead. However, there are several cases where this lookahead will fail:
```html
<script type='other'>
var x = 0;
</script>
<script
type='text/other'>
var x = 0;
</script>
<script type=text/javascriptFOO>
var x = 0;
</script>
```
This PR adds a robust system for detecting attributes that determine the language. As implemented, this should handle all of the corner cases for JavaScript and CSS. In addition, third parties could use a system like YAML Macros to easily extend the core syntax with …

[HTML] Improved language detection in `<script>` and `<style>` tags

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

PHP 7.2 introduces the "object" type hint: https://wiki.php.net/rfc/object-typehint
Without this modification, it looks actually like this:
After this PR, it will correctly use the same colors of the other type hints:

[PHP] Add new type hinting "object" for PHP 7.2

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Should fix #1367 and #1377. Tests added.
The Python syntax should probably have comments in the prototype rather than including it manually. I ran into a comment bug while working on this, and there are probably more lurking. It's much easier to put `meta_include_prototype: false` in a handful of places than `include: comments` in dozens of places.
There was a bit of invalid Python in a test, and fixing this broke the following test. I changed the first test to avoid the problem. It's possible that there's some special error behavior that the first test is trying to trigger; someone more familiar with the Python syntax definition might take a look.

[Python] Fixed a couple of newline-related bugs.

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

As noted [on the forum](https://forum.sublimetext.com/t/html-comment-false-highlighting/34605), the HTML syntax definition currently marks strings of hyphens inside comments as errors. This is congruent with the [HTML4](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.4) spec. However, the [HTML5](https://www.w3.org/TR/html5/syntax.html#comments) spec is more lenient. This PR updates the HTML syntax definition and tests to use the HTML5 rules.

[HTML] Updated comment errors for HTML5.

---

HTML/HTML.sublime-syntax

Added valid HTML tags listed on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element), including:
- audio
- bdi
- canvas
- datalist
- details
- dialog
- figcaption
- figure
- mark
- menu
- menuitem
- meter
- output
- picture
- progress
- rp
- rt
- rtc
- ruby
- source
- summary
- template
- time
- track
- video
- wbr

[HTML] Added HTML5 tags. Factored out lists of tag names.

---

HTML/HTML.sublime-syntax
HTML/html_completions.py

auxclick is new event, equivalent to click but for non-primary mouse buttons. [Spec](https://w3c.github.io/uievents/#event-type-auxclick).
Implemented in at least Blink and Gecko.
I didn't add a syntax test for this on the basis that it wouldn't add anything over the [existing event attribute test](https://github.com/sublimehq/Packages/blob/e0759e08f54b51a436f589c51b836ac3ae5894b1/HTML/syntax_test_html.html#L213), but if you disagree I'm more than happy to write one.

[HTML] Add the onauxclick event attribute

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

Some interplay between the last few merges caused a regression where an empty array assignment is incorrectly scoped as the start of a function definition. The fix is one extra byte in the `is_function` lookahead.
```bash
#!/bin/bash
my_array=()
```

[ShellScript] Fix: empty array assignment regression

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #1419. Also removes an unreachable rule.
Spec: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

[HTML] Should handle all HTML5 attribute names.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js
JavaScript/tests/syntax_test_js_bindings.js

Adapted variable binding pattern logic from #1338 to handle function parameters, finishing #1102. Should now cover all corner cases. Added comprehensive tests.
Notes:
- Commas in function parameter lists are scoped `punctuation.separator.parameter` rather than `punctuation.separator.comma`. I preserve the old behavior here. I'm not sure what the reason is for the distinction.
- Function parameter initializers were formerly scoped `meta.parameter.optional`. This is not a standard scope, and I'm not sure what its purpose would be. (No other syntaxes appear to use this scope, excepting syntaxes derived directly from this one.) If we do want to differentiate parameters with initializers, I'm open to suggestions on how to do it.
- Object destructuring patterns were formerly scoped …

[JavaScript] Improved function parameter bindings (and tests).

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

See documentation at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target).
The `meta.instance.constructor.js` scope complicates this. When we see `new`, we can't reliably tell whether it's followed by `.target` or an expression. In order to apply that meta scope, we have to guess anyway; then, we have to recover from a wrong guess. No independent syntax appears to use the `meta.instance` scope, so it might be a good candidate for removal.

[JavaScript] Added new.target construct.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

[TC39 proposal](https://github.com/tc39/proposal-object-rest-spread) (Stage 4, implemented and widely used in Babel).
Also added tests for object rest spread.
Reported [here](https://github.com/Thom1729/Sublime-JS-Custom/issues/19).
Looks like the bug was introduced in #1344.

[JavaScript] Object literal rest spread handles complex expressions.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

```js
(
()
=> { return; }
//  ^^ storage.type.function.arrow
//     ^^^^^^^^^^^ meta.block - meta.object-literal
//       ^^^^^^ keyword.control.flow
);
```
Fixes the bug identified in #1430.

[JavaScript] Fixed arrow function body block bug.

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Java 10 is almost here so we can add this feature to the syntax.
`var` is explained here: http://openjdk.java.net/jeps/286

[Java] 'var' keyword

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Highlights 
```md
[](http://example.com)
```
They are grammatically correct.

[Markdown] Allow empty alt/text in images/link

---

Rust/Rust.sublime-build

5b29174: Sublime Text loads environment variables on startup (`zsh -l`, in case of zsh), so the hardcoded path in Rust.sublime-build file overrides the loaded path. On top of that, the hardcoded path doesn't include `~/.cargo/bin` anyway, so the build does not work.
2552ed0: I didn't initially intend to pull-request it, but I did not know GitHub would tack it onto the pull request on push. In any case, it adds a build variant to build and run the Rust file. It's been convenient while learning Rust to just have one-off files here and there to play with. I won't be at all surprised if you don't accept this one, though.

[Rust] OSX: don't override loaded path and build & run a single file

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Implemented the identifier rules from the spec.
The syntax previously used `\b` in a lot of rules. This is not quite right, and it leads to some bugs:
```js
function$NotAFunction
```
Where `\b` followed identifier characters, I replaced it with a negative lookahead. (Testing showed that there was no effect on performance.) Where `\b` *preceded* identifier characters, we would need a lookbehind, which the fast regexp engine does not support. However, we don't actually need assertions at the beginning of matches if we maintain the invariant that the "cursor" should never pause with identifier characters on both sides. This is guaranteed if every match that ends with an identifier character ends with the negative lookahead.
Implementing this correctly required changing the implementation of …

[JavaScript] Improved identifier and number lexing.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

There were two separate code paths handling function arguments, and they worked slightly differently. As a result, some comma separators were being parsed as comma operators. This is not currently visible in the core syntax (though see #831), but JS Custom offers an option to distinguish them. Because the solution is a straight simplification, I thought it reasonable to handle this upstream.
Now, all function call arguments are handled with one context. I renamed this context `function-call-arguments` (from `function-call`).
I also added semicolons to some related syntax tests. They worked either way, but without the semicolons they were a bit misleading.

[JavaScript] Simplified function arguments.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Cleaned up some scopes that were nested inconveniently. (While the change is functionally trivial, it would likely conflict with future functional changes, so this seemed an opportune time to make it.)
In the process, found/fixed a dollar highlighting case that was missing:
```js
var obj = {
$: 0,
//  ^ meta.object-literal.key.dollar.only punctuation.dollar
};
```

[JavaScript] Clean up nested scopes, fix a missing dollar highlight.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

This PR does for statements what #1009 did for expressions. Fortunately, this is a much, much simpler change.
This change:
- Allows for the removal of some code that worked slightly differently for statements and expressions. This was especially noticeable in the case of import/export statements.
- Properly treats semicolons as part of the statements they terminate. An immediately observable consequence is that the semicolon ending an import/export statement will be scoped `meta.import|export`.
- Scopes the semicolon of an empty statement `punctuation.terminator.statement.empty`. (These semicolons are usually unwanted.) This will make it much easier to write sensible tests for statements that do not require a semicolon.
- Fixes the `of`/`in` keyword in `for` loops, which was apparently …

[JavaScript] Refactor statements.

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

This PR provides better support for loose list items - instead of treating them as indented code blocks, it correctly identifies that they continue the list item. Fixes #1466.

[Markdown] better support for loose list items

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

PHPUnit is the most popular (or say, dominant) unit test framework for PHP.
For example, this PR highlights the `@dataProvider` in the following code.
```php
/**
* Test Parser::parse().
*
* @dataProvider parserParseDataProvider
*
* @param string $input    The input
* @param array  $expected The expected output
*/
public function testParse(string $input, array $expected): void
{
$this->assertEquals($expected, Parser::parse($input));
}
```
Ref: 
- PHPUnit annotations: https://phpunit.readthedocs.io/en/latest/annotations.html

[PHP] Add highlight for PHPUnit annotations

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

This fixes a bug whereby if one had invalid spaces inside an inline image link, the rest of the file would be stuck in the `image-inline-after-text` context. Also, it previously didn't correctly handle newlines before/around the link uri and title - this has also now been resolved. I have, of course, added some new assertions to prove that it now works as expected.

[Markdown] better support of inline images and links with whitespace

---

JavaScript/JavaScript.sublime-syntax

Adds explicit meta contexts to prevent nested lists. See discussion in #1469.

[JavaScript] Un-nest statement meta contexts.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Since #1348, `extend` has supported arbitrary expressions. This is actually overgenerous; only "left expressions" can be the target of `extend`. I have implemented the logic more thoroughly. As a result, the name of the extended class can be properly scoped `entity.other.inherited-class` in more cases than before. (Due to line lookahead limitations, there are a few cases where an identifier may be incorrectly scoped `entity.other.inherited-class`, but the syntax will recover immediately.) Tests have been added and improved.
As an added bonus, this is much of the logic we'll need to implement decorators. This also makes it much easier and less intrusive to extend the syntax to support a type system like Flow (e.g. `class Child extends Parent<TypeParam>`).

[JavaScript] Improved handling of class inheritance names.

---

CSS/css_completions.py

Missing coma was causing the completion to be `columndense` instead of `column` and `dense` for `grid-auto-flow`.

Fix missing coma for `grid-auto-flow` completion

---

Git Formats/Git Config.sublime-syntax

Applies the Git Config syntax to .gitmodules files.
> The .gitmodules file, located in the top-level directory of a Git working tree, is a text file with a syntax matching the requirements of git-config[1].
https://www.git-scm.com/docs/gitmodules#_description

gitmodules are git config

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Implements the [`import.meta` proposal](https://github.com/tc39/proposal-import-meta). The proposal is at Stage 3, and the syntax should be stable.
Due to line lookahead limitations, the following will be highlighted incorrectly:
```js
import
.meta;
```
In that example, `import` will receive `meta.import keyword.control.import-export`. When the dot is encountered, highlighting will proceed correctly.

[JavaScript] Implement `import.meta` proposal.

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Fixes #1209 
Note that this doesn't allow arbitrary strings as `strftime` formats. We can't tell the difference between a `datetime` argument and something else.
```python
'{0:%Y%m%d}'.format(datetime.date.today()) # legal, newly highlighted
'{0:%Y-%m-%d}'.format(datetime.date.today()) # legal, not highlighted
'{0:%Y%m%d}'.format('foo') # not legal, newly highlighted
'{0:%Y-%m-%d}'.format('foo') # not legal, not highlighted
```

[Python] strftime in format() strings

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

This adds the footnote command to the LaTeX syntax as requested by @DOFfactory in #1472 . I also decided to give it an italic markup by default.
ping @randy3k

[LaTeX] Add footnote command

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Fixes #1521.
```js
class Test {
['foo']() {}
//  ^^^^^^^^^ meta.function.declaration
static ['foo']() {}
//         ^^^^^^^^^ meta.function.declaration
async foo() {}
//  ^^^^^ storage.type
static async foo() {}
//         ^^^^^ storage.type
}
```
The lookahead handling computed property names is a bit problematic. The bracket could contain an arbitrary expression, so it's not really possible to look over it with a regexp. I have loosened it here, but it would be nice to find a better solution.

[JavaScript] Fix a couple of problems with method parsing.

---

JavaScript/JavaScript.sublime-syntax

Removes a `+` on a negative-lookahead group that causes problems with some regex implementations.
See this short discussion with @Thom1729: https://github.com/sublimehq/Packages/pull/1427#discussion_r184985538

Remove superfluous '+' in JavaScript syntax

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Supersedes #1236.
Implements the [decorators proposal](https://github.com/tc39/proposal-decorators), resolving #1477. The proposal is just shy of our usual standard of adoption: it's Stage 2 and expected to advance, and a conformant implementation is expected for Babel 7 (though a *nonconformant* implementation has existed for years). For historical reasons, there's a fair bit of code out there using decorators anyway, and because the feature is on the standards track I think it's reasonable to add it.
The proposed syntax is not completely finalized, but it is a virtual certainty that it will be a subset of this implementation (based on the `LeftExpression` production). Radical change is extremely unlikely at this point.
Currently, decorators are the sole major core ECMAScript feature …

[JavaScript] Implemented decorators.

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #1536.
[Reference](https://mimesniff.spec.whatwg.org/#javascript-mime-type).

[HTML] Accept all recognized JavaScript MIME types in <script> tags.

---

Lua/Completion Rules.tmPreferences

issue: https://forum.sublimetext.com/t/bug-lua-autocomplete-not-working-between-if-then/36635/2
Up to this commit auto completion is cancel, if a line contains the `then` keyword.
The original intention may have been to avoid auto completions after the keyword `then` but the user can't therefore make use of completions within the <condition> of an if-clause while altering an existing statement.
Example:
if (<condition>) then
end
This commit enables those completions by removing `then` from the `cancelCompletion` rule.
_Note: It also removes the not required capture._

[Lua] Don't cancel completions in lines with 'then'

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

For example, in
```
printFunction "$variableString1" "$(declare -p variableArray)"
```
the token `variableArray` is scoped with the vardef-name context, and it should
pop when encountering the closing parenthesis. We solve this by looking ahead
for a metacharacter.
In general more gratuitous popping in the vardef-* contexts is applied in order
to not get stuck in an unwanted context.
Closes https://github.com/sublimehq/Packages/issues/1535.

[ShellScript] Fix vardef-name context not popping

---

C#/C#.sublime-syntax
C#/syntax_test_c#.cs

[C#] fix bug when "dynamic" is used as the return type of a method

---

PHP/Indentation Rules.tmPreferences

as reported at https://forum.sublimetext.com/t/sublime-text-3-1/36591/34

[PHP] fix bug whereby indentation isn't decreased with `<? }`

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Fixes #1593
According to the minimal test case, if `.a()` is not followed by an opening `{` (a real `function-block`), the closing `}` of the owning object is matched as closing punctuation of the none present function block.
As a result the context of the owning object (`meta.object-literal`) is never popped off anymore.
The reason for that issue is located within the `function-block` context, which consumes the next available `}` after a function declaration without respect to a prior `{` to be required.
The code structure and the use of the `function-block` context is adapted to `function-declaration-parameters`.
It now contains the rule to set the `meta.block` context only.
An opening `{` is required before looking for a closing `}` for it.
By removing the `else-pop`, some look aheads …

[JavaScript] Fix function declarations within objects break highlighting

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

(See also #831.)
JavaScript uses the comma in two distinct ways. The most common is as an item separator, such as in function parameters and array or object literals. In these cases, it is and ought to be scoped `punctuation.separator`.
There is also the relatively obscure [comma *operator*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator). This is a binary operator that evaluates both of its operands and returns the right operand. It is a true operator syntactically and semantically, just like `+` or `-`. It is rarely used deliberately, although a developer who omits semicolons may *accidentally* use it, thereby producing a bug.
The formal ECMAScript grammar is carefully written to maintain the distinction between the comma operator and comma …

[JavaScript] Distinguish the comma operator from comma punctuation.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

In `+123`, the plus sign is part of the literal, not an operator. The syntax almost implemented this, but prefix operators were parsed before number literals. This has been corrected.

[JavaScript] Scope plus/minus as part of number literals.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

See #1569. As far as I can tell, these scopes are not useful for anything. Maybe they once were, in the `tmLanguage` days. The benefit to removing them is simplicity: they will no longer interfere with the `support` scopes that need updating (#1563).
Examples of formerly scoped constructs:
```js
Class3.prototype = function() {};
// ^^^^^^^^^^^^^ meta.prototype.declaration
Proto.prototype.attr
// ^^^^^^^^^^^^ meta.prototype.access
```

[JavaScript] Remove meta.prototype scopes.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Functions should be enclosed in a `meta.function` scope. Currently, the JavaScript syntax does not do this. However, it does enclose part of the function in a `meta.function.declaration` scope.
This PR encloses the entire function in `meta.function`. The old `meta.function.declaration` behavior is preserved exactly. The scope changes between `meta.function.js` and `meta.function.declaration.js`; it does not use both at once.

[JavaScript] Extend `meta.function` scope to entire function.

---

JavaScript/Default.sublime-keymap
JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Supersedes #1137.
The key bindings are modeled after the defaults and after the Babel package.
There is a minor change to the syntax. Generally, string punctuation is marked simply `punctuation.definition.string.begin|end` regardless of string type. The JavaScript syntax has been updated to conform to this convention.

[JavaScript] Key bindings for backtick strings.

---

C++/C++.sublime-syntax
C++/C.sublime-syntax
C++/syntax_test_c.c
C++/syntax_test_cpp.cpp
LaTeX/syntax_test_latex.tex
Markdown/syntax_test_markdown.md
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m
Python/Python.sublime-syntax
Python/syntax_test_python.py
ShellScript/Bash.sublime-syntax
ShellScript/commands-builtin-shell-bash.sublime-syntax
ShellScript/commands-builtin-shell-bash.yml
ShellScript/test/syntax_test_bash.sh

Relating to RFC #1228, this adds/refines scopes for jumping type flow control keywords. In this context jumping refers to more arbitrary changes in flow than the branch from an `if` or such.
This only covers **C, C++, Python and Bash** and does not attempt to do any standardization across languages and does not replace existing scopes. It also does not change anything for support functions like `exit` or `assert`, but this can be reviewed in future if necessary and most of these already have fairly specific scopes.

[C++/Python/ShellScript] Flow control keywords - more specific scopes for "jumping" keywords.

---

Python/Default.sublime-keymap

Auto-pairing was disabled when following the string modifiers.
Closes #1441.

[Python] Add special bindings for auto-pairing

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

Closes https://github.com/sublimehq/Packages/issues/1527.
The `macro_identifier` variable is too greedy right now. It may match tokens like `T` or `A` or `B`. Defining single-character macros is extremely unwise and frowned upon. Moreover, the syntax may incorrectly parse an operator overload like this one:
```
template <class T> class Sample {
T operator[](const int x);
};
```
Here, the `T` is assumed to be a macro, while it should be a proper return type (namely the template type `T`). This PR changes the `macro_identifier` variable so that only identifiers with at least two characters get parsed as a macro.
It is still possible to trip up the syntax with two-character template parameters like `T1` or `T2`.

[C++/ObjC] Fix: macro_identifier should be at least two characters long

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

Add highlighting for the coproc construct, introduced in bash 4.0. [Read more about coproc here](https://unix.stackexchange.com/a/86372).
One piece of the puzzle for https://github.com/sublimehq/Packages/issues/1358.

[ShellScript] Add coproc keyword

---

C++/C.sublime-syntax
C++/syntax_test_c.c
C++/syntax_test_cpp.cpp
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m

[C++/ObjC] Fix: '-->' character sequence was not recognized as '--' and '>'

---

HTML/HTML.sublime-syntax

`inc` means `include`, which is not a language-specific term.
`tpl` and `tmpl` which mean `template` are the same.
But I am **NOT** sure about this change. Maybe people use these file extensions in HTML more? Feel free to reject this PR.
Related: https://forum.sublimetext.com/t/first-line-match-mode-shell-script/36742/3

[HTML] The .inc (and some others) extension could be generally any language

---

Perl/Perl.sublime-syntax
Perl/Snippets/Conditional-if-(if).sublime-snippet
Perl/Snippets/Conditional-if..else-(ife).sublime-snippet
Perl/Snippets/Conditional-one-line-(xif).sublime-snippet
Perl/Snippets/Conditional-one-line-(xunless).sublime-snippet
Perl/Snippets/Conditional-one-line-(xwhen).sublime-snippet
Perl/Snippets/Conditional-unless-(unless).sublime-snippet
Perl/Snippets/Conditional-unless..else-(unlesse).sublime-snippet
Perl/Snippets/Conditional-unless..elsif..else-(unlessee).sublime-snippet
Perl/Snippets/Conditional-when-(when).sublime-snippet
Perl/Snippets/Loop-for-(for).sublime-snippet
Perl/Snippets/Loop-foreach-(fore).sublime-snippet
Perl/Snippets/Loop-one-line-(xfor).sublime-snippet
Perl/Snippets/Loop-one-line-(xfore).sublime-snippet
Perl/Snippets/Loop-one-line-(xuntil).sublime-snippet
Perl/Snippets/Loop-one-line-(xwhile).sublime-snippet
Perl/Snippets/Loop-while-(while).sublime-snippet
Perl/syntax_test_perl.pl

Fixes #541, #1029, #1325, #1326, #1495
Supersedes #1556
According to #481 this PR provides an Oniguruma free Perl syntax definition written from scratch.
1. fixes all currently open issues
2. much more feature complete
3. completely compatible with new regex engine
4. uses embed to include custom syntaxes within POD and HEREDOCS (CSS,JS,JSON,HTML,SQL,XML)
5. provides a syntax test file
6. uses as much atomic rules from Perl.sublime-syntax and
ModernPerl package as possible (with some fixes/modifications)
7. follows the doc http://perldoc.perl.org as close as possible
8. add some snippets with some files renamed to match naming style
1. The benchmark tests on a 100k file with all kinds of statements output about 360ms for evaluation on a Windows box.
2. The main focus is to create a robust …

[Perl] Refactor whole syntax definition to drop Oniguruma

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Effectively makes parenthesized parts of control statements optional, improving behavior when typing. Fixes #1589.
This also suffices to implement the [TC39 optional catch binding](https://github.com/tc39/proposal-optional-catch-binding) proposal.

[JavaScript] Add handling for incomplete control statements.

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #1575
This commit enables correct comment highlighting within following tags.
```
<script type="text/html">
</script>
```
The issue was caused by two reasons:
1. By including the `main` context after the `script-close-tag` in html scripts its "full featured" comment rule could never match.
-> Change include order.
2. The `script-close-tag` context matches `<!--` WITH preceding whitespace.
-> Remove `\s*`
1. The embedded JavaScript syntax in `<script>` does not allow normal html highlighting.
2. The embedded CSS syntax in `<style>` does not allow normal html highlighting.
HTML comments were used there in order to prevent parsing issues with old browsers.
Not sure how to handle `script-other` or `style-other`.

[HTML] Fix comment highlighting within script tags

---

Git Formats/Git Common.sublime-syntax
Git Formats/syntax_test_git_attributes
Git Formats/syntax_test_git_ignore

“asterisk” is misspelled in git-formats syntax scope names. This corrects the spelling.

[Git Formats] fix misspelling (asterix → asterisk)

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Allow for code blocks like
``` ruby
def foo(x)
return 3
end
```
with whitespace between the opening fence and the 'ruby' keyword.
closes #1615

[Markdown] Allow whitespace between opening fence and language

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

The Javascript syntax uses `source.js`. This caused failures in syntect where a broken reference is an error, which perhaps it shouldn't be if it isn't in Sublime.
cc @keith-hall

[Markdown] Fix reference to Javascript Syntax

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Tagged template literals were handled specially when the tag was an identifier, but the general case was broken (it caused the expression to end early). The general case has been fixed and the special case eliminated.
```js
1``
/a/;
//  ^^^ - string
//  ^ keyword.operator.arithmetic
//    ^ keyword.operator.arithmetic
```
Part of #1600.

[JavaScript] Fixed bug with tagged template literals.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

- `goto` has no meaning in JavaScript, but it was erroneously marked as a keyword.
- `break` and `continue` take optional labels. The syntax did not handle this, leading to bugs in corner cases.
- `continue` had no tests at all.
Part of #1600.

[JavaScript] Eliminate goto, add break/continue labels.

---

Rust/RustSymbols.tmPreferences

This PR simply enables the indexed symbol list for Rust symbols, to allow Goto Definition to be used in Rust code.

[Rust] enable Goto Definition for enums, functions, structs etc.

---

ShellScript/Bash.sublime-syntax

fixes https://github.com/sublimehq/Packages/issues/1503.
When typing keywords like "done" or "fi", previously these got scoped as a
function call when the cursor was at the EOF.

[ShellScript] Fix: scope keywords correctly while typing

---

C#/C#.sublime-syntax

I noticed one of the `match` patterns (along with the `scope`/`captures`) was duplicated in the C# syntax, so this PR removes the duplicate.

[C#] remove duplicate match pattern

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Removed the `meta.instance.constructor` scope and simplified the parsing of the `new` operator. The `new` operator itself is no longer scoped `meta.function-call.constructor`; only the call itself is. This PR de-kludges the changes made in #1424.

[JavaScript] Simplify parsing of new operator.

---

PHP/PHP Source.sublime-syntax
PHP/PHP.sublime-syntax
PHP/syntax_test_php.php

Up to this commit, the trailing white space after a closing php tag `?>` up to the end of line is scoped as `punctuation.`.
1. As white space is no punctuation, this commit therefore removes this scope. Trailing white space is already tagged as `meta.html-newline-after-php.php` anyway.
2. The `php-end-tag-pop` section is introduced to reduce duplicated rule definitions in the PHP.sublime-syntax.

[PHP] More precise php-end-tag scoping

---

C++/Comments (C++).tmPreferences

Without this, tools like Wrap Lines Plus won't be able to correctly wrap doxygen comments.

[C++] Teach the C++ comments settings about doxygen comment prefixes.

---

JavaScript/JavaScript.sublime-syntax

Because of https://github.com/SublimeTextIssues/Core/issues/2354, and because it's generally better anyway.

[JavaScript] Remove isolated regexp flags from variables.

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Allow special names to override `variable.annotation` and `variable.function` and ensure that these scopes are *still* being set before the special ones.
This is noticeable when you set italics rendering on these two scopes and have foreground color overrides on the special names like `support`.

[Python] Ensure variable.annotation/function

---

CSS/css_completions.py

This will add completions for [`will-change `](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) as it exists in the syntax file but its completions were missing.

[CSS] Add `will-change` to CSS completions

---

C++/C++.sublime-syntax
C++/C.sublime-syntax
C++/syntax_test_c.c
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m

Fixes https://github.com/sublimehq/Packages/issues/1537.
Commit db206f06c1 introduced a workaround for macros on their own line, but had
the side-effect of not scoping function definition with an all-upper-case
identifier return type on a separate line as entity.name.function anymore.
This commit makes sure to check for this case.
I had to split up the (maybe not in hindsight) clever `scope:source.c#preprocessor-practical-workarounds` includes in C++ and Objective-C++ in order to account for possible path-separator tokens (`::`) that are not possible in C.

[C++/ObjC] Fix: UPPER_CASE return types on separate line of function

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Now only requires two consecutive upper-case letters and allows digits.
Supersedes/Closes #1577.
Fixes #1607.

[Python] Update constant identifier regex

---

ShellScript/Bash.sublime-syntax

This just adds `.zshrc` as a valid extension for shell scripts in the same vein as `.bashrc`.

[ShellScript] Add .zshrc as a valid extension

---

SQL/SQL.sublime-syntax
SQL/syntax_test_sql.sql

Problem described at [Sublime forum](https://forum.sublimetext.com/t/wrong-ligature-for-null-safe-equal-to-operator-in-sql-syntax/37407/4).

[SQL] NULL-safe equal to operator ligature.

---

Python/Python.sublime-syntax

Not many changes for 3.7, which is currently in rc1 and the scheduled release date is at the [end of this month](https://www.python.org/dev/peps/pep-0537/#schedule), in exactly one week.
Syntax changes were the deprecation of `async` and `await` as non-keywords, which we cannot address in the syntax definition, and addition of a `__future__` import to prevent type annotation evaluation at load time, which also doesn't matter for us.
A single built-in function was added and three new magic methods from features in the stdlib.
See https://docs.python.org/3.7/whatsnew/3.7.html for the complete list.
Also no tests because …

[Python] Python 3.7 support

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This PR applies a change inspired by @keith-hall to avoid possibly breaking the `break` variable if it is used in extended regex patterns. It includes surrounding the `::` by tabs as well.
The second commit turns an `(?x)` into an `(?x: ...` as the latter one was used in another context the same way like.

[Perl] Small whitespace related improvements

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js
JavaScript/tests/syntax_test_js_bindings.js

Example:
```js
const /* cursor here while typing */
const bar = 42;
```
This is not valid JavaScript, so we should choose the most convenient highlighting. Previously, the second `const` would be scoped as the name of a variable. After this change, the first `const` declaration will terminate and the second `const` will be scoped `storage.type`. Similar changes have been applied to `function`, `class`, `import`, and `export` declarations.
The result should be less “churn” while typing.
A couple of other obscure issues have been fixed along the way.

[JavaScript] Better highlighting of invalid identifiers while typing.

---

Ruby/Default.sublime-keymap
Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes #1458. Uses interpolation scopes based on Python. See #1432 for further discussion.

[Ruby] Fixed keybind for interpolation and improved scopes.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Fixes #1767.
Should correctly differentiate the various types of `for` loops and highlight `in`/`of` where appropriate. `for` loops were apparently undertested, so I've added a few tests.
Semi-related issues:
1. ~~Currently, semicolons in `for` loop conditions are scoped `punctuation.terminator.statement`. This is arguably incorrect; they are separating expressions and/or variable declarations, not terminating statements. They should probably be `punctuation.separator.expression` or somesuch.~~
2. ~~`for (; function() {} /a/g;);` is broken. This is because `for-condition-contents` uses `statements-in-parens`, which uses `statements`, which is wrong because the second and third terms are conditions, not statements. As a result, the `function() {}` is parsed as a function declaration, not a …

[JavaScript] Improved for loop conditions.

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

Fixes https://github.com/sublimehq/Packages/issues/1349.
Fixes https://github.com/sublimehq/Packages/issues/1206.

[C++/ObjC] Fix: raw strings on their own line are scoped now

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

The 'final' keyword for a class declaration is highlighted as storage.modifier
now.
Closes https://github.com/sublimehq/Packages/issues/1131.

[C++/ObjC] Fix: final class

---

ShellScript/Bash.sublime-syntax

Closes https://github.com/sublimehq/Packages/issues/1666.
See: https://jlk.fjfi.cvut.cz/arch/manpages/man/PKGBUILD.5
See: https://wiki.archlinux.org/index.php/PKGBUILD

[ShellScript] Add PKGBUILD to the list of valid filename extensions

---

C++/C.sublime-syntax
C++/syntax_test_c.c
Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc.m

Closes #1282.
before this change:
```
struct point **alloc_points();
struct point* alloc_point();
```
`alloc_points` would be correctly highlighted as entity.name.function, while `alloc_point` would be incorrectly highlighted as variable.function. Now, both highlight as entity.name.function.

[C/ObjC] Fix: recognize pointers aligned to the type in function declarations

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

Fixes https://github.com/sublimehq/Packages/issues/1713.
Fixes https://github.com/sublimehq/Packages/issues/1327.
For things like std::function<A<B<C>>()> f(g), the grammar got confused and
thought this was a templated function call (the function name being "function"
and the start of the opening parenthesis for the function call being the
parenthesis after the "f" identifier). However, this is a new variable called
"f" of type "std::function<A<B<C>>()>" initialized with the variable "g".
To address this, the generic_lookahead variable had to be changed to account
for possible opening and closing parentheses inside of its template argument.
The result is a somewhat insane generic_lookahead, but it makes the syntax more
correct.

[C++/ObjC] Fix: Function type in template args

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

There were some issues with the type context overflowing into subsequent contexts. This resolves *most* of these issues, but one still remains:
```scala
type S = Map
evalNT
// ^^^^^^ - support.type.scala
new Foo
evalNT
// ^^^^^^ - support.type.scala
```
Both of these tests fail. Unfortunately, we can't just treat `\n` as a stop token because of types like this:
```scala
type Foo = A ::
B ::
C ::
D
```
And this:
```scala
type Foo =
A
```
So it's tricky. I think we need to stop cheating and actually have the even/odd state machine in the type expressions (where the odd state uses `\n` as a stop character, but even doesn't), which would match Scala's own parser, but it's a pain to do this so I'm skipping it for now.

[Scala] Improved stop tokens in types

---

Groovy/Groovy.sublime-syntax
Groovy/syntax_test_groovy.groovy

Fixes issue #1451, #1542
This commit fixes an issue with the closing `"` of a  string being matched as start of a new string, which caused the region after it to be scoped as invalid.
The reason for this issue was the end of the embedded code block `${ ... }` not being recognized due to the used expression inside, which expected the code block to end at the end of line only.

[Groovy] Fix invalid highlighting after embedded code in string

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html
Markdown/syntax_test_markdown.md

This commit introduces/proposes the following changes:
1. A fix for issue #1565 which is caused by not handling all the DOCTYPE internal syntax elements.
2. Highlight the CDATA tag as self closing xml/html tag.
3. Don't handle unknown `<! ... >` tags leaving them to special purpose syntaxes, which include this general purpose html syntax.
Point 2. and 3. are not directly related to #1565 but were part of handling opening/closing brackets within special tags. CDATA was the only remaining one within the `<!` context, which somehow made no sense but putting it into another PR would have caused conflicts.
For details about the changes please refer to the commit messages as this PR is split for better readability.

[HTML] Fix DOCTYPE and improve CDATA highlighting

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Whitespace is no punctuation and should therefore not scoped as such.
This commit changes the `tag-end-maybe-self-closing` to no longer include the preceding space into the `punctuation.tag.end.html`.
The reason for it to be included here is not obvious anyway as none, one or any number of spaces would cause the `/?>` to be detected as `end of tag` anyway.
_Note:_ In order to reduce duplication and increase code reuse dedicated contexts for the 3 different tag-end punctuation rules were created before fixing the issue.

 [HTML] More precise html-end-tag scoping

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

This PR proposes the following changes to the `entities` context:
1. Scope the `;` as `punctuation.terminator`
2. Fix the `punctuation.definition` test for hexadecimal entities
3. Remove an unused capturing group
For details please refer to the commit messages.

[HTML] Improve entities

---

Git Formats/Git Common.sublime-syntax
Git Formats/syntax_test_git_commit

Fix an issue with user name references like @user-name which contain hyphens not being fully highlighted.

[Git Formats] Fix user-name references

---

Perl/Perl.sublime-syntax

This commit does not introduce functional changes but fixes some linting issues found in the Perl.sublime-syntax recently.
The indention level in the `declarations` section was too high and yaml-lint wants comments to be preceded by at least 2 spaces.

[Perl] Fix some linting issues

---

Diff/Diff.sublime-syntax
Diff/syntax_test_diff.diff

The toc-list of a changed hunk in a patch file can contain hints about the context of a change - maybe a function name.
As this hint was not yet respected in the diff syntax, the hint was highlighted as normal text. If a color scheme defines a background color not the whole line was highlighted.
Hence this commit adds support to properly highlight section hints.

[Diff] highlight diff section hints

---

Haskell/Haskell.sublime-syntax
Haskell/syntax_test_haskell.hs

Fixes #1701
This commit adds the missing (*) operator and simplifies the whole pattern by adding the `|\(,+\)` token to the character first class.

[Haskell] Add missing (*) to infix functions

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

[Markdown] correctly scope escaped tildes for no strikethrough

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

[Python] correctly scope the colon after elif

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

[Rust] support paths to constants for sizes in nested array types

---

ShellScript/Bash.sublime-syntax

The shell script syntax and snippets do not support fish.
In the future, we should consider importing https://github.com/Phidica/sublime-fish

[ShellScript] Remove fish as an extension for shell script

---

Matlab/Indent.tmPreferences

Indent is not added automatically after `classdef` or `properties`, etc like:
This pull request added auto indenting for:   
- `classdef`
- `properties`
- `methods`
- `events`
- `enumeration`
This is my first pull request, if somehow I made mistake, please help me to correct it

[Matlab] Fix auto-indenting for OOP

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/syntax_test_objc++.mm

I found that a closing brace found inside a class definition gets a redundant `meta.group.c++` which separates it from the openining brace. This should not happen, since the opening and closing braces should have the same amount of `meta.group.c++` scopes.
Fix #1406 
Fix #1500 
I struggle to find the appropriate way to write syntax tests for this. Would you mind helping me?

[C++] Remove redundant meta.group.c++ scope from brace

---

Rust/Rust.sublime-syntax

New versions of Rust support `eprint!(..)` and `eprintln!(..)` in addition to the `print!(..)` and `println!(..)` macros: https://doc.rust-lang.org/stable/std/macro.eprint.html

[Rust] Add eprint and eprintln macros

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs

This updates the C# syntax definition to correctly handle tuple deconstruction in `foreach` constructs. The newly added test case came from https://stackoverflow.com/a/51281398/4473405.

[C#] support tuple deconstruction in foreach

---

JavaScript/JavaScript.sublime-syntax

Fix #1750. No change to JavaScript behavior except when embedded.

[JavaScript] Don't pop the main context.

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html
PHP/syntax_test_php.php

Fixes #1619 
1. According to https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state a html5 tag name may contain nearly any character, which is scoped as `entity.name.tag.other` by this commit. A couple of really weird tag names were tested and worked with Firefox.
2. According to https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts custom element tags may contain lower case characters which are not limited to ASCII or digits. Hence this commit uses the `custom_element_char` variable from the CSS.sublime-syntax to match custom-element-tags as it defines the same rule for them.
3. In order to make sure custom/other tag names don't interfere with normal html tags, the `\b` is replaced by `{{tag_name_break}}` in all tag name patterns. This …

[HTML] html5 custom element and other tag names

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html
PHP/syntax_test_php.php

This PR is an extension for PR #1784.
It provides the following changes:
1. Adds [noncharacters](https://infra.spec.whatwg.org/#noncharacter) to the list of characters an attribute must not contain.
2. Renames the variable `attribute_char` to `attribute_name`
3. Changes the hex notation to `\x{0000}` to match the `custom_element_name` style.
4. Replaces the negative lookaheads to improve parsing performance by 35..40%
5. The second commit of this PR replaces the `not_equals_lookahead` in favor of the existing `else-pop` context.
After merging PR #1784 and this one the parsing time for the following file with about 55k lines of code reduced from 1.5s to 0.9s on my box.
```html
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
<tag-name attribute="test" attribute="test" …
```

[HTML] html5 complient attribute names

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #1786
As described in #1786 the `]]>` was found to be valid text. Hence the normally used `invalid.illegal.stray` handling can't be applied.
This issue is an oversight/regression introduced with commit 015472d.

[HTML] Fix ]]> being scoped as invalid

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

The angle unit is optional after the number 0.
https://developer.mozilla.org/en-US/docs/Web/CSS/angle

[CSS] 0 is a valid angle value

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

https://drafts.csswg.org/css-grid/#named-lines
Grids have a thing where you can name lines, via the `[<custom-ident>*]` syntax:
```
grid-template-columns: [first nav-start] 150px [main-start] 1fr [last];
grid-template-rows: [first header-start] 50px [main-start] 1fr [footer-start] 50px [last];
```
I'm not 100% sure of the scope naming here and decided to keep it simple.

[CSS] support Named Grid Lines

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

Before this commit the lambda operator `=>` was not matched within function call arguments like `func(arg => anonymous)`.
To fix the issue the negative lookahead `(?!=)` in the `arguments` context is extended to restrict the matching of `=` as assignment. A positive lookahead with a negated character class is used as ST's regex engine can handle that much faster than negative lookaheads.

[C#] Fix lambda operator not matched in function arguments

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

```html
<script>42</script >
```
Noticed this while commenting on https://github.com/SublimeTextIssues/Core/issues/2326.

[HTML] Fix bug when closing script tag.

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

[Rust] scope support types in generics

---

ShellScript/Bash.sublime-syntax

Closes #1834
According to https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout all the mentioned file extensions belong to the zsh ecosystem as well es the already supported .zshrc file extension. So we could safely support them.

[Bash] Add .zlogin, .zlogout, .zprofile, .zshenv extension

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

The syntax now supports all built-in types and functions rather than just `make` and `new`. This feature is purely additive: built-ins receive additional `support` scopes; the user can opt out by not including these scopes into a color scheme.

[Go] support built-in types and funcs

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

Adds missing support for positional `fmt` placeholders:
```go
fmt.Printf("%[1]v = %[1]v", "blah")
```
Addresses #1804.

[Go] support positional fmt placeholders

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #1827
This commit reorders the `script-html` context. The `script-close-tag` context needs to be called before `main` to pop off correctly. As it introduces an issue with html comments not being highlighted correctly
within the embedded <html> ... </html> block anymore, the `comment` context is included before `main` as well.

[HTML] Fix script-html context exit

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

This is a slightly bigger change than I normally do, at least in terms of concept. Most of my PRs are effectively bug fixes, or just refining functionality that already exists. Here I'm *changing* the scope of an existing and very common construct, and I want to be quite clear that this is intentional and *why* I think this is a good idea. Flagging specifically so you can consider this as such, @wbond.
Here's what I'm changing:
```scala
foo match {
case bar => ???
//         ^^ storage.type.function.arrow.case.scala
}
```
The assertion above is the *new* scope. It was previously `keyword.operator.arrow.scala`. While there's nothing particularly *wrong* with the `keyword` scope here, it is inconsistent. The following is valid:
```scala
either.fold(
x => 42,
{ case y => 24 })
```
Both the …

[Scala] Arrow scoping unification

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

Most operators were matched character-wise which breaks ligatures. Also
add more refined scope names where applicable.

[Rust] Refine operator matches (for ligatures)

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

The opening `"` wasn't included previously.

[Rust] Fix raw string punctuation

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Unit test gives a good example. It's a relatively common pattern in Scala, as in many languages, to use interpolated strings in the following way:
```scala
val x = "Daniel"
println(s"x = '$x'; printing it out!")
```
Note the quoting around the interpolated variable. That's not syntax: it's just, part of the string. Unfortunately, Scala identifiers can contain trailing `'` characters in Typelevel Scala (and this has been proposed as a change to upstream). The Sublime scala mode deals with this correctly, but what it *doesn't* do is correctly handle the situation where it appears within an interpolated string. It's kind of an edge case, but given the popularity of this particular syntactic pattern, one that is well worth addressing.
The Scala compiler appears to ignore trailing `'` …

[Scala] Fix overly-greedy consumption of ' character in string contexts

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

Without this override, `var` and `val` parameters were scoped inconsistently (with only `val` being consistent with unmodified params).

[Scala] Added missing var scope override for class parameters

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

The tests are valid Scala. For example:
```scala
val abc: () => Unit = () => println("hello, world")
(abc)()
```
This prints "hello, world". Before my fix, the `()` on the second line would scope the same as if it were on the line by itself (i.e. as a `constant`).

[Scala] Dispatch can immediately follow braces

---

JavaScript/JSON.sublime-syntax
JavaScript/tests/syntax_test_json.json

In direct response to #421.
Use `meta.key` and `meta.value` for key and value tokens respectively. In the process, generalize `meta.sequence` and `meta.mapping` (and "fix" their punctuation scopes).
Investigation on how this might affect third-party color schemes should likely be performed, for the latter change only, which I doubt had any special coloring applied.
The scopes changed in the first change have only been added in https://github.com/sublimehq/Packages/commit/5e24e2b77f6ee16e2fbc705558d393b0f1d58485 (https://github.com/sublimehq/Packages/pull/816), which hasn't been part of any build yet.

[JSON] Meta scopes for mapping and sequence

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Now distinguishes between mappings and sets, allowing more fine-grained matching and meta scopes.
Also add meta.mapping.{key,value} scope to the appropriate sections of a dict literal.
This is in line with the proposed changes to JSON in https://github.com/sublimehq/Packages/pull/862.

[Python] Introduce meta.{mapping,sequence,set}

---

Matlab/Matlab.sublime-syntax
Matlab/syntax_test_matlab.m

Add parfor as a keyword in MATLAB syntax.
(https://uk.mathworks.com/help/distcomp/parfor.html)

[MATLAB] add parfor as a keyword

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This PR adds support for properly handling Test::Unit::Assertions' assert_no_match. Before this fix, syntax highlighting falls over for the remainder of the file once an assert_no_match assertion is used.
(The [previous PR](https://github.com/sublimehq/Packages/pull/1520) was closed by GitHub when I switched to a topic branch.)

[Ruby] Add support for assert_no_match

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This PR adds support for angle-bracket quoted strings to the Perl syntax definition.
see: https://docs.perl6.org/language/quoting#Word_quoting:_%3C_%3E
https://github.com/erlang/otp/blob/master/make/fixup_development_runtime_dependencies

[Perl] Fix angle quoted strings break highlighting

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

The keyword `sub` is used to identify the definition of a subroutine. It can be compared to `def` in python or `function` in Bash.
It does not describe a control-structure nor does it a storage.type.

[Perl] Scope sub as storage.type.function

---

Rails/Snippets/after_validation_on_create.sublime-snippet
Rails/Snippets/after_validation_on_update.sublime-snippet
Rails/Snippets/before_validation_on_create.sublime-snippet
Rails/Snippets/before_validation_on_update.sublime-snippet

This syntax has been dropped in Rails 3 (2010) and replaced by the one
suggested in this commit.
~~Removes these four methods from the `support.function.activerecord.rails` match as well.~~
https://apidock.com/rails/ActiveRecord/Callbacks/before_validation_on_create
https://apidock.com/rails/ActiveRecord/Callbacks/before_validation_on_update
https://apidock.com/rails/ActiveRecord/Callbacks/after_validation_on_update
https://apidock.com/rails/ActiveRecord/Callbacks/after_validation_on_create
~~Note: the suggested changes in snippets use the "new" hash syntax `on: :create` instead of `:on => :create`. The "new" syntax was introduced in ruby 1.9, [as of now the oldest supported version of ruby is 2.2](https://www.ruby-lang.org/en/).~~
Question to the maintainers: I could open another PR …

[Rails] Update before/after validation on create/update

---

C#/C#.sublime-syntax
C#/tests/syntax_test_GeneralStructure.cs

Fixes https://github.com/sublimehq/Packages/issues/1866
To get this working, I had to duplicate and tweak the `string_placeholder_format` context so that it behaves correctly for normal strings as well as "long strings" and "long format strings". It sure would be great for maintenance if contexts could take parameters and then somehow the contents of that context could use those parameters to tweak the regex patterns ;)

[C#] correctly handle escapes in long string placeholders

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This commit reorders the `label` and `quoted-like` expression contexts to fix upper-case labels scoping. Before this commit they were matched as `constants` which is wrong.

[Perl] Fix upper-case labels

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Add missing \b to capture inline for inside a dict.
Add relevant test.
Reported in forum: https://forum.sublimetext.com/t/python-syntax-highlight-bug-after-update/42248

[Python] Fix mapping element starting with 'for'

---

Python/Python.sublime-syntax

In 0550509bcd5, `path` was modified to allow spaces around `.`. Later, `simple_expression` started using `path` but within a `(?x:...)`, which means this:
\b[[:alpha:]_][[:alnum:]_]*\b *\. *
is equivalent to:
\b[[:alpha:]_][[:alnum:]_]*\b*\.*
While sregex doesn't complain about that, `\b*` is invalid in Oniguruma:
Note that even with sregex, the meaning of the regex changes.
By using a character class for the space, the pattern works the same way
whether it's within a `(?x:...)` or not.

[Python] Fix Oniguruma incompatibility with regex for path

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua_support.lua

Existing syntax had some erroneous builtin functions and was missing highlighting for builtin functions specific to Lua 5.1/5.2 (note that Lua 5.1 is still very much in use, e.g. LuaJIT).
Reference manuals:
- Lua 5.1: https://www.lua.org/manual/5.1/#index
- Lua 5.2: https://www.lua.org/manual/5.2/#index
- Lua 5.3: https://www.lua.org/manual/5.3/#index

[Lua] Fix builtins + add Lua 5.1/5.2 builtins

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

Fixes #1902
Issue #1902 is triggered by not correctly distinguishing class/object member functions from member variables. An identifier after `->` which does not start with `$` was detected as function call.
As the same syntax was assumed for `builtin` function calls and user defined `sub` calls, the first token after the identifier was expected to be the first argument. In #1902 this means the `<` after `->value` was assumed to be the beginning of the first angular quoted string argument.
This PR therefore adds a couple of commits to fix that issue by correctly detecting functions and variable members. Please refere to the commit messages for more details about the single steps.

[Perl] Fix member function vs. member variable matching

---

Lua/Indent.tmPreferences

Fixes incorrectly indenting after strings like doSomething, thenSomething
```lua
local blah = doSomething()
```
Fixes #1910

[Lua] Fix missing \b in do/then indent rule

---

JavaScript/JSON.sublime-syntax
JavaScript/tests/syntax_test_json.json

Object keys are being highlighted using an anonymous context that includes `inside-string` instead of pushing it onto the stack. Thus the `meta_include_prototype: false` of the `inside-string` context does not apply, and comments are being matched inside object keys.

[JSON] Remove prototype from object keys

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

I'm sorry for the new pull request. The old one was automatically closed for some reason.
When a struct or class has been forward declared in a namespace or other class, the class or struct can be defined using an identifier with a path in front of it. I added this possibility.
**Example**
```C++
namespace Namespace
{
class BaseClass;
}
class Namespace::BaseClass {};
```
Hi! Thank you all for your feedback. 
> @wbond The :: should not get entity.name.class, neither should the namespace. The namespace name should be something like support.namespace.
Yes that’s what I thought too and then I looked at how scopes got applied to function definitions and function calls with namespace paths and realised that `entity.name.function` and `variable.function` where applied to the entire path …

[C++/ObjC] Add support for paths in front of struct/class identifiers

---

C++/C.sublime-syntax
C++/syntax_test_c.c
Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc.m

Fixes #1712.
Since there were not any tests that failed after removing a line in the match rule, I am somewhat hesitant about merging this. @wbond let me know what could go wrong in this case.

[C/ObjC] Fix: be more lenient about macro identifiers with enum return types

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

Fixes #1868 
Fixes #1871
This PR ...
1. proposes to rename the control keywords in order to comply with #1228 inspired by the structure of the C# syntax, which should be applied to other syntaxes in the future as well
2. fixes a design issue with the _case_ context
3. improves the keyword boundary lookahead and applies it to the case contexts
For details please refere to the commit messages.

[ShellScript] Control Structure Improvements

---

Python/Python.sublime-syntax
Python/syntax_test_python.py
Python/syntax_test_python_strings.py

This commit 
1. applies `keyword.control` scopes as discussed in #1228.
2. fixes some inconsistencies with punctuation `:` scopes in control flow statements.
3. removes some unrequired capture groups.

[Python] Fix control keywords and punctuation

---

Haskell/Haskell.sublime-syntax
Haskell/syntax_test_haskell.hs

Addresses #1320 and #1880. Shamelessly adapted from `SublimeHaskell`'s syntax file [here](https://github.com/SublimeHaskell/SublimeHaskell/blob/master/Syntaxes/Haskell-SublimeHaskell.sublime-syntax#L311).
The test on [line 75](https://github.com/sublimehq/Packages/pull/1885/files#diff-38b1f0659739bb29fa8ff5fc5899f9efL75) of `syntax_test_haskell.hs` was deleted because it relied on the `=` operator to pop the type signature context.
Sublime's default Haskell syntax is a bit dated and could use a rewrite. There are a number of problems inherent to its current design, like #1321. A merge with `SublimeHaskell` may be a good start, but I've found that it too has a couple of idiosyncrasies. I'm not sure how to best engage the community.

[Haskell] Fix type signature context not popping when encountering a guard or an instance declaration.

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

See http://docs.phpdoc.org/references/phpdoc/tags/var.html .
Currently we only have multi-line doc highlighted.
```php
/**
* @var string $name        Should contain a description
* @var string $description Should contain a description
*/
```
However, this inline doc is valid as well.
```php
/** @var string|null Should contain a description */
//  ^ keyword.other.phpdoc
```

[PHP] Add support for inline PHPDoc

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This commit applies the latest standardized `constant.numeric` scope names to the perl syntax.
See: https://www.sublimetext.com/docs/3/scope_naming.html#constant

[Perl] Apply numeric scopes

---

Matlab/Matlab.sublime-syntax

Just a typo fix in a comment in the Matlab syntax highlighting file.

[Matlab] Fix typo in comment

---

Matlab/Snippets/unwind_protect-cleanup-end.sublime-snippet

There's a typo in one of the identifiers in the Octave-oriented "unwind" snippet in the Matlab package.

[Matlab] Fix typo in unwind snippet

---

Matlab/Snippets/Octave-function.sublime-snippet
Matlab/Snippets/unwind_protect-cleanup-end.sublime-snippet

Most of the Matlab snippets are applied to both `source.matlab` and `source.octave` code. Except for the `octfun` and `unwind` snippets, which are, curiously, Octave-specific.
This PR makes them available in `source.octave` code as well.

[Matlab] Make octfun and unwind snippets available in source.octave code

---

ShellScript/Snippets/#!-usr-bin-env-(!env).sublime-snippet
ShellScript/Snippets/case-..-esac-(case).sublime-snippet
ShellScript/Snippets/elif-..-(elif).sublime-snippet
ShellScript/Snippets/for-...-done-(for).sublime-snippet
ShellScript/Snippets/for-in-done-(forin).sublime-snippet
ShellScript/Snippets/if-...-then-(if).sublime-snippet
ShellScript/Snippets/until-(done).sublime-snippet
ShellScript/Snippets/while-(done).sublime-snippet

This PR follows on from discussion in #1663. Though no clear consensus was reached, I present a potential solution to the issue for practical discussion.
Specifically, the problem is that snippets which only work in Bash (or other Bourne-like shells) are suggested for the `source.shell` scope, which includes `source.shell.fish` ([Phidica/sublime-fish](https://github.com/Phidica/sublime-fish)) despite the syntaxes being entirely incompatible. The `run_shell_script` command also provided by the ShellScript package is shell-agnostic, and makes a good case for `source.shell` to be the underlying scope for all shell scripts regardless of their compatibility with Bash.
Accepting this PR would change the applicable scope of the snippets to be the scope assigned by the Bash syntax, …

[ShellScript] Make snippets friendlier to other shell packages

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Comments in JavaScript are usually not tokenized, but block comments containing newlines are tokenized as LineTerminators. This has implications for constructs that care about LineTerminators, like `break`, `continue`, `return`, `throw`, and `async function`.

[JavaScript] Recognize line endings in block comments.

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js_support_builtin.js

https://forum.sublimetext.com/t/js-deprecated-feature-highlighting-sucks/42979
`escape()` and `unescape()` are old functions implemented in some browsers. They are mostly nonstandard — the ECMAScript spec catalogues them in Annex B. We currently scope them `invalid.deprecated support.function`. However, while developers should avoid creating variables that share names with builtins like `isNaN` or `Object`, it's perfectly reasonable to have a variable named `escape`. This PR eliminates the special treatment of `escape` and `unescape`.
We also use `invalid.deprecated` for the Annex B properties `__proto__`, `__defineGetter__`, `__defineSetter__`, and `__lookupGetter__`. It seems unlikely that anyone would use a property with one of those names for legitimate purposes, but I suppose it's …

[JavaScript] Remove special scoping of escape/unescape.

---

PHP/Indentation Rules.tmPreferences

correctly unindent `else if:` followed by `?>` - fixes #1924

[PHP] correctly unindent `else if:` followed by `?>`

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes 'class:' and 'module:' being marked as keywords instead of symbols.
Adds test cases for this issue to the syntax test.
Fixes #1934

[Ruby] Fix hash keys with reserved keywords still being marked incorrectly

---

Makefile/Makefile.sublime-syntax
Makefile/syntax_test_makefile.mak

Fixes #1941
A quotation mark found in the arguments of a function-call causes the parser to push into the quoted-string context. The region up to the next quotation mark is then scoped as quoted string.
But make interprets single quotation marks in functions like `subst` as ordinary characters.
The following escapes all quotation marks in $1:
$(subst ",\", $1)
This commit proposes to just eat escaped quotation marks (\", \') or those followed by the arguments separator.
They are scoped as whatever the parent context scopes the current region. The example posted in issue #1941 causes the quotation marks to be scoped as `string.unquoted`.

[Makefile] Fix highlighting of unbalanced quotations in functions

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs

[C#] deconstructed tuple doesnt require space between `var` and `(`

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This commit fixes an issue with regexp patterns not being detected, if tabs are used for indention.
**Example:**
$var =~
/pattern/;
The `/pattern/` is now detected as such, even if the line starts with tabs.
~_Note: Can't add a test as PackageDev complains about tabs being used as indention._~

[Perl] Fix regexp patterns at line start with tabs

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

Expression block fails for numbers like:
```
if number > .2 then
else
end
```

[Lua] Syntax number fixes

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Fix #1949.
The original implementation in #1292 did not properly support private property accessors, but in most cases they worked almost-correctly by coincidence. #1949 identifies a case in which they do not work at all. This PR implements them correctly.
Private fields are part of the [TC39 class fields proposal](https://github.com/tc39/proposal-class-fields), which is Stage 3.

[JavaScript] Support private property accessors.

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This commit fixes a typo, which causes the `lt` operator not to be scoped. Also adds test cases to ensure it doesn't happen again.

[Perl] Fix lt operator not being scoped

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

The `<flags>` of a regexp expression like `s/<pattern>/<repl>/<flags>` must directly follow the separator `/` without any whitespace in between.
This PR applies this rule to the Perl.sublime-syntax by immediately popping the `quoted-like-flags` off the stack, if anything but a valid flags character is matched (including whitespace).

[Perl] Fix regexp flags matching

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This PR adds support to scope the item access of an array or a map.
**Examples:**
$array[0][2]
$dict{'key1'}{'key2'}
This change is required to properly highlight those expressions in string interpolations. Otherwise the array index would not be part of the interpolation.
It turned out an array is initialized with the following expression:
$array = [ item1, item2, ...];
This PR therefore adds the "brackets" contexts with rules to scope the opening and closing brackets.
**Note:**
1. The `groups-nested` is not added everywhere to reduce the risk of interfering with HEREDOCs. It is assumed no one decides to define a HEREDOC within an array item access expression.
2. The `groups-nested` was not yet used and contained a therefore unrevealed issue, which is fixed as well. It used the wrong …

[Perl] Add array item access

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

Reserved words are now recognized and highlighted as invalid in:
- function definitions
- function calls
- item access
- member access
- parenthesized expressions
Fixes #1916.

[Lua] Gracefully recover from invalid reserved word usage

---

Perl/Perl.sublime-syntax

An identifier can be followed by a double-colon. Hence using the `{{break}}` is not appropriate and needs to be fixed.
This is a theoretical issue which is not triggered at any point of the current implementation. This commit therefore has no functional effect to the current syntax definition, but may have due to future changes.
Note: This change is covered by existing test cases.

[Perl] Fix identifier break

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This commit fixes an issue with special preprocessor function blocks not being highlighted as such, if not following the `sub` keyword.
SEE: https://perldoc.perl.org/perlmod.html#BEGIN%2c-UNITCHECK%2c-CHECK%2c-INIT-and-END
Note:
The code blocks `BEGIN {}` are scoped as ordinary function blocks even though they are executed by the interpreter at compile time as there is no syntactical difference. It's therefore a little bit different situation than with preprocessor macros of other languages, which tend to differ from normal runtime code.

[Perl] Fix BEGIN/CHECK/END/... blocks

---

Perl/Perl.sublime-syntax

This PR enables Sublime Text to detect Perl syntax via certain tags in the first line, like:
```
```
This commit is inspired by the way ShellScript provides such support.

[Perl] Extend first_line_match to support editorconfig

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

PHP 7.4 has been feature-freezed so this PR will no longer add new things.

[PHP] PHP 7.4 new syntax

---

PHP/PHP Source.sublime-syntax

The deprecated `var` keyword is equivalent to `public` so I think they should share the same scope.
https://www.php.net/manual/en/language.oop5.visibility.php
```
Note: The PHP 4 method of declaring a variable with the var keyword
is still supported for compatibility reasons (as a synonym for the
public keyword). In PHP 5 before 5.1.3, its usage would generate an
E_STRICT warning.
```

[PHP] "var" is equivalent to "public"

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

1) excludes the space after a key from the `constant.other.key` scope.
BEFORE:
```
map(key => "value")
^^^^ constant.other.key
```
AFTER:
```
map(key => "value")
^^^ constant.other.key
^ - constant
```
2) groups the `constant.other` rules in the `constants-other` context.

[Perl] Fix key constants

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Previously, `\{{` imposed problems with both regex raw strings and
normal due to the `\{` being matched first and the final `{` then being
interpreted as the opening of an f-string. We now match the entire token
and scope it appropriately.
Before: ![2019-05-15_21-52-07](https://user-images.githubusercontent.com/931051/57806089-b3e0dc00-775e-11e9-99b1-8ed1bf83ee9e.png)
After: ![2019-05-15_21-59-21](https://user-images.githubusercontent.com/931051/57806093-b5aa9f80-775e-11e9-97b2-c31f92212db4.png)

[Python] Handle f-string escape sequences with other escapes

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js_support_builtin.js

Fix #1980.
The `.error` scope doesn't seem useful (it's not standard), so I removed it when adding `.builtin`.

[JavaScript] Scope builtin errors as support.class.builtin.

---

Rust/Cargo.sublime-build

Paths in error messages are relative to the top-level directory, so ensure the
working_dir is set to that.
This also sets Cargo.sublime-build to be active when there's a Cargo.toml file,
rather than when editing Rust source code, which ensures it's an available build
system in more circumstances (e.g., when editing Cargo.toml)

[Rust] Fix next_result handling for Cargo build errors

---

Git Formats/Git Config.sublime-syntax
Git Formats/syntax_test_git_config

I have a background color tweak for `string` that makes the problem more obvious.

[Git] End gitconfig strings before newline

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Via https://docs.python.org/3/reference/lexical_analysis.html#literals.

[Python] Octal string escapes accept **up to** 3 digits

---

Python/Python.sublime-syntax
Python/syntax_test_python.py
Python/syntax_test_python_strings.py

[Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html) will include the following syntax changes:
I skipped assignment expressions for now because they are a tad bit more involved and ideally I'd like to see some consensus on #1842 regarding the scope names I should use for the identifiers that are assigned to. Because the assignments are inline, it would seem useful for those to be highlighted differently compared to normal variable usages.
Anyway, here are the small changes I've done so far.
The final release is [scheduled for 2019-10-21](https://www.python.org/dev/peps/pep-0569/).

[Python] Add support for some new syntax in Python 3.8

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

- Use a deterministic approach by pushing all expected tokens at once.
- Clean up closing punctuation matches to make them easier to
understand.
- Recover from unmatched tokens more gracevully through 'else-pop'
context.
- Accept whitespace around multi-match separator (Rust compiles fine
with them).
- Add more details to scope names.
- Match comma as macro matcher separator.
Fixes #2014.
Before:
After:
```rust
#[macro_export]
macro_rules! vec {
( $( $x:expr ) , * ) => {
{
let mut v = Vec::new();
$(v.push($x);)*
v
}
};
}
#[macro_export]
macro_rules! test [($($x:tt),*) => ($x)];
fn main() {
let v = vec![1, 2, 3];
println!("{:#?}", v);
}
```

[Rust] Restructure macro parsing

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

- `string.template` → `string.quoted.other`
- `punctuation.definition.template-expression` → `punctuation.section.interpolation`
- `meta.template.expression` → `meta.interpolation`

[JavaScript] Use proper scopes for interpolation in template strings.

---

C#/Symbol List Structs.tmPreferences

I finally figured out why some of my types weren't in the Goto Symbol in Project… list: they are structs!
I went ahead and looked at the Classes and Interfaces files and added one for Structs, lo and behold it just worked and I know too little about Sublime development to know what effects this has, except that now I can finally jump around to my structs, so I thought I'd make a PR for it. 😬 
Let me know if there's something you need from me. ❤️ 👏

[C#] include structs in symbol list

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

Partly reverts and updates 61e2cd280231da90afe37d07f591084f51affd9f.
I also made `1.` a proper match because that works as well and removed capturing group.
See #1937.

[Lua] Update number patterns again

---

XML/XML.sublime-syntax

Apply XML syntax to all files starting with `<!DOCTYPE >`, if it is not html. `<!DOCTYPE html>` is reserved for HTML syntax.
Sometimes the <?xml ...> prolog may be omitted in XML files which may also have an arbitary extension such as `*.ts` which is not associated to XML otherwise.

[XML] Highlight files starting with DOCTYPE as XML

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

Comments are valid after identifiers in function definitions, if the function body starts at the next line.

[Perl] Fix line comments after sub identifiers

---

Rust/Rust.sublime-syntax

Since https://github.com/rust-lang/rust/pull/38482 Rust has had native `u128` and `i128` integers.

[Rust] Add u128 and i128 primitive types.

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp

Allows Javadoc style comments to be recognized in scope. Word wrapping depends on it to wrap comment blocks properly.

[C++] Add support for Javadoc style comments

---

D/D.sublime-syntax
D/tests/syntax_test_d.d

Leading asterisk/plus in multi line comment will now be treated as
punctuation definition. Word wrapping depends on it to wrap comment blocks properly.

[D] Add support for Javadoc style comment

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Allow leading asterisks (excluding leading white space) in body of Javadoc style comments to be recognized as "punctuation.definition" scope. Default word wrapping will depend on it to wrap comment blocks properly.

[JavaScript] Improve scope for Javadoc style comments

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

Allow leading asterisks (excluding leading white space) in body of Javadoc style comments to be recognized as "punctuation.definition" scope. Default word wrapping will depend on it to wrap comment blocks properly.

[Rust] Improve scope for Javadoc style comments

---

JavaScript/JSON.sublime-syntax
JavaScript/tests/syntax_test_json.json

Allow leading asterisks (excluding leading white space) in body of Javadoc style comments to be recognized as "punctuation.definition" scope. Default word wrapping will depend on it to wrap comment blocks properly.

[JSON] Improve scope for Javadoc style comments

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

In order to access an item of a hash (dictionary), the caller can use an unquoted string as key.
In the other way round: The `item_key` in `$the_hash{item_key}` is a simple unquoted string.
Prior to this commit, the key was not scoped at all and would so as function/method call in the future.
_Note: This fix is one result of the discussion in issue #2017._

[Perl] Add unquoted hash keys highlighting

---

Matlab/Matlab.sublime-syntax
Matlab/syntax_test_matlab.m

Fix #1647.
This pull request adds a check for a transpose comma after fields of structures using dot notation `a.b'` to prevent false highlighting as a string, see [this comment](https://github.com/sublimehq/Packages/issues/1647#issuecomment-483157721). Previously, the rule of the context `transpose` did not apply to `a.b'` because it requires a variable name (`{{id}}`) preceding the transpose comma, but `a.b` was already matched by the rule of context `members`. Therefore I included the transpose comma check, which is already used after parens/brackets/braces, to matches of the form `a.b`.
Detecting the transpose comma will also work for nested structures of the form `a.b.c`, `a.b.c.d` etc. now, even though these are not entirely matched by the context `members`.

[Matlab] Fix transpose highlight following fields

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

In PR #1912 the scope names were renamed to match the latest scope naming guidelines.
This PR is a result of further investigations about how Perl parses numbers.
The main intentions are:
1. add support for incomplete floating point numbers like `1.`, `.1` or `1e1`.
2. fix some edge cases with numbers followed by `+` or `.` operator, which are broken up to this commit. Need to avoid breaking the `..` range operator, though.
3. properly apply the `constant.numeric.integer.octal` scope to numbers beginning with `0`.
Furthermore this PR intends to create some kind of consistency with other languages like D, Go or Python with regards of scoping decimal punctuation or leading `0b`, `0x` and `0` in bin/hex/oct constants.

[Perl] Improve numeric highlighting

---

D/D.sublime-syntax
D/tests/syntax_test_d.d

`/**/` and `/++/` would cause the comment to never end

Fix D multiline-comments not ending without content

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

Up to this commit all `${...}` or `%{...}` tokens are scoped as `variable.other` while they contain ordinary expressions.
This commit...
1. replaces the scope by a `meta.variable` to avoid otherwise unmatched parts of the expressions being highlighted in a wrong way.
2. adds the `regexp-pop` context right after the opening punctuation in order to fix an issue with `/patter/flags` not being detected.
Note:
This change is part to solve issue #2017

[Perl] Fix ${...} meta scope name

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

According to [https://drafts.csswg.org/css-fonts-3/#descdef-src](https://drafts.csswg.org/css-fonts-3/#descdef-src) the font face name within `local()` can optionally be enclosed in quotes.
```css
@font-face {
font-family: 'Ubuntu';
src: local('Ubuntu Regular'),
url('Ubuntu-Regular.ttf') format('truetype');
}
@font-face {
font-family: "Ubuntu";
src: local("Ubuntu Regular"),
url("Ubuntu-Regular.ttf") format("truetype");
}
```
Before:
After:

[CSS] Fix missing string punctuation within local()

---

C#/Symbol List Classes.tmPreferences
C#/Symbol List Enums.tmPreferences
C#/Symbol List Interfaces.tmPreferences
C#/Symbol List Namespace.tmPreferences

As discussed in #2001 this PR removes the `class`, `enum`, `interface`, and `namespace` prefixes inserted via symbol transformation. It's nice to have but really something that should be taken care of by Sublime Text in a more coherent manner.
🙅‍♂ **Before**
🙆‍♂ **After**

[C#] Removed type prefixes from symbol list

---

CSS/CSS.sublime-syntax
CSS/css_completions.py

Fixes #2046
This commit adds completions and highlighting for the `justify-content` values as documented at
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

[CSS] Add justify-content values

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Fixes #2038
Fenced code blocks are defined 
- implicitly by indenting content by at least 4 characters or
- explicitly by optionally indented lines starting with 3 backticks/tilds.
Therefore the capturing group `([ ]{0,3})` in `fenced_code_block_start` seems to make no sense and is removed.
The missing `\t` indention is added to both `fenced_code_block_start` and `fenced_code_block_escape`.

[Markdown] Fix tab indented fenced code blocks

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes #2000
This commit causes the `require` context to pop off by `}` in addition to the end of a line in order to make it work properly within string interpolations.
It also removes some unnecessary captures.
_Note: Not sure why the method `require` pushes into a context to add a meta, while the other method's don't. Looks like all should be handled as `meta.function-call`._

[Ruby] Fix interpolated require

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes #1387
This commit
1) sorts rules to correctly match all operators. This fixes some operators not being replaced by ligatures.
2) tweaks scope names a little bit.
a) `|` and `~` are bitwise operators
b) `..` is scoped `keyword.operator.range`

[Ruby] Fix operators ligatures and scopes

---

C++/Snippets/#ifndef-#define-#endif.sublime-snippet
C++/Snippets/#include-(#inc angle).sublime-snippet
C++/Snippets/#include-(#inc).sublime-snippet
C++/Snippets/#include-(inc angle).sublime-snippet
C++/Snippets/#include-(inc).sublime-snippet
C++/Snippets/$1.begin()-$1.end()-(beginend).sublime-snippet
C++/Snippets/030-for-int-loop-(fori).sublime-snippet
C++/Snippets/Enumeration.sublime-snippet
C++/Snippets/Typedef.sublime-snippet
C++/Snippets/class-..-(class).sublime-snippet
C++/Snippets/do...while-loop-(do).sublime-snippet
C++/Snippets/forv.sublime-snippet
C++/Snippets/fprintf.sublime-snippet
C++/Snippets/if-..-(if).sublime-snippet
C++/Snippets/main()-(int main).sublime-snippet
C++/Snippets/main()-(main).sublime-snippet
C++/Snippets/namespace-..-(namespace).sublime-snippet
C++/Snippets/printf-..-(printf).sublime-snippet
C++/Snippets/read-file-(readF).sublime-snippet
C++/Snippets/std-map-(map).sublime-snippet
C++/Snippets/std-vector-(v).sublime-snippet
C++/Snippets/struct.sublime-snippet
C++/Snippets/template-typename-..-(template).sublime-snippet

Fixes #2055
Prevent snippets from being added to the completions when the caret is within an include directive.

[C/C++/ObjC/ObjC++] Exclude snippets from #include<...>

---

Scala/Scala.sublime-syntax
Scala/Symbols-val.tmPreferences
Scala/Symbols-var.tmPreferences
Scala/Symbols.tmPreferences
Scala/syntax_test_scala.scala

This changes loads of stuff. I'm sorry for the mega PR. I kept the commits granular so you can see in a bit more fine-grained fashion what changed, but I can squish a lot of it together. This mostly boils down to making the scoping of most constructs align more consistently with other modes. In particular, I relied on JavaScript and C# as the primary canon, though I also looked at Java (NB: the Java mode scopes imports inconsistently and still has some unfortunate bugs).
Some big ticket bullets:
- I changed `val` and `var` scoping. They used to use `entity.name`, and now they use `variable.other`, so as to be consistent with JavaScript. I went back and forth on this *a lot*, because `val` is not materially different from a no-argument `def` in Scala, and they are conventionally used …

[Scala] Scope overhaul to better align with convention

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

This PR adds indexing support for using aliases, just like typedefs.
fixes #1578
```c++
typedef Foo MyAlias;  
using MyAlias = Foo; 
```

[C++/ObjC++] Add highlighting and indexing support for using aliases

---

PHP/PHP Source.sublime-syntax

Added functions mentioned in PHP 7 Changelog
- oci_set_call_timeout
- oci_set_db_operation
- gmp_binomial
- gmp_lcm
- gmp_perfect_power
- gmp_kronecker
- openssl_pkey_derive
- is_countable
- hrtime
- ftp_append
- spl_object_id
- hash_hkdf
- is_iterable
- socket_export_stream
- error_clear_last
- http_response_code

[PHP] Updated PHP Syntax to include PHP 7+ functions

---

Java/Java.sublime-syntax

This PR proposes to remove some remaining quotation marks from the match patterns because most of them are already unquoted.
This PR does not change functionality, but is only for consistent code style.

[Java] Remove quotation marks from match patterns

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Fixes #1858
This PR is a local hotfix for issue #1858. If the identifier of an inherit class starts with a lowercase character, the rest of the class definition becomes broken. Therefore the methods aren't properly scoped and not part of the index.
Supporting lowercase here, would mean to support lowercase class identifiers in general to be complete, but this seems to be a bit more complicated.

[Java] Fix lowercase inherit interface identifier

---

LaTeX/LaTeX.sublime-syntax

Fixes #608
The issue was partly fixed by PR #370. 
This PR adds support for highlighting XML/HTML inside `\begin{minted}{...} ... \end{minted}`.

[LaTeX] Add html/xml support to embedded code blocks

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

Fixes #2057
This commit modifies the `meta.selector` lookahead in order to exclude leading whitespace.
Whitespace between entities and after the last one keep untouched.

[CSS] Fix selector symbol index

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes #1324
Any method call's argument list can start with a regexp pattern `/<patterhn>/<flags>` syntactically, even though a certain function may not expect one.
Update the list of string patterns to correctly scope functions with trailing `?` and `!`.
Add `rindex` builtin.

[Ruby] Fix Invalid String#match? highlighting

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

Reported by @Resike on Discord.
While I was at it, I also implemented `meta.mapping.{key,value}`, as we established those as standards a while ago and as they are used in Python, JS (?) and JSON. It made sense to add to the PR because it would otherwise be conflicting.
And highlighting of metamethod and normal method assignments.

[Lua] Update mapping matching

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

generic_lookahead should not include patterns like '<<', '<<<', which causes bugs like #2042.

[C++/ObjC++] Fix #2042, generic has no form like '<<'

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

This PR aims to retry the attempt in #1083. 
More details can be seen in #2080. 
With this PR, friend methods **with body** is marked with `entity.name.function`, 
while other types of declarations remain untouched.

[C++/ObjC++] Highlight friend methods with body

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

This PR attempts to support a fix for https://github.com/SublimeTextIssues/Core/issues/2960
It includes 2 major changes.
1. Add support for entity highlighting in unquoted attribute values according to [whatwg.org / 12.2.5.38 Attribute value (unquoted) state](https://html.spec.whatwg.org/multipage/parsing.html#after-attribute-value-(quoted)-state)
2. Split the `meta.class-name` and `meta.toc-list.id` tokens by spaces in order to make the meta-scopes represent a single class or id only. This change makes it possible to target each class/id individually.
_Note: This PR does not add a `punctuation.separator.sequence` for the space between the classes or ids, because it is unclear, whether a space should really be scoped as punctuation._
```html
<html>
<head>
<style type="text/css">
#MyId { …
```

[HTML] Improve class/id attribute lists

---

Makefile/Makefile.sublime-settings

The default is already to detect indentation, so a user override should
be respected

[Makefile] Fix "detect_indentation" setting overriding user settings

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

Fixes #2008
This commit adds a lookahead to avoid matching a string after `{{` as interpolation, if not followed by `}}` in the same line.
Note:
Any character - even quotation marks - are allowed within the interpolation, because an interpolation can contain quoted strings as well.

[Go] Fix unclosed {{ string highlighting

---

Makefile/Makefile.sublime-syntax

This commit applies the `first_line_match` pattern from Bash and Perl syntaxes to improve shebang and editorconfig support.

[Makefile] improve first line match

---

Ruby/Ruby.sublime-syntax

This commit applies the `first_line_match` pattern from Bash and Perl syntaxes to improve shebang and editorconfig support.

[Ruby] improve first line match

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

This commit scopes the `assert` keyword as `keyword.control.flow`.

[Python] Rename scope of assert keyword

---

Git Formats/Git Log.sublime-syntax

This PR proposes to use the `embed` command instead of `push with_prototype` to include the Git Commit.sublime-syntax into Git Log.sublime-syntax
It is a performance tweak (about 5% faster).
**Note:**
It contains a workaround for 
https://github.com/SublimeTextIssues/Core/issues/2395
as the `Git Commit.sublime-syntax` "sets away from main", which causes the `escape` command to be ignored with all current builds of ST3.

[Git Formats] Embed commit message into git log

---

Git Formats/Git Log.sublime-settings

This PR proposes to add a syntax specific settings file for the `Git Log` to prevent such files from being modified upon saving due to
"ensure_newline_at_eof_on_save": true,
"trim_trailing_white_space_on_save": true,
being set in the User/Preferences.sublime-settings
Git indents the git commit messages by 4 spaces including empty lines. Therefore empty commit message lines always contain 4 space characters which are deleted if "ensure_newline_at_eof_on_save": true is set and a gitlog file is saved.

[Git Formats] Add Git Log settings

---

R/R.sublime-syntax

Fixes #1935
The `.S` file extension is used by assembly code, which causes them to be highlighted as R by accident.

[R] Remove .S file extension

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

Formalized in https://www.python.org/dev/peps/pep-0572/ and included in Python 3.8, to be released [later this month](https://www.python.org/dev/peps/pep-0569/). This is the final syntax change required for 3.8 support.
Tests should be self-explanatory. While I was at it, I added a meta scope for lambda bodies and added invalid highlighting for various known locations.

[Python] Highlight inline expression operator :=

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

Fixes #2127
1. replaces the `capture` by pushing into a dedicated comment context as it is slightly faster and therefore already used in a couple of other syntax definitions.
2. includes the newline `\n` into the comment scope in order to fix the issue #2127 and avoid normal completions to be triggered at the end of a comment line.

[Lua] Include newline into comments

---

Git Formats/Git Commit.sublime-syntax
Git Formats/syntax_test_git_commit

```
```
This make it possible to make the `renamed:` (and `copied:`) line more readable by giving a dedicated scope to the `->` separator.
---
`typechage:` has no `->`.

[Git Formats/Git Commit] Add scope for rename punctuation "->"

---

Diff/diff.py

Sublime Text only considers \n a newline character, while readlines()
also splits on various unicode characters. See
https://github.com/SublimeTextIssues/Core/issues/2825 for a bug caused
by this.

Fix files being split on unicode newlines in diff.py

---

Matlab/Matlab.sublime-syntax
Matlab/syntax_test_matlab.m

Simple reorder of context fix the issue.
Add corresponding test.
Fix issue #2111

[Matlab] Fix imaginary number scoped as invalid (#2111)

---

D/D.sublime-syntax
D/tests/syntax_test_d.d

Example:
```d
switch (str) {
case "foo", "bar":
break;
}
```

[D] Fix multiple values in case statement not being parsed correctly

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

This a fix for annoying pink highlights, when class using annotations for a parameter list, for example:
```scala
class TestController @Inject()(controllerComponents: ControllerComponents) extends AbstractController(controllerComponents) with I18nSupport
```
Without that fix, `extends` and `with` have this illegal syntax hightlights.

[SCALA] Proper parsing annotations in a class parameter list

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

This commit removes the `variable-erlang` context, which was used to scope all `erlang` tokens as `variable.namespace`.
As a result the `erlang` token is scoped as ordinary atom if not followed by an accessor.
For the reason of change, please refer to:
https://github.com/sublimehq/Packages/pull/1878#issuecomment-543071180

[Erlang] Remove special scoping of erlang atoms

---

R/R.sublime-syntax
R/Symbol List - Sections.tmPreferences
R/syntax_test_r.R

[R] Add support for named code sections
The issue was filed at:
https://forum.sublimetext.com/t/r-named-sections-not-taken-by-sublime/46891
The function is described at:
https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections
Notes:
As all `#` in front of a section are scoped as `punctuation.` the same is done for normal comments to keep their look synced.

[R] Add support for named code sections

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Fixes #2117
This PR adds support for attributes. The implementation is borrowed from the HTML.sublime-syntax.
The different styles of attribute names (with or without `:`) are not handled in a special way.

[Markdown] Add link/ref/image attribute support

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

Since #1552, preceding signs are scoped as part of numeric literals. This is wrong. I have no idea why I thought that that was correct. I can only plead temporary insanity. This PR restores order.

[JavaScript] Signs aren't part of numeric literals

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js

[Nullish coalescing](https://github.com/tc39/proposal-nullish-coalescing) (Stage 3)
[Optional chaining](https://github.com/tc39/proposal-optional-chaining) (Stage 3)
The regexp to match a dotted property access is now `\.(?!\?[\[(])\??`, which is regrettable.

[JavaScript] Add optional chaining and nullish coalescing.

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

Two minor updates to template strings:
- New `slice` function [added in v1.13](https://golang.org/doc/go1.13#text/template).
- Re-assignment operator `=` [added in v1.11](https://golang.org/doc/go1.11#text/template).
> *Sidebar*: I added a test for the new `slice` function. Previously the only function being tested was `printf`. If we think there's value in testing all those template functions, I can add additional tests.

[Go] Templates String Updates

---

Git Formats/Git Commit.sublime-syntax
Git Formats/syntax_test_git_commit

I feel that hashes in commit messages deserve more attention than they do now (which is none at all), because they are frequently used to cross-reference commits.
I intended to use a `variable.other.hash` scope, because that's basically what hashes are used like (as references), but we already have `constant.numeric.hex.hash.git.commit` in the syntax definition, so I didn't change that. I totally could, if people are in favor of it, however.

[Git Formats] Match hash in commit message

---

RestructuredText/reStructuredText.sublime-syntax
RestructuredText/syntax_test_restructuredtext.rst

This:
* Allows comments to start at columns other than the first
* Allows blank lines to appear in comments, directives, and verbatim blocks
---
My eventual goal here is to allow:
* Latex environments to be embedded in sphinx RsT `.. math::` blocks
* RsT blocks to be embedded in python docstrings

[RestructuredText] Improve handling of directives, verbatim, and comments

---

SQL/SQL.sublime-syntax
SQL/syntax_test_sql.sql

[SQL] handle schemas when scoping `create table` etc., for a more accurate symbol list

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js
Markdown/syntax_test_markdown.md

This PR proposes to modify control structure keyword scope names to make them comply with the results of the discussion in issue #1228.
The goal is to make all default syntaxes use the same precise scopes for related keywords.
Notes:
The following keywords haven't been discussed yet:
1) `await`    -> `keyword.control.flow.await`
2) `debugger` -> `keyword.control.flow.debugger`
3) `with`     -> ~~`keyword.control.flow.with`~~ `keyword.control.import.with`
~~The `with` might need to use another scope though, as it has a slightly different meaning.~~

[JavaScript] Update control keyword scopes

---

XML/XML.sublime-settings

Files with the following extensions can be considered Xml files by default (and it's currently tedious to set syntax manually for each file or change defaults for each MSBuild extension if you happen to work with such project files).
| Extension | Description |
| --- | --- |
| `fsproj` | F# project file |
| `vbproj` | VB.NET project file |
| `shproj` | Shared project file |
| `vcxproj` | Visual C++ project file |
| `sqlproj` | SQL project file |
| `props` | MSBuild properties file |
| `targets` | MSBuild targets file |

[XML] Add associations for MSBuild file extensions

---

PHP/PHP Source.sublime-syntax

BR, NL, TAB, YES, NO, ON, OFF
These constants seem to be nonexistent. I cannot find docs mentioning them and they are just not working as built-in constants in PHP (tried PHP 5.3 and 7.4).

[PHP] Remove nonexistent consts

---

Git Formats/Git Log.sublime-syntax
Git Formats/Git Rebase.sublime-syntax
Git Formats/syntax_test_git_log
Git Formats/syntax_test_git_rebase

This commit renames the remaining scopes to `constant.other.hash` as it was introduced by commit 71aeb9ad2812bbd4bc8cf6e139e963d7a37b7dd8.

[Git Formats] Rename the remaining hash constants

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

After trying the merged https://github.com/sublimehq/Packages/pull/2134 in my daily work. I found constants no longer get highlighted. And according my test, PHP's consts are case-*sensitive* hence should not have `(?i:)` except for some special constants like `true`, `false`, `null`.
```
[Clover@Clover-NB nthu-ee-ust-enroll-censor](master)$ php74 -r "echo JSON_THROW_ON_ERROR;"
4194304
[Clover@Clover-NB nthu-ee-ust-enroll-censor](master)$ php74 -r "echo json_THROW_ON_ERROR;"
Warning: Use of undefined constant json_THROW_ON_ERROR - assumed 'json_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in Command line code on line 1
json_THROW_ON_ERROR
```

[PHP] Fix missing (?x:) for regexes

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

Fixes https://github.com/sublimehq/Packages/pull/1878#issuecomment-546978653
This PR improves the quoted identifier pattern as the old one caused the namespace lookahead to be triggered in the wrong place.
The following token was matched as `namespace` by the `(?={{ident}}\s*:[^:=])` lookahead pattern in the namespace context by accident:
'$get_stacktrace') catch exit:'$get_stacktrace':
The new pattern makes sure to stop matching at the first unescaped single quote. Any number of escaped backslashes is allowed in front of it.
Note: This change has no impact on parsing performance.

[Erlang] Fix quoted identifier lookahead

---

R/R.sublime-syntax
R/syntax_test_r.R

1. adds punctuation scopes to numbers.
2. renames the imaginary numbers to `constant.numeric.complex.imaginary`
3. merges some rules to compensate performance impacts caused by the added capture groups required for (1).
4. makes use of character classes where appropriate (e.g.: [eE] )
5. removes some unnecessary escapes (e.g. (\+\-) => [-+])
6. adds a couple of test cases for the different types of numbers

[R] Improve numbers

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Fixes #1453
This PR is an attempt to fix the issue #1453.

[Markdown] Fix ligature tokanization

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

This PR proposes to ...
1. rename some scope names to comply with the recent changes to the scope naming guidelines.
2. merges the float and imaginary match rules in order to improve parsing performance by about 14%. The solution is borrowed from Perl and adapted to Python.
EDIT:
Another banchmark even shows up to 30% improvement. The test case consists of some more complicated numbers.
```
12_34_5.1_23_45e+10 12_34_5.1_23_45e+10 12_34_5.1_23_45e+10 12_34_5.1_23_45e+10
```

[Python] Improve numbers

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This PR
1. Fixes #2126
I used the scope ~~`constant.numeric.integer.rational.ruby` for e.g. `12r` and `constant.numeric.float.rational.ruby` for `12.3r`~~ `constant.numeric.rational.ruby` for e.g. `12r` and `12.3r`.
2. Fixes numbers with decimal or octal prefix, which are not highlighted currently
3. ~~Changes the dot in e.g. `1.` to be included in the number, instead of having the scope `punctuation.accessor` (which is wrong in my opinion)~~
4. Applies more specific scopes `integer`, `float`, `decimal`, `binary`, `octal`, `hexadecimal` instead of just `constant.numeric.ruby`
Notice: What is the purpose of the negative lookahead `(?![^[:space:][:digit:]])`, which is currently used in the regex after a decimal dot? I don't see any benefit from it, so I deleted it. In case it was to allow …

[Ruby] Improve numbers

---

JavaScript/JavaScript.sublime-syntax
JavaScript/tests/syntax_test_js.js
JavaScript/tests/syntax_test_js_bindings.js

This PR
1. uses `storage.type.numeric` scope for numeric literal suffixes.
2. adds more detailed `constant.numeric.[integer|float]` scopes.
Note:
1. The 2nd change required to change the pattern for floating point numbers and its order in the context in order to correctly distinguish between integers and floats.
2. The 1st rule being used to match illegal octal numbers is removed as its function is handled by the 2nd illegal octal rule.
3. The changes don't have an impact on parsing performance.

[JavaScript] Improve numbers

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

This PR adds the `keyword.declaration` scope to the `package` and `sub` keywords.

[Perl] add keyword declaration scope

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

This PR ...
1. applies numeric scopes according to the scope naming guidelines
2. adds decimal punctuation scopes
3. simplifies the numeric literal suffixes
4. cleans up the floating point pattern a bit
5. removes duplicated numeric test cases
6. adds test cases especially to check the floating point variations

[Scala] Improve numbers

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

This PR renames `constant.numeric.integer.generic-base` to `constant.numeric.integer.other` and scopes the whole base part as punctuation to equalize with hexadecimal prefixes.

[ShellScript] Improve numbers

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This commit renames the scopes for `0x`, `0b`, `0` numeric prefixes to `punctuation.definition.numeric.base`.

[Ruby] Rename numeric base scopes

---

Haskell/Haskell.sublime-syntax
Haskell/syntax_test_haskell.hs

This commit applies the numeric scope naming guidelines and adds some basic test cases.

[Haskel] Improve numbers

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

This commit
1. removes the punctuation scope from the `e` exponent character
2. scopes the whole base part of integers as `punctuation.definition.numeric.base`.
_Note:_
When I saw the `punctuation.definition.numeric.base` scope I wondered whether it was a good general scope name for all kinds of numeric prefixes like `0x`, 0b`, etc.
Most syntaxes use specialized scopes like `punctuation.definition.numeric.hexadecimal`.
Thoughts?

[Erlang] Improve numbers

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs
C#/tests/syntax_test_Generics.cs
C#/tests/syntax_test_Operators.cs
C#/tests/syntax_test_PreprocessorDirectives.cs
C#/tests/syntax_test_c#.cs

1. applies the scope naming guidelines to all numeric literals
2. removes some numeral variables which are used only once and introduces some of those from other syntaxes
4. Improves the floating point pattern by avoiding lookaheads for parsing performance reasons.
Parsing performance increases by about 7%.

[C#] Improve numbers

---

LaTeX/LaTeX.sublime-syntax
LaTeX/syntax_test_latex.tex

- Add multi-cite variants and a couple other supported by biblatex.
- Allow multiple sets of []{} parameter blocks for multi-cite.
Just add them to all so we don't have to duplicate the entire match.
- Add a test for star variant and ensure they work.
- Add a reference to biblatex's doc.
- Remove an unnecessary capture group.
Closes #1813.
Fixes #1762.

[LaTeX] Rewrite citation matches

---

YAML/YAML.sublime-syntax
YAML/tests/syntax_test_block.yaml
YAML/tests/syntax_test_types.yaml

This commit adds some capturing groups to the existing numeric literal match patterns in order to distinguish the types (int/float/...) and to add scopes for the separators.

[YAML] Improve numbers

---

D/D.sublime-syntax
D/tests/syntax_test_d.d
D/tests/syntax_test_old.d

This commit applies the latest numeric scope naming guidelines.
1. scope number literals  `constant.numeric.[imaginary|integer|float].[binary|decimal|hexadecimal]
2. scope number suffixes `storage.type.numeric`
3. scope number prefixes `punctuation.definition.numeric.base`
4. add/rename variables for several number patterns as done in the other syntaxes as well.
5. add test cases for imaginary numbers and some possible tricky edge cases especially with floating point numbers with trailing `.`
_Benchmark:_
Parsing performance improved by 4%.
10k lines of:
2_0__000; 1L; 1u; 1U; 1Lu; 1LU; 1uL; 1UL; 0b1; 0b10__1; 0B1; 0xFf; 0x012_3; 0X1; 0_.0_; 0_.;.123_1243; 2313472389742e1i; 3423.2e-45;.4E+4L; 1f; 0x123p2f; 0b10101101f; 0x.1aFp2; 0xF.AP-2f;

[D] Improve numbers

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

Adds the following numeric literal updates [introduced in v1.13](https://golang.org/doc/go1.13#language) — all of these changes were part of [recent number literal proposal](https://github.com/golang/proposal/blob/master/design/19308-number-literals.md):
- [Binary integer literals](https://golang.org/ref/spec#Integer_literals).
- [Octal integer literals](https://golang.org/ref/spec#Integer_literals) behind a new (additional) prefix.
- [Hexadecimal floating-point literals](https://golang.org/ref/spec#Floating-point_literals).
- [Imaginary literals](https://golang.org/ref/spec#Imaginary_literals) can now be used with any numeric literal.
- [Numeric separators](https://github.com/golang/proposal/blob/master/design/19308-number-literals.md#digit-separators) can be used in any numeric literal.

[Go] Numeric Literal Updates (v1.13)

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

They did not allow for literals before.
Fixes #2173.

[Python] Relax dict and set heuristics

---

JavaScript/JavaScript.sublime-syntax

This PR is to improve the parsing performance of numeric literals. It does not change any behavior.
The `{{identifier_break}}` is a negative lookahead of `{{identifier_part}}` and thus should not be required to ensure the boundaries of an illegal numeric literal.
I can't explain why, but this lookaheads even have a negative impact on parsing performance if the parsed code contains only valid numbers and therefore the context should be popped off before any of those rules is matched. (Or is it due to ST merging all rules to one single rule?)
before: 400ms
after: 334ms
result: -15%
10k lines of the following content:
0b010100101 0b010100101 0b010100101 0x123af 0x123af 0x123af 0.002 123.42 123e10
Benchmarks with pure binary numbers even result in up to -24%!

[JavaScript] Improve numbers parsing performance

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Multi-line raw f-strings had an invalid line continuation context included.
Whil I was at it, I noticed that we didn't highlight line contiuations for block strings at all, so I added that.
Reported in https://forum.sublimetext.com/t/python-multiline-f-string-r-string-syntax-highlighting/47471.

[Python] Fix raw f-block-strings

---

Ruby/Snippets/Wrap-in-Begin-Rescue-End.sublime-snippet

* Don't trap Exception by default, but rather StandardError
If you rescue from Exception, you're unintentionally trapping Signals from the system like SIGQUIT

Ruby rescue block, idiomatic Snippet

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Fixes #2181
In order to avoid the `{{identifier}}{{method_punctuation}}` in the `identifiers-accessors` context matching reserved words as method call the `try-regex` context needs to pop off without consuming any whitespace.
This issue was introduced for the `.to_s` method by PR #2017, but already existed for methods like `assert_match` if they were not followed by a regexp pattern.

[Ruby] Fix inline conditional keyword highlighting

---

R/R.sublime-syntax
R/syntax_test_r.R

Functions and variables after the `$` sign should not be recognized as build-in functions.
Before
After

[R] do not highlight builtin functions after $

---

C++/C++.sublime-syntax
C++/C.sublime-syntax
C++/syntax_test_c.c
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/Objective-C.sublime-syntax
Objective-C/syntax_test_objc++.mm
Objective-C/syntax_test_objc.m

This commit...
1. applies scope naming guidelines to all numeric literals
2. implements dedicated C style and C++ style contexts with the syntax specific behavior.
a) C/ObjC supports only limited amount of predefined suffixes C++/ObjC++ supports all kind of suffixes which are either predefined (see C) or user defined via `operator ""` keyword.
b) C++14 introduces `'` as digit to improve readability of large numbers, while C does not support it.
c) both C and C++ support hexadecimal floats
Dedicated means, C++ does no longer import C number contexts as the required patterns are simply differ too much.
3. adds illegal matching of octal or hexadecimal digits as well as unsupported suffixes (in C). The implementation is inspired by Bash.sublime-syntax and complies with the compiler error …

[C/C++/ObjC/ObjC++] Improve numbers

---

CSS/CSS.sublime-syntax

This PR
1. removes unhandled capture groups
2. removes unnecessary push/pop for `:` punctuation
3. adds missing `\b`
4: removes some quotes
It does not change the external behavior.

[CSS] Improve media query properties

---

JavaScript/JSON.sublime-syntax
JavaScript/tests/syntax_test_json.json

This commit applies the numeric literal scope naming guidelines.

[JSON] Improve numbers

---

CSS/CSS.sublime-syntax

This commit is just to improve parsing performance by removing capture groups within the literal-string context.

[CSS] Remove capturing groups from strings

---

Rails/Snippets/$LABEL.sublime-snippet
Rails/Snippets/%3C%=-Fixtures_identify(%3Asymbol)-%%3E.sublime-snippet

Rails shouldn't pollute all YAML files with these snippets.

[Rails] Remove Rails snippets for YAML

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

Congrats for ST 4 :beer: 
```php
$var = fn($x)
//     ^^ meta.function.arrow-function.php - meta.function-call
=> $x * 2;
// ^^ punctuation.definition.arrow-function
$var = fn($x)
//     ^^ meta.function-call - meta.function.arrow-function.php
;
```
- Before PHP 7.4, `fn` can be used as a function name.
- Since PHP 7.4, `fn` is a reserved word for arrow function.
[Previously](https://github.com/sublimehq/Packages/pull/1961/commits/c6210f7a1cfa62376f0aa9aed499e983b337e430), I assumed that `fn` is always a reserved word because of ST's parsing engine's limitation.
---
PHP 7.4.0 will just be released by the end of this month.

[PHP] Fix "fn" function call

---

CSS/CSS.sublime-syntax
CSS/syntax_test_css.css

`1e1` wasn't recognized and the exponent pattern was repeated, allowing
`.1e1e1`.

[CSS] Number fixes revolving exponents

---

Rust/Rust.sublime-syntax
Rust/syntax_test_rust.rs

Simply swap comparison and assignement operator to be sure assignment get tested first.
Add relevant test.
Fixes issue #2147

[Rust] Fix scope for assignment operator

---

Rails/syntax_test_rails.rb
Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This PR applies the #1228 and tries to find proper solutions for some special keywords/situations where needed.

[Ruby] Improve keyword scopes

---

ShellScript/Bash.sublime-settings

I guess it's reasonable to use `\n` as the default line ending for the `Bash` syntax because
- `.sh` files are mostly run/written under/for Unix env 
- Unix bash will emit `: No such file or directory` or `'\r': command not found` if using `\r\n` as the line ending
- My Windows git-bash won't emit error with either line ending. But I personally prefer using `\n` for everything unless it must be `\r\n` (such as `Batch`).
```bash
#!/usr/bin/env bash
echo hello
```
It looks like the shebang executable is recognized as `bash\r` or `\r`.
```text
[root ~]$ ./hello.sh 
: No such file or directory
```
```text
[root ~]$ bash hello.sh 
hello.sh: line 2: $'\r': command not found
hello.sh: line 4: $'\r': command not found
hello
```
- https://forum.sublimetext.com/t/unix-line-endings-for-sh-files/47653 …

[Bash] Use LF as the default line ending

---

C++/C++.sublime-syntax
C++/syntax_test_cpp.cpp
Objective-C/Objective-C++.sublime-syntax
Objective-C/syntax_test_objc++.mm

Coroutines are a new feature of C++20. The new keywords are
- co_await
- co_return
- co_yield
Any function with such a keyword in its body is considered a [coroutine](https://en.cppreference.com/w/cpp/language/coroutines).

[C++/ObjC++] Add C++20 coroutine keywords

---

TCL/Tcl.sublime-syntax
TCL/syntax_test_tcl.tcl

Fixes issue #2201 :
- Add scope to the regexp flag separator
- Allow regexp not in curly brace following the separator
- Add relevant test
- Remove tab indentation from the test (warning message from ST)

[TCL] Support regex not in curly braces

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

There was an issue in that the rendering of the Clojure code block in
a Markdown file would not be rendered properly. This is documented in
Issue #1769 - with screen grabs. This addition to the syntax file
corrects that issue by adding the section for the Clojure code block in
the Markdown file.

[#1769] Fix for Clojure code block

---

CSS/Default.sublime-keymap
CSS/css_completions.py

Fixes #2076
This PR proposes several changes to the css_completions module. The main goal is to create a consistent behavior in manner of completing property names and adding colon and/or semi-colon after it. The current implementation of the css_completions and the related keymap entries result in different behavior in manner of handling the `: ;` after a property name.
Furthermore completions should always be triggered at the end of a CSS selector section no matter which syntax embedds the CSS. It was limited to HTML up to this commit.
Some more details can be found in the commit messages.

[CSS] Improve completions

---

Go/Go.sublime-syntax

This commit removes some variables which were replaced by
10c4b5c6051091132083f69518f273acb510835c and therefore are no longer used.

[Go] Remove unused variables

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

1. removes the unusual syntax in the `match-operators` context.
2. groups the operator match patterns by scope and length to
a) ensure ligatures to keep working properly
b) increase parsing performance by about 8..12%
3. applies more detailed scope names to most of the operators.

[Go] Optimize operators

---

XML/DTD.sublime-syntax

_I know about the intention not to add further syntax definitions. Therefore this is just a proposal without a strong meaning about whether it is worth to add or not - but the effort is just too small to do it anyway._
The XML.sublime-syntax contains all we need for fully qualified support for dedicated DTD files.
This PR therefore proposes to expose these existing rules to enable Sublime Text to highlight doctype definition files and their subsets (*.ent, *.mod) out of the box.
Notes:
1. The test cases for doctype definitions are located in the syntax_test_xml.xml.
2. This file type seems not to be used by any officially listed 3rd party package at packagecontrol.io so far.

[XML] Add support for dtd/ent/mod files

---

YAML/YAML.sublime-syntax

Fixes https://github.com/SublimeTextIssues/Core/issues/3110
Fixes https://github.com/sublimehq/sublime_text/issues/3215 (partly)
This PR proposes a change to avoid the first letter of mapping keywords not being detected as separate token, which results in wrong autocompletion results.

[YAML] Fix tokenization issue

---

Java/Java.sublime-syntax
Java/syntax_test_java.java

Extended rules for escapes to handle all types present in Java:
1. Unicode escape:
```
System.out.println("\u0078 \u0079 \u007A");
```
2. Octal escapes:
```
System.out.println("\170 \171 \172");
```
3. Simple escapes now limited to a set of allowed ones instead of matching `\\.`

[Java] Unicode and octal escapes in strings

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Reported at https://forum.sublimetext.com/t/python-f-block-string-scoping-bug/48027.

 [Python] Fix f-string ending punctuation scope name 

---

Go/Go.sublime-syntax
Go/syntax_test_go.go

This commit scopes the `name` in `package name` statements as entity the same way as Perl.

[Go] add scope for package name

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

The previous implementation is too strict so that it fails parsing exceptions scattered in multiple lines.
```php
try {
// ...
} catch (
// vvv failed
\Custom\Exceptoin1 |
\Custom\Exceptoin2 $e
// ^^^ failed
) {
// ...
}
```
If the `st3` branch is still maintained, I can make a PR to it.
---
Fixes https://github.com/sublimehq/Packages/issues/2358

[PHP] Fix catch multiple exceptions in a single catch

---

PHP/PHP Source.sublime-syntax
PHP/syntax_test_php.php

Previously it's only done in the `class-body`.
```php
trait {
public static ?Foo $str = '';
//                ^ storage.type.nullable
//                 ^^^ support.class
}
```
If the `st3` branch is still maintained, I can make a PR to it.

[PHP] Fix typed property not highlighted in trait

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

This PR ...
1. consolidates the way the case-insensitive flag `(?i)` is applied to match rules. All remaining rules are modified to apply it as local flag for strings only.
Notes:
a) The `{{javascript_mime_type}}` is case-insensitive already.
b) It is removed from lookaheads with non-word characters only.
c) All tag attributes are matched case-insensitive now.
2. removes the leading `\b` in some remaining tag and attribute names as the way the syntax works already ensures any match to start at an appropriate position (not in the middle of a word).
3. replaces the trailing `\b` in some remaining tag and attribute names by `{{tag_name_break}}` or `{{attribute_name_break}}` to make sure to properly match the name boundaries according to the whatwg specs under all circumstances.
4. …

[HTML] Consolidate tag/attribute name matching

---

HTML/HTML.sublime-syntax

This PR proposes to consolidate the usage of escapes vs. quotes in all remaining matches. It prefers unquoted values, if the required escapes are shorter and still well readable.
It does not provide any functional changes.

[HTML] Consolidate quotes

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Fixes #2248
Unsure on the scope to use, but I like the `.github` tag at the end. In a sense, `constant.language` is "right," considering that these represent Booleans, but I didn't think that would go over well.

[Markdown] Add GitHub list checkboxes

---

Scala/Scala.sublime-syntax
Scala/syntax_test_scala.scala

In `single-type-expression-tail`, `@/` would match the lookahead on line `1774` but not the annotation, thus causing an infinite loop.

[Scala] Fix infinite loop

---

JavaScript/Default.sublime-keymap

When the interpolated string scopes were changed, the key bindings broke. This PR updates the keymap to use the new scopes.

[JavaScript] Fix key bindings in template strings.

---

Groovy/Groovy.sublime-syntax

This will allow Sublime Text to detect syntax for files without extension but with specified shebang line, such as Jenkinsfiles with non-standard names (e.g. `Jenkinsfile-build`, `Jenkinsfile-deploy`, etc).
Tested locally (`~/.config/sublime-text-3/Packages/User/Groovy.sublime-syntax`) with different types of shebang lines:
* `#!/usr/bin/env groovy`
* `#!/usr/bin/groovy`
* `#! groovy`
* `#!groovy`
* etc

[Groovy] Adding Groovy detection using shebang line

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

Add word boundary checks to the heredoc type names to ensure correct scoping of short and long tag names like SH vs. SHELL.
Without those only SH is scoped in SHELL.
A tag name like SHOUT was scoped as SH heredoc as well.

[Ruby] Fix SHELL heredoc tag boundaries

---

Lua/Indentation Rules.tmPreferences
Lua/Indention Rules.tmPreferences

Fixes #2260
1. excludes `comment` and `string` quotes from indention rules
2. renames the file to `Indention Rules.tmPreferences` as this is the most commonly used name in most packages in order to improve the common look of the packages.

[Lua] Fix indention rules' scopes

---

Graphviz/DOT.sublime-syntax
Graphviz/syntax_test_dot.dot

Since relationships are the primary thing of interest in Graphviz files, they shouldn't be marked as `punctuation`.
I've had this locally for ages and forgot to push it.

[Graphviz] Change relationship scope

---

AppleScript/Comments.tmPreferences

The old file was causing the wrong multi-line comment characters to be reported to a package extension i have. This change fixes it

[Applescript]Fixed the multi-line comment characters that are used/reported.

---

CSS/Comments.tmPreferences
CSS/Symbol Index.tmPreferences
CSS/Symbol List - Group.tmPreferences
CSS/Symbol List - Selector.tmPreferences

[CSS] Fix tmPreferences

---

Groovy/Comments.tmPreferences
Groovy/Symbol List - Class Variables.tmPreferences
Groovy/Symbol List - Classes.tmPreferences
Groovy/Symbol List - Methods.tmPreferences
Groovy/Symbol List - Variables.tmPreferences

The goal is a common naming scheme to be applied to all packages, so
files of a certain function have the same name in each package.

[Groovy] Fix tmPreferences

---

Lua/Comments.tmPreferences
Lua/Symbol List.tmPreferences

[Lua] Fix tmPreferences

---

Markdown/Indentation Rules.tmPreferences
Markdown/Symbol List - Heading.tmPreferences
Markdown/Symbol List - Reference Link.tmPreferences

[Markdown] Fix tmPreferences

---

PHP/Comments.tmPreferences
PHP/Indentation Rules - Annex.tmPreferences
PHP/Indentation Rules - heredoc end.tmPreferences
PHP/Indentation Rules.tmPreferences
PHP/Symbol List.tmPreferences

3. tweaks the formatting of some tmPreferences
The goal is a common naming scheme to be applied to all packages, so
files of a certain function have the same name in each package.

[PHP] Fix tmPreferences

---

ShellScript/Comments.tmPreferences
ShellScript/Indentation Rules.tmPreferences
ShellScript/Symbol List - Aliases.tmPreferences
ShellScript/Symbol List - Expansions.tmPreferences
ShellScript/Symbol List - Functions.tmPreferences
ShellScript/Symbol List - Variables.tmPreferences

3. removes symbol transformations to display symbols as collected from the source code

[ShellScript] Fix tmPreferences

---

SQL/Comments.tmPreferences
SQL/Indentation Rules.tmPreferences

[SQL] Fix tmPreferences

---

XML/Comments.tmPreferences
XML/Indentation Rules.tmPreferences

[XML] Fix tmPreferences

---

YAML/Comments.tmPreferences
YAML/Symbol List.tmPreferences

This commit just removes the `name` keys and the DOCTYPE.

[YAML] Fix tmPreferences

---

Pascal/Comments.tmPreferences
Pascal/Indentation Rules.tmPreferences

1. splits and renames the tmPreferences according to their function
2. removes the `name` key.

[Pascal] Fix tmPreferences

---

Python/Comments.tmPreferences
Python/Indentation Rules.tmPreferences

1. splits and renames the tmPreferences according to their function
2. removes the `name` key.
Note: Symbol List and Symbol Index are already part of a former PR.

[Python] Fix tmPreferences

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

Fixes #2307
Closes #2315
This commit makes sure to pop off the context after matching while/until keywords to properly scope grouped conditions. The missing `pop` caused them to be scoped as expansions instead.

[ShellScript] Fix while/until condition highlighting

---

Git Formats/Git Config.sublime-syntax
Git Formats/syntax_test_git_config

https://github.com/git/git/commit/87f17d790d8e350e8df1101476882f7751581ee0
The release notes [say](https://github.com/git/git/blob/master/Documentation/RelNotes/2.26.0.txt#L38-L39) "the basic 7 colors" get "bright" modifiers, but there are 8. I think they forgot to count "0" in 0-7.

[Git] Add 'bright' versions of colors

---

Makefile/Makefile.sublime-syntax
Makefile/syntax_test_makefile.mak

Fixes #2318
The Makefile.sublime-syntax includes the Bash.sublime-syntax.
The `scope:source.shell#prototype` is injected into the embedded Bash.sublime-syntax using `with_prototype` maybe as workaround for https://github.com/sublimehq/sublime_text/issues/1062
The `with_prototype` command ignores `meta_include_prototype: false`, which is heavily used by Bash.sublime-syntax to prevent the `prototype` context from being included into a bunch of contexts such as strings.
As the prototype context is not included into source.shell's main context only, it is not necessary to inject it via `with_protoype`. Hence it is moved to the `shell-body` together with `source.shell`, which is suggested by the core issue as proper workaround.
The `prototype` context of the Bash.sublime-syntax also includes …

[Makefile] Fix embedded ShellScript prototypes

---

XML/Comments.tmPreferences

Fixes #2325
This commit includes the punctuation.definition.tag scope into the
comments trigger selector to enable commenting out a tag if
1. the caret is positioned directly before the tag
2. the caret is located at the end of a tag, which also is the end of file as this situation prevents the `meta.tag` scope from being popped off the stack correctly.
As a result the toggle_command does
1. still not work when toggled from within a tag (which is intended behavior) in order to
2. prevent a tag from being messed up by comments.

[XML] Fix comment trigger scopes

---

C#/C#.sublime-syntax

This PR simplifies a pattern in the C# syntax while leaving it functionally unchanged.
The old pattern is susceptible to catastrophic backtracking due to a combinatorial explosion caused by the inner and outer `*` modifier. Sublime text didn't really show any performance problems, but we did experience problems downstream in syntect/bat: https://github.com/sharkdp/bat/issues/677
The appearance of catastrophic backtracking for the old pattern can be seen here: https://regex101.com/r/O2AcN7/1
This change was originally proposed by @keith-hall [here](https://github.com/sharkdp/bat/issues/677#issuecomment-612502648).
Performance in Sublime text is not adversely affected.

[C#] Simplify pattern to avoid catastrophic backtracking

---

PHP/PHP Source.sublime-syntax
PHP/tests/syntax_test_php.php

Our PHP syntax has already detected single/double-quoted regex strings which are written in a single line. Thanks to `branch_point` in ST 4, this PR makes it also detect those which are written in multiple lines.
```php
$regex = '/
a{0,6}
//   ^^^^^ keyword.operator.quantifier.regexp
/ux';
$regex = '/foo?/ux';
//            ^ keyword.operator.quantifier.regexp
$not_regex = 'foo?';
//               ^ string - source.regexp
$not_regex = '/foo?';
//                ^ string - source.regexp
// there is no "T" regex modifier
$not_regex = '/foo?/uTx';
//                ^ string - source.regexp
```

[PHP] Add highlight for multiline regex string

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Fixes #2360
Reference definitions need to be separated by line to correctly display them in the Goto Symbol Overlay. The newline `\n` is no longer included into the `meta.link.reference` scope in order to separate the lines from each other.
**Before**
**After**
**Notes**
1. As `\s*` includes the `\n` the `link-title` context is modified accordingly.
2. The former `after-link-title` and `link-ref-def` contexts are merged into a `link-ref-def-expect-end`

[Markdown] Separate bibliography reference links

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

This commit removes overlapping of
`meta.function.inline.python meta.function.inline.parameters.python`

[Python] Fix overlapping meta scope in lambdas

---

Python/Python.sublime-syntax
Python/syntax_test_python.py

This commit fixes the return type annotation after line continuation.
It also removes the `comments` from the `function-after-parameters` as it seems not to be used at all.
The `:` is moved into a dedicated `function-terminator` context to avoid the `(?=:)` lookahead used to pop the return type annotation context.

[Python] Fix function return type annotation

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

This commit modifies the syntax definition in order to highlight all leading `%` as punctuation.definition.comment as it looks a bit odd to have only the first one colored differently in documentation comments like.
```Erlang
%%----------
%% Section
%%----------
```

[Erlang] Fix comment punctuation scope

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

This commit pops the `let` statement if a `;` is detected and adds support for line continuation operator `\`.
See: https://forum.sublimetext.com/t/color-bug-in-shell/51820

[ShellScript] Fix let statement termination

---

ShellScript/Bash.sublime-syntax
ShellScript/test/syntax_test_bash.sh

This commit adds the `case-end-ahead` context to all nested case pattern parentheses in order to ensure to limit invalid syntax highlighting to the `case ... esac` block if the closing parenthesis is missing.

[ShellScript] Fix incomplete case patterns

---

Python/Python.sublime-build

Since Python 3.3, a `py` launcher is installed on Windows, which is by
far the best choice to execute python scripts on Python. It can
interpret shebang lines, read the default Python version configuration
and even handle virtualenvs (although the latter is unlikely to occur
within ST's environment). It will also be available in the PATH with the
default installer configuration, unlike the `python` executable.
Also change the main command to use `cmd` instead of `shell_cmd`.
https://docs.python.org/3/using/windows.html#launcher
Closes #381.

[Python] Use Windows launcher for build system

---

Python/Snippets/for.sublime-snippet

I also tried to be smart and replaced a couple `${1:pass}` with `${1:${SELECTION:pass}}`, but it seems the SELECTION variable is always defined, even if the selection is empty, so the default is never used.

[Python] Update for snippet to Python 3

---

PHP/Snippets/class-{-}.sublime-snippet
PHP/Snippets/declare-strict_types.sublime-snippet
PHP/Snippets/do-while(-).sublime-snippet
PHP/Snippets/elseif(-).sublime-snippet
PHP/Snippets/for(-).sublime-snippet
PHP/Snippets/foreach(-).sublime-snippet
PHP/Snippets/function-xx(-).sublime-snippet
PHP/Snippets/if(-)-else(-).sublime-snippet
PHP/Snippets/if(-).sublime-snippet
PHP/Snippets/switch(-)-case.sublime-snippet
PHP/Snippets/switch(-).sublime-snippet
PHP/Snippets/while(-).sublime-snippet

- use `//` to comment rather than `#` (`#` is valid but I have never seen people use it in PHP)
- use `condition` rather than `$a <= 10` (just like other snippets such as [if-else](https://github.com/sublimehq/Packages/blob/f36b8f807d5f30d2b8ef639232a9fc5960f550fa/PHP/Snippets/if(-)-else(-).sublime-snippet))
and
- add a snippet for adding `declare(strict_types=1);`, which is used basically at the beginning of every serious modern PHP files.

[PHP] Minor snippet refinements

---

ShellScript/Bash.sublime-syntax

So why do we use `Bourne Again Shell (bash)` while we don't use `Structured Query Language (SQL)`? Let's make it cleaner.
---
Resolves https://github.com/sublimehq/Packages/issues/2384

[Bash] Change syntax name to "Bash"

---

HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

Fixes #2403
According to the linked specification at (1) the `.` is part of the
allowed custom tag characters. The current implementation allows an escaped dot `\.` only, which is wrong.
```
PotentialCustomElementName ::=
[a-z] (PCENChar)* '-' (PCENChar)*
PCENChar ::=
"-" | "." | [0-9] | "_" | [a-z] | #xB7 | [#xC0-#xD6] | [#xD8-#xF6]
| [#xF8-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x203F-#x2040]
| [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF]
| [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
```
(1) https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts

[HTML] Fix dotted custom tag names

---

JavaScript/JavaScript.sublime-syntax
JavaScript/TypeScript.sublime-syntax
JavaScript/tests/syntax_test_js.js
JavaScript/tests/syntax_test_typescript.ts

Rewrite of #2394. This should reliably differentiate methods from class fields or object properties. In addition, the behavior for `get`/`set`/`async` should always be correct (even when someone uses one as a class field name or property name).

[JavaScript] Use branching for method detection, take two

---

C#/C#.sublime-syntax
C#/tests/syntax_test_C#7.cs
C#/tests/syntax_test_GeneralStructure.cs

Some fixes for bugs in the C# syntax definition which I noticed during day-to-day work; there are no open issues relating to these:
- fix `implicit operator` methods
- fix `for` loops without `var` etc.
- add support for `readonly get` accessors
- fix `stackalloc` and ternary operators

[C#] assorted fixes

---

Erlang/Erlang.sublime-syntax
Erlang/Indexed Reference List.tmPreferences
Erlang/Symbol List - Function Definition.tmPreferences
Erlang/syntax_test_erlang.erl

This commit renames all `meta.[function|macro|...].name` scopes to
`meta.[function|macro|...].identifier` because
1. the scope naming guideline uses `meta.annotation.identifier`
2. the identifier may consist of a qualifier and the name
3. this scope name is already used in syntaxes like Java.

[Erlang] Rename scope meta...name->meta...identifier

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This is my first try to implement #1879. I checked that Rubymine behaves in the same way.
An open task would be to adopt changes into `syntax_test_ruby.rb`, but I'd do this only after someone acknowledged the way I did it and that it's okay.
Examples would be:
```
%I(asd foo#{1 + 1 + 'x'} bar)
%I[asd foo#{1 + 1 + 'x'} bar]
%I<asd foo#{1 + 1 + 'x'} bar>
%I!asd foo#{1 + 1 + 'x'} bar!
%i(asd foo bar)
%i[asd foo bar]
%i<asd foo bar>
%i!asd foo bar!
```
Since I haven't worked on syntax files yet I would appreciate any feedback.

[Ruby] Change color of %i and %I symbol array literal elements according to symbol color (#1879)

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

Fixes #2398
Only the closing characters of a single quoted string and the corresponding q// functions may be escaped. All other characters are
interpreted as is.

[Perl] Fix single-quoted escapes

---

JavaScript/Comments.tmPreferences

JSON is in a separate package now and defines [its own comments file](https://github.com/sublimehq/Packages/blob/master/JSON/Comments.tmPreferences).
Reverts 483657a3db466716505255c6380f57698354508b.

[JavaScript] Don't affect source.json scope

---

Markdown/Markdown.sublime-syntax

In Sublime Text, JSON is really JSONC (JSON with comments and trailing commas), so enable `jsonc` as a marker for the same embed.

[Markdown] Alias jsonc -> json

---

Regular Expressions/File Pattern.sublime-syntax
Regular Expressions/syntax_test.sublime-file-patterns

Minimal syntax for ST [file patterns](https://www.sublimetext.com/docs/file_patterns.html). Like #2214 does with Regex Replace, this is for internal use if/when the "Where" (which files) portion of "Find in Files" can be scoped.
Also provides an entry point for things like PackageDev's [Project.sublime-syntax](https://github.com/SublimeText/PackageDev/blob/master/Package/Sublime%20Text%20Project/Sublime%20Text%20Project.sublime-syntax) that might not want the `,` included. ~(Although the bits anchored with `^` probably won't work either as JSON values.)~ _[Fixed?]_
I tried to distinguish the `/*` and `*/` behavior from the normal `*` behavior so that people might notice it works differently.

[Regex] Sublime internal file patterns

---

Lua/Lua.sublime-syntax
Lua/tests/syntax_test_lua.lua

This fixes missing references in "Goto Reference..." (Shift+F12) for Lua source files by using the appropriate scope `meta.function-call.lua` in functions calls.
Missing `keyword.declaration` scope names for **function** keyword were also added according to the documented syntax naming conventions to have a better Lua syntax highlighting in some newer color schemes.

[Lua] Fix goto function references

---

HTML/HTML.sublime-syntax

This PR proposes to ...
1. add section headers `###[ name ]###` to group related contexts.
2. sort sections and contexts logically based on the model of the XML.sublime-syntax.
It does not provide any functional changes.
Note: I tracked all the changes but at some point it was not easy to update all the small commits, thus had to squash them.

[HTML] Add sections and logically sort contexts

---

Matlab/Matlab.sublime-syntax
Matlab/syntax_test_matlab.m

* Add scope for base prefixes for [hexadecimal and binary number literals](https://www.mathworks.com/help/matlab/matlab_prog/specify-hexadecimal-and-binary-numbers.html), wich were introduced in R2019b
* Add scope for type suffixes for hexadecimal and binary number literals
* Add scope for decimal separator in floating point numbers
* Notice: all numbers without base prefix are stored as floating point by default in Matlab

[Matlab] Improve numbers

---

Ruby/Ruby.sublime-syntax
Ruby/syntax_test_ruby.rb

This is mostly to fix the ligature issue, since `->` is currently tokenizing as arithmetic and comparision
Before:
After (ligature works):

[Ruby] Add lambda operator to the list of builtin functions

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Thoughts? GitHub's syntax highlighter clearly disagrees with this change.
I wrote it while I was editing a big Markdown file and adding code spans in list items that switched the highlighting for large swathes of the rest of the file. I found that to be disconcerting... but if someone forgot to close a code span in a README and pushed it, that could be worse, depending on their MD implementation. 🤷‍♂️

[Markdown] Make code spans end at new list item

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

Fixes #2372
This PR proposes few scope changes which attempt to help color schemes to better highlight/distinguish the different types of entities used in Erlang.

[Erlang] Tweak some scopes

---

Python/Python.sublime-syntax
Python/syntax_test_python_strings.py

Correctly match some tricky format specifications using branches. Some
quite unusual ones are not correctly matched but tests have been added
to document the exact behavior.
My first experiement with non-determinism and quite a tricky case at that because we're not aiming for 100% accuracy but it still allows for more correct highlighting.
Closes #2232.
Closes #2241.

[Python] Non-deterministic format-spec matching

---

Markdown/Markdown.sublime-syntax
Markdown/MultiMarkdown.sublime-syntax
Markdown/syntax_test_markdown.md

Because this may only match at the very beginning of the file, it cannot be tested. I tried.
Closes #1783.

[Markdown] Add YAML frontmatter highlighting

---

Erlang/Erlang.sublime-syntax
Erlang/syntax_test_erlang.erl

Fixes #2428
The `!` operator can be compared with the pipe operator of ShellScript, but from right to left. As it assigns the evaluated value of the right hand expression to the left one, it is added to the group of assignment operators.

[Erlang] Fix operator scope names

---

Perl/Perl.sublime-syntax
Perl/syntax_test_perl.pl

Fixes #2432
Using generic patterns or substitutions such as `/<pattern>/<flags>` as function arguments without enclosing them into parentheses may be an ambiguous expression as it can't be distinguished from arithmetic operations in many situations. Things become even more difficult if generic patterns span multiple lines or contain semi-colons.
This commit splits the list of builtin functions into those which are known to not support pattern like arguments and those which might do.
These lists might not be perfect. May be tweaked in future, when further issues about broken highlighting arrive - or maybe someone wants to investigate which ones do.
User defined functions require arguments to be enclosed in parentheses, if the first one is a pattern or substitution.

[Perl] Fix ambiguous function arguments

---

ASP/ASP.sublime-syntax
ASP/HTML-ASP.sublime-syntax
ASP/syntax_test_asp.asp
HTML/HTML.sublime-syntax
HTML/syntax_test_html.html

This PR...
1. proposes to use `pop: 1` instead of `pop: true` in sublime-syntax version 2 only.
2. renames the `attribute-...-equals` context to `attribute-...-assignment` which looks more appropriate.
3. adds a lot of named contexts in order to introduce entry points for inherited syntax definitions to add custom highlighting.
4. tweaks the recently added `src/href` attribute contexts 
a) to ensure maximum re-usablility in inerhited syntax definitions by avoiding  `pop: 2`
b) by adding `meta.path.url` to the url values.
5. tweaks the usage of `meta_scope` and `meta_content_scope` in the script/style attriubtes to avoid assigning meta scopes via normal `scope` directives.
6. moves `meta.class-name`, `meta.toc-list.id` and `meta.path` so that an inherited syntax can easily clear string …

[HTML] Prepare for inheritance

---

Markdown/Markdown.sublime-syntax

This PR proposes to use
- `markup.heading.3.markdown` for level 3 heading (changed from `markup.heading.markdown`)
- `markup.heading.4.markdown` for level 4 heading (changed from `markup.heading.markdown`)
- `markup.heading.5.markdown` for level 5 heading (changed from `markup.heading.markdown`)
- `markup.heading.6.markdown` for level 6 heading (changed from `markup.heading.markdown`)
---
My original idea is to give headings different background colors via color scheme rules according to their levels.
But soon I found that there are only `markup.heading.1.markdown`, `markup.heading.2.markdown` and other levels are all `markup.heading.markdown`. It's weird that we highlight `punctuation.definition.heading.begin.markdown` up to 6 levels but only gives level 1 and level 2 specific …

[Markdown] Assign specific scopes to level 3~5 headings

---

Erlang/Erlang.sublime-syntax

This PR tweaks the shebang line highlighting.
1. The scope is changed to `comment.line.shebang` as JavaScript uses it.
A dedicated scope further allows dedicated shebang highlighting.
2. The statements context is set onto stack after the shebang but not after the next start of line or non-whitespace character. This is to make sure, the shebang is highlighted within fenced code blocks of Markdown. It is to support _escript_.
**Example**
```
```Erlang
#!/usr/bin/erlang
%% Erlang test module
-module('my-test-module').
-compile(export_all).
-ifndef(HAVE_DEBUG).
- define(HAVE_DEBUG, 1).
-endif.
```
**Screenshot**

[Erlang] Tweak shebang

---

Erlang/HTML (Erlang).sublime-syntax

This PR makes use of the `extends` keyword to implement the HTML (Erlang) syntax and updates it to version 2.

[Erlang] Implement YAWS by extending HTML

---

Perl/Perl.sublime-syntax

This PR adds a support for specieal highlighting of the shebang line.
Some fonts provide ligatures for the `#!` sign, thus need to ensure it is tokenized correctly.
The statements context is set onto stack after shebang matches but not after the next start of line or non-whitespace character. This is to make sure, the shebang is highlighted within fenced code blocks of Markdown.
Related with Erlang. Others may follow.

[Perl] Add shebang

---

PHP/PHP Source.sublime-syntax
PHP/PHP.sublime-syntax

Since we are on `version: 2`, keep `pop` always using an `int` for consistency.

[PHP] Use `pop: 1` rather than `pop: true`

---

Markdown/Markdown.sublime-syntax
Markdown/syntax_test_markdown.md

Addresses https://github.com/MonoLisaFont/feedback/issues/36
This PR extends the existing ligatures tokenization fix to match more arrow like ligatures correctly, by just consuming everything, which looks like a ligature candidate.

[Markdown] Fix more arrow like ligatures

---

HTML/Default.sublime-keymap
HTML/html_completions.py

This include two changes that make typing HTML a slightly less frustrating experience:
- Allow over-typing the closing > of an HTML tag. This seems fairly straightforward, and shouldn't cause any trouble, at least from situations I could think of. If a user does with to have multiple >>, then can press the > key twice.
- Augment attribute completions with extra fields. Now when a user completes an attribute, they will always have a field they can tab to "finish" the completion. If the completion closes the tag, they will have two fields, one after the attribute to allow for more attributes to be added, and a second one after the closing > of the tag.

[HTML] Improvements to attribute completions
